'use strict';
const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer');
const sizes=[[1024,768],[1280,720],[1366,768],[1440,900],[1536,864],[1600,900],[1920,1080],[2560,1440]];
const shots=new Set(['1024x768','1366x768','1440x900','1920x1080','2560x1440']);
const out='C:/Temp/KARETA_HOME_DESKTOP_84_114';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await puppeteer.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const events=[],results=[];
try{const page=await browser.newPage();await page.setBypassServiceWorker(true);await page.setCacheEnabled(false);
page.on('console',m=>{if(['error','warn'].includes(m.type()))events.push({kind:'console',level:m.type(),text:m.text()})});page.on('pageerror',e=>events.push({kind:'pageerror',message:e.message}));page.on('response',r=>{if(r.status()>=400)events.push({kind:'http',status:r.status(),url:r.url()})});
await page.setViewport({width:1024,height:768,deviceScaleFactor:1});await page.goto('http://localhost/?desktop_home_test='+Date.now()+'#/home',{waitUntil:'domcontentloaded',timeout:20000});
await page.waitForFunction(()=>window.KaretaNext?.audit?.().ok===true,{timeout:20000});
await page.evaluate(()=>{try{window.KaretaOnboardingApp?.setActive?.(false)}catch(_e){};document.getElementById('onb2-overlay')?.remove();document.getElementById('onboarding-welcome')?.remove();if(location.hash!=='#/home')location.hash='#/home';});
await page.waitForSelector('[data-page="home"]',{timeout:10000});await new Promise(r=>setTimeout(r,1200));
for(const [width,height] of sizes){await page.setViewport({width,height,deviceScaleFactor:1});await new Promise(r=>setTimeout(r,220));const state=await page.evaluate(()=>{const q=s=>document.querySelector(s),rect=s=>{const n=q(s);if(!n)return null;const r=n.getBoundingClientRect(),c=getComputedStyle(n);return{x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height),display:c.display,overflowX:c.overflowX}},cols=s=>{const n=q(s);if(!n)return 0;const v=getComputedStyle(n).gridTemplateColumns.trim();return v?v.split(/\s+/).length:0},root=document.documentElement;const hero=rect('.k-home-ref-hero'),actions=rect('.k-home-ref-actions'),nearby=rect('[data-home-section="nearby"]'),popular=rect('[data-home-section="popular"]'),home=rect('.k-home-reference'),search=rect('.k-home-ref-search'),feed=rect('[data-home-feed="works"]'),sidebar=rect('#k-desktop-sidebar'),mobile=rect('#k-mobile-nav');const expectedSidebar=innerWidth>=1280?248:84;const feedCols=cols('[data-home-feed="works"]');const pass=!((root.scrollWidth-root.clientWidth)>1)&&!!home&&home.w<=1441&&cols('.k-home-reference')===12&&hero&&actions&&Math.abs(hero.y-actions.y)<=2&&hero.x+hero.w<=actions.x+2&&nearby&&popular&&Math.abs(nearby.y-popular.y)<=2&&nearby.x+nearby.w<=popular.x+2&&search&&Math.abs(search.w-home.w)<=2&&feed&&getComputedStyle(q('[data-home-feed="works"]')).display==='grid'&&q('[data-home-feed="works"]').scrollWidth<=q('[data-home-feed="works"]').clientWidth+1&&feedCols===(innerWidth>=1600?4:3)&&sidebar&&Math.abs(sidebar.w-expectedSidebar)<=1&&mobile?.display==='none';return{release:window.KARETA_BOOT_RELEASE||'',viewport:{w:innerWidth,h:innerHeight},document:{clientWidth:root.clientWidth,scrollWidth:root.scrollWidth,overflowX:(root.scrollWidth-root.clientWidth)>1},home,homeCols:cols('.k-home-reference'),search,hero,actions,nearby,popular,feed,feedCols,feedClient:q('[data-home-feed="works"]')?.clientWidth||0,feedScroll:q('[data-home-feed="works"]')?.scrollWidth||0,sidebar,mobile,quickActions:q('.k-home-ref-actions')?.children.length||0,pass};});const key=width+'x'+height;let screenshot='';if(shots.has(key)){screenshot='home__client__'+key+'__chrome__84_114.jpg';try{await page.screenshot({path:path.join(out,screenshot),type:'jpeg',quality:65,fullPage:false});}catch(e){events.push({kind:'screenshot',viewport:key,message:e.message});screenshot='';}}results.push({width,height,state,screenshot});console.log(JSON.stringify({size:key,pass:state.pass,home:state.home?.w,hero:state.hero?.w,actions:state.actions?.w,feedCols:state.feedCols,feedClient:state.feedClient,feedScroll:state.feedScroll,overflow:state.document.overflowX,sidebar:state.sidebar?.w}));}
const evidence={release:'188.5.5.6.84.114',url:'http://localhost/#/home',browser:await browser.version(),generatedAt:new Date().toISOString(),pass:results.every(r=>r.state.pass),results,events};fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log('SUMMARY '+results.filter(r=>r.state.pass).length+'/'+results.length+' EVENTS='+events.length);if(!evidence.pass)process.exitCode=2;
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});