'use strict';
const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer');
const sizes=[[390,844],[430,932],[768,1024],[820,1180],[1023,768]];
const shots=new Set(['390x844','768x1024','1023x768']);
const out='C:/Temp/KARETA_HOME_MOBILE_REGRESSION_84_114';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await puppeteer.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const results=[],events=[];
try{const page=await browser.newPage();await page.setBypassServiceWorker(true);await page.setCacheEnabled(false);
page.on('console',m=>{if(['error','warn'].includes(m.type()))events.push({kind:'console',level:m.type(),text:m.text()})});page.on('pageerror',e=>events.push({kind:'pageerror',message:e.message}));page.on('response',r=>{if(r.status()>=400)events.push({kind:'http',status:r.status(),url:r.url()})});
await page.setViewport({width:390,height:844,deviceScaleFactor:1});await page.goto('http://localhost/?home_mobile_regression='+Date.now()+'#/home',{waitUntil:'domcontentloaded',timeout:20000});await page.waitForFunction(()=>window.KaretaNext?.audit?.().ok===true,{timeout:20000});await page.evaluate(()=>{try{window.KaretaOnboardingApp?.setActive?.(false)}catch(_e){};document.getElementById('onb2-overlay')?.remove();document.getElementById('onboarding-welcome')?.remove();if(location.hash!=='#/home')location.hash='#/home';});await page.waitForSelector('[data-page="home"]',{timeout:10000});await new Promise(r=>setTimeout(r,1000));
for(const [width,height] of sizes){await page.setViewport({width,height,deviceScaleFactor:1});await new Promise(r=>setTimeout(r,220));const state=await page.evaluate(()=>{const q=s=>document.querySelector(s),rect=s=>{const n=q(s);if(!n)return null;const r=n.getBoundingClientRect(),c=getComputedStyle(n);return{x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height),display:c.display,overflowX:c.overflowX}},root=document.documentElement,feed=q('[data-home-feed="works"]'),home=q('.k-home-reference'),side=q('#k-desktop-sidebar'),mobile=q('#k-mobile-nav'),hero=q('.k-home-ref-hero'),actions=q('.k-home-ref-actions');const hs=home?getComputedStyle(home):null,fsx=feed?getComputedStyle(feed):null,ss=side?getComputedStyle(side):null,ms=mobile?getComputedStyle(mobile):null;const cols=hs?.gridTemplateColumns?.trim()?hs.gridTemplateColumns.trim().split(/\s+/).length:0;const pass=(root.scrollWidth-root.clientWidth)<=1&&!!home&&rect('.k-home-reference').w<=root.clientWidth+1&&ss?.display==='none'&&ms?.display==='grid'&&fsx?.display==='flex'&&feed.scrollWidth>=feed.clientWidth&&cols<12&&!!hero&&!!actions;return{release:window.KARETA_BOOT_RELEASE||'',viewport:{w:innerWidth,h:innerHeight},document:{clientWidth:root.clientWidth,scrollWidth:root.scrollWidth,overflowX:(root.scrollWidth-root.clientWidth)>1},home:rect('.k-home-reference'),homeCols:cols,hero:rect('.k-home-ref-hero'),actions:rect('.k-home-ref-actions'),sidebar:rect('#k-desktop-sidebar'),mobileNav:rect('#k-mobile-nav'),feed:rect('[data-home-feed="works"]'),feedDisplay:fsx?.display||'',feedClient:feed?.clientWidth||0,feedScroll:feed?.scrollWidth||0,pass};});const key=width+'x'+height;let screenshot='';if(shots.has(key)){screenshot='home__client__'+key+'__chrome__mobile-regression.jpg';await page.screenshot({path:path.join(out,screenshot),type:'jpeg',quality:65,fullPage:false});}results.push({width,height,state,screenshot});console.log(JSON.stringify({size:key,pass:state.pass,overflow:state.document.overflowX,homeCols:state.homeCols,sidebar:state.sidebar?.display,mobileNav:state.mobileNav?.display,feed:state.feedDisplay,feedClient:state.feedClient,feedScroll:state.feedScroll}));}
const evidence={release:'188.5.5.6.84.114',url:'http://localhost/#/home',browser:await browser.version(),generatedAt:new Date().toISOString(),pass:results.every(r=>r.state.pass),results,events};fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log('SUMMARY '+results.filter(r=>r.state.pass).length+'/'+results.length+' EVENTS='+events.length);if(!evidence.pass)process.exitCode=2;
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});