'use strict';
const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer');
const sizes=[[390,844],[430,932],[768,1024],[820,1180],[1023,768]];
const shotSet=new Set(['390x844','768x1024','1023x768']);
const out='C:/Temp/KARETA_MASTER_HOME_MOBILE_REGRESSION_84_115';fs.mkdirSync(out,{recursive:true});
const context={id:910000,key:'MASTER_FIXTURE',type:'profile',profileType:'master',label:'Мастер'};
const identity={authenticated:true,account:{id:900000,status:'active'},session:{id:'fixture',contextRevision:1},contexts:[context],currentContext:context,capabilities:['profile.master','profile.read','work_orders.read','services.manageOwn'],deniedCapabilities:[],accountTypes:[{role:'master',status:'active'}],sessionContext:{contextRevision:1}};
const legacy={ok:true,authenticated:true,user:{id:900000,name:'Responsive Master',phone:'',role:'master',entry_role:'master',onboarded:1,onboarding_stage:'done',active:1,city:'Усть-Каменогорск',initials:'RM'},access:{role:'master',defaultRoute:'masterDashboard',routes:['masterDashboard','masterSchedule','orders','servicesManage','parts'],capabilities:['profile.master','profile.read','work_orders.read','services.manageOwn']},dbReady:true,fixture:true};
const workplace={ok:true,data:{master:{id:910000,name:'Responsive Master',availability:'online'},activeOrders:[
{id:'a1',date:'2026-09-25',time:'10:00',clientCar:'Toyota Camry',serviceNames:'Диагностика двигателя',clientName:'Клиент A',status:'process',chatId:'c1'},
{id:'a2',date:'2026-09-25',time:'13:30',clientCar:'Lexus IS250',serviceNames:'Тормозная система',clientName:'Клиент B',status:'accepted'}
],waitingOrders:[{id:'p1',date:'2026-09-25',time:'15:00',clientCar:'Kia Sorento',serviceNames:'Подвеска',clientName:'Клиент C',status:'waiting_parts'}],todayOrders:[
{id:'t1',date:'2026-09-25',time:'10:00',clientCar:'Toyota Camry',serviceNames:'Диагностика двигателя',clientName:'Клиент A',status:'process'},
{id:'t2',date:'2026-09-25',time:'16:00',clientCar:'Nissan Sunny',serviceNames:'Электрика',clientName:'Клиент D',status:'accepted'}
],timers:[{id:'tm1',orderId:'a1',status:'running',startedAt:'10:00'}],preferences:{windows:{status:true,attention:true,nextOrder:true,newAccepted:true,todayQueue:true,upcoming:true},params:{upcomingLimit:6,autoRefreshSec:0,compactCards:false}}}};
(async()=>{const browser=await puppeteer.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const results=[],events=[];
try{const page=await browser.newPage();await page.setBypassServiceWorker(true);await page.setCacheEnabled(false);await page.setRequestInterception(true);
page.on('request',req=>{try{const u=new URL(req.url());if(req.method()==='GET'&&u.pathname==='/api/auth_session.php')return req.respond({status:200,contentType:'application/json',body:JSON.stringify(legacy)});if(req.method()==='GET'&&u.pathname==='/api/identity_session.php')return req.respond({status:200,contentType:'application/json',body:JSON.stringify(identity)});if(req.method()==='GET'&&u.pathname==='/api/master_onboarding.php'&&u.searchParams.get('action')==='current')return req.respond({status:200,contentType:'application/json',body:JSON.stringify({ok:true,status:'completed',contextId:'910000',currentStep:4,currentView:'review'})});if(req.method()==='GET'&&u.pathname==='/api/db.php'&&u.searchParams.get('action')==='masterWorkplace.get')return req.respond({status:200,contentType:'application/json',body:JSON.stringify(workplace)});if(req.method()==='GET'&&u.pathname==='/api/db.php'&&u.searchParams.get('action')==='pull')return req.respond({status:200,contentType:'application/json',body:JSON.stringify({ok:true,users:[],masters:[],services:[],parts:[],orders:[],chats:[],news:[],workPosts:[]})});if(req.method()==='GET'&&u.pathname==='/api/realtime.php')return req.respond({status:200,contentType:'text/event-stream',body:': fixture heartbeat\\n\\n'});req.continue();}catch(e){req.continue();}});
page.on('console',m=>{if(['error','warn'].includes(m.type()))events.push({kind:'console',level:m.type(),text:m.text()})});page.on('pageerror',e=>events.push({kind:'pageerror',message:e.message}));page.on('requestfailed',r=>events.push({kind:'requestfailed',url:r.url(),failure:r.failure()}));page.on('response',r=>{if(r.status()>=400)events.push({kind:'http',status:r.status(),url:r.url()})});
await page.setViewport({width:390,height:844,deviceScaleFactor:1});await page.goto('http://localhost/?master_desktop='+Date.now()+'#/master',{waitUntil:'domcontentloaded',timeout:20000});await page.waitForFunction(()=>window.KaretaNext?.audit?.().ok===true,{timeout:20000});await page.waitForFunction(()=>window.KaretaIdentity?.snapshot?.().compatibilityRole==='master'&&window.KaretaMasterOnboardingGate?.snapshot?.().verified===true,{timeout:10000});await page.evaluate(()=>{window.KaretaOnboardingApp?.setActive?.(false);document.getElementById('onb2-overlay')?.remove();document.getElementById('onboarding-welcome')?.remove();try{history.replaceState(null,'','#/master')}catch(_e){location.hash='#/master'};window.KaretaRouteRuntime?.transition?.('masterDashboard',{source:'master-desktop-fixture',force:true});});await page.waitForFunction(()=>document.querySelector('#k-master-workplace')?.dataset.phase==='ready',{timeout:12000}).catch(()=>null);await new Promise(r=>setTimeout(r,500));const debug=await page.evaluate(()=>({hash:location.hash,route:document.querySelector('#k-page-outlet')?.dataset.currentRoute||'',outletText:(document.querySelector('#k-page-outlet')?.innerText||'').slice(0,500),phase:document.querySelector('#k-master-workplace')?.dataset.phase||'',identity:window.KaretaIdentity?.snapshot?.()||null,gate:window.KaretaMasterOnboardingGate?.snapshot?.()||null,role:window.KaretaRoleAccess?.currentRole?.()||'',htmlRole:document.documentElement.dataset.userRole||''}));console.log('DEBUG '+JSON.stringify(debug));if(debug.phase!=='ready'){fs.writeFileSync(path.join(out,'debug.json'),JSON.stringify({debug,events},null,2));process.exitCode=3;return;}
for(const [width,height] of sizes){await page.setViewport({width,height,deviceScaleFactor:1});await new Promise(r=>setTimeout(r,220));const state=await page.evaluate(()=>{const q=s=>document.querySelector(s),rect=s=>{const n=q(s);if(!n)return null;const r=n.getBoundingClientRect(),c=getComputedStyle(n);return{x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height),display:c.display,gridColumn:c.gridColumnStart+'/'+c.gridColumnEnd,gridRow:c.gridRowStart+'/'+c.gridRowEnd}},root=document.documentElement,wp=q('#k-master-workplace'),actions=q('.k-master-home-quick-actions .k-master-native-actions'),titles=[...document.querySelectorAll('.k-master-home-quick-actions .k-master-native-action b')].map(x=>x.textContent.trim()),blocks=[...document.querySelectorAll('#k-master-workplace>[data-master-block]')].map(x=>x.dataset.masterBlock),side=rect('.k-master-home-status'),req=rect('.k-master-home-my-requests'),today=rect('.k-master-home-today'),notes=rect('.k-master-home-notes'),paused=rect('.k-master-home-paused'),sidebar=rect('#k-desktop-sidebar'),mobile=rect('#k-mobile-nav');const actionCols=actions?getComputedStyle(actions).gridTemplateColumns.trim().split(/\s+/).length:0,ratio=req&&side?req.w/(req.w+side.w):0;const expectedActionCols=innerWidth<=900?2:4;const pass=(root.scrollWidth-root.clientWidth)<=1&&wp?.dataset.phase==='ready'&&getComputedStyle(wp).display==='grid'&&blocks.join(',')==='header,status,quick-actions,my-requests,notes,paused,today'&&titles.join(',')==='Мои заявки,Заметки,Услуги,Запчасти'&&req&&side&&today&&notes&&paused&&req.gridColumn==='auto/auto'&&side.gridColumn==='auto/auto'&&req.y>side.y&&notes.y>req.y&&paused.y>notes.y&&today.y>paused.y&&actionCols===expectedActionCols&&sidebar?.display==='none'&&mobile?.display==='grid';return{release:window.KARETA_BOOT_RELEASE||'',role:window.KaretaRoleAccess?.currentRole?.()||'',actualRoute:q('#k-page-outlet')?.dataset.currentRoute||'',phase:wp?.dataset.phase||'',viewport:{w:innerWidth,h:innerHeight},document:{clientWidth:root.clientWidth,scrollWidth:root.scrollWidth,overflowX:(root.scrollWidth-root.clientWidth)>1},blocks,titles,workplace:rect('#k-master-workplace'),requests:req,status:side,today,notes,paused,actionCols,sidebar,mobileNav:mobile,ratio,pass};});const key=width+'x'+height;let screenshot='';if(shotSet.has(key)){screenshot='master-home__fixture__'+key+'__chrome__mobile-regression.jpg';await page.screenshot({path:path.join(out,screenshot),type:'jpeg',quality:68,fullPage:false});}results.push({width,height,state,screenshot});console.log(JSON.stringify({size:key,pass:state.pass,role:state.role,route:state.actualRoute,actions:state.actionCols,overflow:state.document.overflowX,sidebar:state.sidebar?.display,mobile:state.mobileNav?.display}));}
await page.evaluate(()=>window.scrollTo(0,0));await page.evaluate(()=>document.querySelector('[data-master-home-jump="notes"]')?.click());await new Promise(r=>setTimeout(r,500));const noteInteraction=await page.evaluate(()=>{const target=document.querySelector('[data-master-block="notes"]');return{hash:location.hash,scrollY:Math.round(window.scrollY),targetTop:target?Math.round(target.getBoundingClientRect().top):null,ok:location.hash==='#/master'&&window.scrollY>0&&!!target};});const evidence={release:'188.5.5.6.84.115',url:'http://localhost/#/master',browser:await browser.version(),fixture:'synthetic_master_identity_onboarding_workplace_get_only_mobile_regression',fixtureLimitations:['no_real_account','no_POST_actions','workplace_data_synthetic'],generatedAt:new Date().toISOString(),pass:results.every(r=>r.state.pass)&&noteInteraction.ok,noteInteraction,results,events};fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log('SUMMARY '+results.filter(r=>r.state.pass).length+'/'+results.length+' EVENTS='+events.length);if(!evidence.pass)process.exitCode=2;
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});