(() => {
  'use strict';
  const ui=window.KaretaPageUI;
  const esc=v=>window.KaretaUIKit?.esc?.(v)??String(v??'');
  const icon=n=>window.KaretaUIIcons?.svg?.(n)||'';
  let controller=null;
  async function request(action='overview',method='GET',payload=null,query=''){
    controller?.abort();controller=new AbortController();
    const url='/api/admin_operations.php?action='+encodeURIComponent(action)+(query?'&'+query:'');
    const res=await fetch(url,{method,credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{Accept:'application/json',...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):null});
    const type=String(res.headers.get('content-type')||'');const text=await res.text();if(!type.includes('application/json'))throw new Error('admin_invalid_response');let data;try{data=JSON.parse(text)}catch{throw new Error('admin_invalid_json')}if(!res.ok||data.ok===false)throw new Error(data.error||('admin_http_'+res.status));return data;
  }
  function adminNav(active){
    const items=[['adminMonitoring','#/admin/monitoring','monitor','Мониторинг'],['adminUsers','#/admin/users','users','Пользователи'],['adminOrganizations','#/admin/organizations','organization','Организации'],['adminManagement','#/admin/management','settings','Управление'],['platform','#/platform','grid','Платформа'],['corePlatform','#/core','core','Ядро']];
    return `<nav class="k-admin-context-nav" aria-label="Разделы администратора">${items.map(([key,href,ico,label])=>`<a href="${href}" class="${active===key?'is-active':''}" ${active===key?'aria-current="page"':''}><span>${icon(ico)}</span><b>${label}</b></a>`).join('')}</nav>`;
  }
  const dialogs=()=>`<dialog class="k-admin-dialog" data-admin-action-dialog><form method="dialog" data-admin-action-form><header><div><small>ADMIN ACTION</small><h2 data-admin-action-title>Операция</h2></div><button type="button" data-admin-dialog-close aria-label="Закрыть">×</button></header><div class="k-admin-dialog-fields" data-admin-action-fields></div><label><span>Причина *</span><textarea name="reason" required minlength="3" maxlength="500" placeholder="Укажите основание операции"></textarea></label><div class="k-admin-dialog-error" data-admin-dialog-error></div><footer><button type="button" class="k-btn" data-admin-dialog-close>Отмена</button><button type="submit" class="k-btn k-btn--primary">Выполнить</button></footer></form></dialog><dialog class="k-admin-detail-dialog" data-admin-detail-dialog><section><header><div><small>IDENTITY CONTROL</small><h2>Карточка Identity</h2></div><button type="button" data-admin-detail-close aria-label="Закрыть">×</button></header><div data-admin-detail-content></div></section></dialog>`;
  const shell=(ctx,title,subtitle,body,key)=>ui.pageShell(ctx,title,subtitle,adminNav(key)+body+dialogs(),{page:key,eyebrow:'ADMIN OPERATIONS'});
  function render(key,ctx){
    if(key==='adminUsers')return shell(ctx,'Пользователи','Account, Person, профили, сессии и контексты.',`<section class="k-admin-ops" data-admin-page="users"><header class="k-admin-toolbar"><label>${icon('search')}<input type="search" placeholder="Телефон или имя" data-admin-search></label><button type="button" class="k-btn" data-admin-refresh>Обновить</button></header><div data-admin-summary></div><div class="k-admin-data-grid" data-admin-content></div><div class="k-admin-status" data-admin-status aria-live="polite"></div></section>`,'adminUsers');
    if(key==='adminOrganizations')return shell(ctx,'Организации','СТО, магазины, участники и состояние контекстов.',`<section class="k-admin-ops" data-admin-page="organizations"><header class="k-admin-toolbar"><label>${icon('search')}<input type="search" placeholder="Название или ID" data-admin-search></label><button type="button" class="k-btn" data-admin-refresh>Обновить</button></header><div data-admin-summary></div><div class="k-admin-data-grid" data-admin-content></div><div class="k-admin-status" data-admin-status aria-live="polite"></div></section>`,'adminOrganizations');
    if(key==='adminMonitoring')return shell(ctx,'Мониторинг','Состояние Identity, схемы, сессий, миграций и действий администратора.',`<section class="k-admin-ops" data-admin-page="monitoring"><header class="k-admin-toolbar"><button type="button" class="k-btn" data-admin-refresh>Обновить показатели</button><a class="k-btn k-btn--secondary" href="#/admin/identity-migration">Миграции</a></header><div class="k-admin-kpis" data-admin-summary></div><section class="k-admin-audit"><h2>Последние административные действия</h2><div data-admin-content></div></section><div class="k-admin-status" data-admin-status aria-live="polite"></div></section>`,'adminMonitoring');
    return shell(ctx,'Управление и модерация','Тарифы, лимиты аккаунтов, модерационные кейсы и системные операции.',`<section class="k-admin-ops" data-admin-page="management"><header class="k-admin-toolbar"><button type="button" class="k-btn k-btn--primary" data-create-case>Новый кейс</button><button type="button" class="k-btn" data-admin-refresh>Обновить</button></header><section class="k-admin-tariff-control"><header><div><small>ACCOUNT TARIFFS</small><h2>Лимиты тарифов</h2><p>Четыре фиксированных плана: обычный и KARETA PRO отдельно для Клиента и Мастера. Название PRO фиксировано; администратор управляет лимитами и ценой платного тарифа.</p></div></header><div class="k-admin-tariff-grid" data-admin-tariffs><p class="k-empty">Загрузка тарифов…</p></div></section><section class="k-admin-moderation-control"><header><h2>Модерационные кейсы</h2></header><div class="k-admin-data-grid" data-admin-content></div></section><div class="k-admin-status" data-admin-status aria-live="polite"></div></section>`,'adminManagement');
  }
  const status=(root,text,type='')=>{const el=root.querySelector('[data-admin-status]');if(el){el.textContent=text||'';el.dataset.type=type}};
  function accountCard(x){return `<article class="k-admin-entity-card"><header><div><b>${esc(x.fullname||'Без имени')}</b><span>${esc(x.phone)}</span></div><i data-state="${esc(x.accountStatus)}">${esc(x.accountStatus)}</i></header><dl><div><dt>Account</dt><dd>#${esc(x.accountId)}</dd></div><div><dt>Person</dt><dd>#${esc(x.personId||'—')}</dd></div><div><dt>Профили</dt><dd>${esc(x.profiles||'client')}</dd></div><div><dt>Сессии</dt><dd>${esc(x.activeSessions||0)}</dd></div></dl><footer><button type="button" data-account-detail="${esc(x.accountId)}">Identity</button><button type="button" data-admin-mutate="setAccountStatus" data-id="${esc(x.accountId)}" data-next="${x.accountStatus==='active'?'blocked':'active'}">${x.accountStatus==='active'?'Заблокировать':'Активировать'}</button><button type="button" data-admin-mutate="revokeSessions" data-id="${esc(x.accountId)}">Отозвать сессии</button></footer></article>`;}
  function orgCard(x){return `<article class="k-admin-entity-card"><header><div><b>${esc(x.name)}</b><span>${esc(x.type)} · ${esc(x.city||'')}</span></div><i data-state="${esc(x.status)}">${esc(x.status)}</i></header><dl><div><dt>ID</dt><dd>${esc(x.id)}</dd></div><div><dt>Участники</dt><dd>${esc(x.members)}</dd></div><div><dt>Контексты</dt><dd>${esc(x.contexts)}</dd></div><div><dt>Телефон</dt><dd>${esc(x.phone||'—')}</dd></div></dl><footer><button type="button" data-admin-mutate="setOrganizationStatus" data-id="${esc(x.id)}" data-next="${x.status==='active'?'blocked':'active'}">${x.status==='active'?'Заблокировать':'Активировать'}</button></footer></article>`;}
  function caseCard(x){return `<article class="k-admin-entity-card"><header><div><b>${esc(x.entityType)} #${esc(x.entityId)}</b><span>${esc(x.reason||'Без описания')}</span></div><i data-state="${esc(x.status)}">${esc(x.status)}</i></header><dl><div><dt>Приоритет</dt><dd>${esc(x.priority)}</dd></div><div><dt>Кейс</dt><dd>${esc(x.caseKey)}</dd></div><div><dt>Создан</dt><dd>${esc(x.createdAt)}</dd></div></dl><footer>${['approved','rejected','hidden','escalated','closed'].map(next=>`<button type="button" data-admin-mutate="resolveModerationCase" data-id="${esc(x.id)}" data-next="${next}">${next}</button>`).join('')}</footer></article>`;}

  function tariffLimitLabel(key){return ({acceptedRequestsPerDay:'Принятых заявок в день',activeIntakesPerDay:'Активных приёмов на день',openRepairs:'Незакрытых машин в ремонте',activeRequests:'Активных заявок',vehicles:'Автомобилей в гараже'})[key]||key;}
  function tariffAdminCard(plan){const limits=plan?.limits||{},type=plan?.accountType==='master'?'Мастер':'Клиент',paid=!!plan?.isPaid;return `<form class="k-admin-tariff-card ${paid?'is-pro':''}" data-tariff-plan="${esc(plan?.code||'')}"><header><div><small>${esc(type)} · ${paid?'ПЛАТНЫЙ':'ОБЫЧНЫЙ'}</small><h3>${esc(plan?.name||'Тариф')}</h3><p>${esc(plan?.description||'')}</p></div><i>${paid?'PRO':'STANDARD'}</i></header><div class="k-admin-tariff-fields">${Object.entries(limits).map(([key,value])=>`<label><span>${esc(tariffLimitLabel(key))}</span><input type="number" min="0" max="10000" step="1" name="limit_${esc(key)}" value="${esc(value)}" required><small>0 = без ограничения</small></label>`).join('')}${paid?`<label><span>Цена KARETA PRO, ₸/мес.</span><input type="number" min="0" max="10000000" step="100" name="monthlyPrice" value="${plan?.monthlyPrice??''}" placeholder="Задаёт администратор"><small>Пусто — цена ещё не опубликована</small></label>`:'<input type="hidden" name="monthlyPrice" value="0">'}</div><footer><button type="submit" class="k-btn k-btn--primary">Сохранить лимиты</button><output data-tariff-save-status></output></footer></form>`;}
  async function tariffApi(action,method='GET',payload=null){const options={method,cacheTtlMs:0,dedupe:false};if(payload){options.headers={'Content-Type':'application/json'};options.body=JSON.stringify({action,...payload});}const url=method==='GET'?`api/db.php?action=${encodeURIComponent(action)}`:'api/db.php';const r=await window.KaretaApiClient.request(url,options);if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'tariff_admin_failed');return r.payload?.data||r.data||{};}
  async function loadTariffs(root){const host=root.querySelector('[data-admin-tariffs]');if(!host)return;try{const data=await tariffApi('tariffs.adminList');const plans=Array.isArray(data.plans)?data.plans:[];host.innerHTML=plans.map(tariffAdminCard).join('')||'<p class="k-empty">Тарифы не найдены</p>';}catch(error){host.innerHTML=`<p class="k-empty">${esc(error.message||'Не удалось загрузить тарифы')}</p>`;}}
  const stateBadge=value=>`<i data-state="${esc(value)}">${esc(value||'—')}</i>`;
  function identityDetail(data){
    const account=data.account||{};const profiles=Array.isArray(data.profiles)?data.profiles:[];const contexts=Array.isArray(data.contexts)?data.contexts:[];const sessions=Array.isArray(data.sessions)?data.sessions:[];
    return `<div class="k-admin-identity"><section class="k-admin-identity-head"><div><small>ACCOUNT #${esc(account.accountId)}</small><h3>${esc(account.fullname||'Без имени')}</h3><p>${esc(account.phone)} · Person #${esc(account.personId||'—')}</p></div>${stateBadge(account.accountStatus)}</section><section><h3>Профили</h3><div class="k-admin-identity-rows">${profiles.map(profile=>`<article><div><b>${esc(profile.profileType)}</b><small>Profile #${esc(profile.id)} · ${esc(profile.legacyEntityType||'native')} ${esc(profile.legacyEntityId||'')}</small></div>${stateBadge(profile.status)}<button type="button" data-admin-mutate="setProfileStatus" data-id="${esc(profile.id)}" data-current="${esc(profile.status)}">Изменить</button></article>`).join('')||'<p class="k-empty">Профилей нет</p>'}</div></section><section><h3>Контексты и memberships</h3><div class="k-admin-identity-rows">${contexts.map(context=>`<article><div><b>${esc(context.contextKey)}</b><small>Context #${esc(context.id)} · ${esc(context.contextType)}${context.organizationName?' · '+esc(context.organizationName):''}<br>${esc(context.capabilitySet||'без capability set')}</small></div>${stateBadge(context.status)}<button type="button" data-admin-mutate="setContextStatus" data-id="${esc(context.id)}" data-current="${esc(context.status)}">Контекст</button>${context.membershipId?`${stateBadge(context.membershipStatus)}<button type="button" data-admin-mutate="setMembershipStatus" data-id="${esc(context.membershipId)}" data-current="${esc(context.membershipStatus)}">Доступ</button>`:''}</article>`).join('')||'<p class="k-empty">Контекстов нет</p>'}</div></section><section><h3>Сессии</h3><div class="k-admin-identity-rows">${sessions.map(session=>{const active=!session.revokedAt&&new Date(session.expiresAt).getTime()>Date.now();return `<article><div><b>Session #${esc(session.id)}</b><small>${esc(session.currentContextKey||'без контекста')} · ${esc(session.ipPrefix||'IP не записан')}<br>Последняя активность: ${esc(session.lastSeenAt||session.createdAt)}</small></div>${stateBadge(active?'active':'revoked')}${active?`<button type="button" data-admin-mutate="revokeSession" data-id="${esc(session.id)}" data-account-id="${esc(account.accountId)}">Отозвать</button>`:''}</article>`;}).join('')||'<p class="k-empty">Сессий нет</p>'}</div></section></div>`;
  }
  function actionSpec(button){
    const action=button.dataset.adminMutate;const id=button.dataset.id;const next=button.dataset.next||'';const specs={
      setAccountStatus:{title:'Статус аккаунта',payload:{accountId:Number(id)},field:['status','Новый статус',['active','blocked','deleted'],next]},
      revokeSessions:{title:'Отозвать все сессии',payload:{accountId:Number(id)}},
      revokeSession:{title:'Отозвать сессию',payload:{sessionId:Number(id),accountId:Number(button.dataset.accountId)}},
      setOrganizationStatus:{title:'Статус организации',payload:{organizationId:id},field:['status','Новый статус',['active','inactive','blocked','archived'],next]},
      setProfileStatus:{title:'Статус профиля',payload:{profileId:Number(id)},field:['status','Новый статус',['draft','active','suspended','archived'],button.dataset.current]},
      setContextStatus:{title:'Статус контекста',payload:{contextId:Number(id)},field:['status','Новый статус',['active','suspended','archived'],button.dataset.current]},
      setMembershipStatus:{title:'Статус membership',payload:{membershipId:Number(id)},field:['status','Новый статус',['invited','active','suspended','revoked'],button.dataset.current]},
      resolveModerationCase:{title:'Решение по модерации',payload:{caseId:Number(id)},field:['status','Решение',['approved','rejected','hidden','escalated','closed'],next]}
    };return specs[action]?{action,...specs[action]}:null;
  }
  async function mount(){
    const root=document.querySelector('[data-admin-page]');if(!root)return;const actionDialog=document.querySelector('[data-admin-action-dialog]');const detailDialog=document.querySelector('[data-admin-detail-dialog]');let busy=false;let pending=null;let detailAccountId=0;
    const setBusy=value=>{busy=!!value;root.setAttribute('aria-busy',String(busy));root.querySelectorAll('button,input').forEach(element=>element.disabled=busy);};
    async function load(){setBusy(true);status(root,'Загрузка…');try{const page=root.dataset.adminPage;if(page==='users'){const q=encodeURIComponent(root.querySelector('[data-admin-search]')?.value||'');const data=await request('users','GET',null,'q='+q);root.querySelector('[data-admin-content]').innerHTML=data.items.map(accountCard).join('')||'<p class="k-empty">Нет пользователей</p>';}else if(page==='organizations'){const q=encodeURIComponent(root.querySelector('[data-admin-search]')?.value||'');const data=await request('organizations','GET',null,'q='+q);root.querySelector('[data-admin-content]').innerHTML=data.items.map(orgCard).join('')||'<p class="k-empty">Нет организаций</p>';}else if(page==='management'){const [data]=await Promise.all([request('moderation'),loadTariffs(root)]);root.querySelector('[data-admin-content]').innerHTML=data.items.map(caseCard).join('')||'<p class="k-empty">Модерационных кейсов нет</p>';}else{const data=await request('overview');await window.KaretaDashboardEngine?.loadLayout?.('admin.main','admin','admin');root.querySelector('[data-admin-summary]').innerHTML=window.KaretaDashboardEngine?.render?.('admin.main',data,{context:{type:'system',key:'admin'},contextKey:'admin',widgets:['admin.metrics','admin.audit']})||'';root.querySelector('[data-admin-content]').innerHTML='';}status(root,'');}catch(error){if(error.name!=='AbortError')status(root,error.message,'error');}finally{setBusy(false);}}
    async function loadDetail(accountId){detailAccountId=Number(accountId);const box=detailDialog.querySelector('[data-admin-detail-content]');box.innerHTML='<p class="k-empty">Загрузка Identity…</p>';if(!detailDialog.open)detailDialog.showModal();try{const data=await request('accountDetail','GET',null,'accountId='+encodeURIComponent(detailAccountId));box.innerHTML=identityDetail(data);}catch(error){box.innerHTML=`<p class="k-empty">${esc(error.message)}</p>`;}}
    const actionChoice=(name,value,label,current)=>`<button type="button" class="k-r84-choice ${String(value)===String(current)?'is-active':''}" data-admin-choice="${esc(name)}" data-value="${esc(value)}">${esc(label)}</button>`;
    const actionChoiceBlock=(name,label,values,current)=>`<section class="k-r84-choice-block"><span>${esc(label)}</span><input type="hidden" name="${esc(name)}" value="${esc(current||values[0]||'')}"><div class="k-r84-choice-grid">${values.map(value=>actionChoice(name,value,value,current||values[0])).join('')}</div></section>`;
    function openAction(spec){pending=spec;const fields=actionDialog.querySelector('[data-admin-action-fields]');actionDialog.querySelector('[data-admin-action-title]').textContent=spec.title;actionDialog.querySelector('[data-admin-dialog-error]').textContent='';actionDialog.querySelector('textarea[name="reason"]').value='';fields.innerHTML=spec.field?actionChoiceBlock(spec.field[0],spec.field[1],spec.field[2],spec.field[3]):'';actionDialog.showModal();}
    function openCreateCase(){pending={action:'createModerationCase',title:'Новый модерационный кейс',payload:{}};actionDialog.querySelector('[data-admin-action-title]').textContent=pending.title;actionDialog.querySelector('[data-admin-dialog-error]').textContent='';actionDialog.querySelector('textarea[name="reason"]').value='';actionDialog.querySelector('[data-admin-action-fields]').innerHTML=`${actionChoiceBlock('entityType','Тип сущности',['product','post','account','organization'],'product')}<label><span>ID сущности</span><input name="entityId" required maxlength="128"></label>${actionChoiceBlock('priority','Приоритет',['normal','low','high','critical'],'normal')}`;actionDialog.showModal();}
    root.addEventListener('submit',async event=>{const form=event.target.closest('[data-tariff-plan]');if(!form)return;event.preventDefault();const out=form.querySelector('[data-tariff-save-status]');const limits={};form.querySelectorAll('[name^=limit_]').forEach(input=>limits[input.name.slice(6)]=Number(input.value));out.textContent='Сохранение…';try{await tariffApi('tariffs.updatePlan','POST',{planCode:form.dataset.tariffPlan,limits,monthlyPrice:form.elements.monthlyPrice?.value??null});out.textContent='Сохранено';window.KaretaToast?.success?.('Лимиты тарифа сохранены');await loadTariffs(root);}catch(error){out.textContent=error.message||'Ошибка сохранения';window.KaretaToast?.error?.(out.textContent);}});
    root.addEventListener('click',event=>{if(busy)return;if(event.target.closest('[data-admin-refresh]'))return load();const detail=event.target.closest('[data-account-detail]');if(detail)return loadDetail(detail.dataset.accountDetail);const mutation=event.target.closest('[data-admin-mutate]');if(mutation){const spec=actionSpec(mutation);if(spec)openAction(spec);return;}if(event.target.closest('[data-create-case]'))openCreateCase();});
    detailDialog.addEventListener('click',event=>{if(event.target.closest('[data-admin-detail-close]'))detailDialog.close();const mutation=event.target.closest('[data-admin-mutate]');if(mutation){const spec=actionSpec(mutation);if(spec)openAction(spec);}});
    actionDialog.querySelectorAll('[data-admin-dialog-close]').forEach(button=>button.addEventListener('click',()=>actionDialog.close()));detailDialog.querySelector('[data-admin-detail-close]')?.addEventListener('click',()=>detailDialog.close());
    actionDialog.addEventListener('click',event=>{const choice=event.target.closest('[data-admin-choice]');if(!choice)return;const name=choice.dataset.adminChoice,hidden=actionDialog.querySelector(`input[type=\"hidden\"][name=\"${name}\"]`);if(hidden)hidden.value=choice.dataset.value||'';actionDialog.querySelectorAll(`[data-admin-choice=\"${name}\"]`).forEach(node=>node.classList.toggle('is-active',node===choice));});
    actionDialog.querySelector('[data-admin-action-form]').addEventListener('submit',async event=>{event.preventDefault();if(!pending)return;const form=event.currentTarget;const submit=form.querySelector('[type="submit"]');const errorBox=form.querySelector('[data-admin-dialog-error]');submit.disabled=true;errorBox.textContent='';try{const values=Object.fromEntries(new FormData(form).entries());await request(pending.action,'POST',{action:pending.action,...pending.payload,...values});actionDialog.close();window.KaretaToast?.success?.('Операция выполнена');await load();if(detailAccountId&&detailDialog.open)await loadDetail(detailAccountId);}catch(error){errorBox.textContent=error.message||'Операция не выполнена';}finally{submit.disabled=false;}});
    root.querySelector('[data-admin-search]')?.addEventListener('keydown',event=>{if(event.key==='Enter')load();});await load();
  }
  window.KaretaAdminWorkspacePages=Object.freeze({render,mount});
})();
