(() => {
 'use strict';
 const api=()=>window.KaretaApiClient;
 const ui=()=>window.KaretaUIKit;
 const esc=v=>ui()?.esc?.(v)??String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 function renderCalendarBooking(){return `<section class="k-page k-calendar-booking"><header class="k-r84-workspace-head"><div><small>КАЛЕНДАРЬ</small><h1>Календарь и запись</h1><p>Свободные окна, записи клиента и загрузка рабочего контекста.</p></div><div data-layout="actions-row"><button class="k-btn k-btn--secondary" type="button" data-cal-refresh>Обновить</button><button class="k-btn k-btn--primary" type="button" data-book-open>Новая запись</button></div></header><section class="k-calendar-panel k-r84-flat-surface"><h2>Ближайшие записи</h2><div data-calendar-list></div></section><div class="k-booking-message" data-book-message></div><dialog class="k-r84-work-dialog" data-book-dialog><div class="k-r84-work-dialog__surface"><header><div><small>РАБОЧЕЕ ОКНО</small><h2>Новая запись</h2></div><button type="button" data-book-close aria-label="Закрыть">×</button></header><div class="k-r84-work-dialog__body"><div class="k-booking-form"><label>Дата<input type="date" data-book-date></label><div class="k-r84-choice-block"><span>Длительность</span><input type="hidden" data-book-duration value="60"><div class="k-r84-choice-grid">${[['30','30 минут'],['60','1 час'],['90','1,5 часа'],['120','2 часа']].map(([v,l])=>`<button type="button" data-book-duration-value="${v}" class="${v==='60'?'is-active':''}">${l}</button>`).join('')}</div></div><label>Название<input data-book-title maxlength="255" placeholder="Диагностика или обслуживание"></label><label>Ресурс / пост<input data-book-resource maxlength="128" placeholder="Например: post:1"></label><button class="k-btn k-btn--secondary" type="button" data-book-find>Показать окна</button></div><div class="k-booking-slots" data-book-slots></div></div><footer><button class="k-btn k-btn-secondary" type="button" data-book-close>Закрыть</button></footer></div></dialog></section>`}
 async function mountCalendarBooking({signal}={}){const root=document.querySelector('.k-calendar-booking');if(!root)return;let selected='';const dialog=root.querySelector('[data-book-dialog]'),date=root.querySelector('[data-book-date]');date.value=new Date().toISOString().slice(0,10);const msg=t=>root.querySelector('[data-book-message]').textContent=t||'';
 const load=async()=>{root.querySelector('[data-calendar-list]').innerHTML=ui().skeleton(4);try{const d=await api().getCalendarView({from:date.value});const rows=d.events||[];root.querySelector('[data-calendar-list]').innerHTML=rows.map(x=>ui().card({title:x.title,meta:`${x.startsAt} → ${x.endsAt}`,body:`${ui().badge(x.status,x.status==='cancelled'?'neutral':'info')}${x.bookingKey?`<button class="k-btn k-btn--ghost" data-cancel-book="${esc(x.bookingKey)}">Отменить</button>`:''}`})).join('')||ui().empty('Записей пока нет');}catch(e){root.querySelector('[data-calendar-list]').innerHTML=ui().error(e.message||'Не удалось загрузить календарь');}};
 const slots=async()=>{selected='';msg('');const duration=root.querySelector('[data-book-duration]').value;const box=root.querySelector('[data-book-slots]');box.innerHTML=ui().skeleton(3);try{const d=await api().getBookingAvailability({date:date.value,duration});box.innerHTML=(d.slots||[]).map(s=>`<button class="k-booking-slot" type="button" data-slot="${esc(s.startsAt)}" data-end="${esc(s.endsAt)}">${esc(s.label)}</button>`).join('')||ui().empty('Свободных окон нет');}catch(e){box.innerHTML=ui().error(e.message||'Не удалось получить окна');}};
 const close=()=>{if(dialog?.open)dialog.close();selected='';root.querySelector('[data-book-slots]').innerHTML='';};
 root.addEventListener('click',async e=>{if(e.target.closest('[data-book-open]')){if(dialog&&!dialog.open)dialog.showModal();date.focus();return;}if(e.target.closest('[data-book-close]')){close();return;}const duration=e.target.closest('[data-book-duration-value]');if(duration){root.querySelector('[data-book-duration]').value=duration.dataset.bookDurationValue||'60';root.querySelectorAll('[data-book-duration-value]').forEach(x=>x.classList.toggle('is-active',x===duration));return;}const slot=e.target.closest('[data-slot]');if(slot){root.querySelectorAll('[data-slot]').forEach(x=>x.classList.remove('is-selected'));slot.classList.add('is-selected');selected=slot.dataset.slot;slot.dataset.selectedEnd=slot.dataset.end;return;}if(e.target.closest('[data-book-find]'))return slots();if(e.target.closest('[data-cal-refresh]'))return load();const cancel=e.target.closest('[data-cancel-book]');if(cancel){await api().cancelServiceBooking(cancel.dataset.cancelBook);return load();}if(e.target.closest('[data-book-slots]')&&selected)return;});
 dialog?.addEventListener('cancel',e=>{e.preventDefault();close();});dialog?.addEventListener('click',e=>{if(e.target===dialog)close();});
 root.querySelector('[data-book-slots]').addEventListener('dblclick',async e=>{const slot=e.target.closest('[data-slot]');if(!slot)return;const title=root.querySelector('[data-book-title]').value.trim()||'Запись на обслуживание';try{await api().createServiceBooking({title,startsAt:slot.dataset.slot,endsAt:slot.dataset.end,resourceKey:root.querySelector('[data-book-resource]').value.trim()});msg('Запись создана');close();await load();}catch(err){msg(err.message||'Не удалось создать запись');}});
 await load();if(signal)signal.addEventListener('abort',()=>{close();},{once:true});}
 window.KaretaCalendarBookingPages=Object.freeze({renderCalendarBooking,mountCalendarBooking});
})();
