(() => { 'use strict';
 const ui=()=>window.KaretaUIKit; const store=()=>window.KaretaStateManager; const client=()=>window.KaretaApiClient; const repo=()=>window.KaretaDomainRepository;
 const labels={person:'Пользователь',organization:'Организация',vehicle:'Автомобиль',work_request:'Заявка',work_order:'Заказ-наряд'};
 function renderCorePlatform(){return `<section class="k-page k-core-platform"><header class="k-core-hero"><div><span class="k-core-eyebrow">R181.4 UNIFIED FRONTEND CORE</span><h1>Единый доменный контур</h1><p>Нормализованный state, единые компоненты и общий timeline для доменных сущностей.</p></div><button class="k-btn k-btn--primary" data-core-refresh>Обновить</button></header><div class="k-core-stats" data-core-stats></div><div class="k-core-entity-layout"><section><h2>Доменные сущности</h2><div class="k-core-entity-list" data-core-entities></div></section><aside class="k-core-inspector" data-core-inspector><div class="k-core-empty">Выберите сущность</div></aside></div><div class="k-core-grid"><section><h2>Календарь</h2><div data-core-calendar></div></section><section><h2>Платежи</h2><div data-core-payments></div></section><section><h2>Центр уведомлений</h2><div data-core-notifications></div></section><section><h2>Последние события</h2><div data-core-events></div></section></div></section>`}
 function mountCorePlatform(){let dead=false;const root=document.querySelector('.k-core-platform');if(!root)return;
  const inspect=async(type,key)=>{const box=root.querySelector('[data-core-inspector]');box.innerHTML=ui().skeleton(4);try{const data=await repo().get(type,key,{force:true});const e=data.entity;store().setEntityGraph(type,key,{entity:e,relations:data.relations||[],timeline:data.timeline||[]});root.querySelectorAll('[data-domain-type]').forEach(node=>node.setAttribute('aria-selected',String(node===root.querySelector(`[data-domain-type=\"${CSS.escape(type)}\"][data-domain-key=\"${CSS.escape(String(key))}\"]`))));box.innerHTML=`<div class="k-core-inspector__toolbar"><span>${ui().badge(labels[type]||type,'info')}</span>${ui().button('Обновить',{tone:'secondary',attributes:{'data-domain-reload':true}})}</div><div class="k-core-inspector__head"><h2>${ui().esc(e.title)}</h2><p>${ui().esc(e.status)}</p></div><section><h3>Связи</h3>${(data.relations||[]).map(r=>ui().card({title:r.relationType,meta:`${r.sourceType}:${r.sourceKey} → ${r.targetType}:${r.targetKey}`,body:''})).join('')||ui().empty('Связей пока нет','Связи появятся после доменных действий.')}</section><section><h3>Timeline</h3>${(data.timeline||[]).length?ui().timeline((data.timeline||[]).map(x=>({title:x.eventType,text:`${x.aggregateType} · ${x.aggregateKey}`,time:x.occurredAt}))):ui().empty('Событий пока нет','История будет строиться из domain_events.')}</section>`}catch(e){box.innerHTML=ui().error('Не удалось открыть сущность',e.message)}};
  const paint=data=>{if(dead)return;store().set(data);const counts=data.counts||{};root.querySelector('[data-core-stats]').innerHTML=[['Сущности',counts.domain_entities||0],['События',counts.domain_events||0],['Календарь',counts.calendar_events||0],['Платежи',counts.payment_records||0],['Уведомления',counts.notification_center||0]].map(([a,b])=>`<div class="k-core-stat"><strong>${b}</strong><span>${a}</span></div>`).join('');store().upsertEntities(data.entities||[]);const empty=ui().empty();
   root.querySelector('[data-core-entities]').innerHTML=(data.entities||[]).map(x=>`<button class="k-core-entity" data-domain-type="${ui().esc(x.type)}" data-domain-key="${ui().esc(x.key)}"><span>${ui().badge(labels[x.type]||x.type,'neutral')}</span><strong>${ui().esc(x.title)}</strong><small>${ui().esc(x.status)}</small></button>`).join('')||empty;
   root.querySelector('[data-core-calendar]').innerHTML=(data.calendar||[]).map(x=>ui().card({title:x.title,meta:`${x.startsAt} → ${x.endsAt}`,body:ui().badge(x.status,'info')})).join('')||empty;root.querySelector('[data-core-payments]').innerHTML=(data.payments||[]).map(x=>ui().card({title:ui().money(x.amount,x.currency),meta:x.paymentKey,body:ui().badge(x.status,x.status==='paid'?'success':'warning')})).join('')||empty;root.querySelector('[data-core-notifications]').innerHTML=(data.notifications||[]).map(x=>ui().card({title:x.title,meta:x.createdAt,body:`<p>${ui().esc(x.body||'')}</p>${ui().badge(x.status,x.status==='unread'?'warning':'neutral')}`})).join('')||empty;root.querySelector('[data-core-events]').innerHTML=(data.events||[]).map(x=>ui().card({title:x.eventType,meta:`${x.aggregateType} · ${x.aggregateKey}`,body:`<time>${ui().esc(x.occurredAt)}</time>`})).join('')||empty};
  const load=async()=>{const version=store().begin();try{const result=await client().getDomainSnapshot({force:true});if(!result.ok)throw new Error(result.message||result.code||'domain_api_error');const data=result.data?.counts?result.data:result.payload;store().resolve(version,data);paint(data);window.KaretaEventBus?.emit?.('domain.snapshot.loaded',{counts:data.counts||{}});}catch(e){store().reject(version,e);root.querySelector('[data-core-stats]').innerHTML=ui().error('Не удалось загрузить Core',e.message)}};
  let selected=null;root.addEventListener('click',e=>{const b=e.target.closest('[data-domain-type]');if(b){selected={type:b.dataset.domainType,key:b.dataset.domainKey};inspect(selected.type,selected.key);return;}if(e.target.closest('[data-domain-reload]')&&selected)inspect(selected.type,selected.key);});root.querySelector('[data-core-refresh]')?.addEventListener('click',load);load();return()=>{dead=true}}
 window.KaretaCorePlatformPages=Object.freeze({renderCorePlatform,mountCorePlatform});
})();
