(() => {
'use strict';
const api=()=>window.KaretaApiClient, ui=()=>window.KaretaUIKit;
const esc=v=>ui()?.esc?.(v)??String(v??'');
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v||0))+' ₸';
const num=v=>Number(v||0);
const icon=name=>window.KaretaUIIcons?.svg?.(name)||'';
async function mutate(promise){const r=await promise;if(!r?.ok)throw new Error(r?.message||r?.code||'Операция не выполнена');return r;}
function renderFinance(){const period=new Date().toISOString().slice(0,7);return `<section class="k-page k-finance k-operational-finance k-finance-r75"><header class="k-finance-r75-toolbar"><div><strong>Финансы СТО</strong><span>Выручка, долги, касса и выплаты без вложенных карточек.</span></div><div class="k-finance-head-actions"><label><span>Период</span><input type="month" value="${period}" data-op-period></label><button class="k-btn k-btn-primary" data-fin-refresh>${icon('refresh')}<span>Обновить</span></button></div></header><div data-op-message class="k-op-fin-message"></div><div data-op-finance>${ui()?.skeleton?.(8)||'Загрузка…'}</div><details class="k-fin-legacy"><summary>Сметы, счета и бухгалтерский журнал</summary><div data-fin-legacy></div></details><dialog class="k-fin-r75-dialog" data-fin-dialog><form method="dialog" data-fin-dialog-form><header><div><small>ФИНАНСОВОЕ ДЕЙСТВИЕ</small><h2 data-fin-dialog-title>Операция</h2></div><button type="button" data-fin-dialog-close aria-label="Закрыть">${icon('close')}</button></header><div data-fin-dialog-body></div><footer><button type="button" class="k-btn k-btn-secondary" data-fin-dialog-cancel>Отмена</button><button type="submit" class="k-btn k-btn-primary" data-fin-dialog-submit>Сохранить</button></footer></form></dialog></section>`}

function summaryCards(s){return `<div class="k-op-fin-summary k-fin-r75-summary">${[['Выручка',s.revenue],['Себестоимость',s.cost],['Валовая прибыль',s.grossProfit],['Маржа',`${num(s.marginPercent).toFixed(1)}%`,true],['Долги клиентов',s.receivables],['Просрочено',s.overdue],['Начислено зарплаты',s.payrollAccrued],['Выплачено',s.payrollPaid]].map(([l,v,text])=>`<span><small>${esc(l)}</small><strong>${text?esc(v):money(v)}</strong></span>`).join('')}</div>`}
function trend(items){const max=Math.max(1,...items.map(x=>num(x.revenue)));return `<section class="k-op-fin-panel"><header><h2>Динамика за 6 месяцев</h2></header><div class="k-op-fin-trend">${items.map(x=>`<article><div><i style="height:${Math.max(4,num(x.revenue)/max*100)}%"></i><b style="height:${Math.max(3,Math.max(0,num(x.profit))/max*100)}%"></b></div><span>${esc(x.label)}</span><strong>${money(x.revenue)}</strong><small>прибыль ${money(x.profit)}</small></article>`).join('')}</div></section>`}
function profitability(items,title='Прибыльность услуг'){return `<section class="k-op-fin-panel"><header><h2>${esc(title)}</h2></header><div class="k-op-fin-table"><div class="is-head"><span>Направление</span><span>Заказы</span><span>Выручка</span><span>Затраты</span><span>Прибыль</span><span>Маржа</span></div>${items.map(x=>`<div><span>${esc(x.serviceName||x.masterName||'—')}</span><span>${num(x.ordersCount)}</span><span>${money(x.revenue)}</span><span>${money(x.cost)}</span><strong class="${num(x.profit)<0?'is-negative':''}">${money(x.profit)}</strong><span>${num(x.marginPercent).toFixed(1)}%</span></div>`).join('')||'<p>Нет завершённых заказов за период.</p>'}</div></section>`}
function receivables(items){return `<section class="k-op-fin-panel k-fin-r75-section"><header><div><h2>Долги клиентов</h2><p>Оплата связана с заказом и кассой.</p></div></header><div class="k-fin-r75-list">${items.map(x=>`<div class="k-fin-r75-row ${x.status==='overdue'?'is-overdue':''}"><span><b>${esc(x.clientName||x.clientPhone||'Клиент')}</b><small>${esc(x.title||x.orderId)} · срок ${esc(x.dueAt||'не указан')}</small></span><span><strong>${money(x.balanceAmount)}</strong><small>оплачено ${money(x.paidAmount)}</small></span><div><button class="k-btn k-btn-primary" data-order-pay="${esc(x.orderId)}" data-balance="${esc(x.balanceAmount)}">${icon('finance')}<span>Оплата</span></button><button class="k-btn k-btn-secondary" data-receivable-due="${esc(x.orderId)}">${icon('calendar')}<span>Срок</span></button></div></div>`).join('')||'<p class="k-fin-r75-empty">Задолженности отсутствуют.</p>'}</div></section>`}

function cash(d){return `<section class="k-op-fin-panel k-fin-r75-section"><header><div><h2>Касса СТО</h2><p>Баланс: <b>${money(d.summary?.cashBalance)}</b></p></div><button class="k-btn k-btn-secondary" data-cash-expense>${icon('plus')}<span>Расход</span></button></header><div class="k-fin-r75-list is-compact">${(d.cashMovements||[]).slice(0,30).map(x=>`<div class="k-fin-r75-row"><span><b>${esc(x.description||x.category)}</b><small>${esc(x.paymentMethod)} · ${esc(x.occurredAt)}</small></span><strong class="${x.movementType==='expense'?'is-negative':''}">${x.movementType==='expense'?'−':'+'}${money(x.amount)}</strong></div>`).join('')||'<p class="k-fin-r75-empty">Движений пока нет.</p>'}</div></section>`}

function payroll(d){const groups={};(d.payrollAccruals||[]).forEach(a=>{const k=a.masterId||'self';groups[k]??={masterId:k,name:a.masterName||'Мастер',amount:0,paid:0,periodId:a.periodId};groups[k].amount+=num(a.amount);if(a.status==='paid')groups[k].paid+=num(a.amount);});return `<section class="k-op-fin-panel k-fin-r75-section"><header><div><h2>Зарплата Мастеров</h2><p>Правила и выплаты в одном журнале.</p></div>${d.scope.type==='sto'?`<button class="k-btn k-btn-secondary" data-payroll-close>${icon('check')}<span>Закрыть период ${esc(d.scope.periodKey)}</span></button>`:''}</header>${d.scope.type==='sto'?`<div class="k-fin-r75-list k-fin-r75-rules">${(d.payrollRules||[]).map(r=>`<div class="k-fin-r75-row"><span><b>${esc(r.name)}</b><small>${esc(r.spec||'')} · ${esc(r.calculationMode||'Правило не задано')}</small></span><button class="k-btn k-btn-secondary" data-payroll-rule="${esc(r.id)}" data-mode="${esc(r.calculationMode||'gross_profit_percent')}" data-percent="${esc(r.basePercent||0)}" data-hourly="${esc(r.hourlyRate||0)}" data-fixed="${esc(r.fixedMonthly||0)}">${icon('settings')}<span>Настроить</span></button></div>`).join('')}</div>`:''}<div class="k-fin-r75-list">${Object.values(groups).map(g=>`<div class="k-fin-r75-row"><span><b>${esc(g.name)}</b><small>Начислено ${money(g.amount)} · выплачено ${money(g.paid)}</small></span>${d.scope.type==='sto'&&g.amount-g.paid>0?`<button class="k-btn k-btn-primary" data-payroll-pay="${esc(g.masterId)}" data-period-id="${esc(g.periodId||'')}">${icon('finance')}<span>Выплатить ${money(g.amount-g.paid)}</span></button>`:''}</div>`).join('')||'<p class="k-fin-r75-empty">Начислений за период ещё нет.</p>'}</div></section>`}

function orders(items){return `<section class="k-op-fin-panel"><header><h2>Финансовый результат заказов</h2></header><div class="k-op-fin-table"><div class="is-head"><span>Заказ</span><span>Клиент</span><span>Выручка</span><span>Затраты</span><span>Прибыль</span><span>Маржа</span></div>${items.map(x=>`<div><a href="#/orders/item/${encodeURIComponent(x.orderId)}">${esc(x.serviceNames||x.orderId)}</a><span>${esc(x.clientName||x.clientPhone||'—')}</span><span>${money(x.revenueTotal)}</span><span>${money(x.directCostTotal)}</span><strong>${money(x.grossProfit)}</strong><span>${num(x.marginPercent).toFixed(1)}%</span></div>`).join('')||'<p>Нет данных.</p>'}</div></section>`}
function operational(d){return `${summaryCards(d.summary||{})}${trend(d.trend||[])}<div class="k-fin-r75-two">${profitability(d.serviceProfitability||[])}${d.scope?.type==='sto'?profitability(d.masterProfitability||[],'Результат по Мастерам'):''}</div>${receivables(d.receivables||[])}${d.scope?.type==='sto'?cash(d):''}${payroll(d)}${orders(d.orders||[])}`}
function legacy(d){const x=d.summary||{};return `<div class="k-fin-summary">${[['Выставлено',x.invoiced],['Оплачено',x.paid],['К оплате',x.outstanding]].map(a=>`<article><span>${a[0]}</span><strong>${money(a[1])}</strong></article>`).join('')}</div><div class="k-op-fin-grid"><section class="k-op-fin-panel"><h2>Счета</h2>${(d.invoices||[]).map(i=>`<article><b>${esc(i.title)}</b><span>${money(i.paidAmount)} / ${money(i.totalAmount)}</span></article>`).join('')||'<p>Счетов нет.</p>'}</section><section class="k-op-fin-panel"><h2>Последние проводки</h2>${(d.ledger||[]).slice(0,20).map(l=>`<article><b>${esc(l.description||l.accountCode)}</b><span>${esc(l.entryType)} ${money(l.amount)}</span></article>`).join('')||'<p>Проводок нет.</p>'}</section></div>`}
async function mountFinance(){
  const root=document.querySelector('.k-finance');if(!root)return;
  const host=root.querySelector('[data-op-finance]'),dialog=root.querySelector('[data-fin-dialog]'),dialogForm=root.querySelector('[data-fin-dialog-form]'),dialogBody=root.querySelector('[data-fin-dialog-body]'),dialogTitle=root.querySelector('[data-fin-dialog-title]');
  const msg=t=>root.querySelector('[data-op-message]').textContent=t||'';let current=null,dialogState=null;
  const paymentMethods=[['cash','Наличные'],['card','Карта'],['bank_transfer','Перевод']];
  const payrollModes=[['revenue_percent','% от выручки'],['gross_profit_percent','% от прибыли'],['labor_percent','% от работ'],['hourly','Почасовая'],['fixed_plus_percent','Фикс + %']];
  const choice=(name,items,value)=>`<div class="k-fin-r75-choice" data-choice="${esc(name)}">${items.map(([v,l])=>`<button type="button" class="${String(v)===String(value)?'is-active':''}" data-choice-value="${esc(v)}">${esc(l)}</button>`).join('')}</div><input type="hidden" name="${esc(name)}" value="${esc(value)}">`;
  const closeDialog=()=>{dialogState=null;dialog?.open&&dialog.close();};
  const openDialog=(kind,title,body,state={})=>{dialogState={kind,...state};dialogTitle.textContent=title;dialogBody.innerHTML=body;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');};
  const load=async()=>{host.innerHTML=ui().skeleton(8);msg('');try{const period=root.querySelector('[data-op-period]').value;const [op,old]=await Promise.all([api().getOperationalFinanceDashboard({period}),api().getFinanceView()]);if(!op.ok)throw new Error(op.message);current=op.data||op.payload?.data||{};host.innerHTML=operational(current);root.querySelector('[data-fin-legacy]').innerHTML=old.ok?legacy(old.data||old.payload?.data||{}):`<p>${esc(old.message)}</p>`;}catch(e){host.innerHTML=ui().error(e.message||'Не удалось загрузить финансовые данные')}};
  root.addEventListener('change',e=>{if(e.target.matches('[data-op-period]'))load()});
  root.addEventListener('click',async e=>{try{
    if(e.target.closest('[data-fin-refresh]'))return load();
    if(e.target.closest('[data-fin-dialog-close],[data-fin-dialog-cancel]'))return closeDialog();
    const choiceButton=e.target.closest('[data-choice-value]');if(choiceButton){const wrap=choiceButton.closest('[data-choice]'),name=wrap?.dataset.choice,input=dialogBody.querySelector(`input[name="${name}"]`);wrap?.querySelectorAll('[data-choice-value]').forEach(b=>b.classList.toggle('is-active',b===choiceButton));if(input)input.value=choiceButton.dataset.choiceValue||'';return;}
    const pay=e.target.closest('[data-order-pay]');if(pay){openDialog('payment','Принять оплату',`<label>Сумма, ₸<input name="amount" type="number" min="1" step="1" required value="${esc(pay.dataset.balance||0)}"></label><div><span>Способ оплаты</span>${choice('method',paymentMethods,'cash')}</div>`,{orderId:pay.dataset.orderPay});return;}
    const due=e.target.closest('[data-receivable-due]');if(due){openDialog('due','Изменить срок оплаты',`<label>Новый срок<input name="dueAt" type="date" required></label>`,{orderId:due.dataset.receivableDue});return;}
    if(e.target.closest('[data-cash-expense]')){openDialog('expense','Добавить расход',`<label>Сумма, ₸<input name="amount" type="number" min="1" step="1" required></label><label>Назначение<input name="description" maxlength="180" required placeholder="Например: расходные материалы"></label><div><span>Способ оплаты</span>${choice('method',paymentMethods,'cash')}</div>`);return;}
    const rule=e.target.closest('[data-payroll-rule]');if(rule){openDialog('payroll-rule','Правило зарплаты',`<div><span>Схема расчёта</span>${choice('calculationMode',payrollModes,rule.dataset.mode||'gross_profit_percent')}</div><label>Процент<input name="basePercent" type="number" min="0" max="100" step="0.1" value="${esc(rule.dataset.percent||0)}"></label><label>Ставка за час, ₸<input name="hourlyRate" type="number" min="0" step="1" value="${esc(rule.dataset.hourly||0)}"></label><label>Фикс за месяц, ₸<input name="fixedMonthly" type="number" min="0" step="1" value="${esc(rule.dataset.fixed||0)}"></label>`,{masterId:rule.dataset.payrollRule});return;}
    if(e.target.closest('[data-payroll-close]')){await mutate(api().closePayrollPeriod({periodKey:current.scope.periodKey}));return load();}
    const salary=e.target.closest('[data-payroll-pay]');if(salary){if(!salary.dataset.periodId)throw new Error('Сначала закройте расчётный период');await mutate(api().payPayroll({periodId:salary.dataset.periodId,masterId:salary.dataset.payrollPay,method:'cash'}));return load();}
  }catch(err){msg(err.message||'Операция не выполнена')}});
  dialogForm?.addEventListener('submit',async e=>{e.preventDefault();if(!dialogState)return;const fd=new FormData(dialogForm),data=Object.fromEntries(fd.entries());try{dialogForm.querySelector('[data-fin-dialog-submit]').disabled=true;if(dialogState.kind==='payment')await mutate(api().recordOrderPayment({orderId:dialogState.orderId,amount:data.amount,method:data.method||'cash'}));else if(dialogState.kind==='due')await mutate(api().updateReceivableDue({orderId:dialogState.orderId,dueAt:String(data.dueAt||'')+' 23:59:59'}));else if(dialogState.kind==='expense')await mutate(api().recordStoExpense({amount:data.amount,description:data.description,method:data.method||'cash'}));else if(dialogState.kind==='payroll-rule')await mutate(api().savePayrollRule({masterId:dialogState.masterId,calculationMode:data.calculationMode||'gross_profit_percent',basePercent:data.basePercent||0,hourlyRate:data.hourlyRate||0,fixedMonthly:data.fixedMonthly||0}));closeDialog();await load();}catch(err){msg(err.message||'Операция не выполнена')}finally{const b=dialogForm.querySelector('[data-fin-dialog-submit]');if(b)b.disabled=false;}});
  await load();
}

window.KaretaFinancePages=Object.freeze({renderFinance,mountFinance});
})();
