(() => {
  'use strict';
  const api=window.KaretaApiClient;
  const social=window.KaretaSocialState;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v||0));
  function renderFollowing(){return `<main class="k-following-page k-following-ref-v2" data-following-page><header class="k-following-head"><div><h1>Мои подписки</h1><p>Мастера и СТО, новости и работы которых вы отслеживаете.</p></div><a class="k-btn k-btn-secondary" href="#/masters">Найти специалистов</a></header><nav class="k-following-tabs" aria-label="Фильтр подписок"><button class="is-active" data-following-tab="all">Все</button><button data-following-tab="masters">Мастера</button><button data-following-tab="sto">СТО</button><button data-following-tab="news">Новости</button><button data-following-tab="works">Работы</button></nav><section class="k-following-list" data-following-list><div class="k-following-skeleton">${'<i></i>'.repeat(3)}</div></section></main>`;}
  function providerLink(row){return row.type==='sto'?`#/masters/profile/sto/${encodeURIComponent(row.id)}`:`#/masters/profile/master/${encodeURIComponent(row.id)}`;}
  function card(row){const social=row.social_state||{},isSto=row.type==='sto',label=isSto?'СТО':'Мастер',spec=row.spec||row.description||(isSto?'Автосервис':'Автомастер');return `<article class="k-following-card" data-following-card="${esc(row.id)}" data-provider-type="${isSto?'sto':'master'}"><div class="k-following-avatar">${esc((row.initials||row.name||label).slice(0,2).toUpperCase())}</div><div class="k-following-main"><div class="k-following-title"><div><small>${label}</small><h2>${esc(row.name||label)}</h2><p>${esc(spec)}</p></div><button type="button" class="k-following-unfollow" data-following-unfollow="${esc(row.id)}" data-provider-type="${isSto?'sto':'master'}">Подписан</button></div><div class="k-following-metrics">${!isSto?`<span>★ ${Number(row.rating||0).toFixed(1)}</span>`:''}${Number(row.min_price||0)>0?`<span>от ${money(row.min_price)} ₸</span>`:''}<span>${Number(row.followers_count||0)} подписчиков</span></div><div class="k-following-settings"><label><input type="checkbox" data-following-setting="followNews" data-provider-type="${isSto?'sto':'master'}" data-provider-id="${esc(row.id)}" ${social.followNews!==false?'checked':''}> Новости</label><label><input type="checkbox" data-following-setting="followWorks" data-provider-type="${isSto?'sto':'master'}" data-provider-id="${esc(row.id)}" ${social.followWorks!==false?'checked':''}> Работы</label></div><div class="k-following-actions"><a href="${providerLink(row)}?tab=wall">Стена</a><a href="#/chats?${isSto?'stoId':'masterId'}=${encodeURIComponent(row.id)}">Сообщение</a><a href="${providerLink(row)}">Профиль</a></div></div></article>`;}
  async function mountFollowing(ctx={}){
    const root=document.querySelector('[data-following-page]'),list=root?.querySelector('[data-following-list]');if(!root||!list)return;
    let items=[],tab=sessionStorage.getItem('kareta.following.tab')||'all',busy=false,pending=new Set();
    root.querySelectorAll('[data-following-tab]').forEach(x=>x.classList.toggle('is-active',x.dataset.followingTab===tab));const paint=()=>{const shown=items.filter(x=>tab==='all'||tab===x.type||(tab==='masters'&&x.type==='master')||(tab==='news'&&x.social_state?.followNews!==false)||(tab==='works'&&x.social_state?.followWorks!==false));list.innerHTML=shown.length?shown.map(card).join(''):`<div class="k-empty"><h2>${items.length?'Нет подписок с таким фильтром':'Вы пока ни на кого не подписаны'}</h2><p>${items.length?'Измените фильтр или настройки подписок.':'Откройте каталог и подпишитесь на интересных мастеров или СТО.'}</p><a class="k-btn k-btn-primary" href="#/masters">Найти специалистов</a></div>`;};
    const load=async()=>{if(busy)return;busy=true;try{const r=await api.getFollowingMasters({signal:ctx.lifecycle?.signal});if(!r?.ok)throw new Error(r?.payload?.message||'Не удалось загрузить подписки');items=Array.isArray(r.payload?.items)?r.payload.items:[];social?.replaceFollowing?.(items);paint();}catch(e){if(e?.name==='AbortError')return;list.innerHTML=`<div class="k-empty"><h2>Не удалось загрузить подписки</h2><p>${esc(e.message||'Повторите позже.')}</p><button class="k-btn k-btn-primary" data-following-retry>Повторить</button></div>`;}finally{busy=false;}};
    const onClick=async e=>{const t=e.target.closest('[data-following-tab]');if(t){tab=t.dataset.followingTab;sessionStorage.setItem('kareta.following.tab',tab);root.querySelectorAll('[data-following-tab]').forEach(x=>x.classList.toggle('is-active',x===t));paint();return;}const u=e.target.closest('[data-following-unfollow]');if(u){const id=u.dataset.followingUnfollow,type=u.dataset.providerType,key=`unfollow:${type}:${id}`;if(pending.has(key))return;pending.add(key);u.disabled=true;try{const r=type==='sto'?await api.updateStoSocial(id,'following',false):await api.updateMasterSocial(id,'following',false);if(!r?.ok)throw new Error(r?.payload?.message||'Не удалось отменить подписку');items=items.filter(x=>!(String(x.id)===String(id)&&x.type===type));paint();window.KaretaToast?.success?.('Подписка отменена');}catch(err){u.disabled=false;window.KaretaToast?.error?.(err.message||'Не удалось отменить подписку');}finally{pending.delete(key);}return;}if(e.target.closest('[data-following-retry]'))load();};
    const onChange=async e=>{const c=e.target.closest('[data-following-setting]');if(!c)return;const id=c.dataset.providerId,type=c.dataset.providerType,field=c.dataset.followingSetting,key=`setting:${type}:${id}:${field}`;if(pending.has(key)){c.checked=!c.checked;return;}pending.add(key);c.disabled=true;try{const r=type==='sto'?await api.updateStoSocial(id,field,c.checked):await api.updateMasterSocial(id,field,c.checked);if(!r?.ok)throw new Error(r?.payload?.message||'Не удалось сохранить настройку');const row=items.find(x=>String(x.id)===String(id)&&x.type===type);if(row){row.social_state=row.social_state||{};row.social_state[field]=c.checked;}window.KaretaToast?.success?.('Настройки обновлены');}catch(err){c.checked=!c.checked;window.KaretaToast?.error?.(err.message||'Не удалось сохранить настройку');}finally{pending.delete(key);c.disabled=false;}};
    const unsubscribeSocial=social?.on?.(event=>{if(!document.contains(root))return;if(event.type==='provider.following'&&!event.following){items=items.filter(row=>!(String(row.id)===String(event.providerId)&&String(row.type)===String(event.providerType)));paint();}if(event.type==='provider.setting'){const row=items.find(x=>String(x.id)===String(event.providerId)&&String(x.type)===String(event.providerType));if(row){row.social_state=row.social_state||{};row.social_state[event.field]=event.value;paint();}}});
    root.addEventListener('click',onClick);root.addEventListener('change',onChange);ctx.lifecycle?.addCleanup?.(()=>{unsubscribeSocial?.();root.removeEventListener('click',onClick);root.removeEventListener('change',onChange);});
    await load();
  }
  window.KaretaFollowingPages=Object.freeze({renderFollowing,mountFollowing});
})();
