(() => {
  'use strict';
  const ui=window.KaretaPageUI;
  const apiModule=window.KaretaMasterScheduleApi;
  if(!ui||!apiModule) throw new Error('Master schedule dependencies are required');
  const MASTER_CAPACITY_R67_CONTRACT='R188.5.5.6.67';
  const MASTER_SHIFT_R69_CONTRACT='R188.5.5.6.69';
  const MASTER_DAY_OPS_R70_CONTRACT='R188.5.5.6.70';
  const MASTER_UI_R71_CONTRACT='R188.5.5.6.71';
  const MASTER_RECOVERY_R72_CONTRACT='R188.5.5.6.72';
  const MASTER_WORKSPACE_R81_CONTRACT='R188.5.5.6.81';
  const esc=ui.escHtml;
  const state={data:null,error:'',lastRecoveryScanAt:0,countdownTimer:0,recoveryTimer:0};
  const mins=v=>Math.max(0,Number(v||0));
  const durationLabel=v=>{const m=mins(v),h=Math.floor(m/60),r=m%60;return h?(r?`${h} ч ${r} мин`:`${h} ч`):`${r} мин`;};
  const dateLabel=v=>{try{return new Date(`${v}T00:00:00`).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'});}catch(_e){return v;}};
  const dateTimeLabel=v=>{if(!v)return '—';try{return new Date(String(v).replace(' ','T')).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}catch(_e){return String(v);}};
  const toInputDateTime=v=>String(v||'').replace(' ','T').slice(0,16);
  const time=v=>String(v||'').slice(-8,-3).includes(':')?String(v||'').slice(-8,-3):String(v||'').slice(0,5);
  const icon=(name,className='k-master-r71-icon')=>window.KaretaUIIcons?.svg?.(name,{className})||'';
  const carIcon=icon('car');
  const weekdayNames=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
  const blockLabels={lunch:'Обед',technical:'Технический перерыв',personal:'Личная блокировка',meeting:'Встреча'};
  const arrivalLabels={on_way:'Едет',arrived:'Прибыл',late:'Опаздывает',no_show:'Не приехал'};
  const serviceRules={
    'Диагностика':['Зафиксировать жалобу клиента и входные параметры','Провести сканирование и первичные измерения','Сохранить результаты и согласовать дальнейшие работы'],
    'Замена масла':['Проверить уровень и отсутствие течей до начала работ','Заменить масло и фильтр по спецификации автомобиля','Запустить двигатель, проверить давление и герметичность'],
    'Тормоза':['Проверить остаток колодок, дисков и состояние направляющих','Выполнить работы с очисткой и смазкой допустимых зон','Проверить педаль тормоза и выполнить контрольный осмотр'],
    'Подвеска':['Провести осмотр на подъёмнике и проверить люфты','Зафиксировать дефекты фото и согласовать перечень работ','После ремонта проверить крепёж и выполнить контрольную поездку'],
    'Электрика':['Проверить питание, массу и состояние предохранителей','Выполнить измерения под нагрузкой и локализовать цепь','После ремонта удалить ошибки и провести повторную проверку'],
    'Кондиционер':['Проверить давление, температуру и утечки','Выполнить обслуживание только после диагностики герметичности','Проверить работу системы во всех режимах'],
    'default':['Провести приёмку и фотофиксацию состояния автомобиля','Согласовать объём, цену и дополнительные работы до выполнения','После ремонта провести контроль качества и оформить результат']
  };
  function regulationFor(service){const name=String(service||''),key=Object.keys(serviceRules).find(k=>k!=='default'&&name.toLowerCase().includes(k.toLowerCase()))||'default';return serviceRules[key];}
  function renderMasterSchedule(){return `<section class="k-page k-master-page k-master-surface-page k-master-schedule-page" data-r67-contract="${MASTER_CAPACITY_R67_CONTRACT}" data-r69-contract="${MASTER_SHIFT_R69_CONTRACT}" data-r70-contract="${MASTER_DAY_OPS_R70_CONTRACT}" data-r72-contract="${MASTER_RECOVERY_R72_CONTRACT}"><div id="k-master-schedule" class="k-master-schedule"><section class="k-empty"><h2>Загружаем график</h2><p>Рассчитываем смены, перерывы, занятость и фактическое время ремонта.</p></section></div></section>`;}
  function summary(d){const a=d.analytics||{},w=a.weekForecast||{};return `<section class="k-master-schedule-summary"><article><span class="k-summary-icon">${carIcon}</span><strong>${Number(a.ordersPlanned||0)}</strong><span>реальных машин</span></article><article><strong>${durationLabel(a.averageRepairMinutes||0)}</strong><span>среднее время ремонта</span></article><article><strong>${durationLabel(w.freeMinutes||0)}</strong><span>свободно на 7 дней</span></article><article><strong>${Number(w.loadPct||0).toFixed(0)}%</strong><span>загрузка недели</span></article></section>`;}
  function weeklyForecast(d){const w=d.analytics?.weekForecast||{},days=Array.isArray(w.days)?w.days:[];return `<section class="k-master-r69-forecast"><header><div><small>7 ДНЕЙ</small><h2>Прогноз загрузки</h2></div><p>${durationLabel(w.bookedMinutes||0)} занято · ${durationLabel(w.blockedMinutes||0)} перерывы · ${durationLabel(w.freeMinutes||0)} свободно</p></header><div>${days.map(day=>`<article class="${day.warning?'is-warning':''}"><span>${esc(dateLabel(day.date))}</span><strong>${Number(day.loadPct||0).toFixed(0)}%</strong><small>${durationLabel(day.bookedMinutes||0)} / ${durationLabel(day.workMinutes||0)}</small></article>`).join('')}</div></section>`;}
  function weeklyTemplate(d){const rows=Array.isArray(d.weeklyTemplate)?d.weeklyTemplate:[];return `<section class="k-master-r69-weekly"><header><div><small>ШАБЛОН НЕДЕЛИ</small><h2>Мои смены</h2><p>Этот шаблон применяется автоматически. Настройка конкретной даты ниже имеет приоритет.</p></div></header><form data-weekly-shift-form>${rows.map((row,index)=>`<div class="k-master-r69-week-row" data-weekday="${Number(row.weekday||index+1)}"><strong>${weekdayNames[index]||`День ${index+1}`}</strong><label>Начало<input type="time" name="startTime" value="${esc(row.startTime||'09:00')}"></label><label>Конец<input type="time" name="endTime" value="${esc(row.endTime||'18:00')}"></label><label class="k-master-r69-dayoff"><input type="checkbox" name="isDayOff" ${row.isDayOff?'checked':''}> Выходной</label></div>`).join('')}<button class="k-btn k-btn--primary" type="submit">Сохранить шаблон недели</button></form></section>`;}
  function recoveryStatusLabel(item){const status=String(item?.status||'');return ({safe:'Можно перенести',protected:'Защищено',unresolved:'Нет свободного окна',tariff_blocked:'Лимит тарифа',bay_blocked:'Нет свободного бокса',race_conflict:'Конфликт изменился'})[status]||status||'Конфликт';}
  function recoveryPanel(d){
    const r=d.autoRecovery||{},recent=Array.isArray(r.recent)?r.recent:[],control=r.controlCenter||{},items=Array.isArray(control.items)?control.items:[],sum=control.summary||{},notifications=Array.isArray(r.notifications)?r.notifications:[];
    const rows=items.length?items.map(item=>{const can=!!item.safe,prot=!!item.protected,reason=(Array.isArray(item.reasonLabels)?item.reasonLabels:[]).join(' · ')||recoveryStatusLabel(item);return `<article class="k-master-r72-conflict ${can?'is-safe':''} ${prot?'is-protected':''}" data-recovery-order="${esc(item.orderId||'')}"><label class="k-master-r72-select"><input type="checkbox" data-recovery-select value="${esc(item.orderId||'')}" ${can?'checked':'disabled'}><span></span></label><div class="k-master-r72-conflict__main"><div><strong>${esc(item.vehicleTitle||'Автомобиль')}</strong><span>${esc(item.serviceNames||'Работы')}</span></div><small>${esc(reason)}</small><div class="k-master-r72-route"><span><b>Сейчас</b>${esc(dateTimeLabel(item.oldStart))}</span><i>${icon('chevronRight')}</i><span><b>${can?'Предложение':'Статус'}</b>${can?esc(dateTimeLabel(item.candidateStart)):esc(recoveryStatusLabel(item))}</span></div>${item.bay?.required?`<small>Бокс СТО: ${item.bay.available?esc(item.bay.bayName||'свободный найден'):'свободного бокса нет'}</small>`:''}</div><div class="k-master-r72-conflict__actions"><button type="button" data-recovery-protect="${esc(item.orderId||'')}" data-protected="${prot?'1':'0'}">${icon(prot?'unlock':'lock')}<span>${prot?'Снять защиту':'Защитить'}</span></button></div></article>`;}).join(''):'<div class="k-master-r72-empty"><strong>Конфликтов нет</strong><span>Текущий график не требует ручного восстановления.</span></div>';
    const history=notifications.length?notifications.slice(0,12).map(n=>`<article><div><b>${esc(n.title||'Уведомление')}</b><span>${esc(n.body||'')}</span><small>${esc(dateTimeLabel(n.createdAt))} · ${n.isRead?'прочитано':'не прочитано'}</small></div><button type="button" data-recovery-resend="${esc(n.orderId||'')}">${icon('bell')}<span>Повторить</span></button></article>`).join(''):'<div class="k-master-r72-empty"><span>Уведомлений о переносах пока нет.</span></div>';
    return `<section class="k-master-r72-control" data-r72-recovery-control><header><div><small>R72 · КОНТРОЛЬ ГРАФИКА</small><h2>Конфликты и автопереносы</h2><p>Сначала preview, затем применение. Защищённые записи автоматика не двигает.</p></div><button class="k-btn k-btn--secondary" type="button" data-recovery-preview>${icon('refresh')}<span>Обновить preview</span></button></header><div class="k-master-r72-stats"><span><b>${Number(sum.conflicts||0)}</b> конфликтов</span><span><b>${Number(sum.safe||0)}</b> можно перенести</span><span><b>${Number(sum.protected||0)}</b> защищено</span><span><b>${Number(sum.tariffBlocked||0)+Number(sum.bayBlocked||0)}</b> заблокировано</span></div><div class="k-master-r72-conflicts" data-recovery-conflicts>${rows}</div><footer><label><input type="checkbox" data-recovery-notify ${r.notifyEnabled!==false?'checked':''}> Уведомить клиентов после переноса</label><div><button class="k-btn k-btn--secondary" type="button" data-recovery-apply-selected ${Number(sum.safe||0)?'':'disabled'}>Применить выбранные</button><button class="k-btn k-btn--primary" type="button" data-recovery-apply-all ${Number(sum.safe||0)?'':'disabled'}>Применить все безопасные</button></div></footer><details class="k-master-r72-history"><summary>История уведомлений</summary><div>${history}</div></details>${recent.length?`<details class="k-master-r72-runs"><summary>Последние recovery-run</summary><div>${recent.map(x=>`<article><b>${esc(dateTimeLabel(x.createdAt))}</b><span>${esc(x.triggerType||'recovery')}</span><small>перенесено ${Number(x.movedCount||0)} · уведомлено ${Number(x.notifiedCount||0)}</small></article>`).join('')}</div></details>`:''}</section>`;
  }
  function dayTimeline(d){
    const day=(Array.isArray(d.days)?d.days:[]).find(x=>x.isToday)||null;if(!day)return '';
    const rows=[];
    (Array.isArray(day.blocks)?day.blocks:[]).forEach(x=>rows.push({time:x.startTime,end:x.endTime,type:'block',title:blockLabels[x.type]||'Блокировка',meta:x.note||'',icon:'clock'}));
    (Array.isArray(day.items)?day.items:[]).forEach(x=>rows.push({time:x.plannedStart,end:x.plannedEnd,type:x.timer?'running':(x.noShow?'no_show':'order'),title:x.vehicleTitle||'Автомобиль',meta:x.serviceNames||'Работы',orderId:x.id,chatId:x.chatId||'',icon:x.timer?'work':(x.noShow?'warning':'car')}));
    rows.sort((a,b)=>String(a.time||'').localeCompare(String(b.time||'')));
    const body=rows.length?rows.map(x=>{
      const chat=x.chatId?`<a href="#/chats" data-order-chat="${esc(x.chatId)}">${icon('chats')}<span>Чат</span></a>`:'';
      const actions=x.orderId?`<nav><a href="#/orders/item/${encodeURIComponent(x.orderId)}">${icon('orders')}<span>Заказ</span></a>${chat}</nav>`:'';
      return `<li class="is-${esc(x.type)}"><div class="k-master-r71-day__time"><strong>${esc(time(x.time))}</strong>${x.end?`<small>${esc(time(x.end))}</small>`:''}</div><span class="k-master-r71-day__marker" aria-hidden="true">${icon(x.icon)}</span><div class="k-master-r71-day__event"><strong>${esc(x.title)}</strong><small>${esc(x.meta)}</small></div>${actions}</li>`;
    }).join(''):'<li class="is-empty"><div class="k-master-r71-day__event"><strong>Свободный день</strong><small>Записей и блокировок на сегодня нет.</small></div></li>';
    return `<section class="k-master-r70-timeline k-master-r71-day" data-r71-day-timeline><header><div><span class="k-master-r71-section-icon">${icon('calendar')}</span><div><small>СЕГОДНЯ</small><h2>График рабочего дня</h2></div></div><span>${rows.length} событий</span></header><ol class="k-master-r71-day__list">${body}</ol></section>`;
  }

  function recoveryToast(payload){const r=payload?.recovery||payload?.payload?.recovery||{};const moved=Number(r.movedCount||0),notified=Number(r.notifiedCount||0);if(moved>0)window.KaretaToast?.success?.(`График восстановлен: перенесено ${moved}, уведомлено ${notified}`);return r;}
  function updateArrivalCountdowns(root){root?.querySelectorAll?.('[data-arrival-countdown]').forEach(el=>{const raw=String(el.dataset.arrivalCountdown||'');const ts=Date.parse(raw.replace(' ','T'));if(!Number.isFinite(ts)){el.textContent='ETA не указан';return;}const diff=Math.round((ts-Date.now())/60000);if(diff>1)el.textContent=`через ${diff} мин`;else if(diff>=-1)el.textContent='ожидается сейчас';else el.textContent=`ETA истёк ${Math.abs(diff)} мин назад`;});}

  function regulation(o){const steps=Array.isArray(o.regulation)&&o.regulation.length?o.regulation:regulationFor(o.serviceNames);return `<details class="k-schedule-regulation"><summary>Регламент ремонта</summary><ol>${steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p>Регламент сформирован из работ заявки. Мастер уточняет его после диагностики и согласования с клиентом.</p></details>`;}
  function arrivalControls(o){const arrival=o.arrival||{},status=String(arrival.status||''),locked=status==='no_show';return `<section class="k-master-r69-arrival ${locked?'is-no-show':''}"><div><small>ПРИЕЗД КЛИЕНТА</small><strong>${esc(arrivalLabels[status]||'Статус не указан')}</strong>${Number(arrival.etaMinutes||0)>0&&['on_way','late'].includes(status)?`<span>ETA ${Number(arrival.etaMinutes)} мин · <b data-arrival-countdown="${esc(arrival.etaAt||'')}">${esc(dateTimeLabel(arrival.etaAt))}</b></span>`:''}</div>${locked?'<p>Неявка зафиксирована, окно освобождено. Для новой записи используйте перенос.</p>':`<label>ETA<input type="number" min="5" max="360" step="5" value="${Math.max(5,Number(arrival.etaMinutes||15))}" data-master-arrival-eta></label><div><button type="button" data-master-arrival="arrived" data-order-id="${esc(o.id)}">Клиент прибыл</button><button type="button" data-master-arrival="late" data-order-id="${esc(o.id)}">Опаздывает</button><button type="button" class="is-danger" data-master-arrival="no_show" data-order-id="${esc(o.id)}">Не приехал</button></div>`}</section>`;}
  function delayImpact(o){const impact=o.delayImpact||{},items=Array.isArray(impact.impacted)?impact.impacted:[];if(!impact.projectedEnd||Number(impact.delayMin||0)<=0)return '';return `<section class="k-master-r69-delay"><header><div><small>РИСК СДВИГА</small><strong>Прогноз +${Number(impact.delayMin)} мин</strong></div><span>до ${esc(time(impact.projectedEnd))}</span></header>${items.length?`<p>Затронуто следующих записей: ${items.length}</p><div>${items.map(x=>`<button type="button" data-schedule-reschedule="${esc(x.orderId)}" data-schedule-current="${esc(toInputDateTime(x.plannedStart))}"><b>${esc(x.vehicleTitle||'Автомобиль')}</b><span>${esc(time(x.plannedStart))} · риск +${Number(x.minutesLate||0)} мин</span><em>Подобрать перенос</em></button>`).join('')}</div>`:'<p>Текущий ремонт выйдет за плановое время, но следующие записи пока не пересекаются.</p>'}</section>`;}
  function slot(o,dayDate){
    const running=o.timer&&o.timer.status==='running',late=Number(o.latenessMin||0)>0,noShow=!!o.noShow;
    return `<article class="k-schedule-slot k-schedule-slot--r71 ${running?'is-running':''} ${o.conflict?'has-conflict':''} ${late?'is-late':''} ${noShow?'is-no-show':''}" data-schedule-order="${esc(o.id)}"><div class="k-schedule-slot-time"><strong>${esc(time(o.plannedStart))}</strong><span>${esc(time(o.plannedEnd))}</span>${late?`<em>+${Math.round(Number(o.latenessMin))} мин</em>`:''}</div><div class="k-schedule-slot-main"><div class="k-schedule-slot-badges"><span class="k-schedule-slot-status">${noShow?'Неявка':esc(o.statusLabel||o.status||'Запланировано')}</span>${late?'<span class="k-schedule-slot-late">Опоздание старта</span>':''}</div><div class="k-schedule-r71-subject"><span aria-hidden="true">${icon('car')}</span><div><h3>${esc(o.vehicleTitle||o.clientCar||'Автомобиль')}</h3><p>${esc(o.serviceNames||'Работы по заявке')}</p></div></div><small>${esc(o.clientName||'Клиент')} · работа ${durationLabel(o.estimatedRepairMin)} + ${durationLabel(o.bufferMin)} резерв</small><div class="k-schedule-slot-metrics"><span>${icon('clock')}Среднее ${durationLabel(o.averageRepairMin||o.estimatedRepairMin)}</span><span>${icon('work')}Факт ${durationLabel(o.actualMinutes||0)}</span>${o.conflict?`<b>${icon('warning')}Пересечение времени</b>`:''}</div>${arrivalControls(o)}${delayImpact(o)}${regulation(o)}</div><div class="k-schedule-slot-actions"><a class="k-btn k-btn--secondary" href="#/orders/item/${encodeURIComponent(o.id)}">${icon('orders')}<span>Заказ</span></a>${o.chatId?`<a class="k-btn k-btn--secondary" href="#/chats" data-order-chat="${esc(o.chatId)}">${icon('chats')}<span>Чат</span></a>`:''}${!running?`<button class="k-btn k-btn--secondary" type="button" data-schedule-reschedule="${esc(o.id)}" data-schedule-current="${esc(dayDate&&o.plannedStart?`${dayDate}T${o.plannedStart}`:(o.plannedStart||''))}">${icon('calendar')}<span>${noShow?'Новая запись':'Перенести'}</span></button><button class="k-btn k-btn--secondary ${o.autoRecoveryProtected?'is-protected':''}" type="button" data-recovery-protect="${esc(o.id)}" data-protected="${o.autoRecoveryProtected?'1':'0'}">${icon(o.autoRecoveryProtected?'unlock':'lock')}<span>${o.autoRecoveryProtected?'Снять защиту':'Защитить'}</span></button>`:''}${noShow?'':running?`<button class="k-btn k-btn--primary" type="button" data-schedule-stop="${esc(o.timer.id)}">${icon('check')}<span>Завершить</span></button>`:`<button class="k-btn k-btn--primary" type="button" data-schedule-start="${esc(o.id)}">${icon('work')}<span>Взять авто</span></button>`}</div></article>`;
  }

  function freeIntervals(day){const rows=Array.isArray(day.freeIntervals)?day.freeIntervals:[];if(day.isDayOff)return '<span class="k-schedule-capacity__off">Выходной</span>';if(!rows.length)return '<span class="k-schedule-capacity__none">Свободных окон в рабочем дне нет</span>';return `<div class="k-schedule-free-intervals">${rows.slice(0,8).map(x=>`<span>${esc(time(x.start))}–${esc(time(x.end))} · ${durationLabel(x.minutes||0)}</span>`).join('')}</div>`;}
  function blocks(day){
    const rows=Array.isArray(day.blocks)?day.blocks:[];
    return `<section class="k-master-r69-blocks k-master-r71-blocks"><header><div><span aria-hidden="true">${icon('clock')}</span><div><small>ПЕРЕРЫВЫ</small><strong>${rows.length?`${rows.length} интервал${rows.length===1?'':'а'}`:'Нет блокировок'}</strong></div></div>${!day.isDayOff?`<button type="button" data-block-open="${esc(day.date)}">${icon('plus')}<span>Добавить</span></button>`:''}</header>${rows.length?`<div>${rows.map(row=>`<article><span>${esc(blockLabels[row.type]||'Перерыв')}</span><b>${esc(row.startTime)}–${esc(row.endTime)}</b>${row.note?`<small>${esc(row.note)}</small>`:''}<button type="button" data-block-delete="${esc(row.id)}" aria-label="Удалить">${icon('trash')}</button></article>`).join('')}</div>`:''}</section>`;
  }

  function dayCard(day){
    const items=Array.isArray(day.items)?day.items:[],cap=day.capacity||{},pct=Math.max(0,Number(cap.loadPct||0)),warn=!!day.capacityWarning;
    const source=String(day.scheduleSource||'').includes('extension')?'Продлённая смена':day.scheduleSource==='exception'?'Исключение даты':day.scheduleSource==='weekly'?'Шаблон недели':'Базовый график';
    return `<article class="k-schedule-day k-schedule-day--r71 k-master-r81-day ${day.isToday?'is-today':''} ${warn?'has-capacity-warning':''}"><header><div class="k-schedule-day-title"><span>${esc(dateLabel(day.date))}${day.isToday?'<b>Сегодня</b>':''}</span><strong>${day.isDayOff?'Выходной':`${time(day.startTime)}–${time(day.endTime)}`}</strong><small>${esc(source)}${Array.isArray(day.blocks)&&day.blocks.length?` · ${day.blocks.length} перерыв${day.blocks.length===1?'':'а'}`:''}</small></div><div class="k-schedule-day-count"><span>${carIcon}</span><strong>${items.filter(x=>!x.noShow).length}</strong><small>машин</small></div></header><section class="k-schedule-capacity"><div class="k-schedule-capacity__head"><div><small>Загрузка</small><strong>${pct.toFixed(0)}%</strong></div><span>${durationLabel(cap.bookedMinutes||0)} / ${durationLabel(cap.workMinutes||0)}</span></div><div class="k-schedule-capacity__bar" aria-label="Загрузка ${pct.toFixed(0)}%"><span style="width:${Math.min(100,pct)}%"></span></div>${warn?`<p>Загрузка выше ${Number(state.data?.preferences?.capacityWarnPct||90)}%.</p>`:''}</section><div class="k-schedule-day-body">${items.length?items.map(item=>slot(item,day.date)).join(''):`<div class="k-schedule-empty">${day.isDayOff?'Выходной день':'Свободный день'}</div>`}</div><footer class="k-master-r81-day__actions"><button class="k-btn k-btn--secondary" type="button" data-r81-day-open="${esc(day.date)}">${icon('settings')}<span>Управлять днём</span></button></footer></article>`;
  }

  function rescheduleDialog(){return `<dialog class="k-master-r67-reschedule" data-schedule-reschedule-dialog><div class="k-master-r67-reschedule__sheet"><header><div><span>ПЕРЕНОС ЗАПИСИ</span><h2>Предложить клиенту новое время</h2></div><button type="button" data-schedule-reschedule-close aria-label="Закрыть">${icon('close')}</button></header><div class="k-master-r67-reschedule__body"><div data-schedule-reschedule-info></div><section><h3>Свободные окна</h3><div class="k-master-r67-slot-list" data-schedule-free-slots><div class="k-master-r67-loading">Рассчитываем окна…</div></div></section><label>Выбранное начало<input type="datetime-local" data-schedule-new-start></label><label>Причина переноса<input type="text" maxlength="500" data-schedule-reschedule-reason placeholder="Например: предыдущий ремонт займёт больше времени"></label><p class="k-master-r67-reschedule__note">Текущее время заказа не изменится, пока клиент не подтвердит перенос.</p></div><footer><button class="k-btn k-btn--secondary" type="button" data-schedule-reschedule-close>Отмена</button><button class="k-btn k-btn--primary" type="button" data-schedule-reschedule-submit>Предложить клиенту</button></footer></div></dialog>`;}
  function blockDialog(){return `<dialog class="k-master-r69-block-dialog" data-block-dialog><div class="k-master-r69-block-dialog__sheet"><header><div><small>БЛОКИРОВКА ВРЕМЕНИ</small><h2>Добавить перерыв</h2></div><button type="button" data-block-close aria-label="Закрыть">${icon('close')}</button></header><div class="k-master-r69-block-dialog__body"><label>Дата<input type="date" data-block-date></label><div class="k-master-r69-block-types" data-block-types><button type="button" class="is-active" data-block-type="lunch">Обед</button><button type="button" data-block-type="technical">Техперерыв</button><button type="button" data-block-type="personal">Личное время</button><button type="button" data-block-type="meeting">Встреча</button></div><div class="k-master-r69-block-time"><label>Начало<input type="time" value="13:00" data-block-start></label><label>Конец<input type="time" value="14:00" data-block-end></label></div><label>Комментарий<input type="text" maxlength="191" data-block-note placeholder="Необязательно"></label></div><footer><button class="k-btn k-btn--secondary" type="button" data-block-close>Отмена</button><button class="k-btn k-btn--primary" type="button" data-block-save>Сохранить перерыв</button></footer></div></dialog>`;}
  function schedulePreferencesForm(d){
    const prefs=d.preferences||{},auto=d.autoRecovery||{};
    return `<form class="k-master-r81-schedule-form" data-schedule-preferences><label>Резерв на приёмку, мин<input name="buffer" type="number" min="0" max="240" step="5" value="${Number(prefs.intakeBufferMin||60)}"></label><label>SLA ответа клиенту, мин<input name="responseSla" type="number" min="5" max="240" step="5" value="${Number(prefs.responseSlaMin||15)}"></label><label>Шаг свободных окон, мин<input name="slotStep" type="number" min="15" max="120" step="5" value="${Number(prefs.slotStepMin||30)}"></label><label>Предупреждать при загрузке, %<input name="capacityWarn" type="number" min="50" max="120" step="5" value="${Number(prefs.capacityWarnPct||90)}"></label><label class="k-master-r70-toggle"><input name="autoRecovery" type="checkbox" ${auto.enabled!==false?'checked':''}><span><b>Автоперенос</b><small>Перестраивать будущие записи при изменении ёмкости.</small></span></label><label class="k-master-r70-toggle"><input name="autoNotify" type="checkbox" ${auto.notifyEnabled!==false?'checked':''}><span><b>Автоуведомления</b><small>Уведомлять клиента и писать системное сообщение в чат.</small></span></label><label>Горизонт автопереноса, дней<input name="autoHorizon" type="number" min="1" max="30" step="1" value="${Number(auto.horizonDays||14)}"></label><label>Допуск прошедшего времени, мин<input name="autoGrace" type="number" min="0" max="120" step="5" value="${Number(prefs.autoRecoveryGraceMin??auto.graceMin??15)}"></label><button class="k-btn k-btn--primary" type="submit">Сохранить параметры</button></form>`;
  }

  function scheduleWorkspaceDialog(d){
    return `<dialog class="k-master-r81-window k-master-r81-schedule-window" data-r81-schedule-window data-r81-contract="${MASTER_WORKSPACE_R81_CONTRACT}"><div class="k-master-r81-window__shell"><header><div><small>ГРАФИК МАСТЕРА</small><h2>Управление графиком</h2><p>Смены, параметры и Recovery не занимают место на основной временной линии.</p></div><button type="button" data-r81-schedule-close aria-label="Закрыть">${icon('close')}</button></header><nav class="k-master-r81-tabs"><button type="button" class="is-active" data-r81-schedule-tab="shifts">Смены</button><button type="button" data-r81-schedule-tab="settings">Параметры</button><button type="button" data-r81-schedule-tab="recovery">Recovery</button></nav><div class="k-master-r81-window__body"><section data-r81-schedule-panel="shifts">${weeklyTemplate(d)}</section><section data-r81-schedule-panel="settings" hidden><div class="k-master-r81-window-copy"><h3>Параметры планирования</h3><p>Свободные окна рассчитываются из реальных заказов, «Моих услуг», смен, перерывов и тарифа; используются только реальные записи из базы.</p></div>${schedulePreferencesForm(d)}</section><section data-r81-schedule-panel="recovery" hidden>${recoveryPanel(d)}</section></div><footer><button class="k-btn k-btn--secondary" type="button" data-r81-schedule-close>Закрыть</button></footer></div></dialog>`;
  }

  function dayWorkspaceDialog(d){
    const days=Array.isArray(d.days)?d.days:[];
    const panels=days.map(day=>{const blockRows=Array.isArray(day.blocks)?day.blocks:[];return `<section data-r81-day-panel="${esc(day.date)}" hidden><div class="k-master-r81-day-window__summary"><div><small>${esc(dateLabel(day.date))}</small><h3>${day.isDayOff?'Выходной':`${esc(time(day.startTime))}–${esc(time(day.endTime))}`}</h3></div><span>${Number(day.capacity?.loadPct||0).toFixed(0)}% загрузка</span></div><form class="k-schedule-day-editor k-master-r81-day-form" data-schedule-day="${esc(day.date)}"><label>Начало<input name="startTime" type="time" value="${esc(time(day.startTime)||'09:00')}"></label><label>Конец<input name="endTime" type="time" value="${esc(time(day.endTime)||'18:00')}"></label><label class="k-schedule-day-off"><input name="isDayOff" type="checkbox" ${day.isDayOff?'checked':''}> Выходной</label><label class="k-schedule-note">Пометка<input name="note" type="text" maxlength="191" value="${esc(day.note||'')}" placeholder="Например: короткая смена"></label><button class="k-btn k-btn--primary" type="submit">Сохранить день</button></form>${!day.isDayOff?`<section class="k-master-r81-day-section"><header><div><h4>Разовое продление</h4><small>${day.extension?.active?`Сейчас до ${esc(day.extension.endTime)}`:'Не задано'}</small></div></header><div class="k-master-r81-inline-form"><label>Продлить до<input type="time" value="${esc(day.extension?.endTime||day.endTime||'19:00')}" data-shift-extension-end="${esc(day.date)}"></label><button type="button" data-shift-extension-save="${esc(day.date)}">Сохранить</button>${day.extension?.active?`<button type="button" class="is-danger" data-shift-extension-delete="${esc(day.date)}">Убрать</button>`:''}</div></section>`:''}<section class="k-master-r81-day-section"><header><div><h4>Перерывы и блокировки</h4><small>${blockRows.length?`${blockRows.length} интервал${blockRows.length===1?'':'а'}`:'Нет блокировок'}</small></div><button type="button" data-block-open="${esc(day.date)}">${icon('plus')}<span>Добавить</span></button></header><div class="k-master-r81-block-list">${blockRows.length?blockRows.map(row=>`<article><span>${esc(blockLabels[row.type]||'Перерыв')}</span><b>${esc(row.startTime)}–${esc(row.endTime)}</b><small>${esc(row.note||'')}</small><button type="button" data-block-delete="${esc(row.id)}" aria-label="Удалить">${icon('trash')}</button></article>`).join(''):'<p>Свободный рабочий интервал.</p>'}</div></section></section>`;}).join('');
    return `<dialog class="k-master-r81-window k-master-r81-day-window" data-r81-day-window><div class="k-master-r81-window__shell"><header><div><small>РАБОЧИЙ ДЕНЬ</small><h2 data-r81-day-title>Управление днём</h2><p>Исключение даты, продление смены и перерывы находятся в одном окне.</p></div><button type="button" data-r81-day-close aria-label="Закрыть">${icon('close')}</button></header><div class="k-master-r81-window__body">${panels}</div><footer><button class="k-btn k-btn--secondary" type="button" data-r81-day-close>Закрыть</button></footer></div></dialog>`;
  }

  function scheduleCanonShell(){
    return `<section class="k-master-canon-search-shell k-master-schedule-canon-shell" aria-label="Поиск и управление графиком">
      <div class="k-master-canon-titlebar"><h1>Мой график</h1><span class="k-master-canon-status">7 дней</span></div>
      <label class="k-master-canon-search"><span class="k-master-canon-search__icon">${icon('search')}</span><input type="search" data-schedule-search placeholder="Найти заказ, автомобиль или клиента…" autocomplete="off"></label>
      <nav class="k-master-canon-filters" aria-label="Действия графика">
        <button type="button" class="is-active" data-schedule-canon-today>${icon('calendar')}<span>Сегодня</span></button>
        <button type="button" data-r81-schedule-open="shifts">${icon('clock')}<span>Смены</span></button>
        <button type="button" data-r81-schedule-open="settings">${icon('settings')}<span>Параметры</span></button>
        <button type="button" class="k-master-canon-filter-icon" data-r81-schedule-open="recovery" aria-label="Recovery">${icon('refresh')}</button>
      </nav>
    </section>`;
  }
  function renderData(d){
    const days=Array.isArray(d.days)?d.days:[],embedded=document.querySelector('.k-master-workplace-page #k-master-schedule');
    return `${embedded?'':scheduleCanonShell()}${summary(d)}${dayTimeline(d)}${weeklyForecast(d)}<section class="k-schedule-grid">${days.map(day=>dayCard(day)).join('')}</section>${scheduleWorkspaceDialog(d)}${dayWorkspaceDialog(d)}${rescheduleDialog()}${blockDialog()}`;
  }

  function renderFreeSlots(payload){const result=payload?.result||{},slots=Array.isArray(result.slots)?result.slots:[],duration=result.duration||{};return {info:`<article class="k-master-r67-duration"><small>Расчёт длительности</small><strong>${durationLabel(duration.serviceMinutes||0)} + ${durationLabel(duration.bufferMin||0)} резерв</strong><span>${duration.source==='my_services'?'По времени в «Моих услугах»':duration.source==='mixed'?'«Мои услуги» + стандартная оценка':'По стандартному времени/оценке заказа'}</span></article>`,html:slots.length?slots.map((s,i)=>`<button type="button" class="k-master-r67-free-slot ${s.capacityWarning?'has-warning':''}" data-schedule-free-slot="${esc(toInputDateTime(s.start))}" data-slot-duration="${Number(s.workMinutes||duration.serviceMinutes||120)}"><b>${esc(dateTimeLabel(s.start))}</b><span>до ${esc(time(s.end))}</span><small>загрузка после записи ${Number(s.projectedLoadPct||0).toFixed(0)}%${s.capacityWarning?' · высокая':''}</small>${i===0?'<em>Ближайшее</em>':''}</button>`).join(''):'<div class="k-master-r67-no-slots"><b>Свободных окон не найдено</b><span>Проверьте смены, перерывы и следующие даты.</span></div>'};}
  async function load(ctx={}){state.error='';const r=await apiModule.get(ctx.api,{signal:ctx.lifecycle?.signal});if(!r.ok){state.error=r.payload?.message||r.payload?.error||'График недоступен';return;}state.data=r.payload?.data||{};}
  function bind(ctx){
    const root=document.querySelector('#k-master-schedule');if(!root)return;
    const rescheduleDialogNode=root.querySelector('[data-schedule-reschedule-dialog]'),blockDialogNode=root.querySelector('[data-block-dialog]'),scheduleWindowNode=root.querySelector('[data-r81-schedule-window]'),dayWindowNode=root.querySelector('[data-r81-day-window]');
    const closeReschedule=()=>{try{rescheduleDialogNode?.close?.();}catch(_e){}};const closeBlock=()=>{try{blockDialogNode?.close?.();}catch(_e){}};
    const scheduleSearch=root.querySelector('[data-schedule-search]');
    const applyScheduleSearch=()=>{
      const query=String(scheduleSearch?.value||'').trim().toLocaleLowerCase('ru');
      root.querySelectorAll('.k-schedule-day').forEach(day=>{
        const slots=[...day.querySelectorAll('.k-schedule-slot')];
        let matched=0;
        slots.forEach(slot=>{const visible=!query||String(slot.textContent||'').toLocaleLowerCase('ru').includes(query);slot.classList.toggle('is-search-hidden',!visible);if(visible)matched+=1;});
        day.classList.toggle('is-search-hidden',!!query&&matched===0);
      });
    };
    scheduleSearch?.addEventListener('input',applyScheduleSearch,{signal:ctx.lifecycle?.signal});
    root.addEventListener('submit',async e=>{
      const dayForm=e.target.closest('[data-schedule-day]'),prefs=e.target.closest('[data-schedule-preferences]'),weekly=e.target.closest('[data-weekly-shift-form]');if(!dayForm&&!prefs&&!weekly)return;e.preventDefault();const button=(dayForm||prefs||weekly).querySelector('button[type="submit"]');if(button)button.disabled=true;
      try{
        if(dayForm){const r=await apiModule.saveDay(ctx.api,{masterId:state.data?.master?.id||'',workDate:dayForm.dataset.scheduleDay,startTime:dayForm.startTime.value||'09:00',endTime:dayForm.endTime.value||'18:00',isDayOff:dayForm.isDayOff.checked,note:dayForm.note.value||''});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'День не сохранён');recoveryToast(r.payload);window.KaretaToast?.success?.('Исключение даты сохранено');}
        else if(weekly){const days=[...weekly.querySelectorAll('[data-weekday]')].map(row=>({weekday:Number(row.dataset.weekday||0),startTime:row.querySelector('[name="startTime"]')?.value||'09:00',endTime:row.querySelector('[name="endTime"]')?.value||'18:00',isDayOff:!!row.querySelector('[name="isDayOff"]')?.checked}));const r=await apiModule.saveWeekly(ctx.api,{days});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Шаблон не сохранён');recoveryToast(r.payload);window.KaretaToast?.success?.('Недельный график сохранён');}
        else{const r=await apiModule.savePreferences(ctx.api,{intakeBufferMin:Number(prefs.buffer.value||60),responseSlaMin:Number(prefs.responseSla?.value||15),slotStepMin:Number(prefs.slotStep?.value||30),capacityWarnPct:Number(prefs.capacityWarn?.value||90),autoRecoveryEnabled:!!prefs.autoRecovery?.checked,autoNotifyEnabled:!!prefs.autoNotify?.checked,autoRecoveryMode:'auto',autoRecoveryHorizonDays:Number(prefs.autoHorizon?.value||14),autoRecoveryGraceMin:Number(prefs.autoGrace?.value||15)});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Не удалось сохранить параметры');window.KaretaToast?.success?.('Параметры планирования сохранены');}
        await mountMasterSchedule(ctx);
      }catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось сохранить график');}finally{if(button?.isConnected)button.disabled=false;}
    },{signal:ctx.lifecycle?.signal});
    root.addEventListener('click',async e=>{
      if(e.target.closest('[data-schedule-reschedule-close]')){closeReschedule();return;}if(e.target.closest('[data-block-close]')){closeBlock();return;}
      if(e.target.closest('[data-schedule-canon-today]')){const today=root.querySelector('.k-schedule-day.is-today');today?.scrollIntoView?.({behavior:'smooth',block:'start'});return;}
      const scheduleOpen=e.target.closest('[data-r81-schedule-open]');if(scheduleOpen&&scheduleWindowNode){const tab=scheduleOpen.dataset.r81ScheduleOpen||'shifts';scheduleWindowNode.querySelectorAll('[data-r81-schedule-tab]').forEach(x=>x.classList.toggle('is-active',x.dataset.r81ScheduleTab===tab));scheduleWindowNode.querySelectorAll('[data-r81-schedule-panel]').forEach(x=>x.hidden=x.dataset.r81SchedulePanel!==tab);scheduleWindowNode.showModal?.();return;}
      if(e.target.closest('[data-r81-schedule-close]')){scheduleWindowNode?.close?.();return;}
      const scheduleTab=e.target.closest('[data-r81-schedule-tab]');if(scheduleTab&&scheduleWindowNode){const tab=scheduleTab.dataset.r81ScheduleTab;scheduleWindowNode.querySelectorAll('[data-r81-schedule-tab]').forEach(x=>x.classList.toggle('is-active',x===scheduleTab));scheduleWindowNode.querySelectorAll('[data-r81-schedule-panel]').forEach(x=>x.hidden=x.dataset.r81SchedulePanel!==tab);return;}
      const dayOpen=e.target.closest('[data-r81-day-open]');if(dayOpen&&dayWindowNode){const date=dayOpen.dataset.r81DayOpen||'';dayWindowNode.querySelectorAll('[data-r81-day-panel]').forEach(x=>x.hidden=x.dataset.r81DayPanel!==date);const title=dayWindowNode.querySelector('[data-r81-day-title]');if(title)title.textContent=`${dateLabel(date)} · управление`;dayWindowNode.showModal?.();return;}
      if(e.target.closest('[data-r81-day-close]')){dayWindowNode?.close?.();return;}
      const chat=e.target.closest('[data-order-chat]');if(chat){const chatId=chat.dataset.orderChat||'';if(chatId)try{sessionStorage.setItem('kareta.chat.open',chatId);}catch(_e){}}
      const previewRecovery=e.target.closest('[data-recovery-preview]');if(previewRecovery){previewRecovery.disabled=true;try{const r=await apiModule.previewRecovery(ctx.api,{});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Preview недоступен');window.KaretaToast?.success?.(`Preview обновлён: ${Number(r.payload?.preview?.summary?.conflicts||0)} конфликтов`);await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось обновить preview');}finally{if(previewRecovery.isConnected)previewRecovery.disabled=false;}return;}
      const applyButton=e.target.closest('[data-recovery-apply-all],[data-recovery-apply-selected]');if(applyButton){const all=applyButton.hasAttribute('data-recovery-apply-all'),orderIds=all?[]:[...root.querySelectorAll('[data-recovery-select]:checked')].map(x=>x.value).filter(Boolean),notify=!!root.querySelector('[data-recovery-notify]')?.checked;if(!all&&!orderIds.length){window.KaretaToast?.error?.('Выберите хотя бы одну безопасную запись');return;}applyButton.disabled=true;try{const r=await apiModule.applyRecovery(ctx.api,{orderIds,notify});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Перенос недоступен');recoveryToast(r.payload);await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось применить переносы');}finally{if(applyButton.isConnected)applyButton.disabled=false;}return;}
      const protect=e.target.closest('[data-recovery-protect]');if(protect){const orderId=protect.dataset.recoveryProtect||'',protectedNow=protect.dataset.protected==='1';protect.disabled=true;try{const r=await apiModule.protectRecovery(ctx.api,{orderId,protected:!protectedNow});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Защита не изменена');window.KaretaToast?.success?.(protectedNow?'Защита записи снята':'Запись защищена от автопереноса');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось изменить защиту');}finally{if(protect.isConnected)protect.disabled=false;}return;}
      const resend=e.target.closest('[data-recovery-resend]');if(resend){resend.disabled=true;try{const r=await apiModule.resendRecoveryNotification(ctx.api,{orderId:resend.dataset.recoveryResend||''});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Уведомление не отправлено');window.KaretaToast?.success?.('Уведомление клиенту отправлено повторно');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось повторить уведомление');}finally{if(resend.isConnected)resend.disabled=false;}return;}
      const extensionSave=e.target.closest('[data-shift-extension-save]');if(extensionSave){const date=extensionSave.dataset.shiftExtensionSave||'',input=root.querySelector(`[data-shift-extension-end="${date}"]`),endTime=input?.value||'';extensionSave.disabled=true;try{const r=await apiModule.saveExtension(ctx.api,{date,endTime,note:'Разовое продление смены'});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Продление не сохранено');recoveryToast(r.payload);window.KaretaToast?.success?.(`Смена ${dateLabel(date)} продлена до ${endTime}`);await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось продлить смену');}finally{if(extensionSave.isConnected)extensionSave.disabled=false;}return;}
      const extensionDelete=e.target.closest('[data-shift-extension-delete]');if(extensionDelete){const date=extensionDelete.dataset.shiftExtensionDelete||'';extensionDelete.disabled=true;try{const r=await apiModule.deleteExtension(ctx.api,{date});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Продление не удалено');recoveryToast(r.payload);window.KaretaToast?.success?.('Разовое продление убрано');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось убрать продление');}finally{if(extensionDelete.isConnected)extensionDelete.disabled=false;}return;}
      const blockOpen=e.target.closest('[data-block-open]');if(blockOpen&&blockDialogNode){blockDialogNode.dataset.type='lunch';blockDialogNode.querySelector('[data-block-date]').value=blockOpen.dataset.blockOpen||'';blockDialogNode.querySelector('[data-block-start]').value='13:00';blockDialogNode.querySelector('[data-block-end]').value='14:00';blockDialogNode.querySelector('[data-block-note]').value='';blockDialogNode.querySelectorAll('[data-block-type]').forEach(x=>x.classList.toggle('is-active',x.dataset.blockType==='lunch'));blockDialogNode.showModal?.();return;}
      const typeButton=e.target.closest('[data-block-type]');if(typeButton&&blockDialogNode){blockDialogNode.dataset.type=typeButton.dataset.blockType||'technical';blockDialogNode.querySelectorAll('[data-block-type]').forEach(x=>x.classList.toggle('is-active',x===typeButton));return;}
      const blockSave=e.target.closest('[data-block-save]');if(blockSave&&blockDialogNode){blockSave.disabled=true;try{const payload={date:blockDialogNode.querySelector('[data-block-date]').value||'',startTime:blockDialogNode.querySelector('[data-block-start]').value||'',endTime:blockDialogNode.querySelector('[data-block-end]').value||'',type:blockDialogNode.dataset.type||'technical',note:blockDialogNode.querySelector('[data-block-note]').value||''};const r=await apiModule.saveBlock(ctx.api,payload);if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Перерыв не сохранён');closeBlock();recoveryToast(r.payload);window.KaretaToast?.success?.('Перерыв добавлен');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось добавить перерыв');}finally{if(blockSave.isConnected)blockSave.disabled=false;}return;}
      const blockDelete=e.target.closest('[data-block-delete]');if(blockDelete){blockDelete.disabled=true;try{const r=await apiModule.deleteBlock(ctx.api,{id:blockDelete.dataset.blockDelete});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Не удалось удалить блокировку');recoveryToast(r.payload);window.KaretaToast?.success?.('Интервал освобождён');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось удалить блокировку');}finally{if(blockDelete.isConnected)blockDelete.disabled=false;}return;}
      const arrival=e.target.closest('[data-master-arrival]');if(arrival){const panel=arrival.closest('.k-master-r69-arrival'),etaInput=panel?.querySelector('[data-master-arrival-eta]'),status=arrival.dataset.masterArrival||'',etaMinutes=status==='late'?Math.max(5,Number(etaInput?.value||15)):0;arrival.disabled=true;try{const r=await apiModule.setArrival(ctx.api,{orderId:arrival.dataset.orderId,status,etaMinutes});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Статус не сохранён');window.KaretaToast?.success?.(status==='no_show'?'Неявка зафиксирована, окно освобождено':status==='arrived'?'Прибытие клиента отмечено':'Опоздание клиента отмечено');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось обновить приезд');}finally{if(arrival.isConnected)arrival.disabled=false;}return;}
      const reschedule=e.target.closest('[data-schedule-reschedule]');if(reschedule&&rescheduleDialogNode){rescheduleDialogNode.dataset.orderId=reschedule.dataset.scheduleReschedule||'';rescheduleDialogNode.querySelector('[data-schedule-new-start]').value=toInputDateTime(reschedule.dataset.scheduleCurrent||'');rescheduleDialogNode.querySelector('[data-schedule-reschedule-reason]').value='';rescheduleDialogNode.querySelector('[data-schedule-reschedule-info]').innerHTML='';rescheduleDialogNode.querySelector('[data-schedule-free-slots]').innerHTML='<div class="k-master-r67-loading">Рассчитываем окна…</div>';rescheduleDialogNode.showModal?.();try{const r=await apiModule.freeSlots(ctx.api,{orderId:rescheduleDialogNode.dataset.orderId,days:10});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Не удалось рассчитать окна');const view=renderFreeSlots(r.payload||{});rescheduleDialogNode.querySelector('[data-schedule-reschedule-info]').innerHTML=view.info;rescheduleDialogNode.querySelector('[data-schedule-free-slots]').innerHTML=view.html;}catch(error){rescheduleDialogNode.querySelector('[data-schedule-free-slots]').innerHTML=`<div class="k-master-r67-no-slots"><b>Расчёт недоступен</b><span>${esc(error?.message||'Выберите время вручную')}</span></div>`;}return;}
      const free=e.target.closest('[data-schedule-free-slot]');if(free&&rescheduleDialogNode){rescheduleDialogNode.querySelectorAll('[data-schedule-free-slot]').forEach(x=>x.classList.toggle('is-selected',x===free));rescheduleDialogNode.querySelector('[data-schedule-new-start]').value=free.dataset.scheduleFreeSlot||'';rescheduleDialogNode.dataset.durationMin=free.dataset.slotDuration||'';return;}
      const submit=e.target.closest('[data-schedule-reschedule-submit]');if(submit&&rescheduleDialogNode){const orderId=rescheduleDialogNode.dataset.orderId||'',plannedStart=rescheduleDialogNode.querySelector('[data-schedule-new-start]').value||'',reason=rescheduleDialogNode.querySelector('[data-schedule-reschedule-reason]').value||'',durationMin=Number(rescheduleDialogNode.dataset.durationMin||0);if(!plannedStart){window.KaretaToast?.error?.('Выберите новое время');return;}submit.disabled=true;try{const r=await apiModule.proposeReschedule(ctx.api,{orderId,plannedStart,durationMin:durationMin||undefined,reason});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Не удалось предложить перенос');closeReschedule();window.KaretaToast?.success?.('Новое время отправлено клиенту на подтверждение');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось предложить перенос');}finally{if(submit.isConnected)submit.disabled=false;}return;}
      const start=e.target.closest('[data-schedule-start]'),stop=e.target.closest('[data-schedule-stop]'),button=start||stop;if(!button)return;button.disabled=true;try{const r=start?await apiModule.startWork(ctx.api,{orderId:start.dataset.scheduleStart,stageKey:'repair'}):await apiModule.stopWork(ctx.api,{timerId:stop.dataset.scheduleStop});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||(start?'Не удалось начать работу':'Не удалось завершить работу'));window.KaretaToast?.success?.(start?'Автомобиль взят в работу':'Рабочий этап завершён');await mountMasterSchedule(ctx);}catch(error){window.KaretaToast?.error?.(error?.message||'Не удалось выполнить действие');}finally{if(button.isConnected)button.disabled=false;}
    },{signal:ctx.lifecycle?.signal});
  }
  async function mountMasterSchedule(ctx={}){const root=document.querySelector('#k-master-schedule');if(!root)return;if(state.countdownTimer)clearInterval(state.countdownTimer);if(state.recoveryTimer)clearInterval(state.recoveryTimer);state.countdownTimer=0;state.recoveryTimer=0;root.innerHTML='<section class="k-empty"><h2>Загружаем график</h2></section>';await load(ctx);if(!root.isConnected)return;if(state.error){root.innerHTML=`<section class="k-empty"><h2>График недоступен</h2><p>${esc(state.error)}</p></section>`;return;}root.innerHTML=renderData(state.data||{});bind(ctx);updateArrivalCountdowns(root);state.countdownTimer=setInterval(()=>updateArrivalCountdowns(root),30000);ctx.lifecycle?.addCleanup?.(()=>{if(state.countdownTimer)clearInterval(state.countdownTimer);state.countdownTimer=0;});const auto=state.data?.autoRecovery||{};let recoveryBusy=false;const scanDelay=async()=>{if(!auto.enabled||recoveryBusy||Date.now()-state.lastRecoveryScanAt<55000)return;recoveryBusy=true;state.lastRecoveryScanAt=Date.now();try{const r=await apiModule.runRecovery(ctx.api,{triggerType:'delay_scan'});if(r.ok&&Number(r.payload?.recovery?.movedCount||0)>0){recoveryToast(r.payload);await mountMasterSchedule(ctx);}}catch(_e){}finally{recoveryBusy=false;}};if(auto.enabled){await scanDelay();state.recoveryTimer=setInterval(scanDelay,60000);ctx.lifecycle?.addCleanup?.(()=>{if(state.recoveryTimer)clearInterval(state.recoveryTimer);state.recoveryTimer=0;});}}
  window.KaretaMasterSchedulePages=Object.freeze({renderMasterSchedule,mountMasterSchedule,renderData});
})();
