(() => {
  'use strict';
  const api=window.KaretaApiClient,ui=window.KaretaPageUI;
  if(!api||!ui) throw new Error('KaretaApiClient and KaretaPageUI are required before pages/master_wall.js');
  const esc=ui.escHtml;
  const icon=name=>window.KaretaUIIcons?.svg?.(name,{className:'k-master-dialog-icon'})||'';
  const types=Object.freeze({note:'Публикация',advice:'Совет',news:'Новость',video:'Видео',part:'Запчасть'});
  const dt=v=>{if(!v)return '—';const d=new Date(String(v).replace(' ','T'));return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'});};
  let state={master:{},items:[],counts:{}};

  function renderMasterWall(){return `<section class="k-page k-master-page k-master-surface-page k-master-wall-owner-page"><div id="k-master-wall-owner"><section class="k-empty"><h2>Загружаем Стену</h2><p>Собираем публикации, советы, новости и связанные запчасти.</p></section></div></section>`;}
  const stat=(label,value,text)=>`<article><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(text)}</span></article>`;
  function media(item){
    if(item.kind==='video'&&item.videoUrl)return `<a class="k-master-wall-owner-media is-video" href="${esc(item.videoUrl)}" target="_blank" rel="noopener"><span>▶</span><b>Открыть видео</b></a>`;
    const photo=Array.isArray(item.photos)?item.photos[0]:'';if(photo)return `<div class="k-master-wall-owner-media"><img src="${esc(photo)}" alt="${esc(item.title||'Публикация')}" loading="lazy"></div>`;
    if(item.product?.imageUrl)return `<div class="k-master-wall-owner-media"><img src="${esc(item.product.imageUrl)}" alt="${esc(item.product.name||'Запчасть')}" loading="lazy"></div>`;
    return `<div class="k-master-wall-owner-media is-empty"><span>${esc(types[item.kind]||'ПОСТ')}</span></div>`;
  }
  function card(item){
    const live=item.visibility==='public';
    return `<article class="k-master-wall-owner-card" data-master-wall-id="${esc(item.id)}">
      ${media(item)}<div class="k-master-wall-owner-card__body"><header><span class="k-master-wall-owner-kind is-${esc(item.kind)}">${esc(item.kindLabel||types[item.kind]||'Публикация')}</span><span class="k-master-wall-owner-state ${live?'is-live':'is-draft'}">${live?'Опубликовано':'Черновик'}</span><small>${esc(dt(item.date))}</small></header>
      <h3>${esc(item.title||'Без заголовка')}</h3>${item.preview||item.text?`<p>${esc(item.preview||item.text)}</p>`:''}
      ${item.product?`<div class="k-master-wall-owner-product"><b>${esc(item.product.name)}</b><span>${item.product.oem?`OEM ${esc(item.product.oem)} · `:''}${Number(item.product.price||0)>0?new Intl.NumberFormat('ru-RU').format(item.product.price)+' ₸':'Цена по запросу'}</span></div>`:''}
      <div class="k-master-wall-owner-social"><span>♥ ${Number(item.likes||0)}</span><span>💬 ${Number(item.comments||0)}</span></div>
      <footer><button class="k-btn k-btn-secondary" type="button" data-master-wall-edit="${esc(item.id)}">Редактировать</button><button class="k-btn k-btn-secondary" type="button" data-master-wall-delete="${esc(item.id)}">Удалить</button></footer></div>
    </article>`;
  }
  function paint(data){
    state=data||state;const root=document.querySelector('#k-master-wall-owner');if(!root)return;const items=Array.isArray(state.items)?state.items:[],published=items.filter(x=>x.visibility==='public'),drafts=items.filter(x=>x.visibility!=='public'),counts=state.counts||{},master=state.master||{};
    root.innerHTML=`<header class="k-master-wall-owner-hero k-master-page-header"><div><small>СОЦИАЛЬНАЯ СТРАНИЦА</small><h1>Моя Стена</h1><p>Одна лента для реальных работ, обычных записей, советов, новостей, видео и запчастей. Подтверждённые ремонты добавляются через «Мои работы».</p></div><div class="k-master-wall-owner-hero__actions"><button class="k-btn k-btn-primary" type="button" data-master-wall-create>Создать публикацию</button><a class="k-btn k-btn-secondary" href="#/masters/profile/master/${encodeURIComponent(master.id||'')}?tab=wall">Посмотреть как клиент</a></div></header>
      <section class="k-master-wall-owner-stats">${stat('Публикаций',String(counts.published||0),'видят клиенты')}${stat('Черновиков',String(counts.drafts||0),'видите только вы')}${stat('Реальных работ',String(counts.works||0),'из заказ-нарядов')}${stat('Всего на Стене',String(counts.all||0),'единый контент')}</section>
      <section class="k-master-wall-owner-guidance"><div><small>ПРАВИЛО KARETA</small><h2>Работа и публикация — разные сущности одной Стены</h2><p>Реальный ремонт создаётся только из завершённого заказ-наряда с согласием клиента. Здесь вы создаёте обычный социальный контент и можете связать его с видео или товаром.</p></div><a class="k-btn k-btn-secondary" href="#/master/works">Мои подтверждённые работы</a></section>
      <section class="k-master-wall-owner-section"><header><div><small>ПУБЛИЧНО</small><h2>Опубликованные записи</h2></div><span>${published.length}</span></header><div class="k-master-wall-owner-grid">${published.length?published.map(card).join(''):'<div class="k-empty"><h3>Публикаций пока нет</h3><p>Создайте первую запись, совет, новость, видео или публикацию о запчасти.</p></div>'}</div></section>
      ${drafts.length?`<section class="k-master-wall-owner-section"><header><div><small>ПОДГОТОВКА</small><h2>Черновики</h2></div><span>${drafts.length}</span></header><div class="k-master-wall-owner-grid">${drafts.map(card).join('')}</div></section>`:''}
      ${editorDialog()}
      <dialog class="k-master-wall-delete-dialog" data-master-wall-delete-dialog><div><h2>Удалить публикацию?</h2><p>Она исчезнет со Стены, но подтверждённые работы из заказ-нарядов этим действием не удаляются.</p><input type="hidden" data-master-wall-delete-id><footer><button class="k-btn k-btn-secondary" type="button" data-master-wall-close>Отмена</button><button class="k-btn k-btn-primary" type="button" data-master-wall-delete-confirm>Удалить</button></footer></div></dialog>`;
  }
  function editorDialog(){
    return `<dialog class="k-master-wall-editor" data-master-wall-editor><form data-master-wall-form><header><div><small>СТЕНА МАСТЕРА</small><h2 data-master-wall-editor-title>Новая публикация</h2></div><button type="button" data-master-wall-close aria-label="Закрыть">${icon('close')}</button></header><input type="hidden" name="id"><input type="hidden" name="kind" value="note"><input type="hidden" name="visibility" value="public">
      <section><b>Тип публикации</b><div class="k-master-wall-choice-grid" data-master-wall-kind>${Object.entries(types).map(([key,label],i)=>`<button type="button" class="${i===0?'is-active':''}" data-wall-kind="${key}"><span>${key==='note'?'✎':key==='advice'?'!':key==='news'?'▤':key==='video'?'▶':'▦'}</span><b>${label}</b></button>`).join('')}</div></section>
      <label>Заголовок<input name="title" maxlength="255" placeholder="Коротко о публикации"></label><label>Текст<textarea name="text" rows="7" maxlength="12000" placeholder="Что полезного вы хотите рассказать?"></textarea></label>
      <div data-wall-photo-field><label>Фото<input name="photoUrl" maxlength="500" placeholder="https://… или /uploads/…"></label><small>На этом этапе прикрепляется одно основное фото. Реальные материалы ремонта берутся из заказ-наряда автоматически.</small></div>
      <div data-wall-video-field hidden><label>Ссылка на видео<input name="videoUrl" maxlength="500" placeholder="https://…"></label></div>
      <div data-wall-product-field hidden><label>ID запчасти из KARETA<input name="linkedProductId" maxlength="64" placeholder="product_…"></label><small>Карточка активного товара будет показана внутри публикации.</small></div>
      <section><b>Публикация</b><div class="k-master-wall-choice-grid is-visibility" data-master-wall-visibility><button type="button" class="is-active" data-wall-visibility="public"><b>Опубликовать</b><span>видят клиенты</span></button><button type="button" data-wall-visibility="draft"><b>Черновик</b><span>видите только вы</span></button></div></section>
      <footer><button class="k-btn k-btn-secondary" type="button" data-master-wall-close>Отмена</button><button class="k-btn k-btn-primary" type="submit">Сохранить</button></footer><output data-master-wall-status></output></form></dialog>`;
  }
  async function load(ctx={}){const root=document.querySelector('#k-master-wall-owner');if(!root)return;const r=await api.request('api/db.php?action=masterSocialWall.mine',{method:'GET',cacheTtlMs:0,dedupe:false,signal:ctx.lifecycle?.signal});if(!r.ok){root.innerHTML=`<section class="k-empty"><h2>Не удалось загрузить Стену</h2><p>${esc(r.payload?.message||r.payload?.error||'Повторите попытку')}</p><button class="k-btn k-btn-primary" type="button" data-master-wall-retry>Повторить</button></section>`;return;}paint(r.payload?.data||{});if(new URLSearchParams(String(location.hash).split('?')[1]||'').get('action')==='create')openEditor();}
  function setChoice(form,kind,visibility){form.elements.kind.value=kind;form.elements.visibility.value=visibility;form.querySelectorAll('[data-wall-kind]').forEach(b=>b.classList.toggle('is-active',b.dataset.wallKind===kind));form.querySelectorAll('[data-wall-visibility]').forEach(b=>b.classList.toggle('is-active',b.dataset.wallVisibility===visibility));form.querySelector('[data-wall-video-field]').hidden=kind!=='video';form.querySelector('[data-wall-product-field]').hidden=kind!=='part';}
  function openEditor(item=null){const d=document.querySelector('[data-master-wall-editor]'),f=d?.querySelector('form');if(!d||!f)return;f.reset();f.elements.id.value=item?.id||'';f.elements.title.value=item?.title||'';f.elements.text.value=item?.text||'';f.elements.photoUrl.value=item?.photos?.[0]||'';f.elements.videoUrl.value=item?.videoUrl||'';f.elements.linkedProductId.value=item?.linkedProductId||'';setChoice(f,item?.kind||'note',item?.visibility||'public');d.querySelector('[data-master-wall-editor-title]').textContent=item?'Редактировать публикацию':'Новая публикация';d.showModal();}
  function mountMasterWall(ctx={}){const page=document.querySelector('.k-master-wall-owner-page');if(!page)return()=>{};const click=async e=>{if(e.target.closest('[data-master-wall-create]'))return openEditor();if(e.target.closest('[data-master-wall-retry]'))return load(ctx);if(e.target.closest('[data-master-wall-close]')){e.target.closest('dialog')?.close();return;}const kind=e.target.closest('[data-wall-kind]');if(kind){const f=kind.closest('form');setChoice(f,kind.dataset.wallKind,f.elements.visibility.value);return;}const vis=e.target.closest('[data-wall-visibility]');if(vis){const f=vis.closest('form');setChoice(f,f.elements.kind.value,vis.dataset.wallVisibility);return;}const edit=e.target.closest('[data-master-wall-edit]');if(edit){const item=(state.items||[]).find(x=>String(x.id)===String(edit.dataset.masterWallEdit));return openEditor(item);}const del=e.target.closest('[data-master-wall-delete]');if(del){const d=page.querySelector('[data-master-wall-delete-dialog]');d.querySelector('[data-master-wall-delete-id]').value=del.dataset.masterWallDelete;d.showModal();return;}if(e.target.closest('[data-master-wall-delete-confirm]')){const d=page.querySelector('[data-master-wall-delete-dialog]'),id=d.querySelector('[data-master-wall-delete-id]').value,b=e.target.closest('button');b.disabled=true;const r=await api.request('api/db.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'masterSocialWall.delete',id}),cacheTtlMs:0,dedupe:false});b.disabled=false;if(!r.ok)return window.KaretaToast?.error(r.payload?.message||'Не удалось удалить публикацию');d.close();window.KaretaToast?.success('Публикация удалена');await load(ctx);}};
    const submit=async e=>{const f=e.target.closest('[data-master-wall-form]');if(!f)return;e.preventDefault();const status=f.querySelector('[data-master-wall-status]'),button=f.querySelector('[type=submit]');button.disabled=true;status.textContent='Сохраняем…';const v=Object.fromEntries(new FormData(f));const payload={id:v.id||'',kind:v.kind,title:String(v.title||'').trim(),text:String(v.text||'').trim(),visibility:v.visibility,videoUrl:String(v.videoUrl||'').trim(),linkedProductId:String(v.linkedProductId||'').trim(),photos:String(v.photoUrl||'').trim()?[String(v.photoUrl).trim()]:[]};const r=await api.request('api/db.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'masterSocialWall.save',post:payload}),cacheTtlMs:0,dedupe:false});button.disabled=false;if(!r.ok){status.textContent=r.payload?.message||r.payload?.error||'Не удалось сохранить';return;}f.closest('dialog')?.close();window.KaretaToast?.success(payload.visibility==='public'?'Публикация на Стене':'Черновик сохранён');await load(ctx);};
    page.addEventListener('click',click);page.addEventListener('submit',submit);load(ctx);return()=>{page.removeEventListener('click',click);page.removeEventListener('submit',submit);};}
  window.KaretaMasterWallPages=Object.freeze({renderMasterWall,mountMasterWall});
})();
