(() => {
  'use strict';
  const api=window.KaretaApiClient;
  if(!api) throw new Error('KaretaApiClient is required before pages/master_reviews.js');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>window.KaretaUIIcons?.svg?.(name,{className:'k-master-dialog-icon'})||'';
  const root=()=>document.querySelector('#k-page-outlet');
  const date=v=>{if(!v)return'';try{return new Date(String(v).replace(' ','T')).toLocaleDateString('ru-RU');}catch(_){return String(v)}};
  const stars=n=>'★'.repeat(Math.max(1,Math.min(5,Number(n||0))));
  const dimLabels={quality:'Качество',timing:'Сроки',neatness:'Аккуратность',communication:'Общение'};
  const num=v=>Number(v||0);
  const hashParts=()=>decodeURIComponent(String(location.hash||'').split('?')[0].replace(/^#\/?/,'')).split('/').filter(Boolean);
  const summaryFrom=(items,provided={})=>{
    if(provided&&Number(provided.count||0)>=0&&provided.breakdown)return provided;
    const out={count:items.length,verified:0,average:0,unanswered:0,breakdown:{1:0,2:0,3:0,4:0,5:0},dimensions:{quality:0,timing:0,neatness:0,communication:0}},sums={quality:[0,0],timing:[0,0],neatness:[0,0],communication:[0,0]};let total=0;
    items.forEach(x=>{const r=Math.max(1,Math.min(5,num(x.rating)));total+=r;out.breakdown[r]=(out.breakdown[r]||0)+1;if(x.order_id||x.orderId)out.verified++;if(!String(x.master_reply||x.masterReply||'').trim())out.unanswered++;[['quality','quality_rating'],['timing','timing_rating'],['neatness','neatness_rating'],['communication','communication_rating']].forEach(([k,c])=>{const v=num(x[c]??x[k+'Rating']);if(v>0){sums[k][0]+=v;sums[k][1]++;}})});out.average=items.length?Math.round(total/items.length*10)/10:0;Object.keys(sums).forEach(k=>out.dimensions[k]=sums[k][1]?Math.round(sums[k][0]/sums[k][1]*10)/10:0);return out;
  };
  const dimensionRows=summary=>Object.entries(dimLabels).map(([key,label])=>`<div class="k-master-review-dimension"><span>${esc(label)}</span><b>${num(summary?.dimensions?.[key]).toFixed(1)}</b><i><em style="width:${Math.max(0,Math.min(100,num(summary?.dimensions?.[key])/5*100))}%"></em></i></div>`).join('');
  const breakdown=summary=>[5,4,3,2,1].map(n=>{const c=num(summary?.breakdown?.[n]??summary?.breakdown?.[String(n)]);const pct=num(summary?.count)>0?Math.round(c/num(summary.count)*100):0;return `<div class="k-master-review-break"><span>${n} ★</span><i><em style="width:${pct}%"></em></i><b>${c}</b></div>`}).join('');
  const detailDims=r=>[['Качество',r.quality_rating??r.qualityRating],['Сроки',r.timing_rating??r.timingRating],['Аккуратность',r.neatness_rating??r.neatnessRating],['Общение',r.communication_rating??r.communicationRating]].filter(([,v])=>num(v)>0).map(([l,v])=>`<span><small>${esc(l)}</small><b>${num(v).toFixed(0)}/5</b></span>`).join('');
  const card=(r,{owner=false}={})=>{const reply=String(r.master_reply??r.masterReply??'').trim();const verified=!!(r.order_id||r.orderId);return `<article class="k-master-review-native-card ${reply?'has-reply':'needs-reply'}" data-review-id="${esc(r.id)}"><header><div><b>${esc(r.author_name||r.authorName||'Клиент')}</b><small>${verified?'Подтверждённый заказ':'Отзыв клиента'}${r.created_at||r.createdAt?` · ${esc(date(r.created_at||r.createdAt))}`:''}</small></div><strong>${stars(r.rating)} <em>${num(r.rating).toFixed(0)}/5</em></strong></header>${detailDims(r)?`<div class="k-master-review-native-dims">${detailDims(r)}</div>`:''}<p>${esc(r.text||r.body||'')}</p>${reply?`<div class="k-master-review-native-reply"><small>Ответ Мастера${r.master_reply_at||r.masterReplyAt?` · ${esc(date(r.master_reply_at||r.masterReplyAt))}`:''}</small><p>${esc(reply)}</p>${owner?`<button type="button" class="k-btn k-btn-secondary" data-review-reply="${esc(r.id)}">Изменить ответ</button>`:''}</div>`:owner?`<button type="button" class="k-btn k-btn-primary" data-review-reply="${esc(r.id)}">Ответить на отзыв</button>`:''}${verified?`<a class="k-master-review-order-link" href="#/orders/item/${encodeURIComponent(r.order_id||r.orderId)}">Открыть заказ-наряд</a>`:''}</article>`};
  const summaryBlock=summary=>`<section class="k-master-reviews-summary"><article class="k-master-review-score"><small>РЕЙТИНГ</small><strong>${num(summary.average).toFixed(1)}</strong><span>${num(summary.count)} отзывов · ${num(summary.verified)} подтверждено заказами</span></article><article class="k-master-review-breakdown">${breakdown(summary)}</article><article class="k-master-review-dimensions">${dimensionRows(summary)}</article></section>`;
  function renderMasterReviews(){return `<section class="k-page k-master-page k-master-surface-page k-master-reviews-page"><div class="k-empty">Загружаем отзывы…</div></section>`;}
  function renderProviderReviews(){return `<section class="k-page k-master-reviews-page"><div class="k-empty">Загружаем отзывы…</div></section>`;}
  async function mountMasterReviews(ctx={}){
    const outlet=root();if(!outlet)return;
    const res=await api.request('api/db.php?action=masterReviews.getMine',{method:'GET',cacheTtlMs:0,dedupe:false,signal:ctx.lifecycle?.signal});
    if(!res.ok){outlet.innerHTML=`<section class="k-page k-master-page k-master-surface-page k-master-reviews-page"><div class="k-empty"><h1>Отзывы временно недоступны</h1><p>${esc(res.payload?.message||res.payload?.error||'Не удалось загрузить отзывы')}</p></div></section>`;return;}
    let items=Array.isArray(res.payload?.data?.items)?res.payload.data.items:(Array.isArray(res.payload?.reviews)?res.payload.reviews:[]),filter='all';const master=res.payload?.data?.master||{};const summary=summaryFrom(items,res.payload?.data?.summary||{});
    const paint=()=>{const shown=items.filter(x=>filter==='unanswered'?!String(x.master_reply||'').trim():filter==='answered'?!!String(x.master_reply||'').trim():true);const list=outlet.querySelector('[data-master-reviews-list]');if(list)list.innerHTML=shown.length?shown.map(x=>card(x,{owner:true})).join(''):'<div class="k-empty">В этой категории отзывов нет.</div>';outlet.querySelectorAll('[data-review-filter]').forEach(b=>b.classList.toggle('is-active',b.dataset.reviewFilter===filter));};
    outlet.innerHTML=`<section class="k-page k-master-page k-master-surface-page k-master-reviews-page"><header class="k-master-reviews-head k-master-page-header"><div><small>РЕПУТАЦИЯ МАСТЕРА</small><h1>Отзывы клиентов</h1><p>${esc(master.name||'Мастер')}. Здесь только оценки клиентов по реальным завершённым заказам; комментарии к публикациям в рейтинг не входят.</p></div><a class="k-btn k-btn-secondary" href="#/master/profile">Мой профиль</a></header>${summaryBlock(summary)}<section class="k-master-review-filter-grid"><button type="button" class="is-active" data-review-filter="all"><b>${num(summary.count)}</b><span>Все отзывы</span></button><button type="button" data-review-filter="unanswered"><b>${num(summary.unanswered)}</b><span>Ждут ответа</span></button><button type="button" data-review-filter="answered"><b>${Math.max(0,num(summary.count)-num(summary.unanswered))}</b><span>С ответом</span></button></section><section class="k-master-reviews-list" data-master-reviews-list>${items.map(x=>card(x,{owner:true})).join('')||'<div class="k-empty">Подтверждённых отзывов пока нет.</div>'}</section><dialog class="k-master-review-reply-dialog" data-review-dialog><form method="dialog" class="k-master-review-reply-panel" data-review-reply-form><header><div><small>ОТВЕТ МАСТЕРА</small><h2>Ответить клиенту</h2></div><button type="button" data-review-close aria-label="Закрыть">${icon('close')}</button></header><input type="hidden" name="reviewId"><textarea name="reply" rows="6" maxlength="1600" placeholder="Ответ виден публично рядом с отзывом."></textarea><div class="k-master-review-reply-actions"><button type="button" class="k-btn k-btn-secondary" data-review-clear>Удалить ответ</button><button type="submit" class="k-btn k-btn-primary">Сохранить ответ</button></div><output data-review-status></output></form></dialog></section>`;
    paint();const dialog=outlet.querySelector('[data-review-dialog]'),form=outlet.querySelector('[data-review-reply-form]');
    const open=id=>{const r=items.find(x=>String(x.id)===String(id));if(!r)return;form.elements.reviewId.value=r.id;form.elements.reply.value=String(r.master_reply||'');form.querySelector('[data-review-status]').textContent='';dialog.showModal();};
    const save=async(reply)=>{const id=form.elements.reviewId.value;const button=form.querySelector('[type=submit]');button.disabled=true;const r=await api.request('api/db.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'masterReviews.reply',id,reply}),cacheTtlMs:0,dedupe:false});button.disabled=false;if(!r.ok){form.querySelector('[data-review-status]').textContent=r.payload?.message||'Ответ не сохранён';return false;}const row=items.find(x=>String(x.id)===String(id));if(row){row.master_reply=reply;row.master_reply_at=r.payload?.data?.replyAt||'';}dialog.close();paint();window.KaretaToast?.success(reply?'Ответ опубликован':'Ответ удалён');return true;};
    const click=e=>{const f=e.target.closest('[data-review-filter]');if(f){filter=f.dataset.reviewFilter;paint();return;}const r=e.target.closest('[data-review-reply]');if(r){open(r.dataset.reviewReply);return;}if(e.target.closest('[data-review-close]'))dialog.close();if(e.target.closest('[data-review-clear]'))save('');};
    const submit=e=>{e.preventDefault();save(String(form.elements.reply.value||'').trim());};outlet.addEventListener('click',click);form.addEventListener('submit',submit);return()=>{outlet.removeEventListener('click',click);form.removeEventListener('submit',submit);try{dialog.close();}catch(_){}};
  }
  async function mountProviderReviews(ctx={}){
    const outlet=root();if(!outlet)return;const parts=hashParts(),type=parts[2]||'master',id=parts[3]||'';const res=await api.getProviderDetail(type,id,{signal:ctx.lifecycle?.signal});
    if(!res.ok){outlet.innerHTML=`<section class="k-page k-master-reviews-page"><div class="k-empty"><h1>Отзывы недоступны</h1><p>${esc(res.payload?.message||'Профиль не найден')}</p></div></section>`;return;}
    const data=res.payload?.data||{},p=data.provider||{},items=Array.isArray(data.reviews)?data.reviews:[],summary=summaryFrom(items,data.reviewSummary||{}),profile=`#/masters/profile/${encodeURIComponent(type)}/${encodeURIComponent(id)}`;
    outlet.innerHTML=`<section class="k-page k-master-reviews-page"><header class="k-master-reviews-head"><div><small>ПОДТВЕРЖДЁННАЯ РЕПУТАЦИЯ</small><h1>Отзывы о ${esc(type==='sto'?'СТО':'Мастере')}</h1><p><b>${esc(p.name||p.title||'Исполнитель')}</b>. Отзыв связан с реальным завершённым заказом; обычные комментарии к работам на рейтинг не влияют.</p></div><a class="k-btn k-btn-secondary" href="${profile}">Вернуться в профиль</a></header>${summaryBlock(summary)}<section class="k-master-reviews-list">${items.length?items.map(x=>card(x)).join(''):'<div class="k-empty">Подтверждённых отзывов пока нет.</div>'}</section></section>`;
  }
  window.KaretaMasterReviewsPages=Object.freeze({renderMasterReviews,mountMasterReviews,renderProviderReviews,mountProviderReviews});
})();
