(() => {
  'use strict';
  const ui=window.KaretaPageUI;
  const api=window.KaretaApiClient;
  if(!ui||!api) throw new Error('Request page dependencies are required');
  const esc=ui.escHtml;
  const text=v=>String(v??'').trim();
  const money=v=>`${new Intl.NumberFormat('ru-RU').format(Number(v||0))} ₸`;
  const normalizeRole=v=>{const r=text(v).toLowerCase();if(['master','sto','client','admin','owner','seller'].includes(r))return r;if(r==='мастер')return'master';if(r==='сто')return'sto';return'client';};
  const roleOf=context=>{
    const kind=window.KaretaNavigationCore?.contextKind?.();
    if(kind==='master')return'master';
    if(kind==='organization_service')return'sto';
    if(kind==='seller'||kind==='organization_store')return'seller';
    if(kind==='admin')return'admin';
    if(kind==='personal'||kind==='anonymous')return'client';
    return normalizeRole(context?.state?.user?.role||window.KaretaNext?.state?.user?.role||context?.role||'client');
  };
  const icon=name=>window.KaretaUIIcons?.icon?.(name)||'';
  const categoryIconName=(value,fallback='services')=>window.KaretaUIIcons?.categoryIcon?.(value,fallback)||fallback;
  const categorySvg=(value,fallback='services')=>window.KaretaUIIcons?.svg?.(categoryIconName(value,fallback))||'';
  const cityCatalog=()=>Array.from(new Set([
    ...(window.KaretaOnboardingSelectionCatalog?.cities||[]),
    'Усть-Каменогорск','Семей','Риддер','Алматы','Астана','Шымкент','Караганда','Павлодар'
  ].map(text).filter(Boolean)));
  const cityCoords=Object.freeze({
    'Усть-Каменогорск':[49.9483,82.6275],'Семей':[50.4111,80.2275],Риддер:[50.3442,83.5129],
    Алматы:[43.2389,76.8897],Астана:[51.1694,71.4491],Шымкент:[42.3417,69.5901],Караганда:[49.8064,73.0855],Павлодар:[52.2873,76.9674]
  });
  const todayIso=()=>new Date().toISOString().slice(0,10);
  const tomorrowIso=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10);};

  function copyFor(role){
    if(role==='master')return {title:'Записать клиента',desc:'Клиент и автомобиль → время → работы → подтверждение. Исполнитель уже выбран: это вы.',submit:'Подтвердить запись',eyebrow:'ЗАПИСЬ КЛИЕНТА'};
    if(role==='sto')return {title:'Создать заказ СТО',desc:'Сначала данные клиента и работы, затем три шага завершения заявки.',submit:'Подтвердить заказ',eyebrow:'ПРИЁМ КЛИЕНТА'};
    return {title:'Новая заявка',desc:'Автомобиль → предложение → где и когда → проблема → подтверждение.',submit:'Отправить заявку',eyebrow:'НОВАЯ ЗАЯВКА'};
  }

  const stepMeta=[
    ['vehicle','Какое авто?','Укажите автомобиль для заявки'],
    ['offer','Как получить предложение?','Выберите подходящий сценарий'],
    ['schedule','Где и когда?','Уточните место и удобное время'],
    ['problem','В чём проблема?','Выберите услугу или опишите проблему'],
    ['review','Подтверждение','Проверьте данные перед отправкой']
  ];

  const stepShortLabels=['Авто','Цена','Когда','Проблема','Готово'];
  const stepsHtml=(current,flow=[0,1,2,3,4])=>{const pos=Math.max(0,flow.indexOf(current)),total=flow.length,progress=total>1?(pos/(total-1))*100:0;return `<div class="k-request-progress-shell"><div class="k-request-main-steps" aria-label="Шаги заявки" data-current-step="${pos+1}" style="--k-request-progress:${Math.max(0,Math.min(100,progress))}%">${flow.map((stepIndex,index)=>`<span class="${index===pos?'is-active':index<pos?'is-complete':''}" ${index===pos?'aria-current="step"':''}>${index+1}</span>`).join('')}</div><div class="k-request-progress-caption"><b>Шаг ${pos+1} из ${total}</b><span>${esc(stepShortLabels[current]||'')}</span></div></div>`;};
  const windowHeader=(copy,current=0,flow=[0,1,2,3,4])=>`<header class="k-flow-request-header"><div class="k-request-ref-topbar"><button type="button" class="k-request-ref-back" data-request-head-back aria-label="Назад"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15.5 5 8.5 12l7 7"/><path d="M9 12h11"/></svg></button><img class="k-request-ref-logo" src="/assets/onboarding/kareta_logo_full.png" alt="KARETA.KZ"><a class="k-request-ref-bell" href="#/notifications" aria-label="Уведомления"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg></a></div><div data-request-kflow-steps>${stepsHtml(current,flow)}</div></header>`;
  const selectedContext=()=>`<div class="k-flow-request-context" data-request-context-summary></div>`;

  function requestContent(context={},options={}){
    const role=roleOf(context),copy=copyFor(role),isClient=role==='client',isMaster=role==='master',flowSteps=isMaster?[0,2,3,4]:[0,1,2,3,4];
    return `<section class="k-request-flow-r78 k-flow-window k-flow-request ${options.windowMode?'is-window':''}" data-request-root data-request-role="${esc(role)}" data-request-flow-version="8" data-request-logic-version="9">
      ${windowHeader(copy,0,flowSteps)}
      <div class="k-flow-copy k-flow-request-copy"><h2 data-request-window-title tabindex="-1">${esc(stepMeta[0][1])}</h2><p data-request-window-desc>${esc(stepMeta[0][2])}</p></div>
      <form class="k-request-form-r78 k-flow-request-form" data-request-form data-request-role="${esc(role)}" novalidate>
        <section class="k-request-panel-r78 k-flow-request-panel is-active" data-request-panel="vehicle" data-step-index="0">
          <div class="k-flow-body k-request-step-one">
            ${isClient?'':`<div class="k-request-account-strip k-flow-compact-account"><label class="k-flow-field"><span>Имя клиента</span><input name="clientName" required autocomplete="name" placeholder="Имя клиента"><small>Проверьте клиента перед записью</small></label><label class="k-flow-field"><span>Телефон клиента</span><input name="clientPhone" required type="tel" autocomplete="tel" placeholder="+7 (___) ___-__-__"><small>Для связи и истории заказа</small></label></div>`}
            <div class="k-request-step-one-grid is-single"><section class="k-request-parent-block k-request-parent-block--single">
              <div class="k-flow-section-copy"><small>АВТОМОБИЛЬ</small><h3>Какое авто?</h3><p>Укажите автомобиль для заявки</p></div>
              ${isClient?`<input type="hidden" name="clientName"><input type="hidden" name="clientPhone"><input type="hidden" name="clientVehicleId" data-request-vehicle-id><input type="hidden" name="clientCar" data-request-car-title>
              <div class="k-request-vehicle-stage" data-request-vehicle-stage><div class="k-request-empty-state-hero" data-request-vehicle-empty><div class="k-request-empty-state-hero__icon">${icon('car')||'🚗'}</div><b>Автомобиль не выбран</b><p>Добавьте автомобиль, чтобы продолжить оформление заявки</p><button class="k-flow-outline-action" type="button" data-request-open-picker="vehicle">+ Добавить автомобиль</button></div><button class="k-request-choice-card k-flow-choice" type="button" data-request-open-picker="vehicle" data-request-vehicle-selected hidden><span class="k-request-choice-icon">${icon('car')||'🚗'}</span><span><small>АВТОМОБИЛЬ</small><b data-request-vehicle-label>Выберите машину из гаража</b><em data-request-vehicle-meta>Можно добавить новую прямо здесь</em></span><i>Изменить</i></button></div><div class="k-request-vehicle-quicklist" data-request-vehicle-quicklist hidden></div>`:`<label class="k-flow-field k-request-manual-car"><span>Автомобиль</span><input name="clientCar" required placeholder="Например, Renault Logan 2019"></label>`}
            </section></div>
          </div>
        </section>

        <section class="k-request-panel-r78 k-flow-request-panel" data-request-panel="offer" data-step-index="1" hidden>
          <div class="k-flow-body k-request-final-step k-request-final-offer">${selectedContext()}
            <input type="hidden" name="offerMode" data-request-offer-mode value=""><input type="hidden" name="budgetMode" data-request-budget-mode value="discuss"><input type="hidden" name="directMasterId" data-request-direct-master-id><input type="hidden" name="directMasterName" data-request-direct-master-name>
            <div class="k-request-final-choice-list" data-request-offer-choices>
              ${isClient?`<button class="k-request-final-choice" type="button" data-request-offer-choice="exchange" aria-pressed="false"><span class="k-request-final-choice__icon">${icon('masters')||icon('exchange')||'M'}</span><span><b>Предложения мастеров</b><small>Мастера сами предложат цену и срок</small><em>Получите несколько предложений и выберите подходящее</em></span><i aria-hidden="true">○</i></button><button class="k-request-final-choice" type="button" data-request-offer-choice="own_price" aria-pressed="false"><span class="k-request-final-choice__icon">${icon('finance')||'₸'}</span><span><b>Своя цена</b><small>Укажите бюджет — мастера смогут откликнуться</small></span><i aria-hidden="true">○</i></button>`:`<button class="k-request-final-choice is-selected" type="button" data-request-offer-choice="direct_master" aria-pressed="true" disabled><span class="k-request-final-choice__icon">${icon('user')||'M'}</span><span><b>Прямая запись</b><small>Заказ создаётся в текущем рабочем контексте</small></span><i aria-hidden="true">✓</i></button>`}
            </div>
            <section class="k-request-inline-budget" data-request-inline-budget hidden><label class="k-flow-field"><span>Ваш бюджет</span><div class="k-request-money-field"><input name="budget" data-request-budget type="number" min="1" step="1000" inputmode="numeric" placeholder="25 000"><b>₸</b></div><small>Укажите сумму, которую готовы заплатить</small></label></section>
          </div>
        </section>

        <section class="k-request-panel-r78 k-flow-request-panel" data-request-panel="schedule" data-step-index="2" hidden>
          <div class="k-flow-body k-request-final-step k-request-final-location">${selectedContext()}
            <input type="hidden" name="city" data-request-city><input type="hidden" name="lat" data-request-lat><input type="hidden" name="lng" data-request-lng><input type="hidden" name="visitMode" data-request-visit-mode><input type="hidden" name="date" data-booking-date><input type="hidden" name="time" data-booking-time>
            ${isMaster?'':`<section class="k-request-field-group"><small class="k-request-field-group__label">Город</small><button class="k-request-location-row" type="button" data-request-open-picker="city"><span>${icon('location')||'⌖'}</span><span><b data-request-city-label>Выберите город</b><small>Город обслуживания</small></span><i>›</i></button></section>
            <section class="k-request-field-group"><small class="k-request-field-group__label">Формат обслуживания</small><div class="k-request-final-segmented" data-request-visit-choices><button type="button" data-request-visit-choice="field">Выезд мастера</button><button type="button" data-request-visit-choice="service">Приеду в сервис</button></div></section>
            <label class="k-flow-field k-request-service-address" data-request-address-wrap hidden><span>Адрес выезда</span><input name="serviceAddress" data-request-address maxlength="240" placeholder="Улица, дом или ориентир"><small>Укажите место, куда должен приехать мастер</small></label>`}
            <section class="k-request-field-group"><small class="k-request-field-group__label">Дата</small><div class="k-request-final-segmented k-request-date-segmented" data-request-date-choices><button type="button" data-request-date-choice="today">Сегодня</button><button type="button" data-request-date-choice="tomorrow">Завтра</button><button type="button" data-request-date-choice="custom" data-request-open-picker="schedule">Выбрать дату</button></div></section>
            <section class="k-request-field-group"><small class="k-request-field-group__label">Время</small><button class="k-request-location-row" type="button" data-request-open-picker="schedule"><span>${icon('calendar')||'◷'}</span><span><b data-request-schedule-label>В течение дня</b><small data-request-schedule-meta>Время — предпочтение клиента</small></span><i>›</i></button></section>
          </div>
        </section>

        <section class="k-request-panel-r78 k-flow-request-panel" data-request-panel="problem" data-step-index="3" hidden>
          <div class="k-flow-body k-request-problem-ref k-request-problem-v8">${selectedContext()}
            <input type="hidden" name="problemMode" data-request-problem-mode value="services">
            <div class="k-request-final-segmented k-request-problem-modes" role="tablist" aria-label="Способ описания проблемы"><button type="button" data-request-problem-choice="services" role="tab">Список услуг</button><button type="button" data-request-problem-choice="custom" role="tab">Своя проблема</button></div>
            <section class="k-request-service-mode" data-request-service-mode><div class="k-request-problem-service-head"><b>Выберите известную услугу</b><small>Используйте поиск или категории каталога</small></div><div class="k-request-selected-r78 k-flow-extra-services" data-request-services-list><div class="k-request-empty-r78">Услуги ещё не выбраны.</div></div><div class="k-request-step-one-actions"><button class="k-flow-outline-action" type="button" data-request-open-picker="services">${icon('plus')||'+'} Выбрать услуги</button></div><div class="k-request-selection-total"><span data-request-service-count>0 выбрано</span><strong data-request-services-total>0 ₸</strong></div><div class="k-request-services-status" data-request-services-status>Загрузка каталога услуг…</div></section>
            <label class="k-flow-field k-flow-field--textarea k-request-problem-text"><span data-request-problem-label>Описание проблемы</span><textarea name="description" rows="5" minlength="5" maxlength="2000" required aria-required="true" placeholder="Опишите симптомы или необходимую работу"></textarea><small data-request-problem-help>Минимум 5 символов. Это поможет мастеру понять задачу до отклика.</small></label>
            <div class="k-request-ref-field-title">Фото и видео <span>(по желанию)</span></div><div class="k-request-ref-media-grid"><div class="k-flow-photo-preview" data-request-media-preview></div><label class="k-flow-photo-drop k-request-ref-add-media" data-request-media-drop><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" multiple data-request-media><span class="k-flow-photo-icon">+</span><b>Добавить</b><small>Фото или видео</small></label></div><div class="k-request-media-limit" data-request-media-limit>0 из 10 файлов</div>
            <label class="k-flow-field k-request-ref-extra"><span>Дополнительно <em>(необязательно)</em></span><input name="extraDetails" maxlength="500" placeholder="Пробег, комментарий, ориентир"></label>
          </div>
        </section>

        <section class="k-request-panel-r78 k-flow-request-panel" data-request-panel="review" data-step-index="4" hidden>
          <div class="k-flow-body k-request-final-step k-request-final-review"><div class="k-flow-confirm-state" data-request-confirm-state><span class="k-flow-confirm-icon">${icon('check')||'✓'}</span><h3>Проверьте заявку</h3><p>Нажмите на любой раздел, чтобы изменить его без потери черновика.</p></div><div class="k-request-review k-flow-review" data-request-review></div><label class="k-request-consent" data-request-consent><input type="checkbox" name="consent"><span>Согласен с <a href="#/rules" data-request-terms-link>условиями сервиса</a></span></label><div class="k-flow-confirm-summary" data-request-confirm-summary></div><output class="k-request-status-r78 k-flow-status" data-request-status aria-live="polite"></output><div class="k-request-success-actions" data-request-success-actions hidden><button class="k-flow-outline-action" type="button" data-request-open-created>Открыть заявку</button><a class="k-flow-primary" href="#/home" data-request-home>На главную</a></div></div>
        </section>
        <footer class="k-request-nav-r78 k-flow-actions k-flow-request-actions"><button class="k-flow-back-action" type="button" data-request-prev hidden aria-label="Назад">← <span>Назад</span></button><span data-request-nav-note>Выберите автомобиль.</span><button class="k-flow-primary" type="button" data-request-next>Продолжить</button><button class="k-flow-primary" type="submit" data-request-submit hidden>${esc(copy.submit)}</button></footer>
      </form>
      <dialog class="k-request-picker-r78 k-flow-picker" data-request-picker aria-label="Вложенное окно заявки"><div class="k-request-picker-surface"><header><div><small data-request-picker-eyebrow>ВЫБОР</small><h3 data-request-picker-title>Выберите</h3></div><button type="button" data-request-picker-close aria-label="Закрыть">×</button></header><div class="k-request-picker-body" data-request-picker-body></div></div></dialog>
      <dialog class="k-request-rules-dialog" data-request-rules-dialog aria-label="Правила сервиса"><section><header><div><small>KARETA.KZ</small><h3>Правила сервиса</h3></div><button type="button" data-request-rules-close aria-label="Закрыть">×</button></header><div class="k-request-rules-body"><article><b>Достоверные данные</b><p>Указывайте корректные сведения об автомобиле, неисправности и ожидаемой услуге.</p></article><article><b>Цена и сроки</b><p>Стоимость, сроки и дополнительные работы согласуются между клиентом и исполнителем до выполнения.</p></article><article><b>Безопасность</b><p>Исполнитель обязан соблюдать требования безопасности и сообщать о выявленных рисках.</p></article><article><b>Ответственность</b><p>KARETA.KZ помогает организовать взаимодействие, а условия конкретной работы подтверждаются участниками заявки.</p></article></div><button type="button" class="k-flow-primary" data-request-rules-close>Понятно</button></section></dialog>
    </section>`;
  }

  function renderRequest(context){
    const role=roleOf(context),copy=copyFor(role);
    if(role==='client')return `<section class="k-page k-request-page-ref" data-page="request">${requestContent(context,{windowMode:false})}</section>`;
    return ui.pageShell(context,copy.title,copy.desc,requestContent(context,{windowMode:false}),{page:'request',eyebrow:copy.eyebrow,chromeHeader:false});
  }
  const renderRequestWindow=context=>requestContent(context,{windowMode:true});

  function mountRequest(context={}){
    const scope=context.root instanceof Element?context.root:document;
    const root=scope.querySelector?.('[data-request-root]')||document.querySelector('[data-request-root]');
    const form=root?.querySelector('[data-request-form]');if(!root||!form)return;
    const role=normalizeRole(form.dataset.requestRole||roleOf(context)),isClient=role==='client',isMaster=role==='master',flowSteps=isMaster?[0,2,3,4]:[0,1,2,3,4],windowMode=Boolean(context.windowMode||root.classList.contains('is-window'));if(isClient)document.body.classList.add('k-request-ref-active');
    const nameEl=form.elements.clientName,phoneEl=form.elements.clientPhone,statusEl=root.querySelector('[data-request-status]');
    const nextBtn=root.querySelector('[data-request-next]'),prevBtn=root.querySelector('[data-request-prev]'),submitBtn=root.querySelector('[data-request-submit]');
    const picker=root.querySelector('[data-request-picker]'),rulesDialog=root.querySelector('[data-request-rules-dialog]'),pickerBody=root.querySelector('[data-request-picker-body]'),pickerTitle=root.querySelector('[data-request-picker-title]'),pickerEyebrow=root.querySelector('[data-request-picker-eyebrow]');
    const servicesWrap=root.querySelector('[data-request-services-list]'),serviceCount=root.querySelector('[data-request-service-count]'),servicesTotal=root.querySelector('[data-request-services-total]'),servicesStatus=root.querySelector('[data-request-services-status]');
    const vehicleIdEl=form.querySelector('[data-request-vehicle-id]'),vehicleTitleEl=form.querySelector('[data-request-car-title]'),vehicleLabel=root.querySelector('[data-request-vehicle-label]'),vehicleMeta=root.querySelector('[data-request-vehicle-meta]');
    const offerModeEl=form.querySelector('[data-request-offer-mode]'),cityEl=form.querySelector('[data-request-city]'),latEl=form.querySelector('[data-request-lat]'),lngEl=form.querySelector('[data-request-lng]'),visitModeEl=form.querySelector('[data-request-visit-mode]'),dateEl=form.querySelector('[data-booking-date]'),timeEl=form.querySelector('[data-booking-time]');
    const budgetEl=form.querySelector('[data-request-budget]'),budgetModeEl=form.querySelector('[data-request-budget-mode]'),directMasterIdEl=form.querySelector('[data-request-direct-master-id]'),directMasterNameEl=form.querySelector('[data-request-direct-master-name]');
    const addressEl=form.querySelector('[data-request-address]'),addressWrap=root.querySelector('[data-request-address-wrap]'),problemModeEl=form.querySelector('[data-request-problem-mode]');
    const mediaInput=form.querySelector('[data-request-media]'),mediaPreview=root.querySelector('[data-request-media-preview]'),mediaLimit=root.querySelector('[data-request-media-limit]');
    const REQUEST_DRAFT_KEY='kareta.request.draft.kflow';
    const LEGACY_DRAFT_KEY='kareta.request.draft.v3';
    const LEGACY_SERVICE_DRAFT_KEY='kareta.request.services';
    let prefill=null,draft={},step=0,catalog=[],offers=[],vehicles=[],selectedVehicle=null,servicesReady=false,primaryId='',pickerMode='',createdOrder=null,mastersCatalog=[],customServices=[],submitting=false;
    let mediaFiles=[];
    const mediaUrls=[];
    const selectedIds=new Set();
    try{prefill=JSON.parse(sessionStorage.getItem('kareta.request.prefill')||'null');}catch(_e){prefill=null;}
    try{draft=JSON.parse(sessionStorage.getItem(REQUEST_DRAFT_KEY)||sessionStorage.getItem(LEGACY_DRAFT_KEY)||'{}')||{};}catch(_e){draft={};}
    customServices=(Array.isArray(draft.customServices)?draft.customServices:[]).map(row=>({id:text(row?.id)||`custom:${Date.now()}:${Math.random().toString(36).slice(2,7)}`,name:text(row?.name),category:'По описанию',price:Math.max(0,Number(row?.price||0)),custom:true})).filter(row=>row.name);
    const REQUEST_FLOW_VERSION=9;
    if(Number(draft.flowVersion||0)!==REQUEST_FLOW_VERSION){const previousVersion=Number(draft.flowVersion||0),legacyStep=Math.max(0,Number(draft.step||0));if(previousVersion===8)draft.step=legacyStep;else if(previousVersion===7)draft.step=[0,3,3,1,2,4][Math.min(5,legacyStep)]??0;else draft.step=0;draft.flowVersion=REQUEST_FLOW_VERSION;}
    const hashQuery=String(location.hash||'').split('?')[1]||'';if(hashQuery){const q=new URLSearchParams(hashQuery);if(q.get('vehicleId'))prefill={...(prefill||{}),vehicleId:q.get('vehicleId'),clientVehicleId:q.get('vehicleId')};}
    const makeRequestKey=()=>`order:${Date.now()}:${Math.random().toString(36).slice(2,10)}`;
    if(!text(draft.idempotencyKey))draft.idempotencyKey=makeRequestKey();
    ['source','category','masterId','masterName','stoId','stoName','offerId','offerPrice','offerPriceType','offerPriceMax','promotion'].forEach(key=>{if(prefill&&prefill[key]!==undefined)draft[key]=prefill[key];});
    (Array.isArray(draft.serviceIds)?draft.serviceIds:[]).map(text).filter(Boolean).forEach(id=>selectedIds.add(id));
    primaryId=text(draft.primaryServiceId)||[...selectedIds][0]||'';if(primaryId)selectedIds.add(primaryId);

    const serviceById=id=>catalog.find(item=>text(item.id)===text(id));
    const offerMap=()=>new Map(offers.map(o=>[text(o.serviceId),o]));
    const serviceData=id=>{const item=serviceById(id);if(!item)return null;const offer=offerMap().get(text(id));return {id:text(id),name:text(item.name),category:text(item.categoryName||item.category||'Другое'),price:Number(offer?.price??item.basePrice??item.base_price??0),duration:Number(offer?.durationMin||0)};};
    const selectedServices=()=>[...[...selectedIds].map(serviceData).filter(Boolean),...customServices];
    const currentCarTitle=()=>isClient?text(vehicleTitleEl?.value||selectedVehicle?.title||selectedVehicle&&[selectedVehicle.brand,selectedVehicle.model,selectedVehicle.year_label||selectedVehicle.year].filter(Boolean).join(' ')):text(form.elements.clientCar?.value);
    const currentVehicleId=()=>isClient?text(vehicleIdEl?.value):'';
    const currentOfferMode=()=>text(offerModeEl?.value);
    const currentVisitMode=()=>text(visitModeEl?.value);
    const currentProblemMode=()=>text(problemModeEl?.value)||'services';
    const selectedMaster=()=>({id:text(directMasterIdEl?.value),name:text(directMasterNameEl?.value)});
    const readHomeLocation=()=>{try{const v=JSON.parse(localStorage.getItem('kareta.home.location.v1')||'null');return v&&typeof v==='object'?v:{};}catch(_e){return {};}};
    const offerLabel=mode=>mode==='exchange'?'Предложения мастеров':mode==='own_price'?'Своя цена':mode==='direct_master'?(isMaster?'Текущий мастер':'Выбрать мастера'):role==='master'||role==='sto'?'Прямая запись':'Выберите способ';
    const visitLabel=mode=>mode==='field'?'Выезд мастера':mode==='service'?'Приехать в сервис':'Выберите способ';
    const dateLabel=value=>{const v=text(value);if(!v)return'Дата не выбрана';if(v===todayIso())return'Сегодня';if(v===tomorrowIso())return'Завтра';try{return new Date(v+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'});}catch(_e){return v;}};

    const saveDraft=()=>{
      const data={...draft,flowVersion:REQUEST_FLOW_VERSION,idempotencyKey:text(draft.idempotencyKey)||makeRequestKey(),clientName:text(nameEl?.value),clientPhone:text(phoneEl?.value),clientVehicleId:currentVehicleId(),clientCar:currentCarTitle(),description:text(form.elements.description?.value),extraDetails:text(form.elements.extraDetails?.value),problemMode:currentProblemMode(),offerMode:currentOfferMode(),city:text(cityEl?.value),lat:text(latEl?.value),lng:text(lngEl?.value),visitMode:currentVisitMode(),serviceAddress:text(addressEl?.value),date:text(dateEl?.value),time:text(timeEl?.value),budget:Number(budgetEl?.value||0),budgetMode:text(budgetModeEl?.value)||'discuss',directMasterId:text(directMasterIdEl?.value),directMasterName:text(directMasterNameEl?.value),primaryServiceId:primaryId,serviceIds:[...selectedIds],customServices:customServices.map(row=>({id:row.id,name:row.name,price:row.price})),mediaNames:mediaFiles.map(f=>f.name),submitState:createdOrder?'CREATED':submitting?'SUBMITTING':'IDLE',step,updatedAt:Date.now()};
      delete data.urgent;delete data.urgentTiming;
      draft=data;try{sessionStorage.setItem(REQUEST_DRAFT_KEY,JSON.stringify(data));}catch(_e){}
    };

    const renderContextSummary=()=>{const services=selectedServices();root.querySelectorAll('[data-request-context-summary]').forEach(node=>{node.innerHTML=`<span>${icon('car')||'🚗'} <b>${esc(currentCarTitle()||'Автомобиль не выбран')}</b></span>${services.length?`<span>${icon('work')||'•'} <b>${services.length===1?esc(services[0].name):`${services.length} услуги`}</b></span>`:''}`;});};
    const serviceRow=item=>`<article class="k-request-selected-row k-flow-service-row k-request-ref-service-row"><span class="k-request-ref-service-icon">${categorySvg(item.category)}</span><span class="k-request-ref-service-copy"><b>${esc(item.name)}</b><em>${esc([item.category,item.price?`от ${money(item.price)}`:''].filter(Boolean).join(' · ')||'Услуга')}</em></span><button type="button" data-request-open-picker="services" aria-label="Изменить услугу">›</button></article>`;
    const renderSelected=()=>{const selected=selectedServices(),sum=selected.reduce((n,x)=>n+x.price,0);if(servicesWrap)servicesWrap.innerHTML=selected.length?selected.map(serviceRow).join(''):'<div class="k-request-empty-r78">Услуги ещё не выбраны.</div>';if(serviceCount)serviceCount.textContent=selected.length?`${selected.length} выбрано`:'0 выбрано';if(servicesTotal)servicesTotal.textContent=selected.length?(sum?`от ${money(sum)}`:'Цена уточняется'):'0 ₸';renderContextSummary();syncConditionCards();syncNav();saveDraft();};

    const renderMedia=()=>{mediaUrls.splice(0).forEach(url=>URL.revokeObjectURL(url));if(!mediaPreview)return;if(!mediaFiles.length){mediaPreview.innerHTML='';if(mediaLimit)mediaLimit.textContent='';syncNav();return;}mediaPreview.innerHTML=mediaFiles.map((file,index)=>{const url=URL.createObjectURL(file);mediaUrls.push(url);const video=file.type.startsWith('video/');return `<figure class="${video?'is-video':''}">${video?`<video src="${esc(url)}" muted preload="metadata"></video><span class="k-request-media-play">▶</span>`:`<img src="${esc(url)}" alt="Фото ${index+1}: ${esc(file.name)}">`}<button type="button" data-request-remove-media="${index}" aria-label="Удалить ${esc(file.name)}">×</button><figcaption>${esc(file.name)}</figcaption></figure>`;}).join('');if(mediaLimit)mediaLimit.textContent=`${mediaFiles.length} ${mediaFiles.length===1?'фото':'файла(ов)'}`;syncNav();};

    const syncConditionCards=()=>{
      const mode=currentOfferMode(),master=selectedMaster(),city=text(cityEl?.value),visit=currentVisitMode(),date=text(dateEl?.value),time=text(timeEl?.value),budgetMode=text(budgetModeEl?.value)||'discuss';
      root.querySelectorAll('[data-request-offer-choice]').forEach(button=>{const active=button.dataset.requestOfferChoice===mode;button.classList.toggle('is-selected',active);button.setAttribute('aria-pressed',active?'true':'false');const marker=button.querySelector('i');if(marker)marker.textContent=active?'✓':'○';});
      const budgetBox=root.querySelector('[data-request-inline-budget]');if(budgetBox)budgetBox.hidden=mode!=='own_price';
      root.querySelectorAll('[data-request-inline-budget-mode]').forEach(button=>button.classList.toggle('is-selected',button.dataset.requestInlineBudgetMode===budgetMode));
      const masterBox=root.querySelector('[data-request-direct-master-summary]');if(masterBox)masterBox.hidden=mode!=='direct_master'||!isClient;const masterLabel=root.querySelector('[data-request-direct-master-label]');if(masterLabel)masterLabel.textContent=master.name||text(prefill?.stoName||draft.stoName)||'Мастер не выбран';
      const cityNode=root.querySelector('[data-request-city-label]');if(cityNode)cityNode.textContent=city||'Выберите город';
      root.querySelectorAll('[data-request-visit-choice]').forEach(button=>{const active=button.dataset.requestVisitChoice===visit;button.classList.toggle('is-selected',active);button.setAttribute('aria-pressed',active?'true':'false');});
      if(addressWrap)addressWrap.hidden=visit!=='field';
      root.querySelectorAll('[data-request-date-choice]').forEach(button=>{const choice=button.dataset.requestDateChoice;const active=choice==='today'?date===todayIso():choice==='tomorrow'?date===tomorrowIso():choice==='custom'?Boolean(date&&date!==todayIso()&&date!==tomorrowIso()):false;button.classList.toggle('is-selected',active);button.setAttribute('aria-pressed',active?'true':'false');});
      const scheduleNode=root.querySelector('[data-request-schedule-label]'),scheduleMeta=root.querySelector('[data-request-schedule-meta]');if(scheduleNode)scheduleNode.textContent=time||'В течение дня';if(scheduleMeta)scheduleMeta.textContent=date?`${dateLabel(date)} · ${time?'точное время':'гибкое время'}`:'Сначала выберите дату';
      const problemMode=currentProblemMode(),serviceMode=root.querySelector('[data-request-service-mode]'),problemLabel=root.querySelector('[data-request-problem-label]'),problemHelp=root.querySelector('[data-request-problem-help]'),problemText=form.elements.description;
      root.querySelectorAll('[data-request-problem-choice]').forEach(button=>{const active=button.dataset.requestProblemChoice===problemMode;button.classList.toggle('is-selected',active);button.setAttribute('aria-selected',active?'true':'false');});
      if(serviceMode)serviceMode.hidden=problemMode!=='services';
      if(problemLabel)problemLabel.textContent='Описание проблемы';
      if(problemHelp)problemHelp.textContent=problemMode==='custom'?'Опишите симптом или необходимую работу своими словами. Минимум 5 символов.':'Кратко опишите симптомы или ожидаемый результат. Минимум 5 символов.';
      if(problemText)problemText.placeholder=problemMode==='custom'?'Например: появилась вибрация на холостых, слышен стук справа':'Например: заменить передние колодки, появился скрип';
    };

    const renderReview=()=>{
      const selected=selectedServices(),mode=currentOfferMode(),city=text(cityEl?.value),visit=currentVisitMode(),date=text(dateEl?.value),time=text(timeEl?.value),address=text(addressEl?.value),description=text(form.elements.description?.value),extraDetails=text(form.elements.extraDetails?.value),budget=Number(budgetEl?.value||0),problemMode=currentProblemMode();
      const mediaText=mediaFiles.length?`${mediaFiles.length} ${mediaFiles.length===1?'фото/видео':'файла(ов)'}`:'Без вложений';
      const offerMeta=mode==='own_price'?(budget?money(budget):'Бюджет не указан'):'Мастера сами предложат цену и срок';
      const problemValue=problemMode==='services'?(selected.length===1?selected[0].name:(selected.length?`${selected.length} услуги`:'Услуги не выбраны')):(description||'Проблема не описана');
      const problemMeta=problemMode==='services'?selected.map(x=>x.name).join(' · '):`${extraDetails?`${extraDetails} · `:''}${mediaText}`;
      const rows=isMaster?[
        ['0','car','АВТОМОБИЛЬ',currentCarTitle()||'Не выбран','Клиент записан к вам'],
        ['2','calendar','КОГДА',dateLabel(date),time||'В течение дня'],
        ['3','work','РАБОТЫ',problemValue,problemMeta]
      ]:[
        ['0','car','АВТОМОБИЛЬ',currentCarTitle()||'Не выбран',currentVehicleId()?'Из гаража':''],
        ['1','masters','ПРЕДЛОЖЕНИЕ',offerLabel(mode),offerMeta],
        ['2','location','ГДЕ',city||'Город не выбран',visit==='field'?(address||'Адрес не указан'):visitLabel(visit)],
        ['2','calendar','КОГДА',dateLabel(date),time||'В течение дня'],
        ['3','work','ПРОБЛЕМА',problemValue,problemMeta]
      ];
      const review=root.querySelector('[data-request-review]');if(review)review.innerHTML=rows.map(([idx,iconName,label,value,meta])=>`<button type="button" class="k-request-review-line ${/^Не |не указан|не выбраны|не описана/i.test(value+' '+meta)?'is-incomplete':''}" data-request-review-step="${idx}"><span class="k-request-review-icon">${icon(iconName)||'•'}</span><span class="k-request-review-copy"><small>${label}</small><b>${esc(value)}</b><em>${esc(meta||'')}</em></span><i>Изменить</i></button>`).join('')+`<div class="k-request-review-media">${mediaFiles.length?`${icon('camera')||'▣'} <b>${mediaFiles.length} ${mediaFiles.length===1?'фото':'файла(ов)'}</b>`:`${icon('camera')||'▣'} <b>Без фото</b>`}</div>`;
      const confirm=root.querySelector('[data-request-confirm-summary]');if(confirm)confirm.innerHTML=isMaster?`<div><span>Автомобиль</span><b>${esc(currentCarTitle()||'—')}</b></div><div><span>Исполнитель</span><b>Вы</b></div><div><span>Дата</span><b>${esc(dateLabel(date))}</b></div><div><span>Работы</span><b>${esc(problemMode==='services'?`${selected.length} услуг`:'Своя проблема')}</b></div><div><span>Файлы</span><b>${mediaFiles.length}</b></div>`:`<div><span>Автомобиль</span><b>${esc(currentCarTitle()||'—')}</b></div><div><span>Предложение</span><b>${esc(offerLabel(mode))}</b></div><div><span>Формат</span><b>${esc(visitLabel(visit))}</b></div><div><span>Дата</span><b>${esc(dateLabel(date))}</b></div><div><span>Проблема</span><b>${esc(problemMode==='services'?`${selected.length} услуг`:'Своя проблема')}</b></div><div><span>Файлы</span><b>${mediaFiles.length}</b></div>`;
    };

    const validateStep=index=>{
      if(index===0){const accountReady=text(nameEl?.value)&&text(phoneEl?.value).replace(/\D/g,'').length>=10;const carReady=isClient?Boolean(currentVehicleId()):Boolean(currentCarTitle());return Boolean(accountReady&&carReady);}
      if(index===1){const mode=currentOfferMode(),budget=Number(budgetEl?.value||0);if(!mode)return false;if(isClient&&mode==='own_price'&&budget<=0)return false;return isClient?['exchange','own_price'].includes(mode):mode==='direct_master';}
      if(index===2){const date=text(dateEl?.value);if(isMaster)return Boolean(date);const city=text(cityEl?.value),visit=currentVisitMode(),address=text(addressEl?.value);if(!city||!visit||!date)return false;if(visit==='field'&&address.length<3)return false;return true;}
      if(index===3){const description=text(form.elements.description?.value),mode=currentProblemMode();if(description.length<5)return false;if(mode==='services'&&selectedServices().length<1)return false;return true;}
      return flowSteps.filter(x=>x<4).every(validateStep)&&!!form.elements.consent?.checked;
    };
    const navMessage=()=>step===0?'Укажите клиента и автомобиль.':step===1?'Выберите способ получения предложения.':step===2?(isMaster?'Выберите дату записи.':'Укажите город, формат и дату.'):step===3?(currentProblemMode()==='services'&&selectedServices().length<1?'Выберите услугу.':'Опишите проблему минимум в 5 символах.'):'Проверьте данные и подтвердите согласие.';
    const syncNav=()=>{const ready=validateStep(step);if(nextBtn)nextBtn.disabled=!ready;const note=root.querySelector('[data-request-nav-note]');if(note){note.textContent=ready?(step===4?'Заявка готова к отправке':'Шаг заполнен'):navMessage();note.dataset.state=ready?'ready':'hint';}if(submitBtn)submitBtn.disabled=!validateStep(4);};
    const setStep=index=>{const requested=Math.max(0,Math.min(4,Number(index)||0)),normalized=flowSteps.includes(requested)?requested:(isMaster&&requested===1?2:flowSteps[0]);step=normalized;const pos=Math.max(0,flowSteps.indexOf(step));root.dataset.requestCurrentStep=String(pos+1);root.querySelectorAll('[data-request-panel]').forEach(panel=>{const active=Number(panel.dataset.stepIndex)===step;panel.hidden=!active;panel.classList.toggle('is-active',active);panel.setAttribute('aria-hidden',active?'false':'true');});const stepsNode=root.querySelector('[data-request-kflow-steps]');if(stepsNode)stepsNode.innerHTML=stepsHtml(step,flowSteps);const title=root.querySelector('[data-request-window-title]'),desc=root.querySelector('[data-request-window-desc]');if(title)title.textContent=isMaster&&step===2?'Когда записать клиента?':stepMeta[step][1];if(desc)desc.textContent=isMaster&&step===2?'Выберите дату и удобное время.':stepMeta[step][2];prevBtn.hidden=pos===0||Boolean(createdOrder);nextBtn.hidden=step===4||Boolean(createdOrder);if(nextBtn&&!nextBtn.hidden)nextBtn.textContent=step===3?'Проверить заявку':'Продолжить';submitBtn.hidden=step!==4||Boolean(createdOrder);if(step===4)renderReview();renderContextSummary();syncConditionCards();syncNav();saveDraft();requestAnimationFrame(()=>{const scrollHost=root.closest('.k-request-window-body');if(scrollHost)scrollHost.scrollTo({top:0,left:0,behavior:'auto'});else window.scrollTo({top:Math.max(0,root.getBoundingClientRect().top+window.scrollY),left:0,behavior:'auto'});title?.focus?.({preventScroll:true});});};
    const moveStep=delta=>{const pos=Math.max(0,flowSteps.indexOf(step)),nextPos=Math.max(0,Math.min(flowSteps.length-1,pos+Number(delta||0)));setStep(flowSteps[nextPos]);};
    const flowStepNumber=index=>Math.max(1,flowSteps.indexOf(index)+1);

    const closePicker=()=>{if(picker?.open){try{picker.close();}catch(_e){}}pickerMode='';};
    const syncVehicleStage=()=>{const empty=root.querySelector('[data-request-vehicle-empty]'),selected=root.querySelector('[data-request-vehicle-selected]');if(!empty||!selected)return;const hasVehicle=isClient?Boolean(currentVehicleId()):Boolean(currentCarTitle()),multi=isClient&&vehicles.length>1;empty.hidden=hasVehicle;selected.hidden=!hasVehicle||multi;renderVehicleQuicklist();};
    const showPicker=(title,eyebrow,html,mode)=>{if(!picker)return;pickerMode=mode||'';pickerTitle.textContent=title;pickerEyebrow.textContent=eyebrow;pickerBody.innerHTML=html;if(!picker.open)picker.showModal();requestAnimationFrame(()=>picker.querySelector('button,input,[tabindex]')?.focus?.({preventScroll:true}));};

    const vehicleCard=v=>{const title=text(v.title)||[v.brand,v.model,v.year_label||v.year].filter(Boolean).join(' ')||'Автомобиль';const active=text(v.id)===currentVehicleId(),primary=Number(v.is_default||v.isDefault||0)===1;return `<button class="k-request-vehicle-option ${active?'is-selected':''}" type="button" data-request-vehicle-option="${esc(v.id)}"><span>${icon('car')||'🚗'}</span><span><b>${esc(title)}</b><small>${esc([v.year_label||v.year,v.plate,Number(v.mileage_km||0)?`${Number(v.mileage_km).toLocaleString('ru-RU')} км`:null,primary?'Основной':null].filter(Boolean).join(' · ')||'Без дополнительных данных')}</small></span><i>${active?'✓':'○'}</i></button>`;};
    const renderVehicleQuicklist=()=>{const node=root.querySelector('[data-request-vehicle-quicklist]');if(!node||!isClient)return;const show=vehicles.length>1;node.hidden=!show;if(!show){node.innerHTML='';return;}const rows=vehicles.slice(0,3).map(v=>{const title=text(v.title)||[v.brand,v.model,v.year_label||v.year].filter(Boolean).join(' ')||'Автомобиль',active=text(v.id)===currentVehicleId();return `<button type="button" class="k-request-vehicle-quick ${active?'is-selected':''}" data-request-vehicle-quick="${esc(v.id)}" aria-pressed="${active?'true':'false'}"><span class="k-request-vehicle-quick__icon">${icon('car')||'🚗'}</span><span><b>${esc(title)}</b><small>${esc([v.plate,Number(v.is_default||v.isDefault||0)===1?'Основной':null].filter(Boolean).join(' · ')||'Автомобиль из гаража')}</small></span><i>${active?'✓':'○'}</i></button>`;}).join('');node.innerHTML=`<header><b>Мои автомобили</b><button type="button" data-request-open-picker="vehicle">${vehicles.length>3?`Все ${vehicles.length}`:'Изменить'}</button></header>${rows}<button type="button" class="k-request-vehicle-quick-add" data-request-open-picker="vehicle">+ Добавить автомобиль</button>`;};
    const vehiclePickerHtml=()=>`<div class="k-request-picker-context">Шаг 1 · Автомобиль</div><div class="k-request-picker-search"><input type="search" data-request-vehicle-search placeholder="Найти автомобиль…"></div><div class="k-request-vehicle-options">${vehicles.map(vehicleCard).join('')||'<div class="k-request-empty-state"><span>'+ (icon('car')||'🚗') +'</span><b>Автомобилей пока нет</b><p>Добавьте первый автомобиль, чтобы продолжить оформление заявки.</p></div>'}</div><section class="k-request-add-vehicle"><button class="k-btn k-btn-secondary" type="button" data-request-toggle-add-vehicle>+ Добавить автомобиль</button><form data-request-add-vehicle-form hidden><div class="k-request-add-vehicle-grid"><label>Госномер<input name="plate" required placeholder="123 ABC 16"></label><label>Марка<input name="brand" required placeholder="Renault"></label><label>Модель<input name="model" required placeholder="Logan"></label><label>Год<input name="year" required inputmode="numeric" min="1900" max="2100" placeholder="2019"></label><label>Поколение<input name="generation" placeholder="II рестайлинг"></label><label>VIN<input name="vin" maxlength="17" pattern="[A-HJ-NPR-Z0-9]{17}" placeholder="17 символов"></label><label>Цвет<input name="color" placeholder="Белый"></label></div><label class="k-request-inline-check"><input name="isDefault" type="checkbox"><span>Сделать основным</span></label><footer><button class="k-btn k-btn-primary" type="submit">Сохранить автомобиль</button><output data-request-add-vehicle-status></output></footer></form></section>`;
    const openVehiclePicker=()=>showPicker('Выберите автомобиль','ШАГ 1 · АВТОМОБИЛЬ',vehiclePickerHtml(),'vehicle');

    const servicePickerHtml=()=>{const map=offerMap(),groups=new Map();catalog.forEach(item=>{const offer=map.get(text(item.id));if((role==='master'||role==='sto')&&(!offer||!offer.active||!offer.bookingEnabled||offer.availabilityStatus==='paused'))return;const category=text(item.categoryName||item.category||'Другое')||'Другое';if(!groups.has(category))groups.set(category,[]);groups.get(category).push({item,offer});});const body=[...groups.entries()].map(([category,rows])=>`<section class="k-request-service-group" data-request-service-group><header><span class="k-request-service-group__icon" aria-hidden="true">${categorySvg(category)}</span><b>${esc(category)}</b><small>${rows.length}</small></header>${rows.map(({item,offer})=>{const id=text(item.id),active=selectedIds.has(id),price=Number(offer?.price??item.basePrice??item.base_price??0),duration=Number(offer?.durationMin||0);return `<button type="button" class="k-request-service-option ${active?'is-selected':''}" data-request-service-option="${esc(id)}" data-search="${esc((text(item.name)+' '+category).toLowerCase())}" aria-pressed="${active?'true':'false'}"><span><b>${esc(item.name)}</b><small>${esc([duration?`${duration} мин`:text(item.avgTime),price?`от ${money(price)}`:'Цена уточняется'].filter(Boolean).join(' · '))}</small></span><i>${active?'✓':'+'}</i></button>`;}).join('')}</section>`).join('');return `<div class="k-request-picker-context">Шаг ${flowStepNumber(3)} из ${flowSteps.length} · Услуги</div><div class="k-request-picker-search"><input type="search" data-request-service-search placeholder="Поиск услуги"></div><div class="k-request-service-groups">${body||'<div class="k-request-empty-r78">Доступных услуг пока нет.</div>'}</div><footer class="k-request-picker-footer"><span>Выбрано услуг: ${selectedServices().length}</span><button class="k-btn k-btn-primary" type="button" data-request-picker-done ${selectedServices().length?'':'disabled'}>Добавить выбранные</button></footer>`;};
    const openServicePicker=()=>showPicker('Выберите услугу',`ШАГ ${flowStepNumber(3)} ИЗ ${flowSteps.length} · УСЛУГИ`,servicePickerHtml(),'services');

    const nearestCity=(lat,lng)=>{let best='',bestDist=Infinity;Object.entries(cityCoords).forEach(([city,[clat,clng]])=>{const dy=(Number(lat)-clat)*111.32,dx=(Number(lng)-clng)*111.32*Math.cos(clat*Math.PI/180),d=Math.sqrt(dx*dx+dy*dy);if(d<bestDist){bestDist=d;best=city;}});return best;};
    const cityPickerHtml=()=>{const current=text(cityEl?.value),cities=cityCatalog();return `<div class="k-request-picker-context">Шаг ${flowStepNumber(2)} из ${flowSteps.length} · Город</div><div class="k-request-geo-card"><span>${icon('location')||'⌖'}</span><div><b>Определить автоматически</b><small>Разрешите геопозицию — город и точные координаты сохраняются отдельно.</small></div><button class="k-btn k-btn-secondary" type="button" data-request-detect-city>Определить город</button><output data-request-geo-status></output></div><div class="k-request-picker-divider">или</div><div class="k-request-picker-search"><input type="search" data-request-city-search placeholder="Найти город…"></div><div class="k-request-city-chips">${cities.slice(0,4).map(city=>`<button type="button" data-request-city-option="${esc(city)}" class="${city===current?'is-selected':''}">${esc(city)}</button>`).join('')}</div><div class="k-request-city-list">${cities.map(city=>`<button type="button" data-request-city-option="${esc(city)}" data-search="${esc(city.toLowerCase())}" class="${city===current?'is-selected':''}"><span>${icon('location')||'⌖'}</span><span><b>${esc(city)}</b><small>Казахстан</small></span><i>${city===current?'✓':'○'}</i></button>`).join('')}</div>`;};
    const openCityPicker=()=>showPicker('Выберите город',`ШАГ ${flowStepNumber(2)} ИЗ ${flowSteps.length} · ГОРОД`,cityPickerHtml(),'city');

    const visitPickerHtml=()=>{const current=currentVisitMode();return `<div class="k-request-picker-context">Шаг ${flowStepNumber(2)} из ${flowSteps.length} · Посещение</div><div class="k-request-choice-stack"><button type="button" class="k-flow-mode-choice ${current==='field'?'is-selected':''}" data-request-visit-option="field"><span>${icon('location')||'⌖'}</span><span><b>Выезд мастера</b><small>Мастер приезжает к автомобилю</small></span><i>${current==='field'?'✓':''}</i></button><button type="button" class="k-flow-mode-choice ${current==='service'?'is-selected':''}" data-request-visit-option="service"><span>${icon('car')||'🚗'}</span><span><b>Приехать в сервис</b><small>Запись в мастерскую или СТО</small></span><i>${current==='service'?'✓':''}</i></button></div>`;};
    const openVisitPicker=()=>showPicker('Как будет проходить работа?',`ШАГ ${flowStepNumber(2)} ИЗ ${flowSteps.length} · ПОСЕЩЕНИЕ`,visitPickerHtml(),'visit');

    const masterRows=()=>{const current=selectedMaster().id;return mastersCatalog.map(m=>{const id=text(m.id||m.masterId),name=text(m.name||m.masterName||'Мастер'),rating=Number(m.rating||0),spec=text(m.spec||m.specialization||''),city=text(m.city||'');return `<button type="button" class="k-request-master-option ${id===current?'is-selected':''}" data-request-master-option="${esc(id)}" data-request-master-name="${esc(name)}" data-search="${esc((name+' '+spec+' '+city).toLowerCase())}"><span class="k-request-master-avatar">${esc((name[0]||'М').toUpperCase())}</span><span><b>${esc(name)}</b><small>${rating?`★ ${rating.toFixed(1)} · `:''}${esc([spec,city].filter(Boolean).join(' · ')||'Мастер KARETA')}</small></span><i>${id===current?'✓':'○'}</i></button>`;}).join('')||'<div class="k-request-empty-r78">Мастера появятся после загрузки каталога.</div>';};
    const offerPickerHtml=()=>{const mode=currentOfferMode(),budget=Number(budgetEl?.value||0),budgetMode=text(budgetModeEl?.value)||'discuss';return `<div class="k-request-picker-context">Шаг ${flowStepNumber(1)} из ${flowSteps.length} · Способ</div><div class="k-request-choice-stack"><button type="button" class="k-flow-mode-choice ${mode==='exchange'?'is-selected':''}" data-request-offer-option="exchange"><span>${icon('exchange')||'↔'}</span><span><b>Предложения мастеров</b><small>Мастера предложат цену и срок</small></span><i>${mode==='exchange'?'✓':''}</i></button><button type="button" class="k-flow-mode-choice ${mode==='own_price'?'is-selected':''}" data-request-offer-option="own_price"><span>${icon('finance')||'₸'}</span><span><b>Своя цена</b><small>Укажите желаемый бюджет</small></span><i>${mode==='own_price'?'✓':''}</i></button><button type="button" class="k-flow-mode-choice ${mode==='direct_master'?'is-selected':''}" data-request-offer-option="direct_master"><span>${icon('masters')||'M'}</span><span><b>Выбрать мастера</b><small>Прямая запись без раскрытия контактов</small></span><i>${mode==='direct_master'?'✓':''}</i></button></div>${mode==='own_price'?`<div class="k-request-offer-detail"><label class="k-flow-field"><span>Желаемый бюджет</span><input type="number" min="1" step="1000" data-request-budget-input value="${budget||''}" placeholder="Например, 30000"></label><div class="k-request-segmented"><button type="button" data-request-budget-mode-option="discuss" class="${budgetMode==='discuss'?'is-selected':''}">Бюджет обсуждается</button><button type="button" data-request-budget-mode-option="fixed" class="${budgetMode==='fixed'?'is-selected':''}">Цена фиксированная</button></div><small>Мастер может предложить другую цену — вы решаете, принимать ли предложение.</small><button class="k-btn k-btn-primary" type="button" data-request-offer-save-budget ${budget>0?'':'disabled'}>Сохранить бюджет</button></div>`:''}${mode==='direct_master'?`<div class="k-request-offer-detail"><div class="k-request-picker-search"><input type="search" data-request-master-search placeholder="Найти мастера…"></div><div class="k-request-master-list" data-request-master-list>${masterRows()}</div></div>`:''}`;};
    const openOfferPicker=async()=>{if(!isClient){offerModeEl.value='direct_master';syncConditionCards();return;}if(currentOfferMode()==='direct_master'&&!mastersCatalog.length)await loadMasters();showPicker('Как получить предложения?',`ШАГ ${flowStepNumber(1)} ИЗ ${flowSteps.length} · СПОСОБ`,offerPickerHtml(),'offer');};
    const openMasterPicker=async()=>{if(!mastersCatalog.length)await loadMasters();showPicker('Выберите мастера',`ШАГ ${flowStepNumber(1)} ИЗ ${flowSteps.length} · МАСТЕР`,`<div class="k-request-picker-search"><input type="search" data-request-master-search placeholder="Найти мастера…"></div><div class="k-request-master-list" data-request-master-list>${masterRows()}</div>`,'master');};

    const schedulePickerHtml=()=>{const date=text(dateEl?.value),time=text(timeEl?.value);return `<div class="k-request-picker-context">Шаг ${flowStepNumber(2)} из ${flowSteps.length} · Дата и время</div><div class="k-request-schedule-quick"><button type="button" data-request-quick-date="${todayIso()}" class="${date===todayIso()?'is-selected':''}">Сегодня</button><button type="button" data-request-quick-date="${tomorrowIso()}" class="${date===tomorrowIso()?'is-selected':''}">Завтра</button><label><span>Выбрать дату</span><input type="date" data-request-picker-date min="${todayIso()}" value="${esc(date)}"></label></div><div class="k-request-picker-slots"><header><b>Предпочтительное время</b><small>${esc(isMaster?'Запись к вам':text(cityEl?.value)||'Сначала выберите город')}</small></header><div class="k-request-slot-list" data-request-picker-slots><span class="k-request-slots-loading">${date?'Проверяем свободное время…':'Выберите дату'}</span></div></div><footer class="k-request-picker-footer"><span>${time?`Выбрано: ${esc(time)}`:'Выберите предпочтительное время'}</span><button class="k-btn k-btn-primary" type="button" data-request-schedule-done ${date?'':'disabled'}>Выбрать время</button></footer>`;};
    const openSchedulePicker=()=>{showPicker('Дата и время',`ШАГ ${flowStepNumber(2)} ИЗ ${flowSteps.length} · ДАТА И ВРЕМЯ`,schedulePickerHtml(),'schedule');if(text(dateEl?.value))loadPickerSlots();};

    const applyVehicle=v=>{selectedVehicle=v||null;if(vehicleIdEl)vehicleIdEl.value=text(v?.id);const title=text(v?.title)||[v?.brand,v?.model,v?.year_label||v?.year].filter(Boolean).join(' ');if(vehicleTitleEl)vehicleTitleEl.value=title;if(vehicleLabel)vehicleLabel.textContent=title||'Выберите машину из гаража';if(vehicleMeta)vehicleMeta.textContent=[v?.year_label||v?.year,v?.plate].filter(Boolean).join(' · ')||'Цифровой паспорт автомобиля';renderContextSummary();syncVehicleStage();renderVehicleQuicklist();syncNav();saveDraft();};
    const loadVehicles=async()=>{if(!isClient)return;try{const r=await api.request('api/db.php?action=clientCabinet.get',{cacheTtlMs:15000,cacheKey:'client.cabinet'});vehicles=Array.isArray(r.payload?.data?.vehicles)?r.payload.data.vehicles:[];const wanted=text(prefill?.clientVehicleId||prefill?.vehicleId||draft.clientVehicleId);const chosen=vehicles.find(v=>text(v.id)===wanted)||vehicles.find(v=>Number(v.is_default)===1)||vehicles[0]||null;if(chosen)applyVehicle(chosen);else {syncVehicleStage();syncNav();}}catch(_e){vehicles=[];syncVehicleStage();syncNav();}};
    const renderServicesReady=(rows,offerRows=[])=>{catalog=Array.isArray(rows)?rows:[];offers=Array.isArray(offerRows)?offerRows:[];servicesReady=true;if(servicesStatus)servicesStatus.hidden=true;const prefillId=text(prefill?.serviceId),prefillName=text(prefill?.serviceName).toLowerCase();if(prefillId)selectedIds.add(prefillId);if(prefillName&&!selectedIds.size){const found=catalog.find(x=>{const n=text(x.name).toLowerCase();return n===prefillName||n.includes(prefillName)||prefillName.includes(n);});if(found)selectedIds.add(text(found.id));}if(!primaryId&&selectedIds.size)primaryId=[...selectedIds][0];renderSelected();};
    const loadServices=async()=>{try{if((role==='master'||role==='sto')&&window.KaretaServiceOffersApi){const d=await window.KaretaServiceOffersApi.load({force:true});renderServicesReady(d.catalog||[],d.offers||[]);}else if(window.KaretaServiceOffersApi)renderServicesReady(await window.KaretaServiceOffersApi.loadCatalogFallback({force:true}),[]);else{const r=await api.request('api/db.php?action=services.catalog',{cacheTtlMs:30000,cacheKey:'services.catalog'});renderServicesReady(Array.isArray(r.payload?.data?.services)?r.payload.data.services:[],[]);}}catch(_error){servicesReady=false;if(servicesStatus){servicesStatus.hidden=false;servicesStatus.textContent='Каталог временно недоступен. Повторите загрузку.';}syncNav();}};
    const loadMasters=async()=>{try{const r=await api.getMastersCatalog?.({city:text(cityEl?.value)});const d=r?.payload?.data||r?.payload||{};mastersCatalog=Array.isArray(d.masters)?d.masters:[];}catch(_e){mastersCatalog=[];}};

    const applyCity=(city,coords={})=>{if(cityEl)cityEl.value=text(city);if(latEl)latEl.value=coords.lat!==undefined?String(coords.lat):text(latEl.value);if(lngEl)lngEl.value=coords.lng!==undefined?String(coords.lng):text(lngEl.value);try{localStorage.setItem('kareta.home.location.v1',JSON.stringify({city:text(cityEl?.value),lat:text(latEl?.value)||null,lng:text(lngEl?.value)||null,updatedAt:Date.now()}));}catch(_e){}syncConditionCards();syncNav();saveDraft();};
    const applyVisit=mode=>{if(visitModeEl)visitModeEl.value=mode==='field'?'field':'service';syncConditionCards();syncNav();saveDraft();};
    const setOfferMode=mode=>{if(!offerModeEl)return;const allowed=isClient?(['exchange','own_price'].includes(mode)?mode:''):(mode==='direct_master'?'direct_master':'');offerModeEl.value=allowed;syncConditionCards();syncNav();saveDraft();};
    const setSchedule=(date,time)=>{if(dateEl)dateEl.value=text(date);if(timeEl)timeEl.value=text(time);syncConditionCards();syncNav();saveDraft();};
    const loadPickerSlots=async()=>{const slots=pickerBody.querySelector('[data-request-picker-slots]'),date=text(pickerBody.querySelector('[data-request-picker-date]')?.value||dateEl?.value);if(!slots||!date)return;const wanted=text(timeEl?.value);const options=['','Утро','День','Вечер'];slots.innerHTML=options.map(value=>`<button type="button" data-request-picker-slot="${esc(value)}" class="${wanted===value?'is-selected':''}">${value||'В течение дня'}</button>`).join('')+`<label class="k-request-exact-time"><span>Точное время</span><input type="time" data-request-exact-time value="${/^\d{2}:\d{2}$/.test(wanted)?esc(wanted):''}"></label>`;};

    const fileToDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error||new Error('file_read_failed'));reader.readAsDataURL(file);});
    const uploadMedia=async(order,response)=>{if(!mediaFiles.length||response?.duplicate)return {ok:true,failed:0};const chatId=text(response?.chat?.id||response?.chatId||order?.chat_id||order?.chatId);if(!chatId||typeof api.sendMessage!=='function')return {ok:false,failed:mediaFiles.length};let failed=0;for(let i=0;i<mediaFiles.length;i+=1){const file=mediaFiles[i];try{const data=await fileToDataUrl(file),type=file.type.startsWith('video/')?'video':'image';const r=await api.sendMessage(chatId,{type,text:type==='video'?'Видео к заявке':'Фото к заявке',fileName:file.name,fileType:file.type,fileData:data,orderId:text(order.id)},{idempotencyKey:`request-media:${text(order.id)}:${i}:${file.size}:${file.lastModified}`});if(!r?.ok)failed+=1;}catch(_e){failed+=1;}}return {ok:failed===0,failed};};
    const showCreatedState=(order,response,mediaResult)=>{submitting=false;createdOrder=order||{};const state=root.querySelector('[data-request-confirm-state]');if(state)state.innerHTML=`<span class="k-flow-confirm-icon is-success">${icon('check')||'✓'}</span><h3>${response?.duplicate?'Заявка уже существует':'Заявка создана'}</h3><p>${mediaResult?.failed?`Заявка создана. Не удалось прикрепить файлов: ${mediaResult.failed}.`:`Номер заявки: ${esc(createdOrder.id||'—')}. Данные сохранены.`}</p>`;if(statusEl)statusEl.textContent=mediaResult?.failed?'Файлы можно отправить позже в чате заявки.':'';const actions=root.querySelector('[data-request-success-actions]');if(actions)actions.hidden=false;prevBtn.hidden=true;nextBtn.hidden=true;submitBtn.hidden=true;const stepsNode=root.querySelector('[data-request-kflow-steps]');if(stepsNode)stepsNode.innerHTML='<div class="k-request-success-progress">Заявка отправлена</div>';};

    const applyAccount=user=>{if(!isClient)return;if(nameEl)nameEl.value=text(user?.name);if(phoneEl)phoneEl.value=text(user?.phone);syncNav();};
    applyAccount(window.KaretaNext?.state?.user||context.state?.user||{});if(isClient&&!(text(nameEl?.value)&&text(phoneEl?.value)))api.getSession({force:true}).then(r=>applyAccount(r?.payload?.user||{})).catch(()=>{});
    if(!isClient){if(nameEl)nameEl.value=text(prefill?.clientName||draft.clientName);if(phoneEl)phoneEl.value=text(prefill?.clientPhone||draft.clientPhone);if(form.elements.clientCar)form.elements.clientCar.value=text(prefill?.clientCar||draft.clientCar);}
    if(form.elements.description)form.elements.description.value=text(prefill?.description||draft.description);if(form.elements.extraDetails)form.elements.extraDetails.value=text(prefill?.extraDetails||draft.extraDetails);
    const homeLocation=readHomeLocation();if(cityEl)cityEl.value=text(prefill?.city||draft.city||homeLocation.city||window.KaretaNext?.state?.user?.city||context.state?.user?.city);if(latEl)latEl.value=text(prefill?.lat||draft.lat||homeLocation.lat);if(lngEl)lngEl.value=text(prefill?.lng||draft.lng||homeLocation.lng);if(visitModeEl)visitModeEl.value=text(prefill?.visitMode||draft.visitMode);if(addressEl)addressEl.value=text(prefill?.serviceAddress||prefill?.address||draft.serviceAddress||draft.address);if(dateEl)dateEl.value=text(prefill?.date||draft.date);if(timeEl)timeEl.value=text(prefill?.time||draft.time);if(budgetEl)budgetEl.value=Number(prefill?.budget??draft.budget??0)||'';if(budgetModeEl)budgetModeEl.value=text(prefill?.budgetMode||draft.budgetMode)||'discuss';if(directMasterIdEl)directMasterIdEl.value=text(prefill?.masterId||draft.masterId||draft.directMasterId);if(directMasterNameEl)directMasterNameEl.value=text(prefill?.masterName||draft.masterName||draft.directMasterName);
    if(isMaster){if(cityEl)cityEl.value='';if(latEl)latEl.value='';if(lngEl)lngEl.value='';if(visitModeEl)visitModeEl.value='';if(addressEl)addressEl.value='';if(directMasterIdEl)directMasterIdEl.value='';if(directMasterNameEl)directMasterNameEl.value='';}
    if(problemModeEl){const restoredProblem=text(prefill?.problemMode||draft.problemMode);problemModeEl.value=['services','custom'].includes(restoredProblem)?restoredProblem:(selectedIds.size?'services':text(prefill?.description||draft.description)?'custom':'services');}
    if(isClient){const restoredOffer=text(prefill?.offerMode||draft.offerMode);setOfferMode(['exchange','own_price'].includes(restoredOffer)?restoredOffer:'');}else setOfferMode('direct_master');

    const click=async event=>{
      if(event.target.closest('[data-request-head-back]')){if(flowSteps.indexOf(step)>0)moveStep(-1);else if(windowMode&&window.KaretaRequestWindow?.isOpen?.())window.KaretaRequestWindow.close();else location.hash='#/services';return;}
      if(event.target.closest('[data-request-prev]')){moveStep(-1);return;}
      if(event.target.closest('[data-request-next]')){if(validateStep(step))moveStep(1);else syncNav();return;}
      const termsLink=event.target.closest('[data-request-terms-link]');if(termsLink){event.preventDefault();saveDraft();if(rulesDialog&&!rulesDialog.open)rulesDialog.showModal();return;}if(event.target.closest('[data-request-rules-close]')||event.target===rulesDialog){if(rulesDialog?.open)rulesDialog.close();return;}
      const finalOffer=event.target.closest('[data-request-offer-choice]');if(finalOffer){setOfferMode(finalOffer.dataset.requestOfferChoice||'');syncConditionCards();syncNav();saveDraft();return;}
      const problemChoice=event.target.closest('[data-request-problem-choice]');if(problemChoice){if(problemModeEl)problemModeEl.value=problemChoice.dataset.requestProblemChoice||'services';syncConditionCards();syncNav();saveDraft();return;}
      if(event.target.closest('[data-request-pick-master]')){await openMasterPicker();return;}
      const inlineBudgetMode=event.target.closest('[data-request-inline-budget-mode]');if(inlineBudgetMode){budgetModeEl.value=inlineBudgetMode.dataset.requestInlineBudgetMode||'discuss';syncConditionCards();syncNav();saveDraft();return;}
      const visitChoice=event.target.closest('[data-request-visit-choice]');if(visitChoice){applyVisit(visitChoice.dataset.requestVisitChoice||'');syncConditionCards();return;}
      const dateChoice=event.target.closest('[data-request-date-choice]');if(dateChoice){const choice=dateChoice.dataset.requestDateChoice;if(choice==='custom'){openSchedulePicker();return;}setSchedule(choice==='today'?todayIso():tomorrowIso(),text(timeEl?.value));syncConditionCards();return;}
      const quickVehicle=event.target.closest('[data-request-vehicle-quick]');if(quickVehicle){const selected=vehicles.find(v=>text(v.id)===text(quickVehicle.dataset.requestVehicleQuick));if(selected)applyVehicle(selected);return;}
      const open=event.target.closest('[data-request-open-picker]')?.dataset.requestOpenPicker;if(open==='vehicle'){openVehiclePicker();return;}if(open==='services'){openServicePicker();return;}if(open==='city'){openCityPicker();return;}if(open==='visit'){openVisitPicker();return;}if(open==='offer'){await openOfferPicker();return;}if(open==='schedule'){openSchedulePicker();return;}
      if(event.target.closest('[data-request-picker-close]')||event.target===picker){closePicker();return;}
      if(event.target.closest('[data-request-picker-done]')){closePicker();renderSelected();return;}
      if(event.target.closest('[data-request-custom-toggle]')){const customForm=pickerBody.querySelector('[data-request-custom-service-form]');if(customForm)customForm.hidden=!customForm.hidden;return;}
      const vehicleOption=event.target.closest('[data-request-vehicle-option]');if(vehicleOption){const v=vehicles.find(row=>text(row.id)===text(vehicleOption.dataset.requestVehicleOption));if(v){applyVehicle(v);closePicker();}return;}
      if(event.target.closest('[data-request-toggle-add-vehicle]')){const f=pickerBody.querySelector('[data-request-add-vehicle-form]');if(f)f.hidden=!f.hidden;return;}
      const serviceOption=event.target.closest('[data-request-service-option]');if(serviceOption){const id=text(serviceOption.dataset.requestServiceOption);if(selectedIds.has(id)){selectedIds.delete(id);if(primaryId===id)primaryId=[...selectedIds][0]||'';}else{selectedIds.add(id);if(!primaryId)primaryId=id;}serviceOption.classList.toggle('is-selected',selectedIds.has(id));serviceOption.setAttribute('aria-pressed',selectedIds.has(id)?'true':'false');serviceOption.querySelector('i').textContent=selectedIds.has(id)?'✓':'+';const footer=pickerBody.querySelector('.k-request-picker-footer span');if(footer)footer.textContent=`Выбрано услуг: ${selectedServices().length}`;const done=pickerBody.querySelector('[data-request-picker-done]');if(done)done.disabled=!selectedServices().length;renderSelected();return;}
      const remove=event.target.closest('[data-request-remove-service]');if(remove){const id=text(remove.dataset.requestRemoveService);if(id.startsWith('custom:'))customServices=customServices.filter(row=>row.id!==id);else selectedIds.delete(id);if(primaryId===id)primaryId=[...selectedIds][0]||'';renderSelected();return;}
      const cityOption=event.target.closest('[data-request-city-option]');if(cityOption){applyCity(cityOption.dataset.requestCityOption||'');closePicker();return;}
      if(event.target.closest('[data-request-detect-city]')){const out=pickerBody.querySelector('[data-request-geo-status]');if(!navigator.geolocation){if(out){out.textContent='Геолокация недоступна. Выберите город вручную.';out.hidden=false;}return;}if(out){out.textContent='Определяем местоположение…';out.hidden=false;}navigator.geolocation.getCurrentPosition(pos=>{const lat=Number(pos.coords.latitude),lng=Number(pos.coords.longitude),city=nearestCity(lat,lng);applyCity(city,{lat,lng});if(out)out.textContent=`Определено: ${city}`;setTimeout(()=>closePicker(),350);},()=>{if(out)out.textContent='Доступ к геолокации не получен. Выберите город вручную.';},{enableHighAccuracy:false,timeout:8000,maximumAge:300000});return;}
      const visit=event.target.closest('[data-request-visit-option]');if(visit){applyVisit(visit.dataset.requestVisitOption);closePicker();return;}
      const offer=event.target.closest('[data-request-offer-option]');if(offer){setOfferMode(offer.dataset.requestOfferOption);if(currentOfferMode()==='direct_master'&&!mastersCatalog.length)await loadMasters();pickerBody.innerHTML=offerPickerHtml();return;}
      const budgetMode=event.target.closest('[data-request-budget-mode-option]');if(budgetMode){budgetModeEl.value=budgetMode.dataset.requestBudgetModeOption||'discuss';pickerBody.querySelectorAll('[data-request-budget-mode-option]').forEach(b=>b.classList.toggle('is-selected',b===budgetMode));saveDraft();return;}
      if(event.target.closest('[data-request-offer-save-budget]')){const value=Number(pickerBody.querySelector('[data-request-budget-input]')?.value||0);if(value>0){budgetEl.value=String(value);syncConditionCards();closePicker();}return;}
      const masterOption=event.target.closest('[data-request-master-option]');if(masterOption){directMasterIdEl.value=masterOption.dataset.requestMasterOption||'';directMasterNameEl.value=masterOption.dataset.requestMasterName||'';syncConditionCards();saveDraft();closePicker();return;}
      const quick=event.target.closest('[data-request-quick-date]');if(quick){const inputDate=pickerBody.querySelector('[data-request-picker-date]');if(inputDate)inputDate.value=quick.dataset.requestQuickDate||'';setSchedule(quick.dataset.requestQuickDate||'',text(timeEl?.value));pickerBody.querySelectorAll('[data-request-quick-date]').forEach(b=>b.classList.toggle('is-selected',b===quick));loadPickerSlots();const done=pickerBody.querySelector('[data-request-schedule-done]');if(done)done.disabled=false;return;}
      const slot=event.target.closest('[data-request-picker-slot]');if(slot){timeEl.value=slot.dataset.requestPickerSlot||'';pickerBody.querySelectorAll('[data-request-picker-slot]').forEach(b=>b.classList.toggle('is-selected',b===slot));const footer=pickerBody.querySelector('.k-request-picker-footer span');if(footer)footer.textContent=timeEl.value?`Выбрано: ${timeEl.value}`:'Время согласуем позже';saveDraft();return;}
      if(event.target.closest('[data-request-schedule-done]')){const pickerDate=pickerBody.querySelector('[data-request-picker-date]');setSchedule(pickerDate?.value||dateEl.value,timeEl.value);closePicker();return;}
      const reviewStep=event.target.closest('[data-request-review-step]');if(reviewStep){setStep(Number(reviewStep.dataset.requestReviewStep));return;}
      const removeMedia=event.target.closest('[data-request-remove-media]');if(removeMedia){mediaFiles.splice(Number(removeMedia.dataset.requestRemoveMedia),1);renderMedia();saveDraft();return;}
      if(event.target.closest('[data-request-open-created]')){const href=createdOrder?.id?`#/orders/item/${encodeURIComponent(createdOrder.id)}`:'#/orders';window.KaretaRequestWindow?.close?.({restore:false});if(createdOrder?.id&&!window.KaretaWindowEngine?.openEntity?.(href))location.hash=href;else if(!createdOrder?.id)location.hash=href;return;}
    };

    const input=event=>{if(event.target.matches('[data-request-service-search]')){const q=text(event.target.value).toLowerCase();pickerBody.querySelectorAll('[data-request-service-option]').forEach(row=>row.hidden=!!q&&!text(row.dataset.search).includes(q));pickerBody.querySelectorAll('[data-request-service-group]').forEach(group=>group.hidden=![...group.querySelectorAll('[data-request-service-option]')].some(row=>!row.hidden));return;}if(event.target.matches('[data-request-vehicle-search]')){const q=text(event.target.value).toLowerCase();pickerBody.querySelectorAll('[data-request-vehicle-option]').forEach(row=>row.hidden=!!q&&!text(row.textContent).toLowerCase().includes(q));return;}if(event.target.matches('[data-request-city-search]')){const q=text(event.target.value).toLowerCase();pickerBody.querySelectorAll('[data-request-city-option][data-search]').forEach(row=>row.hidden=!!q&&!text(row.dataset.search).includes(q));return;}if(event.target.matches('[data-request-master-search]')){const q=text(event.target.value).toLowerCase();pickerBody.querySelectorAll('[data-request-master-option]').forEach(row=>row.hidden=!!q&&!text(row.dataset.search).includes(q));return;}if(event.target.matches('[data-request-budget-input]')){const save=pickerBody.querySelector('[data-request-offer-save-budget]');if(save)save.disabled=Number(event.target.value||0)<=0;return;}if(event.target===budgetEl||event.target===addressEl){syncConditionCards();saveDraft();syncNav();return;}saveDraft();syncNav();};
    const change=event=>{if(event.target===mediaInput){const incoming=[...(event.target.files||[])],valid=incoming.filter(file=>{const image=/^image\/(jpeg|png|webp|gif)$/i.test(file.type)&&file.size<=2*1024*1024,video=/^video\/(mp4|webm)$/i.test(file.type)&&file.size<=2.4*1024*1024;return image||video;});mediaFiles=[...mediaFiles,...valid].slice(0,10);event.target.value='';renderMedia();saveDraft();return;}if(event.target.matches('[data-request-picker-date]')){setSchedule(event.target.value,text(timeEl?.value));loadPickerSlots();const done=pickerBody.querySelector('[data-request-schedule-done]');if(done)done.disabled=!event.target.value;return;}if(event.target.matches('[data-request-exact-time]')){setSchedule(text(pickerBody.querySelector('[data-request-picker-date]')?.value||dateEl?.value),text(event.target.value));pickerBody.querySelectorAll('[data-request-picker-slot]').forEach(b=>b.classList.remove('is-selected'));const footer=pickerBody.querySelector('.k-request-picker-footer span');if(footer)footer.textContent=event.target.value?`Выбрано: ${event.target.value}`:'В течение дня';return;}input(event);};

    const submit=async event=>{
      const customForm=event.target.closest('[data-request-custom-service-form]');if(customForm){event.preventDefault();const fd=new FormData(customForm),name=text(fd.get('name')),budget=Math.max(0,Number(fd.get('budget')||0));if(name.length<5)return;customServices.push({id:`custom:${Date.now()}:${Math.random().toString(36).slice(2,8)}`,name,category:'По описанию',price:budget,custom:true});renderSelected();closePicker();window.KaretaToast?.success('Услуга добавлена');return;}
      const vehicleForm=event.target.closest('[data-request-add-vehicle-form]');if(vehicleForm){event.preventDefault();const out=vehicleForm.querySelector('[data-request-add-vehicle-status]'),button=vehicleForm.querySelector('[type="submit"]');button.disabled=true;if(out)out.textContent='Сохраняем…';const fd=new FormData(vehicleForm),vehicle=Object.fromEntries(fd.entries());vehicle.isDefault=fd.has('isDefault');try{const year=Number(vehicle.year||0);if(year<1900||year>new Date().getFullYear()+1)throw new Error('Проверьте год автомобиля');const vin=text(vehicle.vin).toUpperCase();if(vin&&(!/^[A-HJ-NPR-Z0-9]{17}$/.test(vin)))throw new Error('VIN должен содержать 17 символов без I, O, Q');vehicle.vin=vin;vehicle.plate=text(vehicle.plate).toUpperCase();const r=await window.KaretaClientCabinetApi?.saveVehicle?.(vehicle);if(!r?.ok)throw new Error(r?.payload?.message||r?.payload?.error||'Не удалось добавить автомобиль');window.KaretaApiClient?.invalidate?.('client.cabinet');const saved=r.payload?.vehicle||null;await loadVehicles();if(saved){const matched=vehicles.find(v=>text(v.id)===text(saved.id));if(matched)applyVehicle(matched);}closePicker();window.KaretaToast?.success('Автомобиль добавлен');}catch(error){if(out)out.textContent=error?.message||'Ошибка добавления';}finally{button.disabled=false;}return;}
      if(event.target!==form)return;event.preventDefault();const firstInvalid=flowSteps.filter(x=>x<4).find(index=>!validateStep(index));if(firstInvalid!==undefined){setStep(firstInvalid);return;}if(!form.elements.consent?.checked){syncNav();return;}if(createdOrder||submitting)return;
      submitting=true;submitBtn.disabled=true;if(statusEl)statusEl.textContent='Отправляем заявку…';const selected=selectedServices(),description=text(form.elements.description?.value),extraDetails=text(form.elements.extraDetails?.value),mode=currentOfferMode(),master=selectedMaster(),isExchange=isClient&&(mode==='exchange'||mode==='own_price')&&!text(prefill?.masterId||draft.masterId)&&!text(prefill?.stoId||draft.stoId),visit=currentVisitMode(),time=text(timeEl?.value),budget=Number(budgetEl?.value||0);
      const notes=(isMaster?[description,extraDetails?`Дополнительно: ${extraDetails}`:'',`Предпочтительное время: ${time||'В течение дня'}`]:[description,extraDetails?`Дополнительно: ${extraDetails}`:'',`Город: ${text(cityEl?.value)}`,`Предпочтительное время: ${time||'В течение дня'}`,visit==='field'&&text(addressEl?.value)?`Адрес: ${text(addressEl?.value)}`:'',`Посещение: ${visitLabel(visit)}`,`Способ: ${offerLabel(mode)}`,mode==='own_price'&&budget?`Бюджет: ${money(budget)} (${text(budgetModeEl?.value)==='fixed'?'фиксированная':'обсуждается'})`:'']).filter(Boolean).join('\n');
      const payload={clientName:text(nameEl?.value),clientPhone:text(phoneEl?.value),clientVehicleId:currentVehicleId(),clientCar:currentCarTitle(),serviceIds:currentProblemMode()==='services'?selected.filter(x=>!x.custom).map(x=>x.id):[],serviceNames:currentProblemMode()==='services'?selected.map(x=>x.name).join(', '):'Своя проблема',description,comment:description,notes,category:text(prefill?.category||draft.category)||'service',source:role==='master'?'master_client_booking':text(prefill?.source||draft.source)||(role==='sto'?'sto_client_booking':'kflow_request'),priority:'normal',date:text(dateEl?.value),time:/^\d{2}:\d{2}$/.test(time)?time:'',timeMode:/^\d{2}:\d{2}$/.test(time)?'exact':'nearest',fieldService:isMaster?false:visit==='field',address:isMaster?'':(visit==='field'?text(addressEl?.value):text(cityEl?.value)),serviceAddress:isMaster?'':text(addressEl?.value),lat:isMaster?'':text(latEl?.value),lng:isMaster?'':text(lngEl?.value),status:isExchange?'waiting_responses':'new',type:'service_order',masterId:isMaster?'':mode==='direct_master'?text(master.id||prefill?.masterId||draft.masterId):text(prefill?.masterId||draft.masterId),masterName:isMaster?'':mode==='direct_master'?text(master.name||prefill?.masterName||draft.masterName):text(prefill?.masterName||draft.masterName),stoId:text(prefill?.stoId||draft.stoId),stoName:text(prefill?.stoName||draft.stoName),offerId:text(prefill?.offerId||draft.offerId),offerPrice:Number(prefill?.offerPrice??draft.offerPrice??0),offerPriceType:text(prefill?.offerPriceType||draft.offerPriceType),offerPriceMax:Number(prefill?.offerPriceMax??draft.offerPriceMax??0),budgetFrom:mode==='own_price'?budget:undefined,budgetTo:mode==='own_price'?budget:undefined,promotion:Boolean(prefill?.promotion??draft.promotion)};
      saveDraft();let r;try{r=await api.createOrder(payload,{idempotencyKey:draft.idempotencyKey});}catch(error){submitting=false;submitBtn.disabled=false;saveDraft();if(statusEl)statusEl.textContent=error?.message||'Не удалось создать заказ';return;}submitBtn.disabled=false;if(!r.ok){submitting=false;saveDraft();if(statusEl)statusEl.textContent=r.payload?.message||r.payload?.error||'Не удалось создать заказ';return;}const order=r.payload?.order||{};if(statusEl)statusEl.textContent=mediaFiles.length?'Заявка создана. Прикрепляем файлы…':'';const mediaResult=await uploadMedia(order,r.payload||{});if(!r.payload?.duplicate){try{sessionStorage.removeItem(REQUEST_DRAFT_KEY);sessionStorage.removeItem(LEGACY_DRAFT_KEY);sessionStorage.removeItem(LEGACY_SERVICE_DRAFT_KEY);}catch(_e){}}['GET:api/db.php?action=pull','orders.list','client.cabinet','masterWorkplace.get','stoWorkplace.get'].forEach(k=>api.invalidate(k));showCreatedState(order,r.payload||{},mediaResult);
    };

    root.addEventListener('click',click);root.addEventListener('input',input);root.addEventListener('change',change);root.addEventListener('submit',submit);picker?.addEventListener('cancel',e=>{e.preventDefault();closePicker();});
    loadVehicles();loadServices();renderSelected();renderMedia();syncConditionCards();syncVehicleStage();setStep(Math.min(4,Number(draft.step||0)));
    try{sessionStorage.removeItem('kareta.request.prefill');sessionStorage.removeItem(LEGACY_SERVICE_DRAFT_KEY);}catch(_e){}
    context.lifecycle?.addCleanup?.(()=>{closePicker();if(rulesDialog?.open)rulesDialog.close();document.body.classList.remove('k-request-ref-active');mediaUrls.splice(0).forEach(url=>URL.revokeObjectURL(url));root.removeEventListener('click',click);root.removeEventListener('input',input);root.removeEventListener('change',change);root.removeEventListener('submit',submit);});
  }

  window.KaretaRequestPages=Object.freeze({renderRequest,renderRequestWindow,mountRequest});
})();
