(() => {
  'use strict';
  const STO_WORKSPACE_R82_CONTRACT='R188.5.5.6.82';
  const ui=window.KaretaPageUI, apiModule=window.KaretaStoWorkplaceApi;
  if(!ui||!apiModule) throw new Error('Sto workplace dependencies are required');
  const esc=ui.escHtml;
  const icon=name=>window.KaretaUIIcons?.svg?.(name)||'';
  const money=value=>new Intl.NumberFormat('ru-RU').format(Number(value||0))+' ₸';
  const statusLabel=s=>({new:'Новая',accepted:'Принята',assigned:'Назначена',process:'В работе',in_progress:'В работе',work:'В работе',waiting_parts:'Ждёт запчасти',waiting_approval:'Согласование',pending:'Ожидает',completed:'Завершена',done:'Завершена',delivered:'Выдана',closed:'Закрыта',cancelled:'Отменена'}[String(s||'').toLowerCase()]||'Заявка');
  const done=s=>['completed','done','delivered','closed','cancelled'].includes(String(s||'').toLowerCase());
  const fmtDateTime=value=>{if(!value)return '—';try{return new Date(String(value).replace(' ','T')).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}catch(_e){return String(value);}};
  const fmtTime=value=>{if(!value)return '—';try{return new Date(String(value).replace(' ','T')).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});}catch(_e){return String(value).slice(11,16)||String(value);}};
  const pct=value=>Math.max(0,Math.min(160,Number(value||0)));
  const loadBar=value=>`<span class="k-sto-r73-load"><i style="width:${Math.min(100,pct(value))}%"></i></span>`;
  const recoveryLabel=item=>({safe:'Можно перенести',protected:'Защищено',unresolved:'Нет свободного окна',tariff_blocked:'Лимит тарифа',bay_blocked:'Нет свободного бокса',race_conflict:'Конфликт изменился'})[String(item?.status||'')]||String(item?.status||'Конфликт');
  const rangeDays=range=>({day:1,week:7,month:31}[range]||1);
  const rangeLabel=range=>({day:'День',week:'Неделя',month:'Месяц'}[range]||'День');
  const isoDate=value=>String(value||'').slice(0,10);
  const todayYmd=()=>{const d=new Date(),pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;};
  const dateLabel=value=>{if(!value)return '—';try{return new Date(String(value).slice(0,10)+'T00:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'short'});}catch(_e){return String(value).slice(0,10);}};
  const timelineStyle=(item,days)=>{try{const base=new Date();base.setHours(0,0,0,0);const start=new Date(String(item.plannedStart||'').replace(' ','T')),end=new Date(String(item.plannedEnd||'').replace(' ','T'));const total=days*86400000,left=((start-base)/total)*100,width=Math.max(days===1?1.8:.45,((end-start)/total)*100);return `--left:${Math.max(0,left).toFixed(4)}%;--width:${Math.min(100,width).toFixed(4)}%`; }catch(_e){return '--left:0%;--width:1%';}};

  function renderStoWorkplace(){return `<section class="k-page k-sto-workplace-page"><div id="k-sto-workplace"><section class="k-empty"><h2>Загружаем кабинет СТО</h2><p>Собираем мастеров, заказы, боксы и конфликты графика.</p></section></div></section>`;}

  function orderRow(o,opts={}){
    const compact=!!opts.compact, canAssignMaster=opts.canAssignMaster!==false&&!done(o.status), canAssignBay=!!opts.canAssignBay;
    return `<article class="k-sto-r73-order-row ${compact?'is-compact':''}" data-sto-order="${esc(o.id||'')}">
      <div class="k-sto-r73-order-status"><span>${esc(statusLabel(o.status))}</span>${o.overdue?'<b>Просрочено</b>':''}</div>
      <div class="k-sto-r73-order-main"><h3>${esc(o.vehicleTitle||'Автомобиль')}</h3><p>${esc(o.serviceNames||'Работы по заявке')}</p><small>${esc(o.clientName||'Клиент')}${o.masterName?` · ${esc(o.masterName)}`:''}${o.date?` · ${esc(o.date)} ${esc(o.time||'')}`:''}</small></div>
      <div class="k-sto-r73-order-meta">${Number(o.total||0)>0?`<strong>${money(o.total)}</strong>`:''}${o.assignment?.bayId?`<span>${icon('warehouse')}<em>На посту</em></span>`:''}</div>
      <div class="k-sto-r73-order-actions"><a class="k-button k-button-secondary" href="#/orders/item/${encodeURIComponent(o.id)}">${icon('orders')}<span>Заказ</span></a>${canAssignMaster?`<button class="k-button k-button-secondary" type="button" data-sto-master-open="${esc(o.id)}">${icon('masters')}<span>${o.masterId?'Сменить мастера':'Назначить мастера'}</span></button>`:''}${!done(o.status)?`<button class="k-button k-button-secondary" type="button" data-sto-alternative-open="${esc(o.id)}">${icon('refresh')}<span>Альтернатива</span></button>`:''}${canAssignBay?`<button class="k-button k-button-secondary" type="button" data-sto-bay-open="${esc(o.id)}">${icon('warehouse')}<span>На пост</span></button>`:''}${o.assignment?`<button class="k-button k-button-ghost" type="button" data-sto-release="${esc(o.id)}">${icon('unlock')}<span>Освободить</span></button>`:''}</div>
    </article>`;
  }

  function bayRow(b,queue){
    const items=Array.isArray(b.orders)?b.orders:[];
    return `<section class="k-sto-r73-bay-row ${items.length?'is-occupied':'is-free'}" data-sto-bay="${esc(b.id||'')}">
      <header><div><span>${icon('warehouse')}</span><div><small>${esc(b.code||'ПОСТ')}</small><h3>${esc(b.name||'Пост')}</h3></div></div><b>${items.length?'Занят':'Свободен'}</b></header>
      <div class="k-sto-r73-bay-orders">${items.length?items.map(o=>orderRow(o,{compact:true,canAssignBay:false})).join(''):`<div class="k-sto-r73-empty-line"><span>${icon('check')}</span><p>Пост свободен.</p></div>${queue.length?`<div class="k-sto-r73-inline-queue"><small>Ближайшие из очереди</small>${queue.slice(0,3).map(o=>`<button type="button" data-sto-bay-direct="${esc(b.id||'')}" data-order-id="${esc(o.id||'')}"><span><b>${esc(o.vehicleTitle||'Автомобиль')}</b><small>${esc(o.serviceNames||'Работы')}</small></span>${icon('chevronRight')}</button>`).join('')}</div>`:''}`}</div>
    </section>`;
  }

  function masterRow(m,dispatchByMaster){
    const d=dispatchByMaster.get(String(m.id))||{};
    return `<article class="k-sto-r73-master-row"><a class="k-sto-r73-master-main" href="#/masters/profile/master/${encodeURIComponent(m.id)}"><span class="k-sto-r73-avatar">${esc(String(m.name||'М').split(/\s+/).map(x=>x[0]||'').slice(0,2).join('').toUpperCase())}</span><span><b>${esc(m.name||'Мастер')}</b><small>${esc(m.spec||'Специализация не указана')}</small></span></a><div class="k-sto-r73-master-load"><span><b>${Math.round(Number(d.loadPct||0))}%</b><small>загрузка</small></span>${loadBar(d.loadPct)}</div><div class="k-sto-r73-master-kpis"><span><b>${Number(m.todayOrders||0)}</b><small>сегодня</small></span><span><b>${Number(m.activeOrders||0)}</b><small>в работе</small></span><span><b>${Number(m.kpi||0)}%</b><small>KPI</small></span></div><a class="k-button k-button-secondary" href="#/masters/profile/master/${encodeURIComponent(m.id)}">${icon('user')}<span>Профиль</span></a></article>`;
  }

  function jointSchedule(d){
    const items=Array.isArray(d.jointSchedule)?d.jointSchedule:[];
    return `<section class="k-sto-section k-sto-r73-joint"><div class="k-section-head"><div><h2>Совместный график</h2><p>Мастер и бокс рассматриваются как две обязательные мощности одной записи.</p></div><div class="k-sto-r73-view-toggle"><button type="button" data-sto-schedule-range="day" class="is-active">Сегодня</button><button type="button" data-sto-schedule-range="week">7 дней</button></div></div><div class="k-sto-r73-joint-list" data-sto-joint-list>${items.length?items.map(item=>`<a href="#/orders/item/${encodeURIComponent(item.orderId||'')}" data-sto-joint-item data-start="${esc(item.plannedStart||'')}"><time><b>${esc(fmtTime(item.plannedStart))}</b><small>${esc(String(item.plannedStart||'').slice(0,10))}</small></time><span class="k-sto-r73-joint-subject"><b>${esc(item.vehicleTitle||'Автомобиль')}</b><small>${esc(item.serviceNames||'Работы')}</small></span><span>${icon('masters')}<b>${esc(item.masterName||'Мастер')}</b></span><span>${icon('warehouse')}<b>${esc(item.bayName||'Бокс')}</b></span><em>${esc(statusLabel(item.orderStatus))}</em></a>`).join(''):`<div class="k-sto-r73-empty-line"><span>${icon('calendar')}</span><p>На ближайшие дни совместных назначений нет.</p></div>`}</div></section>`;
  }

  function capacityBoard(d){
    const x=d.dispatch||{}, masters=Array.isArray(x.masters)?x.masters:[], bays=Array.isArray(x.bays)?x.bays:[], m=x.metrics||{};
    return `<section class="k-sto-section k-sto-r73-capacity"><div class="k-section-head"><div><h2>Диспетчеризация производства</h2><p>Загрузка смены, мощность постов, ETA, SLA и автоматическое перераспределение ещё не начатых работ.</p></div><button class="k-button k-button-primary" type="button" data-sto-rebalance>${icon('refresh')}<span>Перераспределить</span></button></div><div class="k-sto-r73-capacity-summary"><span><b>${Number(m.capacityMinutes||0)}</b><small>мин мощности</small></span><span><b>${Number(m.bookedMinutes||0)}</b><small>мин занято</small></span><span><b>${Number(m.loadPct||0)}%</b><small>общая загрузка</small></span><span><b>${Number(m.overloadedMasters||0)}</b><small>перегружено мастеров</small></span><span><b>${Number(m.slaBreaches||0)}</b><small>SLA нарушено</small></span></div><div class="k-sto-r73-capacity-grid"><div><h3>${icon('masters')} Мастера</h3>${masters.length?masters.map(row=>`<div class="k-sto-r73-capacity-row ${row.overloaded?'is-overloaded':''}"><span><b>${esc(row.name||'Мастер')}</b><small>${esc(row.spec||'')}</small></span><span>${loadBar(row.loadPct)}<small>${Math.round(Number(row.loadPct||0))}% · ETA ${esc(fmtDateTime(row.etaStart))}</small></span></div>`).join(''):'<p>Нет мастеров.</p>'}</div><div><h3>${icon('warehouse')} Боксы</h3>${bays.length?bays.map(row=>`<div class="k-sto-r73-capacity-row ${Number(row.loadPct||0)>100?'is-overloaded':''}"><span><b>${esc(row.name||'Бокс')}</b><small>${esc(row.bay_type||'general')}</small></span><span>${loadBar(row.loadPct)}<small>${Number(row.booked_minutes||0)} / ${Number(row.daily_capacity_min||0)} мин · ${Math.round(Number(row.loadPct||0))}%</small></span></div>`).join(''):'<p>Боксы не настроены.</p>'}</div></div></section>`;
  }

  function scheduleCommand(d){
    const c=d.scheduleCommand||{},prefs=d.schedulePreferences||c.preferences||{},range=prefs.defaultRange||'day',days=rangeDays(range),masterLanes=Array.isArray(c.masterLanes)?c.masterLanes:[],bayLanes=Array.isArray(c.bayLanes)?c.bayLanes:[],daily=(Array.isArray(c.days)?c.days:[]).slice(0,days),incidents=Array.isArray(c.incidents)?c.incidents:[];
    const visibleMaster=prefs.showMasterLanes!==false,visibleBay=prefs.showBayLanes!==false,summary=prefs.showCapacitySummary!==false,compact=!!prefs.compactDensity;
    const lane=(row,type)=>{const items=(Array.isArray(row.items)?row.items:[]).filter(x=>{const date=isoDate(x.plannedStart),today=todayYmd();if(!date)return false;if(range==='day')return date===today;const max=new Date(today+'T00:00:00');max.setDate(max.getDate()+days);return new Date(date+'T00:00:00')<max;});return `<div class="k-sto-r74-lane ${compact?'is-compact':''}" data-lane-type="${type}" data-lane-id="${esc(row.id||'')}"><header><span>${icon(type==='master'?'masters':'warehouse')}</span><div><b>${esc(row.name||'')}</b><small>${esc(row.subtitle||'')}</small></div><em>${Math.round(Number(row.loadPct||0))}%</em><button type="button" data-sto-incident-open="${esc(row.id||'')}" data-lane-type="${type}" title="Недоступность">${icon('lock')}</button></header><div class="k-sto-r74-track">${items.map(item=>`<a href="#/orders/item/${encodeURIComponent(item.orderId||'')}" class="k-sto-r74-slot" style="${timelineStyle(item,days)}" title="${esc((item.vehicleTitle||'Автомобиль')+' · '+fmtDateTime(item.plannedStart))}"><b>${esc(item.vehicleTitle||'Автомобиль')}</b><small>${range==='day'?esc(fmtTime(item.plannedStart)):esc(dateLabel(item.plannedStart))}</small></a>`).join('')||'<span class="k-sto-r74-track-empty">свободно</span>'}</div></div>`;};
    return `<section class="k-sto-r74-command k-sto-r82-command-surface" data-sto-command data-range="${esc(range)}"><div class="k-section-head"><div><h2>График и мощность СТО</h2><p>Мастера, боксы и ограничения на одной временной шкале.</p></div><div class="k-sto-r74-toolbar"><div class="k-sto-r73-view-toggle"><button type="button" data-sto-command-range="day" class="${range==='day'?'is-active':''}">День</button><button type="button" data-sto-command-range="week" class="${range==='week'?'is-active':''}">Неделя</button><button type="button" data-sto-command-range="month" class="${range==='month'?'is-active':''}">Месяц</button></div><button class="k-button k-button-secondary" type="button" data-sto-window-open="capacity">${icon('settings')}<span>Параметры</span></button></div></div>${summary?`<div class="k-sto-r74-day-summary">${daily.map(row=>{const masterPct=Number(row.masterCapacityMinutes||0)>0?Math.round(Number(row.masterBookedMinutes||0)*100/Number(row.masterCapacityMinutes||1)):0,bayPct=Number(row.bayCapacityMinutes||0)>0?Math.round(Number(row.bayBookedMinutes||0)*100/Number(row.bayCapacityMinutes||1)):0;return `<span class="${Number(row.conflicts||0)>0?'has-conflict':''}"><b>${esc(dateLabel(row.date))}</b><small>М ${masterPct}% · Б ${bayPct}% · ${Number(row.orders||0)} авто${Number(row.conflicts||0)?` · ${Number(row.conflicts)} конфликт`:''}</small></span>`;}).join('')}</div>`:''}${incidents.length?`<div class="k-sto-r74-incidents"><b>Активные ограничения</b>${incidents.map(i=>`<span>${icon(i.laneType==='master'?'masters':'warehouse')}<em>${esc(i.reason||'Ограничение')}</em><small>${esc(fmtDateTime(i.startsAt))} — ${esc(fmtDateTime(i.endsAt))}</small><button type="button" data-sto-incident-resolve="${esc(i.id||'')}">${icon('close')}<span>Снять</span></button></span>`).join('')}</div>`:''}<div class="k-sto-r74-lanes">${visibleMaster?`<div class="k-sto-r74-lane-group"><h3>${icon('masters')} Мастера</h3>${masterLanes.map(x=>lane(x,'master')).join('')||'<p>Мастера не привязаны.</p>'}</div>`:''}${visibleBay?`<div class="k-sto-r74-lane-group"><h3>${icon('warehouse')} Боксы</h3>${bayLanes.map(x=>lane(x,'bay')).join('')||'<p>Боксы не настроены.</p>'}</div>`:''}</div><footer><span>${icon('calendar')}<b>${rangeLabel(range)}</b><small>Изменение мощности всегда проходит preview.</small></span><button class="k-button k-button-primary" type="button" data-sto-rebalance>${icon('refresh')}<span>Перераспределить очередь</span></button></footer></section>`;
  }

  function recoveryControl(d){
    const r=d.recoveryControl||{}, items=Array.isArray(r.items)?r.items:[], s=r.summary||{}, notices=Array.isArray(d.recoveryNotifications)?d.recoveryNotifications:[];
    return `<section class="k-sto-section k-sto-r73-recovery k-sto-r72-recovery" data-sto-recovery><div class="k-section-head"><div><h2>Конфликты и автопереносы</h2><p>Preview не меняет записи. Перед применением сервер повторно проверяет Мастера, тариф и бокс СТО.</p></div><button class="k-button k-button-secondary" type="button" data-sto-recovery-preview>${icon('refresh')}<span>Обновить preview</span></button></div><div class="k-sto-r73-recovery-summary"><span><b>${Number(s.conflicts||0)}</b> конфликтов</span><span><b>${Number(s.safe||0)}</b> безопасно</span><span><b>${Number(s.protected||0)}</b> защищено</span><span><b>${Number(s.blocked||0)}</b> заблокировано</span></div><div class="k-sto-r73-recovery-list">${items.length?items.map(item=>`<article class="k-sto-r73-recovery-row ${item.safe?'is-safe':''} ${item.protected?'is-protected':''}"><label><input type="checkbox" data-sto-recovery-select value="${esc(item.orderId||'')}" ${item.safe?'checked':'disabled'}><span></span></label><div><a href="#/orders/item/${encodeURIComponent(item.orderId||'')}"><b>${esc(item.masterName||'Мастер')} · ${esc(item.vehicleTitle||'Автомобиль')}</b></a><small>${esc((item.reasonLabels||[]).join(' · ')||recoveryLabel(item))}</small><p><span><b>Сейчас</b>${esc(fmtDateTime(item.oldStart))}</span>${icon('chevronRight')}<span><b>${item.safe?'Новое окно':'Статус'}</b>${item.safe?esc(fmtDateTime(item.candidateStart)):esc(recoveryLabel(item))}</span></p>${item.bay?.required?`<em>${icon('warehouse')}${item.bay.available?esc(item.bay.bayName||'Бокс найден'):'Свободного бокса нет'}</em>`:''}</div><button type="button" data-sto-recovery-protect="${esc(item.orderId||'')}" data-protected="${item.protected?'1':'0'}">${icon(item.protected?'unlock':'lock')}<span>${item.protected?'Снять защиту':'Защитить'}</span></button></article>`).join(''):`<div class="k-sto-r73-empty-line"><span>${icon('check')}</span><p>Конфликтов нет.</p></div>`}</div><footer><label><input type="checkbox" data-sto-recovery-notify checked> Уведомить клиентов</label><div><button class="k-button k-button-secondary" type="button" data-sto-recovery-apply-selected ${Number(s.safe||0)?'':'disabled'}>Применить выбранные</button><button class="k-button k-button-primary" type="button" data-sto-recovery-apply-all ${Number(s.safe||0)?'':'disabled'}>Применить все безопасные</button></div></footer><details><summary>История уведомлений <b>${notices.length}</b></summary><div class="k-sto-r73-notice-list">${notices.length?notices.slice(0,16).map(n=>`<article><span><b>${esc(n.masterName||'Мастер')} · ${esc(n.vehicleTitle||'Автомобиль')}</b><small>${esc(n.body||'')}</small><em>${esc(fmtDateTime(n.createdAt))} · ${n.isRead?'прочитано':'не прочитано'}</em></span><button type="button" data-sto-recovery-resend="${esc(n.orderId||'')}">${icon('bell')}<span>Повторить</span></button></article>`).join(''):'<p>Уведомлений пока нет.</p>'}</div></details></section>`;
  }

  function stoOperationRows(d){
    const map=new Map(),recovery=Array.isArray(d.recoveryControl?.items)?d.recoveryControl.items:[];
    const merge=(order,kind,extra={})=>{const id=String(order?.id||order?.orderId||'');if(!id)return;let row=map.get(id);if(!row){row={id,kinds:new Set(),order:{...order},extra:{}};map.set(id,row);}row.kinds.add(kind);row.order={...row.order,...order};row.extra={...row.extra,...extra};};
    recovery.forEach(item=>merge({id:item.orderId,vehicleTitle:item.vehicleTitle,masterName:item.masterName,status:'conflict'},'conflict',{recovery:item}));
    (Array.isArray(d.bays)?d.bays:[]).forEach(b=>(Array.isArray(b.orders)?b.orders:[]).forEach(o=>merge(o,'bay',{bayId:b.id,bayName:b.name||b.code||'Пост',plannedEnd:o.assignment?.plannedEnd||''})));
    (Array.isArray(d.queue)?d.queue:[]).forEach(o=>merge(o,'queue',{}));
    (Array.isArray(d.recentOrders)?d.recentOrders:[]).forEach(o=>{if(!done(o.status)&&String(o.status||'').toLowerCase()==='new')merge(o,'new',{});});
    const rank=row=>row.kinds.has('conflict')?0:row.kinds.has('bay')?1:row.kinds.has('queue')?2:3;
    return [...map.values()].sort((a,b)=>rank(a)-rank(b)||String(a.order.date||a.order.createdAt||'').localeCompare(String(b.order.date||b.order.createdAt||'')));
  }

  function stoOperationRow(row){
    const o=row.order||{},kinds=[...row.kinds],r=row.extra?.recovery||null,onBay=row.kinds.has('bay'),inQueue=row.kinds.has('queue'),isConflict=row.kinds.has('conflict'),isNew=row.kinds.has('new');
    const label=isConflict?'КОНФЛИКТ':onBay?'НА ПОСТУ':isNew?'НОВЫЙ ЗАКАЗ':'ОЧЕРЕДЬ';
    const time=isConflict?fmtDateTime(r?.oldStart):(o.time?`${esc(o.date||'')} ${esc(o.time||'')}`:esc(o.date||o.createdAt||'Без времени'));
    const secondary=[];if(o.masterName)secondary.push(o.masterName);if(row.extra?.bayName)secondary.push(row.extra.bayName);if(onBay&&row.extra?.plannedEnd)secondary.push(`освободится ${fmtTime(row.extra.plannedEnd)}`);if(isConflict&&r?.candidateStart)secondary.push(`вариант ${fmtDateTime(r.candidateStart)}`);
    return `<article class="k-sto-r82-operation ${isConflict?'is-conflict':''} ${onBay?'is-bay':''}" data-sto-operation data-kinds="${esc(kinds.join(' '))}" data-order-id="${esc(row.id)}"><div class="k-sto-r82-operation__state"><small>${label}</small><b>${esc(statusLabel(o.status))}</b><span>${time}</span></div><a class="k-sto-r82-operation__main" href="#/orders/item/${encodeURIComponent(row.id)}"><h3>${esc(o.vehicleTitle||'Автомобиль')}</h3><p>${esc(o.serviceNames||r?.reasonLabels?.join(' · ')||'Работы по заказу')}</p><small>${esc(o.clientName||'Клиент')}${secondary.length?` · ${esc(secondary.join(' · '))}`:''}</small></a><div class="k-sto-r82-operation__actions"><a class="k-button k-button-secondary" href="#/orders/item/${encodeURIComponent(row.id)}">${icon('orders')}<span>Заказ</span></a>${!done(o.status)?`<button class="k-button k-button-secondary" type="button" data-sto-master-open="${esc(row.id)}">${icon('masters')}<span>${o.masterId?'Мастер':'Назначить'}</span></button>`:''}${!done(o.status)?`<button class="k-button k-button-secondary" type="button" data-sto-alternative-open="${esc(row.id)}">${icon('refresh')}<span>Мастер + бокс</span></button>`:''}${inQueue&&!done(o.status)?`<button class="k-button k-button-secondary" type="button" data-sto-bay-open="${esc(row.id)}">${icon('warehouse')}<span>На пост</span></button>`:''}${onBay?`<button class="k-button k-button-ghost" type="button" data-sto-release="${esc(row.id)}">${icon('unlock')}<span>Освободить</span></button>`:''}${isConflict?`<button class="k-button k-button-ghost" type="button" data-sto-window-open="recovery">${icon('warning')}<span>Конфликт</span></button>`:''}</div></article>`;
  }

  function operationsFeed(d){
    const rows=stoOperationRows(d),counts={all:rows.length,queue:rows.filter(x=>x.kinds.has('queue')).length,bay:rows.filter(x=>x.kinds.has('bay')).length,new:rows.filter(x=>x.kinds.has('new')).length,conflict:rows.filter(x=>x.kinds.has('conflict')).length};
    return `<section class="k-sto-r82-operations" data-sto-operations><header><div><small>ДИСПЕТЧЕРСКАЯ</small><h2>Оперативная лента</h2><p>Очередь, машины на постах, новые заказы и конфликты в одном потоке.</p></div><div><a href="#/orders">Все заказы</a><a href="#/workflow">Производство</a></div></header><nav class="k-sto-r82-filter" aria-label="Фильтр оперативной ленты">${[['all','Все'],['new','Новые'],['queue','Очередь'],['bay','На постах'],['conflict','Конфликты']].map(([key,title])=>`<button type="button" data-sto-ops-filter="${key}" class="${key==='all'?'is-active':''}">${title}<em>${counts[key]}</em></button>`).join('')}</nav><div class="k-sto-r82-operation-list">${rows.length?rows.map(stoOperationRow).join(''):`<div class="k-sto-r82-empty">${icon('check')}<div><b>Оперативных задач нет</b><span>Очередь пуста, конфликты отсутствуют.</span></div></div>`}</div></section>`;
  }

  function workspaceSettings(d){
    const prefs=d.schedulePreferences||{};const toggle=(key,title,text)=>`<button type="button" class="k-sto-r82-toggle ${prefs[key]!==false?'is-active':''}" data-sto-r82-pref="${key}" aria-pressed="${prefs[key]!==false?'true':'false'}"><span>${icon(prefs[key]!==false?'check':'close')}</span><b>${title}</b><small>${text}</small></button>`;
    return `<section class="k-sto-r82-settings"><h3>Вид диспетчерской</h3><div class="k-sto-r82-toggle-grid">${toggle('showMasterLanes','Дорожки Мастеров','Показывать рабочие линии Мастеров в графике.')}${toggle('showBayLanes','Дорожки боксов','Показывать занятость постов и подъёмников.')}${toggle('showCapacitySummary','Сводка мощности','Показывать дневные проценты загрузки.')}${toggle('compactDensity','Компактный график','Уменьшить высоту дорожек для плотного диспетчерского режима.')}</div><h3>Период по умолчанию</h3><div class="k-sto-r82-range-choice">${[['day','День'],['week','Неделя'],['month','Месяц']].map(([key,title])=>`<button type="button" data-sto-r82-default-range="${key}" class="${String(prefs.defaultRange||'day')===key?'is-active':''}">${title}</button>`).join('')}</div><div class="k-sto-r82-settings-note">${icon('info')}<p>Изменение графика, мощности и Recovery сохраняют серверные guards R72–R74: scope СТО, тариф Мастера и занятость бокса.</p></div></section>`;
  }

  function stoLocationSettings(d){
    const sto=d.sto||{},point=sto.geoPoint||{},lat=point.latitude??'',lng=point.longitude??'',source=point.source||'manual';
    return `<section class="k-sto-r82-settings" data-sto-geo-settings><h3>Публичная точка СТО</h3><p>Клиенты и мастера будут видеть эту точку в поиске рядом. Адрес и координаты сохраняются вместе.</p><label><span>Город</span><input type="text" maxlength="120" value="${esc(sto.city||'')}" data-sto-geo-city></label><label><span>Адрес</span><input type="text" maxlength="255" value="${esc(sto.address||'')}" data-sto-geo-address></label><input type="hidden" value="${esc(lat)}" data-sto-geo-lat><input type="hidden" value="${esc(lng)}" data-sto-geo-lng><input type="hidden" value="${esc(source)}" data-sto-geo-source><div class="k-sto-r82-settings-note"><span>${icon('location')}</span><p data-sto-geo-status>${lat!==''&&lng!==''?`Точка: ${Number(lat).toFixed(5)}, ${Number(lng).toFixed(5)}`:'Точка ещё не определена.'}</p></div><div><button class="k-button k-button-secondary" type="button" data-sto-geo-detect>${icon('location')}<span>Определить точку</span></button> <button class="k-button k-button-primary" type="button" data-sto-geo-save>${icon('check')}<span>Сохранить точку</span></button></div></section>`;
  }

  function workspaceDialogs(d){
    const shell=(type,kicker,title,body)=>`<dialog class="k-sto-r82-window" data-sto-workspace-window="${type}" data-r82-contract="${STO_WORKSPACE_R82_CONTRACT}"><div class="k-sto-r82-window__shell"><header><div><small>${kicker}</small><h2>${title}</h2></div><button type="button" data-sto-window-close aria-label="Закрыть">${icon('close')}</button></header><div class="k-sto-r82-window__body">${body}</div><footer><button class="k-button k-button-secondary" type="button" data-sto-window-close>Закрыть</button></footer></div></dialog>`;
    return `${shell('schedule','ДИСПЕТЧЕРСКИЙ ГРАФИК','График и мощность СТО',scheduleCommand(d))}${shell('recovery','AUTO RECOVERY','Конфликты и автопереносы',recoveryControl(d))}${shell('capacity','НАСТРОЙКИ СТО','Мощность и вид диспетчерской',`${capacityBoard(d)}${workspaceSettings(d)}`)}${shell('location','ГЕО СТО','Адрес и точка на карте',stoLocationSettings(d))}`;
  }

  function dialogs(){return `<dialog class="k-sto-r73-picker" data-sto-master-dialog><form method="dialog"><header><div><small>НАЗНАЧЕНИЕ СТО</small><h2>Выберите Мастера</h2></div><button value="cancel" aria-label="Закрыть">${icon('close')}</button></header><label class="k-sto-r73-search">${icon('search')}<input type="search" placeholder="Имя или специализация" data-sto-master-search></label><div data-sto-master-candidates><div class="k-sto-r73-picker-loading">Загружаем доступность…</div></div></form></dialog><dialog class="k-sto-r73-picker" data-sto-bay-dialog><form method="dialog"><header><div><small>РЕМЗОНА</small><h2>Выберите пост</h2></div><button value="cancel" aria-label="Закрыть">${icon('close')}</button></header><div data-sto-bay-candidates><div class="k-sto-r73-picker-loading">Проверяем боксы…</div></div></form></dialog><dialog class="k-sto-r73-picker" data-sto-alternative-dialog><form method="dialog"><header><div><small>АЛЬТЕРНАТИВНАЯ МОЩНОСТЬ</small><h2>Мастер + бокс</h2></div><button value="cancel" aria-label="Закрыть">${icon('close')}</button></header><div data-sto-alternative-pairs><div class="k-sto-r73-picker-loading">Ищем свободную пару…</div></div></form></dialog><dialog class="k-sto-r73-picker k-sto-r74-incident-dialog" data-sto-incident-dialog><form method="dialog"><header><div><small>ИЗМЕНЕНИЕ МОЩНОСТИ</small><h2>Недоступность дорожки</h2></div><button value="cancel" aria-label="Закрыть">${icon('close')}</button></header><div class="k-sto-r74-incident-form"><input type="hidden" data-sto-incident-lane-type><input type="hidden" data-sto-incident-lane-id><label>Начало<input type="datetime-local" data-sto-incident-start required></label><label>Окончание<input type="datetime-local" data-sto-incident-end required></label><label class="is-wide">Причина<input type="text" maxlength="191" value="Аварийный простой / изменение графика" data-sto-incident-reason></label><label><input type="checkbox" data-sto-incident-auto checked> Автоперенос безопасных</label><label><input type="checkbox" data-sto-incident-notify checked> Уведомить клиентов</label><div class="is-wide" data-sto-incident-preview><p>Сначала выполните preview.</p></div></div><footer><button class="k-button k-button-secondary" type="button" data-sto-incident-preview>${icon('search')}<span>Preview</span></button><button class="k-button k-button-primary" type="button" data-sto-incident-apply disabled>${icon('check')}<span>Применить</span></button></footer></form></dialog>`;}

  function renderData(d){
    const m=d.metrics||{},rs=d.recoveryControl?.summary||{},sto=d.sto||{},occupied=Number(m.occupied||0),bays=Number(m.bays||0),queue=Number(m.queue||0),active=Number(m.activeOrders||0),today=Number(m.todayOrders||0),conflicts=Number(rs.conflicts||0);
    return `<div class="k-sto-r82-workspace" data-r82-contract="${STO_WORKSPACE_R82_CONTRACT}"><header class="k-sto-r82-header"><div><small>СТО · ДИСПЕТЧЕРСКАЯ</small><h1>${esc(sto.name||'Моё СТО')}</h1><p>${esc([sto.city,sto.address,sto.workHours].filter(Boolean).join(' · ')||'Оперативное управление заказами и производственной мощностью.')}</p></div><div><a class="k-button k-button-primary" href="#/orders/new">${icon('plus')}<span>Создать заказ</span></a><button class="k-button k-button-secondary" type="button" data-sto-reload>${icon('refresh')}<span>Обновить</span></button></div></header><div class="k-sto-r82-kpis"><span><b>${today}</b><small>заказов сегодня</small></span><span><b>${active}</b><small>в работе</small></span><span><b>${queue}</b><small>в очереди</small></span><span><b>${occupied}/${bays}</b><small>постов занято</small></span><span class="${conflicts?'has-alert':''}"><b>${conflicts}</b><small>конфликтов</small></span></div><nav class="k-sto-r82-commandbar" aria-label="Команды СТО"><button type="button" data-sto-window-open="schedule">${icon('calendar')}<span>График</span></button><button type="button" data-sto-window-open="recovery" class="${conflicts?'has-alert':''}">${icon('warning')}<span>Recovery</span>${conflicts?`<em>${conflicts}</em>`:''}</button><button type="button" data-sto-window-open="capacity">${icon('settings')}<span>Мощность</span></button><button type="button" data-sto-window-open="location">${icon('location')}<span>Точка СТО</span></button><a href="#/orders">${icon('orders')}<span>Заказы</span></a><a href="#/masters">${icon('masters')}<span>Мастера</span></a><a href="#/workflow">${icon('work')}<span>Производство</span></a><a href="#/finance">${icon('finance')}<span>Финансы</span></a><a href="#/crm">${icon('crm')}<span>CRM</span></a><a href="#/chats">${icon('chats')}<span>Чаты</span></a></nav>${operationsFeed(d)}${workspaceDialogs(d)}${dialogs()}</div>`;
  }

  function renderMasterCandidates(dialog,data){
    const target=dialog.querySelector('[data-sto-master-candidates]'),items=Array.isArray(data.items)?data.items:[];dialog.dataset.orderId=data.orderId||'';
    target.innerHTML=items.length?items.map(m=>`<button type="button" class="k-sto-r73-candidate ${m.assignable?'':'is-blocked'}" data-sto-master-assign="${esc(m.id||'')}" ${m.assignable?'':'disabled'} data-search="${esc((m.name+' '+m.spec).toLowerCase())}"><span class="k-sto-r73-candidate-main"><b>${esc(m.name||'Мастер')}</b><small>${esc(m.spec||'')} · совпадение ${Number(m.serviceMatch||0)}%</small><em>${esc(m.reason||'')}</em></span><span class="k-sto-r73-candidate-load"><b>${Math.round(Number(m.loadPct||0))}%</b>${loadBar(m.loadPct)}<small>ETA ${esc(fmtDateTime(m.etaStart))}</small></span><span class="k-sto-r73-candidate-score"><b>${Math.round(Number(m.score||0))}</b><small>рейтинг назначения</small></span>${icon('chevronRight')}</button>`).join(''):'<div class="k-sto-r73-empty-line"><p>Нет доступных Мастеров.</p></div>';
  }

  function renderBayCandidates(dialog,data){
    const target=dialog.querySelector('[data-sto-bay-candidates]'),items=Array.isArray(data.items)?data.items:[];dialog.dataset.orderId=data.orderId||'';
    target.innerHTML=`<div class="k-sto-r73-picker-window"><span>${icon('calendar')}<b>${esc(fmtDateTime(data.plannedStart))} — ${esc(fmtTime(data.plannedEnd))}</b></span></div>${items.length?items.map(b=>`<button type="button" class="k-sto-r73-candidate ${b.available?'':'is-blocked'}" data-sto-bay-pick="${esc(b.id||'')}" ${b.available?'':'disabled'}><span class="k-sto-r73-candidate-main"><b>${esc(b.name||'Бокс')}</b><small>${esc(b.code||'')}</small><em>${esc(b.reason||'')}</em></span><span class="k-sto-r73-candidate-load"><b>${Math.round(Number(b.loadPct||0))}%</b>${loadBar(b.loadPct)}<small>${Number(b.bookedMinutes||0)} / ${Number(b.capacityMinutes||0)} мин</small></span>${b.current?'<strong>Текущий</strong>':''}${icon('chevronRight')}</button>`).join(''):'<div class="k-sto-r73-empty-line"><p>Боксы не настроены.</p></div>'}`;
  }

  function renderAlternativePairs(dialog,data){
    const target=dialog.querySelector('[data-sto-alternative-pairs]'),pairs=Array.isArray(data.pairs)?data.pairs:[];dialog.dataset.orderId=data.orderId||'';
    target.innerHTML=`<div class="k-sto-r73-picker-window"><span>${icon('calendar')}<b>${esc(fmtDateTime(data.plannedStart))} — ${esc(fmtTime(data.plannedEnd))}</b></span></div>${pairs.length?pairs.map(p=>`<button type="button" class="k-sto-r74-pair" data-sto-pair-master="${esc(p.masterId||'')}" data-sto-pair-bay="${esc(p.bayId||'')}"><span>${icon('masters')}<b>${esc(p.masterName||'Мастер')}</b><small>${esc(p.masterSpec||'')} · услуги ${Number(p.serviceMatch||0)}% · загрузка ${Math.round(Number(p.masterLoadPct||0))}%</small></span><span>${icon('warehouse')}<b>${esc(p.bayName||'Бокс')}</b><small>${esc(p.bayCode||'')}</small></span><em>${Math.round(Number(p.score||0))}</em>${icon('chevronRight')}</button>`).join(''):'<div class="k-sto-r73-empty-line"><p>Для текущего времени свободной пары Мастер + бокс нет.</p></div>'}`;
  }

  function renderIncidentPreview(dialog,preview){
    const target=dialog.querySelector('[data-sto-incident-preview]'),s=preview?.summary||{},items=Array.isArray(preview?.items)?preview.items:[];target.innerHTML=`<div class="k-sto-r74-incident-summary"><b>${Number(s.affected||0)} затронуто</b><span>${Number(s.safe||0)} можно перестроить</span><span>${Number(s.blocked||0)} требуют решения</span></div>${items.slice(0,8).map(i=>`<p><b>${esc(i.vehicleTitle||'Автомобиль')}</b><span>${esc(fmtDateTime(i.oldStart))}</span><em>${i.safe?'→ '+esc(fmtDateTime(i.candidate?.candidateStart)):'нет безопасного окна'}</em></p>`).join('')}`;dialog.querySelector('[data-sto-incident-apply]').disabled=Number(s.affected||0)===0;
  }

  async function mountStoWorkplace(ctx={}){
    const root=document.querySelector('#k-sto-workplace');if(!root)return;let loading=false,currentData=null;
    const load=async()=>{if(loading)return;loading=true;root.setAttribute('aria-busy','true');try{const r=await apiModule.get(ctx.api,{signal:ctx.lifecycle?.signal});if(!root.isConnected)return;if(!r.ok){root.innerHTML=`<section class="k-empty"><h2>Кабинет СТО недоступен</h2><p>${esc(r.payload?.message||r.payload?.error||'Ошибка загрузки')}</p></section>`;return;}currentData=r.payload?.data||{};root.innerHTML=renderData(currentData);}finally{loading=false;root.removeAttribute('aria-busy');}};
    root.addEventListener('input',e=>{const search=e.target.closest('[data-sto-master-search]');if(!search)return;const q=String(search.value||'').trim().toLowerCase(),dialog=search.closest('dialog');dialog?.querySelectorAll?.('[data-sto-master-assign]').forEach(row=>{row.hidden=q!==''&&!String(row.dataset.search||'').includes(q);});},{signal:ctx.lifecycle?.signal});
    root.addEventListener('change',e=>{const pref=e.target.closest('[data-sto-pref]');if(!pref)return;currentData.schedulePreferences=currentData.schedulePreferences||{};currentData.schedulePreferences[pref.dataset.stoPref]=!!pref.checked;const section=root.querySelector('[data-sto-command]');if(section)section.outerHTML=scheduleCommand(currentData);apiModule.saveSchedulePreferences(ctx.api,currentData.schedulePreferences).catch?.(()=>{});},{signal:ctx.lifecycle?.signal});
    root.addEventListener('click',async e=>{
      const reload=e.target.closest('[data-sto-reload]');if(reload){reload.disabled=true;try{await load();}finally{if(reload.isConnected)reload.disabled=false;}return;}
      const windowOpen=e.target.closest('[data-sto-window-open]');if(windowOpen){const dialog=root.querySelector(`[data-sto-workspace-window="${windowOpen.dataset.stoWindowOpen||''}"]`);dialog?.showModal?.();return;}
      const windowClose=e.target.closest('[data-sto-window-close]');if(windowClose){windowClose.closest('dialog')?.close?.();return;}
      const geoDetect=e.target.closest('[data-sto-geo-detect]');if(geoDetect){const panel=geoDetect.closest('[data-sto-geo-settings]'),status=panel?.querySelector('[data-sto-geo-status]');geoDetect.disabled=true;if(status)status.textContent='Определяем точку…';try{let point;if(window.KaretaMobile?.bestLocation)point=await window.KaretaMobile.bestLocation({enableHighAccuracy:true,timeout:10000,maximumAge:120000});else if(navigator.geolocation)point=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,source:'browser'}),reject,{enableHighAccuracy:true,timeout:10000,maximumAge:120000}));else throw new Error('GEOLOCATION_UNAVAILABLE');const lat=Number(point?.latitude),lng=Number(point?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('GEOLOCATION_INVALID');panel.querySelector('[data-sto-geo-lat]').value=String(lat);panel.querySelector('[data-sto-geo-lng]').value=String(lng);panel.querySelector('[data-sto-geo-source]').value=point?.source||'gps';if(status)status.textContent=`Точка: ${lat.toFixed(5)}, ${lng.toFixed(5)}`;}catch(_error){if(status)status.textContent='Не удалось определить точку. Разрешите геолокацию и повторите.';}finally{geoDetect.disabled=false;}return;}
      const geoSave=e.target.closest('[data-sto-geo-save]');if(geoSave){const panel=geoSave.closest('[data-sto-geo-settings]'),sto=currentData?.sto||{},lat=Number(panel?.querySelector('[data-sto-geo-lat]')?.value),lng=Number(panel?.querySelector('[data-sto-geo-lng]')?.value),city=String(panel?.querySelector('[data-sto-geo-city]')?.value||'').trim(),address=String(panel?.querySelector('[data-sto-geo-address]')?.value||'').trim(),source=String(panel?.querySelector('[data-sto-geo-source]')?.value||'manual'),status=panel?.querySelector('[data-sto-geo-status]');if(!sto.id||!city||!address||!Number.isFinite(lat)||!Number.isFinite(lng)){if(status)status.textContent='Укажите город, адрес и определите точку.';return;}geoSave.disabled=true;try{const r=await ctx.api.request('api/geo.php?action=upsert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ownerType:'sto',ownerId:String(sto.id),kind:'service',label:String(sto.name||'СТО'),city,address,latitude:lat,longitude:lng,source,visibility:'exact',active:true}),cacheTtlMs:0,dedupe:false});if(!r?.ok)throw new Error(r?.payload?.message||r?.payload?.error||'Не удалось сохранить точку');window.KaretaToast?.success?.('Точка СТО сохранена');panel.closest('dialog')?.close?.();await load();}catch(error){if(status)status.textContent=error?.message||'Не удалось сохранить точку.';}finally{geoSave.disabled=false;}return;}
      const opsFilter=e.target.closest('[data-sto-ops-filter]');if(opsFilter){const key=opsFilter.dataset.stoOpsFilter||'all';root.querySelectorAll('[data-sto-ops-filter]').forEach(x=>x.classList.toggle('is-active',x===opsFilter));root.querySelectorAll('[data-sto-operation]').forEach(row=>{const kinds=String(row.dataset.kinds||'').split(/\s+/);row.hidden=key!=='all'&&!kinds.includes(key);});return;}
      const r82Pref=e.target.closest('[data-sto-r82-pref]');if(r82Pref){const key=r82Pref.dataset.stoR82Pref||'';if(!key)return;currentData.schedulePreferences=currentData.schedulePreferences||{};const active=!r82Pref.classList.contains('is-active');currentData.schedulePreferences[key]=active;r82Pref.classList.toggle('is-active',active);r82Pref.setAttribute('aria-pressed',active?'true':'false');const mark=r82Pref.querySelector('span');if(mark)mark.innerHTML=icon(active?'check':'close');const section=root.querySelector('[data-sto-command]');if(section)section.outerHTML=scheduleCommand(currentData);apiModule.saveSchedulePreferences(ctx.api,currentData.schedulePreferences).catch?.(()=>{});return;}
      const defaultRange=e.target.closest('[data-sto-r82-default-range]');if(defaultRange){currentData.schedulePreferences=currentData.schedulePreferences||{};currentData.schedulePreferences.defaultRange=defaultRange.dataset.stoR82DefaultRange||'day';defaultRange.parentElement?.querySelectorAll('[data-sto-r82-default-range]').forEach(x=>x.classList.toggle('is-active',x===defaultRange));const section=root.querySelector('[data-sto-command]');if(section)section.outerHTML=scheduleCommand(currentData);apiModule.saveSchedulePreferences(ctx.api,currentData.schedulePreferences).catch?.(()=>{});return;}
      const scheduleRange=e.target.closest('[data-sto-schedule-range]');if(scheduleRange){root.querySelectorAll('[data-sto-schedule-range]').forEach(x=>x.classList.toggle('is-active',x===scheduleRange));const day=scheduleRange.dataset.stoScheduleRange==='day',today=new Date().toISOString().slice(0,10);root.querySelectorAll('[data-sto-joint-item]').forEach(row=>{row.hidden=day&&!String(row.dataset.start||'').startsWith(today);});return;}
      const commandRange=e.target.closest('[data-sto-command-range]');if(commandRange){currentData.schedulePreferences=currentData.schedulePreferences||{};currentData.schedulePreferences.defaultRange=commandRange.dataset.stoCommandRange||'day';const section=root.querySelector('[data-sto-command]');if(section)section.outerHTML=scheduleCommand(currentData);apiModule.saveSchedulePreferences(ctx.api,currentData.schedulePreferences).catch?.(()=>{});return;}
      const alternativeOpen=e.target.closest('[data-sto-alternative-open]');if(alternativeOpen){const dialog=root.querySelector('[data-sto-alternative-dialog]');dialog.dataset.orderId=alternativeOpen.dataset.stoAlternativeOpen||'';dialog.querySelector('[data-sto-alternative-pairs]').innerHTML='<div class="k-sto-r73-picker-loading">Ищем свободную пару…</div>';dialog.showModal?.();const r=await apiModule.alternatives(ctx.api,{orderId:dialog.dataset.orderId});if(r.ok&&dialog.isConnected)renderAlternativePairs(dialog,r.payload?.data||{});else if(dialog.isConnected)dialog.querySelector('[data-sto-alternative-pairs]').innerHTML=`<div class="k-sto-r73-empty-line"><p>${esc(r.payload?.message||r.payload?.error||'Не удалось найти альтернативу')}</p></div>`;return;}
      const pair=e.target.closest('[data-sto-pair-master]');if(pair){const dialog=pair.closest('dialog'),orderId=dialog?.dataset.orderId||'';pair.disabled=true;const r=await apiModule.assignPair(ctx.api,{orderId,masterId:pair.dataset.stoPairMaster,bayId:pair.dataset.stoPairBay});if(!r.ok){window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Пара Мастер + бокс недоступна');pair.disabled=false;return;}dialog?.close?.();window.KaretaToast?.success?.('Плановая пара Мастер + бокс назначена');return load();}
      const incidentOpen=e.target.closest('[data-sto-incident-open]');if(incidentOpen){const dialog=root.querySelector('[data-sto-incident-dialog]'),now=new Date(),later=new Date(now.getTime()+4*3600000),local=x=>new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,16);dialog.querySelector('[data-sto-incident-lane-type]').value=incidentOpen.dataset.laneType||'';dialog.querySelector('[data-sto-incident-lane-id]').value=incidentOpen.dataset.stoIncidentOpen||'';dialog.querySelector('[data-sto-incident-start]').value=local(now);dialog.querySelector('[data-sto-incident-end]').value=local(later);dialog.querySelector('[data-sto-incident-preview]').innerHTML='<p>Сначала выполните preview.</p>';dialog.querySelector('[data-sto-incident-apply]').disabled=true;dialog.showModal?.();return;}
      const incidentPreview=e.target.closest('[data-sto-incident-preview]');if(incidentPreview){const dialog=incidentPreview.closest('dialog'),payload={laneType:dialog.querySelector('[data-sto-incident-lane-type]').value,laneId:dialog.querySelector('[data-sto-incident-lane-id]').value,startsAt:dialog.querySelector('[data-sto-incident-start]').value.replace('T',' ')+':00',endsAt:dialog.querySelector('[data-sto-incident-end]').value.replace('T',' ')+':00',reason:dialog.querySelector('[data-sto-incident-reason]').value};incidentPreview.disabled=true;const r=await apiModule.incidentPreview(ctx.api,payload);incidentPreview.disabled=false;if(!r.ok){window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Preview недоступен');return;}renderIncidentPreview(dialog,r.payload?.preview||{});return;}
      const incidentApply=e.target.closest('[data-sto-incident-apply]');if(incidentApply){const dialog=incidentApply.closest('dialog'),payload={laneType:dialog.querySelector('[data-sto-incident-lane-type]').value,laneId:dialog.querySelector('[data-sto-incident-lane-id]').value,startsAt:dialog.querySelector('[data-sto-incident-start]').value.replace('T',' ')+':00',endsAt:dialog.querySelector('[data-sto-incident-end]').value.replace('T',' ')+':00',reason:dialog.querySelector('[data-sto-incident-reason]').value,autoMove:dialog.querySelector('[data-sto-incident-auto]').checked,notify:dialog.querySelector('[data-sto-incident-notify]').checked};incidentApply.disabled=true;const r=await apiModule.incidentApply(ctx.api,payload);if(!r.ok){window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Изменение мощности не применено');incidentApply.disabled=false;return;}dialog?.close?.();window.KaretaToast?.success?.(`Ограничение сохранено · перенесено ${Number(r.payload?.recovery?.movedCount||0)}`);return load();}
      const incidentResolve=e.target.closest('[data-sto-incident-resolve]');if(incidentResolve){incidentResolve.disabled=true;const r=await apiModule.incidentResolve(ctx.api,{id:incidentResolve.dataset.stoIncidentResolve});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось снять ограничение');else window.KaretaToast?.success?.('Ограничение снято');return load();}
      const masterOpen=e.target.closest('[data-sto-master-open]');if(masterOpen){const dialog=root.querySelector('[data-sto-master-dialog]');dialog.dataset.orderId=masterOpen.dataset.stoMasterOpen||'';dialog.querySelector('[data-sto-master-candidates]').innerHTML='<div class="k-sto-r73-picker-loading">Проверяем загрузку, услуги и тариф…</div>';dialog.showModal?.();const r=await apiModule.masterCandidates(ctx.api,{orderId:dialog.dataset.orderId});if(r.ok&&dialog.isConnected)renderMasterCandidates(dialog,r.payload?.data||{});else if(dialog.isConnected)dialog.querySelector('[data-sto-master-candidates]').innerHTML=`<div class="k-sto-r73-empty-line"><p>${esc(r.payload?.message||r.payload?.error||'Не удалось получить Мастеров')}</p></div>`;return;}
      const masterPick=e.target.closest('[data-sto-master-assign]');if(masterPick){const dialog=masterPick.closest('dialog'),orderId=dialog?.dataset.orderId||'';masterPick.disabled=true;const r=await apiModule.assignMaster(ctx.api,{orderId,masterId:masterPick.dataset.stoMasterAssign});if(!r.ok){window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось назначить Мастера');masterPick.disabled=false;return;}dialog?.close?.();window.KaretaToast?.success?.('Мастер назначен');return load();}
      const bayOpen=e.target.closest('[data-sto-bay-open]');if(bayOpen){const dialog=root.querySelector('[data-sto-bay-dialog]');dialog.dataset.orderId=bayOpen.dataset.stoBayOpen||'';dialog.querySelector('[data-sto-bay-candidates]').innerHTML='<div class="k-sto-r73-picker-loading">Проверяем доступность боксов…</div>';dialog.showModal?.();const r=await apiModule.bayCandidates(ctx.api,{orderId:dialog.dataset.orderId});if(r.ok&&dialog.isConnected)renderBayCandidates(dialog,r.payload?.data||{});else if(dialog.isConnected)dialog.querySelector('[data-sto-bay-candidates]').innerHTML=`<div class="k-sto-r73-empty-line"><p>${esc(r.payload?.message||r.payload?.error||'Не удалось получить боксы')}</p></div>`;return;}
      const bayPick=e.target.closest('[data-sto-bay-pick]');if(bayPick){const dialog=bayPick.closest('dialog'),orderId=dialog?.dataset.orderId||'';bayPick.disabled=true;const r=await apiModule.assign(ctx.api,{bayId:bayPick.dataset.stoBayPick,orderId});if(!r.ok){window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось поставить машину на пост');bayPick.disabled=false;return;}dialog?.close?.();window.KaretaToast?.success?.('Машина поставлена на пост');return load();}
      const bayDirect=e.target.closest('[data-sto-bay-direct]');if(bayDirect){bayDirect.disabled=true;const r=await apiModule.assign(ctx.api,{bayId:bayDirect.dataset.stoBayDirect,orderId:bayDirect.dataset.orderId});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось поставить машину на пост');else window.KaretaToast?.success?.('Машина поставлена на пост');return load();}
      const release=e.target.closest('[data-sto-release]');if(release){release.disabled=true;const r=await apiModule.release(ctx.api,{orderId:release.dataset.stoRelease});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось освободить пост');return load();}
      const rebalance=e.target.closest('[data-sto-rebalance]');if(rebalance){rebalance.disabled=true;const r=await apiModule.rebalance(ctx.api);if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось перераспределить');else window.KaretaToast?.success?.(`Переназначено: ${Number(r.payload?.data?.moved||0)}`);return load();}
      const preview=e.target.closest('[data-sto-recovery-preview]');if(preview){preview.disabled=true;const r=await apiModule.recoveryPreview(ctx.api,{});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Preview недоступен');else window.KaretaToast?.success?.(`Конфликтов: ${Number(r.payload?.preview?.summary?.conflicts||0)}`);return load();}
      const protect=e.target.closest('[data-sto-recovery-protect]');if(protect){protect.disabled=true;const now=protect.dataset.protected==='1',r=await apiModule.recoveryProtect(ctx.api,{orderId:protect.dataset.stoRecoveryProtect,protected:!now});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Не удалось изменить защиту');else window.KaretaToast?.success?.(now?'Защита снята':'Запись защищена');return load();}
      const apply=e.target.closest('[data-sto-recovery-apply-selected],[data-sto-recovery-apply-all]');if(apply){const all=apply.hasAttribute('data-sto-recovery-apply-all'),ids=all?[]:[...root.querySelectorAll('[data-sto-recovery-select]:checked')].map(x=>x.value).filter(Boolean);if(!all&&!ids.length){window.KaretaToast?.error?.('Выберите хотя бы одну запись');return;}apply.disabled=true;const notify=!!root.querySelector('[data-sto-recovery-notify]')?.checked,r=await apiModule.recoveryApply(ctx.api,{orderIds:ids,notify});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Перенос недоступен');else window.KaretaToast?.success?.(`Перенесено ${Number(r.payload?.recovery?.movedCount||0)}, уведомлено ${Number(r.payload?.recovery?.notifiedCount||0)}`);return load();}
      const resend=e.target.closest('[data-sto-recovery-resend]');if(resend){resend.disabled=true;const r=await apiModule.recoveryNotifyResend(ctx.api,{orderId:resend.dataset.stoRecoveryResend});if(!r.ok)window.KaretaToast?.error?.(r.payload?.message||r.payload?.error||'Уведомление не отправлено');else window.KaretaToast?.success?.('Уведомление отправлено повторно');return load();}
    },{signal:ctx.lifecycle?.signal});
    await load();
    const timer=setInterval(async()=>{if(!root.isConnected)return;try{const r=await apiModule.rebalance(ctx.api);if(Number(r?.payload?.data?.moved||0)>0)await load();}catch(_e){}},60000);ctx.lifecycle?.signal?.addEventListener?.('abort',()=>clearInterval(timer),{once:true});
  }
  window.KaretaStoWorkplacePages=Object.freeze({renderStoWorkplace,mountStoWorkplace});
})();
