(() => {
  'use strict';
  const ui=window.KaretaPageUI, apiModule=window.KaretaVehicleApi;
  if(!ui||!apiModule) throw new Error('Vehicle page dependencies are missing');
  const esc=ui.escapeHtml;
  const money=n=>`${new Intl.NumberFormat('ru-RU').format(Number(n||0))} ₸`;
  const date=v=>v?new Date(String(v).replace(' ','T')).toLocaleDateString('ru-RU'):'—';
  const dateTime=v=>v?new Date(String(v).replace(' ','T')).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
  const idFromHash=()=>{const m=location.hash.match(/^#\/garage\/car\/([^/?]+)/);return m?decodeURIComponent(m[1]):'';};
  const fmtKm=n=>`${new Intl.NumberFormat('ru-RU').format(Number(n||0))} км`;
  const text=v=>String(v??'').trim();
  const icon=name=>({
    car:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 10l1.6-4h10.8l1.6 4 2 2v5H3v-5l2-2Z"/><path d="M6 17v2m12-2v2M7.5 13h.01m8.99 0h.01"/></svg>',
    wrench:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.2 6.2a4.5 4.5 0 0 0-5.8 5.8L3 17.4 6.6 21l5.4-5.4a4.5 4.5 0 0 0 5.8-5.8l-3 3-3.6-3.6 3-3Z"/></svg>',
    alert:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5m0 3h.01"/></svg>',
    history:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></svg>',
    part:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3h8l4 4v10l-4 4H8l-4-4V7l4-4Z"/><circle cx="12" cy="12" r="3"/><path d="M12 3v3m0 12v3M3 12h3m12 0h3"/></svg>',
    doc:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></svg>',
    shield:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 4.5 6v5.2c0 4.8 3 8.1 7.5 9.8 4.5-1.7 7.5-5 7.5-9.8V6L12 3Z"/><path d="m9 12 2 2 4-4"/></svg>',
    coins:'<svg viewBox="0 0 24 24" aria-hidden="true"><ellipse cx="9" cy="6" rx="5" ry="2.5"/><path d="M4 6v4c0 1.4 2.2 2.5 5 2.5s5-1.1 5-2.5V6M4 10v4c0 1.4 2.2 2.5 5 2.5 1 0 2-.2 2.8-.5"/><path d="M14 12c3.3 0 6 1.1 6 2.5S17.3 17 14 17s-6-1.1-6-2.5"/><path d="M8 14.5v4c0 1.4 2.7 2.5 6 2.5s6-1.1 6-2.5v-4"/></svg>',
    camera:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h4l1.5-2h5L16 7h4v12H4z"/><circle cx="12" cy="13" r="3.5"/></svg>',
    speed:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 18a8 8 0 1 1 16 0"/><path d="m12 14 4-4M7 18h10"/></svg>'
  }[name]||'');
  function renderVehicle(){return `<section class="k-page k-vehicle-native" data-page="vehicle"><div id="k-vehicle-page" class="k-vehicle-page" data-phase="loading"><section class="k-vehicle-loading"><span class="k-vehicle-loading__icon">${icon('car')}</span><h1>Загрузка автомобиля</h1><p>Собираем цифровой паспорт и историю эксплуатации.</p></section></div></section>`;}
  function empty(textValue){return `<div class="k-vehicle-empty">${esc(textValue)}</div>`;}
  function activeOrders(data){return (data.orders||[]).filter(x=>!['completed','done','closed','issued','cancelled','canceled'].includes(String(x.status||'').toLowerCase()));}
  function openIssues(data){return (data.issues||[]).filter(x=>String(x.status||'open')!=='resolved');}
  function activeRecs(data){return (data.recommendations||[]).filter(x=>String(x.status||'active')==='active');}
  function dueDocCount(data){const now=Date.now(),limit=now+30*86400000;return (data.documents||[]).filter(x=>{if(!x.expires_at)return false;const t=new Date(String(x.expires_at)+'T00:00:00').getTime();return Number.isFinite(t)&&t<=limit;}).length;}
  function statusSummary(data){const issues=openIssues(data),recs=activeRecs(data),docs=dueDocCount(data),orders=activeOrders(data);if(issues.some(x=>['critical','high'].includes(String(x.severity))))return {key:'danger',label:'Требует внимания',note:'Есть важные неисправности'};if(issues.length||recs.length||docs)return {key:'attention',label:'Есть задачи',note:`${issues.length} неиспр. · ${recs.length} рекомендац.`};if(orders.length)return {key:'service',label:'На обслуживании',note:'Есть активный ремонт'};return {key:'ok',label:'В норме',note:'Критичных событий нет'};}
  function passportRows(v){return [
    ['Марка',v.brand],['Модель',v.model],['Год',v.year_label],['Поколение',v.generation],['Кузов',v.body_type],['Двигатель',v.engine_type||v.engine_volume],['Топливо',v.fuel_type],['КПП',v.transmission],['Привод',v.drive_type],['Цвет',v.color],['Госномер',v.plate],['VIN',v.vin]
  ].filter(([,value])=>text(value));}
  function passport(data){const v=data.vehicle||{};const rows=passportRows(v);return rows.length?`<dl class="k-vehicle-passport-grid">${rows.map(([k,val])=>`<div><dt>${esc(k)}</dt><dd>${esc(val)}</dd></div>`).join('')}</dl>`:empty('Паспорт автомобиля пока не заполнен.');}
  function issueCards(items,limit=0){const rows=(items||[]).filter(x=>String(x.status||'open')!=='resolved');const list=limit?rows.slice(0,limit):rows;if(!list.length)return empty('Активных неисправностей нет.');return `<div class="k-vehicle-stack">${list.map(x=>`<article class="k-vehicle-fact-card is-${esc(x.severity||'medium')}"><span class="k-vehicle-fact-card__icon">${icon('alert')}</span><div><small>${esc(x.code_value||'НЕИСПРАВНОСТЬ')}</small><h3>${esc(x.title||'Неисправность')}</h3><p>${esc(x.description||'Описание не добавлено')}</p><time>${esc(date(x.detected_at))}</time></div></article>`).join('')}</div>`;}
  function recCards(items,limit=0){const rows=(items||[]).filter(x=>String(x.status||'active')==='active');const list=limit?rows.slice(0,limit):rows;if(!list.length)return empty('Рекомендаций пока нет.');return `<div class="k-vehicle-stack">${list.map(x=>`<article class="k-vehicle-fact-card is-recommendation"><span class="k-vehicle-fact-card__icon">${icon('wrench')}</span><div><small>${String(x.priority||'normal')==='high'?'ВАЖНО':'РЕКОМЕНДАЦИЯ'}</small><h3>${esc(x.title||'Обслуживание')}</h3><p>${esc(x.description||'')}</p><time>${x.due_date?`до ${esc(date(x.due_date))}`:''}${x.due_mileage_km?`${x.due_date?' · ':''}до ${fmtKm(x.due_mileage_km)}`:''}</time></div></article>`).join('')}</div>`;}
  function historyCards(items,limit=0){const list=limit?(items||[]).slice(0,limit):(items||[]);if(!list.length)return empty('История появится после первого подтверждённого события.');return `<div class="k-vehicle-timeline">${list.map(x=>`<article class="k-vehicle-timeline-item"><span class="k-vehicle-timeline-icon">${icon('history')}</span><div><small>${esc(date(x.event_at||x.eventAt))}</small><h3>${esc(x.title||'Сервисная запись')}</h3><p>${esc(x.summary||'')}</p><div class="k-vehicle-meta">${x.mileage_km?`<span>${fmtKm(x.mileage_km)}</span>`:''}${Number(x.amount)>0?`<strong>${money(x.amount)}</strong>`:''}${x.performed_by?`<span>${esc(x.performed_by)}</span>`:''}</div>${x.order_id?`<a class="k-text-action" href="#/orders/item/${encodeURIComponent(x.order_id)}">Открыть заказ-наряд</a>`:''}</div></article>`).join('')}</div>`;}
  function partCards(items,limit=0){const list=limit?(items||[]).slice(0,limit):(items||[]);if(!list.length)return empty('Установленные детали появятся после выдачи деталей в реальном заказ-наряде.');return `<div class="k-vehicle-part-grid">${list.map(x=>`<article class="k-vehicle-part-card"><span class="k-vehicle-part-card__icon">${icon('part')}</span><div><small>${esc(x.oem||x.sku||'УСТАНОВЛЕННАЯ ДЕТАЛЬ')}</small><h3>${esc(x.part_name||x.partName||'Запчасть')}</h3><p>${esc(x.supplier_label||x.supplierLabel||'Поставщик не указан')}</p><div><span>${Number(x.qty_issued||0)>0?`${Number(x.qty_issued)} шт.`:'установлено'}</span>${Number(x.unit_price||0)>0?`<strong>${money(x.unit_price)}</strong>`:''}</div>${x.order_id?`<a class="k-text-action" href="#/orders/item/${encodeURIComponent(x.order_id)}">Заказ-наряд</a>`:''}</div></article>`).join('')}</div>`;}
  function documentCards(items,limit=0){const list=limit?(items||[]).slice(0,limit):(items||[]);if(!list.length)return empty('Документы не добавлены.');return `<div class="k-vehicle-doc-grid">${list.map(x=>{const expired=x.expires_at&&new Date(String(x.expires_at)+'T23:59:59').getTime()<Date.now();return `<article class="k-vehicle-doc ${expired?'is-expired':''}"><span class="k-vehicle-doc__icon">${icon('doc')}</span><div><small>${esc(String(x.document_type||'DOC').toUpperCase())}</small><h3>${esc(x.title||'Документ')}</h3><p>${x.expires_at?`${expired?'Истёк ':'Действует до '}${esc(date(x.expires_at))}`:'Без срока действия'}</p>${x.file_url?`<a class="k-text-action" href="${esc(x.file_url)}" target="_blank" rel="noopener">Открыть документ</a>`:''}</div></article>`;}).join('')}</div>`;}
  function warrantyCards(items,limit=0){const list=limit?(items||[]).slice(0,limit):(items||[]);if(!list.length)return empty('Активных гарантий пока нет.');return `<div class="k-vehicle-warranty-grid">${list.map(x=>`<article class="k-vehicle-warranty-card"><span>${icon('shield')}</span><div><small>ГАРАНТИЯ</small><h3>${esc(x.title||'Гарантия на ремонт')}</h3><p>${esc(x.provider||'KARETA.KZ')}</p><strong>${x.warranty_until?`до ${esc(date(x.warranty_until))}`:'срок не указан'}</strong></div></article>`).join('')}</div>`;}
  function maintenanceCards(data,limit=0){const rows=[...(data.maintenance||[]).map(x=>({kind:'ТО',title:x.title||'Обслуживание',note:[x.brand,x.model].filter(Boolean).join(' '),when:x.next_due_at,mileage:x.next_due_mileage_km})),...activeRecs(data).map(x=>({kind:'Рекомендация',title:x.title,note:x.description||'',when:x.due_date,mileage:x.due_mileage_km}))];const list=limit?rows.slice(0,limit):rows;if(!list.length)return empty('Плановое обслуживание ещё не добавлено.');return `<div class="k-vehicle-maint-grid">${list.map(x=>`<article><small>${esc(x.kind)}</small><h3>${esc(x.title||'Обслуживание')}</h3><p>${esc(x.note||'')}</p><div>${x.when?`<span>${esc(date(x.when))}</span>`:''}${x.mileage?`<span>${fmtKm(x.mileage)}</span>`:''}</div></article>`).join('')}</div>`;}
  function expenseContent(data){const rows=[...(data.orders||[]).map(x=>({title:x.service_names||`Заказ ${x.num||''}`,amount:Number(x.price||0),date:x.completed_at||x.created_at,type:'Ремонт'})),...(data.expenses||[]).map(x=>({title:x.title||x.category||'Расход',amount:Number(x.amount||0),date:x.expense_date||x.created_at,type:x.category||'Расход'}))].filter(x=>x.amount>0).sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(!rows.length)return empty('Расходы ещё не зафиксированы.');const now=new Date(),year=now.getFullYear(),month=now.getMonth();const totalFor=filter=>rows.filter(filter).reduce((s,x)=>s+x.amount,0);const monthTotal=totalFor(x=>{const d=new Date(String(x.date).replace(' ','T'));return d.getFullYear()===year&&d.getMonth()===month;});const yearTotal=totalFor(x=>new Date(String(x.date).replace(' ','T')).getFullYear()===year);const total=totalFor(()=>true);return `<div class="k-vehicle-expense-summary"><article><small>Этот месяц</small><strong>${money(monthTotal)}</strong></article><article><small>Этот год</small><strong>${money(yearTotal)}</strong></article><article><small>За всё время</small><strong>${money(total)}</strong></article></div><div class="k-vehicle-expense-list">${rows.map(x=>`<article><div><small>${esc(x.type)}</small><h3>${esc(x.title)}</h3><time>${esc(date(x.date))}</time></div><strong>${money(x.amount)}</strong></article>`).join('')}</div>`;}
  function mediaContent(items){if(!(items||[]).length)return empty('Фото и документы из ремонтов пока отсутствуют.');return `<div class="k-vehicle-media-grid">${items.map(x=>`<a class="k-vehicle-media" href="${esc(x.file_url)}" target="_blank" rel="noopener"><span class="k-vehicle-media__icon">${icon('camera')}</span><div><small>${esc(String(x.media_type||'photo').toUpperCase())}</small><h3>${esc(x.caption||'Материал по ремонту')}</h3><p>${esc(x.stage_key||'')} · ${esc(date(x.created_at))}</p></div></a>`).join('')}</div>`;}
  function activeRepair(data){const order=activeOrders(data)[0];if(!order)return empty('Сейчас автомобиль не находится в активном ремонте.');return `<article class="k-vehicle-active-order"><span class="k-vehicle-active-order__icon">${icon('wrench')}</span><div><small>АКТИВНЫЙ РЕМОНТ</small><h3>${esc(order.service_names||`Заказ ${order.num||''}`)}</h3><p>${esc(order.status||'В работе')} · ${esc(date(order.created_at))}</p></div><a class="k-btn k-btn-primary" href="#/orders/item/${encodeURIComponent(order.id)}">Открыть ремонт</a></article>`;}
  function renderData(data){
    const v=data.vehicle||{},m=data.metrics||{},state=statusSummary(data),title=v.title||[v.brand,v.model,v.year_label].filter(Boolean).join(' ')||'Автомобиль';
    const issues=openIssues(data),recs=activeRecs(data),parts=data.installedParts||[],docs=data.documents||[],warranties=(data.warranties||[]).filter(x=>String(x.status||'active')!=='deleted');
    const plate=esc(v.plate||'Без госномера'), mileage=fmtKm(v.mileage_km||0);
    const referenceVehicle=window.KaretaVisualAssets?.vehicleImage?.(v.brand)||'';
    return `<section class="k-vehicle-identity-card k-vehicle-r78-hero k-vehicle-r84-hero">
      <div class="k-vehicle-photo">${v.photo_url?`<img src="${esc(v.photo_url)}" alt="${esc(title)}">`:referenceVehicle?`<img src="${esc(referenceVehicle)}" alt="${esc(title)}" class="is-reference-vehicle" style="object-fit:contain;background:#f7f7f8;padding:6px">`:`<span>${esc((v.brand||'K').slice(0,1))}</span>`}</div>
      <div class="k-vehicle-identity"><small>МОЙ ГАРАЖ</small><h1>${esc(title)}</h1><p>${plate}${v.vin?` · VIN ${esc(v.vin)}`:''}</p><div class="k-vehicle-tags">${v.year_label?`<span>${esc(v.year_label)}</span>`:''}${v.engine_type||v.engine_volume?`<span>${esc(v.engine_type||v.engine_volume)}</span>`:''}${v.transmission?`<span>${esc(v.transmission)}</span>`:''}</div></div>
      <div class="k-vehicle-r78-status k-vehicle-r84-status is-${esc(state.key)}"><span class="k-vehicle-r78-status__dot"></span><div><small>СОСТОЯНИЕ</small><strong>${esc(state.label)}</strong><span>${esc(state.note)}</span></div></div>
      <div class="k-vehicle-r78-primary k-vehicle-r84-primary"><button class="k-btn k-btn-primary" type="button" data-vehicle-create-request>${icon('wrench')}<span>Создать заявку</span></button><button type="button" data-vehicle-action="issue">${icon('alert')}<span>Добавить проблему</span></button></div>
    </section>
    <nav class="k-vehicle-r78-nav k-vehicle-r84-nav" aria-label="Разделы автомобиля">
      <button type="button" data-vehicle-scroll="state"><span>${icon('alert')}</span><b>Состояние</b><small>${issues.length||'0'}</small></button>
      <button type="button" data-vehicle-scroll="history"><span>${icon('history')}</span><b>История</b><small>${Number(m.completedOrders||0)}</small></button>
      <button type="button" data-vehicle-scroll="parts"><span>${icon('part')}</span><b>Детали</b><small>${parts.length}</small></button>
      <button type="button" data-vehicle-scroll="passport"><span>${icon('doc')}</span><b>Паспорт</b><small>${plate}</small></button>
      <button type="button" data-vehicle-scroll="service"><span>${icon('wrench')}</span><b>ТО</b><small>${recs.length}</small></button>
      <button type="button" data-vehicle-scroll="documents"><span>${icon('shield')}</span><b>Документы</b><small>${docs.length}</small></button>
    </nav>
    <section class="k-vehicle-native-metrics k-vehicle-r78-metrics k-vehicle-r84-metrics" aria-label="Сводка автомобиля">
      <article><span>${icon('speed')}</span><small>Пробег</small><strong>${mileage}</strong><button type="button" data-vehicle-action="mileage">Обновить</button></article>
      <article><span>${icon('wrench')}</span><small>Ремонтов</small><strong>${esc(m.completedOrders??0)}</strong><button type="button" data-vehicle-scroll="history">История</button></article>
      <article class="${issues.length?'is-attention':''}"><span>${icon('alert')}</span><small>Проблем</small><strong>${issues.length}</strong><button type="button" data-vehicle-scroll="state">Проверить</button></article>
      <article class="${dueDocCount(data)?'is-attention':''}"><span>${icon('doc')}</span><small>Документов</small><strong>${docs.length}</strong><button type="button" data-vehicle-scroll="documents">Открыть</button></article>
    </section>
    <section class="k-vehicle-native-actions k-vehicle-r78-actions k-vehicle-r84-actions" aria-label="Быстрые действия">
      <a class="k-vehicle-action-tile" href="#/parts"><span>${icon('part')}</span><b>Новые запчасти</b><small>Подбор по автомобилю</small></a>
      <a class="k-vehicle-action-tile" href="#/parts/used"><span>${icon('part')}</span><b>Биржа БУ</b><small>БУ, восстановленные, обмен</small></a>
      <button class="k-vehicle-action-tile" type="button" data-vehicle-open-section="expenses"><span>${icon('coins')}</span><b>Расходы</b><small>${money(m.spent||0)}</small></button>
      <button class="k-vehicle-action-tile" type="button" data-vehicle-open-section="media"><span>${icon('camera')}</span><b>Фотоархив</b><small>${Number(m.media||0)} материалов</small></button>
    </section>
    <section class="k-vehicle-native-layout k-vehicle-r78-layout k-vehicle-r84-layout">
      <div class="k-vehicle-native-main">
        <article class="k-vehicle-native-section k-vehicle-r78-active k-vehicle-r84-section k-vehicle-r84-active" data-vehicle-section="active"><div class="k-vehicle-native-section__head"><div><small>СЕЙЧАС</small><h2>Активный ремонт</h2></div></div>${activeRepair(data)}</article>
        <article class="k-vehicle-native-section" data-vehicle-section="state"><div class="k-vehicle-native-section__head"><div><small>СОСТОЯНИЕ</small><h2>Что требует внимания</h2></div><button type="button" class="k-text-button" data-vehicle-action="issue">+ Проблема</button></div>${issueCards(data.issues,2)}${recs.length?`<div class="k-vehicle-subsection-title"><b>Рекомендации</b><button type="button" data-vehicle-action="recommendation">+ Добавить</button></div>${recCards(data.recommendations,2)}`:''}</article>
        <article class="k-vehicle-native-section" data-vehicle-section="history"><div class="k-vehicle-native-section__head"><div><small>ИСТОРИЯ</small><h2>Последние события</h2></div>${(data.history||[]).length>3?'<button type="button" class="k-text-button" data-vehicle-open-section="history">Вся история</button>':''}</div>${historyCards(data.history,3)}</article>
        <article class="k-vehicle-native-section" data-vehicle-section="parts"><div class="k-vehicle-native-section__head"><div><small>ЗАПЧАСТИ</small><h2>Установленные детали</h2></div>${parts.length>3?'<button type="button" class="k-text-button" data-vehicle-open-section="parts">Все детали</button>':''}</div>${partCards(parts,3)}</article>
      </div>
      <aside class="k-vehicle-native-side">
        <article class="k-vehicle-native-section" data-vehicle-section="passport"><div class="k-vehicle-native-section__head"><div><small>ПАСПОРТ</small><h2>Данные автомобиля</h2></div><button type="button" class="k-text-button" data-vehicle-open-section="passport">Открыть</button></div>${passportRows(v).slice(0,5).length?`<dl class="k-vehicle-passport-preview">${passportRows(v).slice(0,5).map(([k,val])=>`<div><dt>${esc(k)}</dt><dd>${esc(val)}</dd></div>`).join('')}</dl>`:empty('Основные данные не заполнены.')}</article>
        <article class="k-vehicle-native-section" data-vehicle-section="service"><div class="k-vehicle-native-section__head"><div><small>СЕРВИС</small><h2>ТО и сроки</h2></div><button type="button" class="k-text-button" data-vehicle-open-section="maintenance">Все</button></div>${maintenanceCards(data,2)}</article>
        <article class="k-vehicle-native-section" data-vehicle-section="documents"><div class="k-vehicle-native-section__head"><div><small>ДОКУМЕНТЫ</small><h2>Документы и гарантии</h2></div><button type="button" class="k-text-button" data-vehicle-open-section="documents">Все</button></div>${documentCards(docs,2)}${warranties.length?`<div class="k-vehicle-subsection-title"><b>Гарантии</b></div>${warrantyCards(warranties,1)}`:''}</article>
      </aside>
    </section>`;
  }
  function modal(title,body,opts={}){return `<dialog class="k-vehicle-modal k-vehicle-modal-r78 ${opts.full?'is-full':''}" aria-label="${esc(title)}" data-vehicle-modal-root><div class="k-vehicle-modal__sheet"><header><div><small>${esc(opts.eyebrow||'МОЙ АВТОМОБИЛЬ')}</small><h2>${esc(title)}</h2></div><button type="button" data-vehicle-close aria-label="Закрыть">${icon('close')}</button></header><div class="k-vehicle-modal__body">${body}</div></div></dialog>`;}
  function sectionModal(section,data){const map={
    passport:['Паспорт автомобиля',passport(data),'ДАННЫЕ АВТОМОБИЛЯ'],
    history:['История автомобиля',historyCards(data.history),'ПОДТВЕРЖДЁННЫЕ СОБЫТИЯ'],
    parts:['Установленные детали',partCards(data.installedParts||[]),'ИСТОРИЯ ЗАПЧАСТЕЙ'],
    maintenance:['ТО и сервисные сроки',`${maintenanceCards(data)}${(data.warranties||[]).length?`<div class="k-vehicle-modal-section"><h3>Гарантии</h3>${warrantyCards(data.warranties)}</div>`:''}`,'СЕРВИСНАЯ КНИЖКА'],
    documents:['Документы и гарантии',`${documentCards(data.documents||[])}${(data.warranties||[]).length?`<div class="k-vehicle-modal-section"><h3>Гарантии</h3>${warrantyCards(data.warranties)}</div>`:''}`,'ДОКУМЕНТЫ'],
    expenses:['Расходы на автомобиль',expenseContent(data),'ЭКСПЛУАТАЦИЯ'],
    media:['Фотоархив',mediaContent(data.media||[]),'МАТЕРИАЛЫ РЕМОНТОВ']
  };const item=map[section];if(!item)return'';return modal(item[0],item[1],{full:true,eyebrow:item[2]});}
  function severityChoices(){return `<fieldset class="k-vehicle-choice-group"><legend>Критичность</legend><label><input type="radio" name="severity" value="low"><span><b>Низкая</b><small>Наблюдать</small></span></label><label><input type="radio" name="severity" value="medium" checked><span><b>Средняя</b><small>Нужна проверка</small></span></label><label><input type="radio" name="severity" value="high"><span><b>Высокая</b><small>Нужен ремонт</small></span></label><label><input type="radio" name="severity" value="critical"><span><b>Критичная</b><small>Эксплуатация нежелательна</small></span></label></fieldset>`;}
  function actionModal(action,data){const v=data.vehicle||{};if(action==='mileage')return modal('Обновить пробег',`<form data-vehicle-form="mileage"><label>Текущий пробег<input name="mileageKm" type="number" inputmode="numeric" min="${Number(v.mileage_km||0)}" value="${Number(v.mileage_km||0)}" required><small>Новый пробег не может быть меньше последнего сохранённого.</small></label><button class="k-btn k-btn-primary" type="submit">Сохранить пробег</button></form>`,{eyebrow:'ПРОБЕГ'});if(action==='issue')return modal('Добавить проблему',`<form data-vehicle-form="issue"><label>Что происходит<input name="title" required placeholder="Например: стук справа спереди"></label><label>Код ошибки, если есть<input name="code" placeholder="Например: P0301"></label><label>Описание<textarea name="description" placeholder="Когда появляется, при какой скорости, что уже проверяли"></textarea></label>${severityChoices()}<button class="k-btn k-btn-primary" type="submit">Зафиксировать проблему</button></form>`,{eyebrow:'НЕИСПРАВНОСТЬ'});if(action==='recommendation')return modal('Добавить рекомендацию',`<form data-vehicle-form="recommendation"><label>Что нужно сделать<input name="title" required placeholder="Например: заменить масло"></label><label>Описание<textarea name="description"></textarea></label><div class="k-vehicle-form-grid"><label>До даты<input name="dueDate" type="date"></label><label>До пробега<input name="dueMileageKm" type="number" min="0" inputmode="numeric"></label></div><fieldset class="k-vehicle-choice-group k-vehicle-choice-group--three"><legend>Приоритет</legend><label><input type="radio" name="priority" value="low"><span><b>Низкий</b></span></label><label><input type="radio" name="priority" value="normal" checked><span><b>Обычный</b></span></label><label><input type="radio" name="priority" value="high"><span><b>Высокий</b></span></label></fieldset><button class="k-btn k-btn-primary" type="submit">Сохранить рекомендацию</button></form>`,{eyebrow:'СЕРВИС'});return'';}
  function mountVehicle(context){
    const root=document.querySelector('#k-vehicle-page');if(!root)return;const id=idFromHash(),lifecycle=context.lifecycle||{};let currentData=null;
    const closeModal=()=>{const modal=document.querySelector('[data-vehicle-modal-root]');if(!modal)return;if(modal.open){try{modal.close();}catch(_e){}}modal.remove();};
    const show=html=>{closeModal();if(!html)return;document.body.insertAdjacentHTML('beforeend',html);const modal=document.querySelector('[data-vehicle-modal-root]');if(!modal)return;modal.addEventListener('cancel',event=>{event.preventDefault();closeModal();},{once:true});try{modal.showModal();}catch(_e){}requestAnimationFrame(()=>modal.querySelector('button,input,[tabindex]')?.focus?.({preventScroll:true}));};
    const load=async()=>{const r=await apiModule.detail(context.api,id,{signal:lifecycle.signal});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Автомобиль недоступен');currentData=r.payload.data||{};root.dataset.phase='ready';root.innerHTML=renderData(currentData);window.KaretaPageSessionState?.restore?.({root,reason:'vehicle-data',dispatchEvents:false});};
    load().catch(e=>{root.dataset.phase='error';root.innerHTML=`<section class="k-vehicle-loading is-error"><span class="k-vehicle-loading__icon">${icon('alert')}</span><h1>Автомобиль недоступен</h1><p>${esc(e.message)}</p><button class="k-btn k-btn-primary" type="button" data-vehicle-retry>Повторить</button></section>`;});
    const click=e=>{
      if(e.target.closest('[data-vehicle-close]')||e.target.matches('[data-vehicle-modal-root]')){closeModal();return;}
      if(e.target.closest('[data-vehicle-retry]')){root.dataset.phase='loading';root.innerHTML='<section class="k-vehicle-loading"><h1>Загрузка автомобиля</h1><p>Повторяем запрос.</p></section>';load().catch(()=>{});return;}
      if(e.target.closest('[data-vehicle-create-request]')&&currentData){try{sessionStorage.setItem('kareta.request.prefill',JSON.stringify({vehicleId:id,clientVehicleId:id,clientCar:currentData.vehicle?.title||[currentData.vehicle?.brand,currentData.vehicle?.model].filter(Boolean).join(' '),source:'vehicle_passport'}));}catch(_e){}if(!window.KaretaRequestWindow?.open?.('#/orders/new'))location.hash='#/orders/new';return;}
      const scrollKey=e.target.closest('[data-vehicle-scroll]')?.dataset.vehicleScroll;if(scrollKey){root.querySelector(`[data-vehicle-section="${CSS.escape(scrollKey)}"]`)?.scrollIntoView({behavior:'smooth',block:'start'});return;}
      const section=e.target.closest('[data-vehicle-open-section]')?.dataset.vehicleOpenSection;if(section&&currentData){show(sectionModal(section,currentData));return;}
      const action=e.target.closest('[data-vehicle-action]')?.dataset.vehicleAction;if(action&&currentData){show(actionModal(action,currentData));return;}
    };
    const submit=async e=>{
      const f=e.target.closest('[data-vehicle-form]');if(!f)return;e.preventDefault();const payload=Object.fromEntries(new FormData(f).entries());payload.vehicleId=id;let r;
      if(f.dataset.vehicleForm==='issue')r=await apiModule.saveIssue(context.api,payload);else if(f.dataset.vehicleForm==='recommendation')r=await apiModule.saveRecommendation(context.api,payload);else r=await apiModule.saveMileage(context.api,payload);
      if(!r?.ok){window.KaretaToast?.error(r?.payload?.message||r?.payload?.error||'Не удалось сохранить');return;}
      closeModal();window.KaretaApiClient?.invalidate?.('client.cabinet');window.KaretaToast?.success(f.dataset.vehicleForm==='mileage'?'Пробег обновлён':'Сохранено');await load();
    };
    document.addEventListener('click',click);document.addEventListener('submit',submit);
    lifecycle.addCleanup?.(()=>{document.removeEventListener('click',click);document.removeEventListener('submit',submit);closeModal();});
  }
  window.KaretaVehiclePages=Object.freeze({renderers:Object.freeze({vehicle:renderVehicle}),mounts:Object.freeze({vehicle:mountVehicle})});
})();
