(() => {
  'use strict';

  if (window.__KARETA_ACCOUNT_WINDOW__) return;
  window.__KARETA_ACCOUNT_WINDOW__={version:'R188.5.5.6.79'};

  const api=window.KaretaClientCabinetApi;
  const uiIcons=window.KaretaUIIcons;
  if(!api) throw new Error('KaretaClientCabinetApi is required before account_window.js');

  const state={dialog:null,body:null,title:null,subtitle:null,baseHash:'',targetHash:'',kind:'',trigger:null,cleanup:[]};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v||0))+' ₸';
  const icon=name=>uiIcons?.icon?.(name)||'';
  const currentRoute=()=>document.querySelector('#k-page-outlet')?.getAttribute('data-current-route')||'';
  const clientPage=()=>Boolean(document.querySelector('[data-native-ui="client-account"]'));
  const cache={cabinet:null};

  const meta={
    profile:{title:'Профиль',subtitle:'Личные данные клиента',hash:'#/cabinet/data'},
    documents:{title:'Документы',subtitle:'Цифровой архив автомобилей',hash:'#/cabinet/documents'},
    tariff:{title:'Тариф',subtitle:'Лимиты и KARETA PRO',hash:'#/cabinet/tariff'},
    notifications:{title:'Уведомления',subtitle:'События и правила оповещений',hash:'#/notifications'},
    security:{title:'Безопасность',subtitle:'Сессия и доступ к аккаунту',hash:''},
    interface:{title:'Интерфейс',subtitle:'Вид меню и мобильные параметры',hash:'#/cabinet/settings'},
  };

  function ensureDialog(){
    if(state.dialog?.isConnected)return state.dialog;
    const d=document.createElement('dialog');
    d.className='k-account-window-r79';
    d.setAttribute('data-account-window-dialog','');
    d.innerHTML=`<div class="k-account-window-r79__surface"><header class="k-account-window-r79__head"><div><small data-account-window-subtitle>АККАУНТ</small><h2 data-account-window-title>Настройки</h2></div><button type="button" data-account-window-close aria-label="Закрыть">×</button></header><div class="k-account-window-r79__body" data-account-window-body></div></div>`;
    document.body.appendChild(d);
    state.dialog=d;state.body=d.querySelector('[data-account-window-body]');state.title=d.querySelector('[data-account-window-title]');state.subtitle=d.querySelector('[data-account-window-subtitle]');
    d.addEventListener('cancel',e=>{e.preventDefault();close();});
    d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-account-window-close]'))close();});
    return d;
  }
  function cleanup(){state.cleanup.splice(0).reverse().forEach(fn=>{try{fn?.();}catch(_e){}});}
  function listen(node,type,fn,opts){node?.addEventListener?.(type,fn,opts);state.cleanup.push(()=>node?.removeEventListener?.(type,fn,opts));}
  function setHash(hash){if(!hash)return;try{history.replaceState(history.state,'',hash);}catch(_e){}}
  function invalidate(){window.KaretaApiClient?.invalidate?.('client.cabinet');cache.cabinet=null;}
  async function cabinet(force=false){if(cache.cabinet&&!force)return cache.cabinet;const r=await api.get(force?{cacheTtlMs:0,force:true}:{});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Не удалось загрузить аккаунт');return cache.cabinet=r.payload?.data||{};}
  function loading(){state.body.innerHTML='<section class="k-account-window-r79__loading"><span></span><h3>Загрузка…</h3></section>';}
  function error(message){state.body.innerHTML=`<section class="k-account-window-r79__empty">${icon('warning')}<h3>Не удалось открыть раздел</h3><p>${esc(message||'Неизвестная ошибка')}</p><button class="k-btn k-btn-primary" type="button" data-account-retry>Повторить</button></section>`;state.body.querySelector('[data-account-retry]')?.addEventListener('click',()=>render(state.kind,true),{once:true});}
  function choice(name,value,label,current){return `<button type="button" class="k-account-choice ${String(value)===String(current)?'is-selected':''}" data-account-choice="${esc(name)}" data-value="${esc(value)}"><span>${esc(label)}</span></button>`;}
  function bindChoices(root){listen(root,'click',e=>{const b=e.target.closest('[data-account-choice]');if(!b)return;const name=b.dataset.accountChoice,value=b.dataset.value;const hidden=root.querySelector(`input[type="hidden"][name="${name}"]`);if(hidden)hidden.value=value;root.querySelectorAll(`[data-account-choice="${name}"]`).forEach(x=>x.classList.toggle('is-selected',x===b));});}

  function profileHtml(d){const u=d.user||{},avatar=String(u.avatarUrl||u.avatar_url||'');return `<form class="k-account-window-form" data-account-profile-form><div class="k-account-profile-editor"><div class="k-account-profile-avatar">${avatar?`<img src="${esc(avatar)}" alt="">`:`<span>${esc(String(u.name||'К').trim().slice(0,2).toUpperCase())}</span>`}</div><div><small>ПРОФИЛЬ КЛИЕНТА</small><h3>${esc(u.name||'Укажите имя')}</h3><p>${esc(u.phone||'')}</p></div></div><div class="k-account-field-grid"><label>Имя<input name="name" maxlength="120" value="${esc(u.name||'')}" required></label><label>Город<input name="city" maxlength="120" value="${esc(u.city||'')}"></label><label>Email<input name="email" type="email" maxlength="191" value="${esc(u.email||'')}"></label><label>Телефон<input value="${esc(u.phone||'')}" disabled><small>Телефон является логином.</small></label><label class="is-wide">Фото профиля — URL<input name="avatarUrl" type="url" value="${esc(avatar)}" placeholder="https://..."></label><label class="is-wide">О себе<textarea name="bio" maxlength="1000" rows="5">${esc(u.bio||'')}</textarea></label></div><footer><output data-account-status></output><button class="k-btn k-btn-primary" type="submit">Сохранить профиль</button></footer></form>`;}
  async function renderProfile(){const d=await cabinet();state.body.innerHTML=profileHtml(d);const form=state.body.querySelector('[data-account-profile-form]');listen(form,'submit',async e=>{e.preventDefault();const out=form.querySelector('[data-account-status]');out.textContent='Сохранение…';const r=await api.saveProfile(Object.fromEntries(new FormData(form).entries()));if(!r.ok){out.textContent=r.payload?.message||'Не удалось сохранить';window.KaretaToast?.error?.(out.textContent);return;}invalidate();out.textContent='Профиль сохранён';window.KaretaToast?.success?.('Профиль сохранён');try{await window.KaretaCabinetPages?.refreshClientCabinet?.();}catch(_e){}});}

  const docTypes={insurance:'Страховка',inspection:'Техосмотр',registration:'Регистрация',power_of_attorney:'Доверенность',service:'Сервисный документ',warranty:'Гарантия',other:'Другое'};
  function docState(doc){if(!doc.expires_at)return ['active','Без срока'];const days=Math.ceil((new Date(doc.expires_at+'T00:00:00')-new Date())/86400000);if(days<0)return ['expired','Просрочен'];if(days<=Number(doc.reminder_days||30))return ['soon',`Осталось ${days} дн.`];return ['active',`До ${doc.expires_at}`];}
  function documentsList(d){const names=Object.fromEntries((d.vehicles||[]).map(v=>[String(v.id),v.title||[v.brand,v.model].filter(Boolean).join(' ')]));const docs=d.documents||[];return `<div class="k-account-window-toolbar"><div><b>${docs.length} документов</b><small>Архив привязан к автомобилям.</small></div><button class="k-btn k-btn-primary" type="button" data-account-doc-add>${icon('plus')}<span>Добавить документ</span></button></div><div class="k-account-flat-list">${docs.map(doc=>{const [key,label]=docState(doc);return `<article class="k-account-flat-row is-${key}"><div><span>${esc(docTypes[doc.document_type]||'Документ')}</span><b>${esc(doc.title||'Документ')}</b><small>${esc(names[String(doc.vehicle_id)]||'Автомобиль')} · ${esc(doc.document_number||'Без номера')} · ${esc(label)}</small></div><div class="k-account-flat-actions">${doc.file_url?`<a class="k-btn k-btn-secondary" href="${esc(doc.file_url)}" target="_blank" rel="noopener">Файл</a>`:''}<button class="k-btn k-btn-danger" type="button" data-account-doc-delete="${esc(doc.id)}">Удалить</button></div></article>`;}).join('')||'<div class="k-account-window-r79__empty"><h3>Документов пока нет</h3><p>Добавьте страховку, техосмотр, гарантию или другой документ.</p></div>'}</div>`;}
  function documentEditor(d){const vehicles=d.vehicles||[];if(!vehicles.length)return `<section class="k-account-window-r79__empty"><h3>Сначала добавьте автомобиль</h3><p>Документы привязываются к конкретной машине.</p><a class="k-btn k-btn-primary" href="#/cabinet/garage">Открыть гараж</a></section>`;const vehicle=String(vehicles[0]?.id||'');return `<form class="k-account-window-form" data-account-doc-form><div class="k-account-window-toolbar"><button class="k-btn k-btn-secondary" type="button" data-account-doc-back>← Архив</button><b>Новый документ</b></div><section class="k-account-picker-block"><h3>Автомобиль</h3><input type="hidden" name="vehicleId" value="${esc(vehicle)}">${vehicles.map(v=>choice('vehicleId',v.id,v.title||[v.brand,v.model].filter(Boolean).join(' ')||'Автомобиль',vehicle)).join('')}</section><section class="k-account-picker-block"><h3>Тип документа</h3><input type="hidden" name="documentType" value="insurance">${Object.entries(docTypes).map(([k,l])=>choice('documentType',k,l,'insurance')).join('')}</section><div class="k-account-field-grid"><label>Название<input name="title" required placeholder="Полис ОГПО"></label><label>Номер<input name="documentNumber" placeholder="Номер документа"></label><label>Кем выдан<input name="issuerName"></label><label>Дата выдачи<input name="issuedAt" type="date"></label><label>Действует до<input name="expiresAt" type="date"></label></div><section class="k-account-picker-block"><h3>Напомнить заранее</h3><input type="hidden" name="reminderDays" value="30">${[[7,'7 дней'],[14,'14 дней'],[30,'30 дней'],[60,'60 дней'],[90,'90 дней']].map(([v,l])=>choice('reminderDays',v,l,30)).join('')}</section><div class="k-account-field-grid"><label class="is-wide">Ссылка на файл<input name="fileUrl" type="url" placeholder="https://..."></label><label class="is-wide">Примечание<textarea name="note" rows="4"></textarea></label></div><footer><output data-account-status></output><button class="k-btn k-btn-primary" type="submit">Сохранить документ</button></footer></form>`;}
  async function renderDocuments(force=false){const d=await cabinet(force);state.body.innerHTML=documentsList(d);const openEditor=()=>{state.body.innerHTML=documentEditor(d);const form=state.body.querySelector('[data-account-doc-form]');bindChoices(form);state.body.querySelector('[data-account-doc-back]')?.addEventListener('click',()=>renderDocuments(true),{once:true});listen(form,'submit',async e=>{e.preventDefault();const out=form.querySelector('[data-account-status]');out.textContent='Сохранение…';const r=await api.saveDocument(Object.fromEntries(new FormData(form).entries()));if(!r.ok){out.textContent=r.payload?.message||'Не удалось сохранить документ';window.KaretaToast?.error?.(out.textContent);return;}invalidate();window.KaretaToast?.success?.('Документ сохранён');renderDocuments(true);});};state.body.querySelector('[data-account-doc-add]')?.addEventListener('click',openEditor,{once:true});listen(state.body,'click',async e=>{const b=e.target.closest('[data-account-doc-delete]');if(!b)return;const r=await api.deleteDocument(b.dataset.accountDocDelete);if(!r.ok){window.KaretaToast?.error?.(r.payload?.message||'Не удалось удалить документ');return;}invalidate();window.KaretaToast?.success?.('Документ удалён');renderDocuments(true);});}

  function tariffMetric(title,used,limit,note=''){const u=Math.max(0,Number(used||0)),l=Math.max(0,Number(limit||0)),pct=l>0?Math.min(100,Math.round(u*100/l)):0;return `<div class="k-account-tariff-metric"><span><small>${esc(title)}</small><b>${u} / ${l||'∞'}</b></span><i><em style="width:${pct}%"></em></i>${note?`<small>${esc(note)}</small>`:''}</div>`;}
  async function renderTariff(){const role=String(window.KaretaRoleAccess?.currentRole?.()||'client').toLowerCase();const r=await window.KaretaApiClient.request('api/db.php?action=tariffs.getMine',{method:'GET',cacheTtlMs:0});if(!r.ok)throw new Error(r.payload?.message||r.payload?.error||'Не удалось загрузить тариф');const d=r.payload?.data||{},limits=d.limits||{},usage=d.usage||{},current=d.current||{},plans=Array.isArray(d.plans)?d.plans:[];const metrics=role==='master'?[tariffMetric('Принято сегодня',usage.acceptedRequestsToday,limits.acceptedRequestsPerDay),tariffMetric('Приёмы на дату',usage.activeIntakesOnDate,limits.activeIntakesPerDay),tariffMetric('Открытые ремонты',usage.openRepairs,limits.openRepairs)]:[tariffMetric('Активные заявки',usage.activeRequests,limits.activeRequests),tariffMetric('Автомобили',usage.vehicles,limits.vehicles)];state.body.innerHTML=`<section class="k-account-tariff-current"><header><div><small>ТЕКУЩИЙ ТАРИФ</small><h3>${esc(current.name||'—')}</h3><p>${esc(current.description||'')}</p></div><strong>${current.isPaid?(Number(current.monthlyPrice||0)>0?money(current.monthlyPrice)+'/мес.':'Платный тариф'):'Бесплатно'}</strong></header><div class="k-account-tariff-metrics">${metrics.join('')}</div></section><section class="k-account-plan-list">${plans.map(p=>`<article class="${String(p.code)===String(current.code)?'is-current':''}"><div><small>${p.isPaid?'KARETA PRO':'ОБЫЧНЫЙ'}</small><b>${esc(p.name||'Тариф')}</b><p>${esc(p.description||'')}</p></div><strong>${p.isPaid?(Number(p.monthlyPrice||0)>0?money(p.monthlyPrice)+'/мес.':'Платный'):'Бесплатно'}</strong></article>`).join('')}</section>`;}

  async function renderNotifications(){const d=await cabinet();const p=d.preferences||{};state.body.innerHTML=`<form class="k-account-window-form" data-account-notify-form><div class="k-account-setting-list"><label><span><b>Статусы заказов</b><small>Этапы, стоимость и готовность.</small></span><input type="checkbox" name="notify_orders" ${Number(p.notify_orders)!==0?'checked':''}><i></i></label><label><span><b>Напоминания по автомобилю</b><small>ТО, документы и сервисные сроки.</small></span><input type="checkbox" name="notify_service" ${Number(p.notify_service)!==0?'checked':''}><i></i></label><label><span><b>Акции</b><small>Персональные предложения KARETA.</small></span><input type="checkbox" name="notify_promotions" ${Number(p.notify_promotions)!==0?'checked':''}><i></i></label></div><footer><output data-account-status></output><button class="k-btn k-btn-primary" type="submit">Сохранить уведомления</button></footer></form><section class="k-account-events"><header><div><small>ПОСЛЕДНИЕ СОБЫТИЯ</small><h3>Центр уведомлений</h3></div><button class="k-btn k-btn-secondary" type="button" data-account-notify-refresh>Обновить</button></header><div data-account-notify-list><div class="k-account-window-r79__loading">Загрузка…</div></div></section>`;const form=state.body.querySelector('[data-account-notify-form]');listen(form,'submit',async e=>{e.preventDefault();const payload={notify_orders:form.notify_orders.checked,notify_service:form.notify_service.checked,notify_promotions:form.notify_promotions.checked};const out=form.querySelector('[data-account-status]');out.textContent='Сохранение…';const r=await api.savePreferences(payload);if(!r.ok){out.textContent=r.payload?.message||'Ошибка сохранения';return;}invalidate();out.textContent='Сохранено';window.KaretaToast?.success?.('Уведомления сохранены');});const list=state.body.querySelector('[data-account-notify-list]');const loadEvents=async()=>{const r=await window.KaretaApiClient.request('api/domain.php?action=notifications.list',{cacheTtlMs:0,force:true,dedupe:false});const rows=Array.isArray(r.payload?.notifications)?r.payload.notifications:[];list.innerHTML=rows.slice(0,12).map(n=>`<article class="k-account-event-row ${!(n.isRead??Number(n.is_read||0)===1)?'is-unread':''}"><div><b>${esc(n.title||'Уведомление')}</b><small>${esc(n.body||'')}</small></div>${(n.actionUrl||n.action_url)?`<a class="k-btn k-btn-secondary" href="${esc(n.actionUrl||n.action_url)}">Открыть</a>`:''}</article>`).join('')||'<p>Новых событий нет.</p>';};state.body.querySelector('[data-account-notify-refresh]')?.addEventListener('click',loadEvents);loadEvents();}

  async function renderSecurity(){const d=await cabinet();const id=window.KaretaIdentity?.snapshot?.()||{};const account=id.account||{},session=id.session||{},context=id.context||{};state.body.innerHTML=`<section class="k-account-security"><div class="k-account-security-status">${icon(id.authenticated?'lock':'warning')}<div><small>СОСТОЯНИЕ ДОСТУПА</small><h3>${id.authenticated?'Сессия подтверждена':'Требуется проверка сессии'}</h3><p>${esc(d.user?.phone||account.phone||'Телефон не определён')}</p></div></div><div class="k-account-security-rows"><span><small>Контекст</small><b>${esc(context.key||context.contextKey||id.compatibilityRole||'client')}</b></span><span><small>Режим Identity</small><b>${esc(id.mode||'—')}</b></span><span><small>Сессия</small><b>${esc(session.id||session.sessionId||'Активная')}</b></span><span><small>Статус аккаунта</small><b>${esc(account.status||'active')}</b></span></div><div class="k-account-security-actions"><button class="k-btn k-btn-primary" type="button" data-account-session-check>${icon('refresh')}<span>Перепроверить сессию</span></button><a class="k-btn k-btn-secondary" href="#/privacy">Конфиденциальность</a>${window.App?.logout?'<button class="k-btn k-btn-danger" type="button" data-account-logout>Выйти из аккаунта</button>':''}</div><output data-account-security-status></output></section>`;state.body.querySelector('[data-account-session-check]')?.addEventListener('click',async()=>{const out=state.body.querySelector('[data-account-security-status]');out.textContent='Проверка…';try{await window.KaretaIdentity?.load?.({force:true,allowLegacyBridge:true,legacyUser:window.KaretaNext?.state?.user});out.textContent='Сессия подтверждена';window.KaretaToast?.success?.('Сессия проверена');renderSecurity();}catch(e){out.textContent=e.message||'Не удалось проверить сессию';window.KaretaToast?.error?.(out.textContent);}});state.body.querySelector('[data-account-logout]')?.addEventListener('click',()=>{close({restore:false});window.App?.logout?.();},{once:true});}

  function layoutPicker(){return `<section class="k-account-picker-block k-account-picker-block--fixed"><h3>Дополнительное меню «Ещё»</h3><input type="hidden" name="more_menu_layout" value="honeycomb"><div class="k-account-more-fixed"><span aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><b></b></span><div><b>Соты KARETA</b><small>Единое окно V1.2: профиль, 6 быстрых действий и поддержка.</small></div></div></section>`;}

  async function renderInterface(){const d=await cabinet(),p=d.preferences||{};await window.KaretaSmartActionHub?.loadPreference?.();const current=window.KaretaSmartActionHub?.snapshot?.().layout||p.more_menu_layout||'honeycomb';state.body.innerHTML=`<form class="k-account-window-form" data-account-interface-form><div class="k-account-setting-list"><label><span><b>Компактный мобильный режим</b><small>Меньше пояснений и вертикальных отступов.</small></span><input type="checkbox" name="compact_mobile" ${Number(p.compact_mobile)!==0?'checked':''}><i></i></label></div>${layoutPicker(current)}<footer><output data-account-status></output><button class="k-btn k-btn-primary" type="submit">Сохранить интерфейс</button></footer></form><div data-messaging-settings-host></div>`;const form=state.body.querySelector('[data-account-interface-form]');bindChoices(form);listen(form,'submit',async e=>{e.preventDefault();const payload={compact_mobile:form.compact_mobile.checked,more_menu_layout:form.more_menu_layout.value};const out=form.querySelector('[data-account-status]');out.textContent='Сохранение…';const r=await api.savePreferences(payload);if(!r.ok){out.textContent=r.payload?.message||'Ошибка сохранения';return;}await window.KaretaSmartActionHub?.savePreference?.(payload.more_menu_layout);document.documentElement.classList.toggle('k-compact-mobile',payload.compact_mobile);invalidate();out.textContent='Интерфейс сохранён';window.KaretaToast?.success?.('Интерфейс сохранён');});window.KaretaMessagingSettings?.mount?.(state.body.querySelector('[data-messaging-settings-host]'));}

  async function render(kind,force=false){cleanup();state.kind=kind;loading();try{if(kind==='profile')await renderProfile(force);else if(kind==='documents')await renderDocuments(force);else if(kind==='tariff')await renderTariff();else if(kind==='notifications')await renderNotifications();else if(kind==='security')await renderSecurity();else if(kind==='interface')await renderInterface();else throw new Error('Раздел аккаунта не найден');}catch(e){console.error('[KARETA account window]',e);error(e?.message||String(e));}}
  function open(kind,{trigger=null}={}){const m=meta[kind];if(!m)return false;const d=ensureDialog();if(!state.baseHash)state.baseHash=String(location.hash||'#/cabinet');state.trigger=trigger||state.trigger;state.targetHash=m.hash;state.title.textContent=m.title;state.subtitle.textContent=m.subtitle;if(m.hash)setHash(m.hash);if(!d.open)d.showModal();document.documentElement.classList.add('k-account-window-open');render(kind);try{window.dispatchEvent(new CustomEvent('kareta:account-window-open',{detail:{kind,baseHash:state.baseHash}}));}catch(_e){}return true;}
  function close({restore=true}={}){if(!state.dialog)return false;cleanup();if(state.dialog.open)try{state.dialog.close();}catch(_e){}document.documentElement.classList.remove('k-account-window-open');const base=state.baseHash;state.baseHash='';state.kind='';state.targetHash='';if(restore&&base)setHash(base);try{state.trigger?.focus?.({preventScroll:true});}catch(_e){}state.trigger=null;return true;}
  function kindFromLink(link){const explicit=link.dataset.accountWindow;if(explicit)return explicit;const href=String(link.getAttribute('href')||'');return {'#/cabinet/data':'profile','#/cabinet/documents':'documents','#/cabinet/tariff':'tariff','#/cabinet/settings':'interface','#/notifications':'notifications'}[href]||'';}
  function onClick(e){if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const link=e.target.closest('[data-account-window],a[href="#/cabinet/data"],a[href="#/cabinet/documents"],a[href="#/cabinet/tariff"],a[href="#/cabinet/settings"],a[href="#/notifications"]');if(!link||!clientPage()||currentRoute()!=='cabinet')return;const kind=kindFromLink(link);if(!kind)return;e.preventDefault();e.stopImmediatePropagation();open(kind,{trigger:link});}

  function openPending(){
    let kind='';try{kind=sessionStorage.getItem('kareta.account.window.pending')||'';}catch(_e){}
    if(!kind||currentRoute()!=='cabinet'||!clientPage())return;
    try{sessionStorage.removeItem('kareta.account.window.pending');}catch(_e){}
    setTimeout(()=>{if(clientPage()&&currentRoute()==='cabinet')open(kind);},0);
  }
  document.addEventListener('click',onClick,true);
  window.addEventListener('hashchange',()=>{if(state.dialog?.open&&state.targetHash&&String(location.hash)!==state.targetHash)close({restore:false});setTimeout(openPending,0);});
  window.addEventListener('kareta:routechange',()=>setTimeout(openPending,0));
  setTimeout(openPending,0);
  window.KaretaAccountWindow=Object.freeze({open,close,isOpen:()=>Boolean(state.dialog?.open),snapshot:()=>({open:Boolean(state.dialog?.open),kind:state.kind,baseHash:state.baseHash,targetHash:state.targetHash})});
})();
