(() => {
  'use strict';
  const engine=window.KaretaDashboardEngine;if(!engine)throw new Error('KaretaDashboardEngine is required');
  const esc=v=>window.KaretaUIKit?.esc?.(v)??String(v??'');
  const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v||0))+' ₸';
  const orderList=(items,empty)=>`<div class="k-dashboard-alert-list">${(Array.isArray(items)?items:[]).slice(0,6).map(x=>`<a href="#/orders/item/${encodeURIComponent(x.id)}"><b>${esc(x.vehicleTitle||'Автомобиль')}</b><small>${esc(x.serviceNames||x.clientName||'Заказ')}</small></a>`).join('')||`<p class="k-empty">${esc(empty)}</p>`}</div>`;
  engine.register({key:'sto.metrics',title:'Показатели СТО',subtitle:'Текущая загрузка',icon:'dashboard',contextKinds:['organization'],span:4,render:data=>{const m=data.metrics||{};return `<div class="k-dashboard-kpis">${[['Машин сегодня',m.todayOrders],['Постов занято',`${m.occupied||0}/${m.bays||0}`],['Мастеров',m.masters],['Выручка',money(m.monthRevenue)],['Завершено',m.completedMonth],['Средний чек',money(m.avgTicket)]].map(([a,b])=>`<div class="k-dashboard-kpi"><b>${esc(b||0)}</b><span>${esc(a)}</span></div>`).join('')}</div>`;}});
  engine.register({key:'sto.queue',title:'Очередь',subtitle:'Ближайшие автомобили',icon:'orders',contextKinds:['organization'],span:2,href:'#/orders',render:data=>orderList(data.queue,'Очередь пуста')});
  engine.register({key:'sto.team',title:'Команда',subtitle:'Загрузка мастеров',icon:'masters',contextKinds:['organization'],span:2,href:'#/masters',render:data=>{const list=Array.isArray(data.masters)?data.masters:[];return `<div class="k-dashboard-list">${list.slice(0,6).map(x=>`<a href="#/masters/profile/master/${encodeURIComponent(x.id)}"><span>${esc(x.name||'Мастер')}</span><small>${esc(x.activeOrders||0)} в работе · ${esc(x.kpi||0)}%</small></a>`).join('')||'<p class="k-empty">Команда не настроена</p>'}</div>`;}});
  engine.register({key:'sto.overdue',title:'Просроченные',subtitle:'Требуют решения',icon:'history',contextKinds:['organization'],span:1,href:'#/orders',render:data=>orderList(data.alerts?.overdue,'Просроченных заказов нет')});
  engine.register({key:'sto.approvals',title:'Согласование',subtitle:'Ответ клиента или СТО',icon:'check',contextKinds:['organization'],span:1,href:'#/workflow',render:data=>orderList(data.alerts?.waitingApproval,'Нет ожидающих согласования')});
  engine.register({key:'sto.parts',title:'Ожидают запчасти',subtitle:'Проверьте снабжение',icon:'parts',contextKinds:['organization'],span:1,href:'#/parts',render:data=>orderList(data.alerts?.waitingParts,'Ожиданий запчастей нет')});
  engine.register({key:'sto.calendar',title:'Календарь',subtitle:'Ближайшие записи',icon:'calendar',contextKinds:['organization'],span:1,href:'#/calendar',render:data=>{const list=Array.isArray(data.calendar)?data.calendar:[];return `<div class="k-dashboard-list">${list.slice(0,6).map(x=>`<a href="${x.orderId?`#/orders/item/${encodeURIComponent(x.orderId)}`:'#/calendar'}"><span>${esc(x.title||x.vehicleTitle||'Запись')}</span><small>${esc(x.startsAt||x.date||'')}</small></a>`).join('')||'<p class="k-empty">Ближайших записей нет</p>'}</div>`;}});
  engine.register({key:'admin.metrics',title:'Платформа',subtitle:'Ключевые показатели',icon:'monitor',contextKinds:['admin'],span:4,render:data=>{const c=data.counts||{};return `<div class="k-dashboard-kpis">${[['Аккаунты',c.accounts],['Люди',c.persons],['Профили',c.person_profiles],['Контексты',c.contexts],['Организации',c.organizations],['Активные сессии',c.activeSessions],['Открытая модерация',c.openModeration]].map(([a,b])=>`<div class="k-dashboard-kpi"><b>${esc(b||0)}</b><span>${esc(a)}</span></div>`).join('')}</div>`;}});
  engine.register({key:'admin.audit',title:'Последние действия',subtitle:'Audit trail',icon:'history',contextKinds:['admin'],span:4,render:data=>{const rows=Array.isArray(data.audit)?data.audit:[];return `<div class="k-dashboard-list">${rows.slice(0,10).map(a=>`<div><span>${esc(a.actionKey)} · ${esc(a.targetType)} #${esc(a.targetId)}</span><small>${esc(a.createdAt)}</small></div>`).join('')||'<p class="k-empty">Аудит пуст</p>'}</div>`;}});
})();
