(() => {
  'use strict';
  const scriptSource=document.currentScript?.src||'';
  const dependencies=['KaretaRouteRegistry','KaretaDynamicNavigation'];
  if(window.KaretaRuntimeDependencies?.missing?.(dependencies).length){window.KaretaRuntimeDependencies.deferScript('shell_menu',dependencies,scriptSource);return;}
  if(window.__KARETA_SHELL_MENU_MODULE__){window.__KARETA_SHELL_MENU_MODULE__.duplicateLoads+=1;return;}
  window.__KARETA_SHELL_MENU_MODULE__={duplicateLoads:0};
  const registry=window.KaretaRouteRegistry;
  const navigation=window.KaretaDynamicNavigation;
  if(!registry||!navigation)return;
  const state={bound:false,open:false};
  const labels={main:'ОСНОВНОЕ',work:'РАБОТА И ЗАЯВКИ',commerce:'ТОРГОВЛЯ И СКЛАД',management:'УПРАВЛЕНИЕ',communication:'КОММУНИКАЦИИ',account:'АККАУНТ',social:'СООБЩЕСТВО',system:'СИСТЕМА',info:'ИНФОРМАЦИЯ И ПРАВИЛА'};
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function routeItem(key){const route=registry.get(key);const iconName=window.KaretaUIIcons?.routeName?.(key)||'warning';const iconHtml=window.KaretaUIIcons?.routeSvg?.(key)||window.KaretaUIIcons?.svg?.('warning')||'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M12 7v6M12 17h.01"></path></svg>';return `<a class="k-menu-link" href="${esc(route.path)}" data-route-link="${esc(key)}" data-route-key="${esc(key)}"><span class="k-menu-link__icon" data-icon="${esc(iconName)}" aria-hidden="true">${iconHtml}</span><div><b>${esc(route.label)}</b><small>${esc(route.description||'Открыть раздел')}</small></div><i aria-hidden="true">›</i></a>`;}
  function sectionsWithSettings(identity){let sections=navigation.menuSections().map(section=>({id:section.id,keys:[...section.keys]}));const legacyUser=window.KaretaNext?.state?.user||window.KaretaAppState?.user||null;const signedIn=Boolean(identity.authenticated||legacyUser?.id||legacyUser?.phone);const desktopPrimary=new Set(window.KaretaNavigationCore?.desktopItems?.()||[]);const desktopMode=window.matchMedia?.('(min-width: 861px)')?.matches===true;if(desktopMode&&desktopPrimary.size){sections=sections.map(section=>({...section,keys:section.keys.filter(key=>!desktopPrimary.has(key))})).filter(section=>section.keys.length);}const alreadyPresent=sections.some(section=>section.keys.includes('cabinetSettings'));if(signedIn&&registry.has('cabinetSettings')&&!alreadyPresent&&!desktopPrimary.has('cabinetSettings')){let account=sections.find(section=>section.id==='account');if(!account){account={id:'account',keys:[]};sections.push(account);}account.keys.push('cabinetSettings');}return sections;}
  function render(){const content=document.getElementById('k-menu-content');if(!content)return false;const identity=window.KaretaIdentity?.snapshot?.()||{};const contextLabel=identity.context?.label||'Гостевой режим';const sections=sectionsWithSettings(identity);const contextHost=document.getElementById('k-context-switcher');content.innerHTML=sections.map(section=>`<section class="k-menu-section"><div class="k-menu-section-title"><span>${esc(labels[section.id]||section.id.toUpperCase())}</span><small>${esc(contextLabel)}</small></div><div class="k-menu-links">${section.keys.map(routeItem).join('')}</div></section>`).join('');if(contextHost)content.prepend(contextHost);window.KaretaContextManager?.render();return true;}
  function setOpen(next){const drawer=document.getElementById('k-menu-drawer');const backdrop=document.getElementById('k-menu-backdrop');const toggle=document.getElementById('k-menu-toggle');if(!drawer||!backdrop||!toggle)return false;const wasOpen=state.open;state.open=Boolean(next);drawer.classList.toggle('is-open',state.open);drawer.setAttribute('aria-hidden',state.open?'false':'true');toggle.setAttribute('aria-expanded',state.open?'true':'false');toggle.setAttribute('aria-label',state.open?'Закрыть меню':'Открыть меню');backdrop.hidden=!state.open;requestAnimationFrame(()=>backdrop.classList.toggle('is-open',state.open));document.documentElement.classList.toggle('k-menu-open',state.open);if(state.open)document.getElementById('k-menu-close')?.focus({preventScroll:true});else if(wasOpen)toggle.focus({preventScroll:true});return true;}
  const close=()=>setOpen(false);const open=()=>{window.KaretaSmartActionHub?.close?.();render();return setOpen(true)};const closeDetail=()=>{const route=document.querySelector('#k-page-outlet')?.getAttribute('data-current-route')||'';const fallback=route==='serviceDetail'?'#/services':(route==='providerDetail'||route==='providerBooking')?'#/masters':route==='productDetail'?'#/parts':'#/home';if(history.length>1){history.back();return true;}location.hash=fallback;return true;};const toggle=()=>document.documentElement.classList.contains('k-detail-view')?closeDetail():(state.open?close():open());
  function bind(){if(state.bound)return true;const toggleButton=document.getElementById('k-menu-toggle');const closeButton=document.getElementById('k-menu-close');const backdrop=document.getElementById('k-menu-backdrop');if(!toggleButton||!backdrop)return false;toggleButton.addEventListener('click',toggle);closeButton?.addEventListener('click',close);backdrop.addEventListener('click',close);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.open)close()});document.addEventListener('click',event=>{if(state.open&&event.target.closest('#k-menu-drawer [data-route-link]'))close()});['kareta:identity-ready','kareta:capabilities-changed','kareta:context-changed','kareta:navigation-changed'].forEach(name=>window.addEventListener(name,render));state.bound=true;render();return true;}
  window.addEventListener('resize',()=>{if(state.open)render();},{passive:true});
  window.KaretaShellMenu=Object.freeze({bind,open,close,toggle,render,getState:()=>({...state})});
})();
