'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const catalog=JSON.parse(read('storage/catalog/services.json')).services;
const snapshot={status:'ready',catalog,offers:[],context:{role:'master',ownerUserId:1,ownerEntityId:'m1'},metrics:{}};
const window={KaretaPageUI:{escHtml:value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pageShell:(_ctx,_title,_lead,body)=>body},KaretaServiceOffersState:{getSnapshot:()=>snapshot},KaretaServiceOffersApi:{},KaretaRoleAccess:{currentRole:()=> 'master'}};
const context={window,console,Intl};vm.runInNewContext(read('js/next/ui_icons.js'),context);vm.runInNewContext(read('js/next/pages/service_management.js'),context);
const html=window.KaretaServiceManagementPages.renderServiceManagement({});
assert.ok(html.includes('data-master-setup-services')&&html.includes('data-master-setup-equipment'));
assert.ok(html.indexOf('k-master-setup-launch')<html.indexOf('<details class="k-master-service-editor">'));
assert.ok(!html.includes('<details class="k-master-service-editor" open'),'long price list is open by default');
assert.equal((html.match(/data-master-service-row=/g)||[]).length,catalog.length,'canonical service rows changed');
assert.equal((html.match(/class="k-service-themed-icon"/g)||[]).length,catalog.length,'service artwork not unified');
assert.ok(!html.includes('#k-mobile-nav')&&!html.includes('id="k-shell-header"'));
const registry=read('inc/asset_registry.php');const stanza=registry.slice(registry.indexOf("'serviceManagement' =>"),registry.indexOf("'profile' =>",registry.indexOf("'serviceManagement' =>")));
assert.ok(stanza.includes("'lazy' => true"));
assert.ok(stanza.indexOf('js/next/services/master_setup_picker.js')<stanza.indexOf('js/next/pages/service_management.js'));
assert.ok(stanza.includes("'KaretaMasterSetupPicker'"));
const assetVersion=/const KARETA_ASSET_VERSION = '([^']+)'/.exec(read('inc/asset_version.php'))?.[1]||'';
const swRelease=/const RELEASE = '([^']+)'/.exec(read('sw.js'))?.[1]||'';
const endpoint=read('api/master_onboarding.php');
assert.ok(endpoint.indexOf('master_context_required')<endpoint.indexOf("require_once __DIR__.'/master_equipment_profile.php'"));
const server=read('api/master_equipment_profile.php');
assert.ok(server.includes("'equipment_context_changed'")&&server.includes('FOR UPDATE')&&server.includes("'equipment_revision_conflict'"));
assert.ok(server.includes("'$.masterEquipment'"),'profile equipment storage missing');
assert.ok(!server.includes('CREATE TABLE')&&!server.includes('$_COOKIE'),'parallel schema or identity introduced');
console.log(JSON.stringify({status:'PASS',service_rows:catalog.length,canonical_route:'#/services/manage',lazy_loader:true,menu_edits:false,asset_version:assetVersion,sw_release:swRelease,release_parity:assetVersion===swRelease,release_parity_asserted:false,php_execution:'NOT_RUN'}));
