const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const must=(ok,msg)=>{if(!ok)throw new Error(msg)};
const js=read('js/next/pages/request.js');
const css=read('css/next/request_5_steps.css');
const ver=read('inc/asset_version.php');
const sw=read('sw.js');
must(js.includes('k-request-progress-shell')&&js.includes('Шаг ${current+1} из 5'),'progress shell/caption missing');
must(js.includes('data-request-vehicle-quicklist')&&js.includes('renderVehicleQuicklist'),'garage quick list missing');
must(js.includes('k-request-field-group__label')&&js.includes('Формат обслуживания')&&js.includes('Дата')&&js.includes('Время'),'schedule grouping missing');
must(js.includes("nextBtn.textContent=step===3?'Проверить заявку':'Продолжить'"),'step-aware CTA missing');
must(js.includes("requestAnimationFrame(()=>title?.focus?.({preventScroll:true}))"),'step title focus missing');
must(css.includes('R188.5.5.6.84.59')&&css.includes('.k-request-main-steps::before')&&css.includes('.k-request-review-line>i'),'84.59 interface CSS missing');
must(css.includes('@media(min-width:1024px)')&&css.includes('max-width:680px'),'desktop request width missing');
const va=(ver.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1];
const vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
const rev=Number((va||'').split('.').pop()||0);
must(rev>=59&&vs===va,'version mismatch');
console.log('R188.5.5.6.84.59 request interface polish regression: OK');
