'use strict';
const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8');
const must=(ok,msg)=>{if(!ok){console.error('FAIL:',msg);process.exit(1);}};
const js=read('js/next/pages/work_order.js');
const css=read('css/next/client_work_order_v2.css');
const reg=read('inc/asset_registry.php');
const av=read('inc/asset_version.php').match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)?.[1]||'';
const sw=read('sw.js').match(/const RELEASE\s*=\s*'([^']+)'/)?.[1]||'';
must(reg.includes("css/next/client_work_order_v2.css"),'client work-order CSS not registered');
must(js.includes('renderClientDetail')&&js.includes('clientMilestoneProgress'),'client work-order renderer missing');
must(js.includes("role==='client'?renderClientDetail"),'client/professional render split missing');
must(js.includes('Смета для клиента')&&js.includes('Сумма обновляется только после вашего согласования'),'client-safe estimate missing');
must(js.includes('clientReservationRows')&&!js.includes('role===\'client\'&&professional'),'client parts projection missing');
must(js.includes("sessionStorage.setItem('kareta.chat.open'"),'order chat deep-link state missing');
must(css.includes('.k-client-work-progress')&&css.includes('.k-client-work-overview')&&css.includes('.k-client-work-executor'),'client work-order visual primitives missing');
must(css.includes('--k-client-active-bottom-space')&&css.includes('.k-client-work-tabs button.is-active'),'mobile nav clearance/active state missing');
must(css.includes('button span{display:inline!important}'),'mobile tab labels must remain visible');
must(js.includes('clientNextStep')&&js.includes('clientHandoverDocuments')&&js.includes('warrantyStatusLabel'),'client progress/documents/warranty polish missing');
must(js.includes('effectiveWorkOrderRole'),'role fallback missing');
const rev=Number(av.split('.').pop()||0);must(rev>=64&&sw===av,'84.64+ version mismatch');
console.log('R188.5.5.6.84.64 client work-order V2: OK');
