'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(){
  const requests=[],loads=[],nav={innerHTML:''},body={innerHTML:''};
  const snapshot={status:'ready',products:[],categories:[],cart:[]};
  const sandbox={window:{KaretaShopState:{getSnapshot:()=>snapshot,load:p=>{loads.push(p);return Promise.resolve();}},KaretaApiClient:{getUsedMarket:(params,options)=>new Promise((resolve,reject)=>requests.push({params,options,resolve,reject}))},KaretaCatalogCards:{}},location:{hash:'#/parts/used'},document:{documentElement:{lang:'ru'},querySelector:s=>({'[data-shop-navigator]':nav,'[data-market-list-body]':body,'[data-parts-market-list-dialog]':{open:true}}[s]||null),querySelectorAll:()=>[]},URLSearchParams,Intl};
  const source=fs.readFileSync('js/next/pages/parts.js','utf8').replace('window.KaretaPartsPages=Object.freeze({renderParts,mountParts});',`window.KaretaPartsPages={loadUsed,refreshCatalog,usedPagingControls,renderSnapshot,setState:v=>{state={search:'',type:'all',category:'',city:'',sort:'newest',...v};},setMode:v=>{marketMode=v;},setContext:v=>{contextRef=v;},result:()=>({rows:usedRows,loading:usedLoading,error:usedError,hasMore:usedHasMore,nextOffset:usedNextOffset})};`);
  vm.runInNewContext(source,sandbox);
  return {page:sandbox.window.KaretaPartsPages,requests,loads,nav,body,sandbox};
}
const payload=(items,hasMore=false,nextOffset=null)=>({ok:true,payload:{items,hasMore,nextOffset,matchedTotal:3}});
const ids=page=>Array.from(page.result().rows,x=>x.id);
(async()=>{
  const f=fixture(),p=f.page;
  p.setState({search:'starter',type:'sale',category:'electrical',city:'Өскемен',sort:'price_asc'});
  const first=p.loadUsed();
  assert.deepEqual(JSON.parse(JSON.stringify(f.requests[0].params)),{surface:'used',search:'starter',category:'electrical',city:'Өскемен',sort:'price_asc',type:'sale',favorites:'0',limit:50,offset:0});
  f.requests[0].resolve(payload([{id:'a',title:'Server match'},{id:'b'}],true,50));await first;
  assert.deepEqual(ids(p),['a','b'],'server match outside initial page is retained without a second text filter');
  assert.match(p.usedPagingControls(),/data-used-more/);
  const more=p.loadUsed(true);await p.loadUsed(true);
  assert.equal(f.requests.length,2,'double click creates only one page request');
  assert.equal(f.requests[1].params.offset,50);
  f.requests[1].resolve(payload([{id:'b',title:'Updated b'},{id:'c'}]));await more;
  assert.deepEqual(ids(p),['a','b','c']);assert.equal(p.result().rows[1].title,'Updated b');
  assert.doesNotMatch(p.usedPagingControls(),/data-used-more/);await p.loadUsed(true);assert.equal(f.requests.length,2);
  p.setState({search:'old'});const old=p.loadUsed();
  p.setState({search:'new'});const current=p.loadUsed();
  f.requests[3].resolve(payload([{id:'new'}]));await current;
  f.requests[2].resolve(payload([{id:'old'}]));await old;
  assert.deepEqual(ids(p),['new'],'late old response cannot replace new results');
  p.setState({search:'old-error'});const oldError=p.loadUsed();
  p.setState({search:'current'});const newer=p.loadUsed();
  f.requests[4].reject(new Error('stale error'));await oldError;
  assert.equal(p.result().loading,true,'stale rejection cannot clear current loading');assert.equal(p.result().error,'');
  f.requests[5].resolve(payload([{id:'current'}]));await newer;
  const failed=p.loadUsed();f.requests[6].reject(new Error('<offline>'));await failed;
  assert.match(f.nav.innerHTML,/&lt;offline&gt;/);assert.match(f.body.innerHTML,/data-used-retry/);
  assert.doesNotMatch(f.nav.innerHTML,/Пока нет|пока ничего нет/,'network failure is not an empty catalog');
  assert.doesNotMatch(f.body.innerHTML,/ничего не найдено/,'network failure is not an empty search');
  const retry=p.loadUsed();assert.equal(f.requests[7].params.offset,0);f.requests[7].resolve(payload([{id:'retry'}],true,50));await retry;
  const failedMore=p.loadUsed(true);f.requests[8].reject(new Error('page failed'));await failedMore;
  assert.deepEqual(ids(p),['retry']);const retryMore=p.loadUsed(true);assert.equal(f.requests[9].params.offset,50);
  f.requests[9].resolve(payload([{id:'next'}]));await retryMore;assert.deepEqual(ids(p),['retry','next']);
  const ctx={lifecycle:{signal:{aborted:false}}};p.setContext(ctx);const left=p.loadUsed();p.setContext({});
  f.requests[10].resolve(payload([{id:'disposed'}]));await left;assert.deepEqual(ids(p),[],'disposed page cannot receive a late result');
  p.setContext(ctx);const aborted=p.loadUsed();ctx.lifecycle.signal.aborted=true;
  f.requests[11].resolve(payload([{id:'aborted'}]));await aborted;assert.deepEqual(ids(p),[]);
  p.setContext(null);p.setMode('favorites');const favorites=p.loadUsed();assert.equal(f.requests[12].params.favorites,'1');f.requests[12].resolve(payload([]));await favorites;
  p.setState({search:'disc',category:'brakes'});f.sandbox.location.hash='#/parts';await p.refreshCatalog();
  assert.deepEqual(JSON.parse(JSON.stringify(f.loads[0])),{search:'disc',category:'brakes',limit:100});
  console.log('PARTS_PAGINATION: PASS (filters, append/dedup, races, retry, disposal, favorites, new-shop search; VM, no browser)');
})().catch(e=>{console.error(e);process.exitCode=1;});
