const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const expect=(ok,msg)=>{if(!ok){console.error('FAIL:',msg);process.exitCode=1;}};
const config=read('config.php');
const bootstrap=read('api/bootstrap.php');
const diag=read('api/runtime_diagnostics.php');
const manifest=read('api/migration_manifest.php');
const logger=read('js/next/runtime_logger.js');
const asset=read('inc/asset_version.php');
const migrations=fs.readdirSync(path.join(root,'api/migrations')).filter(f=>/^\d+_.*\.php$/.test(f));
const latest=Math.max(...migrations.map(f=>Number(/^([0-9]+)_/.exec(f)[1])));
const declared=Number((/KARETA_DB_VERSION',\s*(\d+)/.exec(config)||[])[1]||0);
expect(latest===129,`latest migration must be 129, got ${latest}`);
expect(manifest.includes("'version' => 129"),'migration manifest version 129 required');
expect(manifest.includes("129 => ['file' => '129_client_first_entry_state.php'"),'migration 129 must be pinned in manifest');
expect(declared===latest,`declared DB version ${declared} must match migration ${latest}`);
expect(/^188\.5\.5\.6\.84\.\d+$/.test((/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/.exec(asset)||[])[1]||''),'short current asset version required');
expect(bootstrap.includes('function kareta_schema_bootstrap_required(PDO $pdo): bool'),'schema fast path missing');
expect(bootstrap.includes("COUNT(*) AS c, COALESCE(MIN(`version`),0) AS min_v"),'migration history aggregate guard missing');
expect(bootstrap.includes("$GLOBALS['KARETA_SCHEMA_BOOTSTRAP_LOCK_HELD'] = true"),'outer bootstrap lock marker missing');
expect(bootstrap.includes("if (!$bootstrapLockHeld)"),'nested migration lock bypass missing');
expect(bootstrap.includes("kareta_db_set_failure_context('migration.history.validate')"),'migration history diagnostic stage missing');
expect(bootstrap.includes("kareta_db_set_failure_context('migration.meta.ensure')"),'migration meta diagnostic stage missing');
expect(bootstrap.includes("$manifestPath = KARETA_API_ROOT . '/migration_manifest.php'"),'manifest-based migration discovery missing');
expect(bootstrap.includes("MIGRATION_STALE_FILES"),'stale migration quarantine logging missing');
expect(diag.includes("'failedMigrationFile'"),'public safe failedMigrationFile missing');
expect(logger.includes("configurationSource"),'runtime logger must show public configuration source');
expect(logger.includes("[not exposed]"),'runtime logger must not render hidden diagnostic fields as false values');
if(!process.exitCode)console.log('R188.5.5.6.84.24 DB runtime recovery test OK');
