'use strict';
const assert=require('assert');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const migration=read('api/migrations/098_role_workspaces_completion.php');
assert.strictEqual(crypto.createHash('sha256').update(migration).digest('hex'),'02a2d591dbc6eb68733177da1b79283f0c0e2b44f66d11ae37f26dd7725c3a0d');
const bootstrap=read('api/bootstrap.php');
const a=bootstrap.indexOf('function kareta_prepare_migration_98_dashboard_layout_compatibility');
const b=bootstrap.indexOf('\nfunction kareta_migrate',a);
const helper=bootstrap.slice(a,b);
for(const needle of ['DROP FOREIGN KEY','dashboard_layout_preferences_recovery','migration_98_duplicate_scope','DROP INDEX `uq_dashboard_layout`','ADD CONSTRAINT','kareta_db_set_failure_context']) assert(helper.includes(needle),needle);
assert(helper.indexOf('DROP FOREIGN KEY')<helper.indexOf('DROP INDEX `uq_dashboard_layout`'));
const diagnostics=read('api/runtime_diagnostics.php');
for(const needle of ['failureStage','failedMigrationVersion','diagnosticCode']) assert(diagnostics.includes(needle),needle);
const release='20260806-r188555-runtime-dependency-bootstrap-r188556-security-hardening-r1885561-atomic-runtime-bootstrap-r1885562-identity-db-recovery-r1885563-migration98-onboarding-recovery-r1885564-fk-detach-schema-recovery-r1885565-serialized-schema-index-recovery';
for(const file of ['inc/asset_version.php','sw.js','js/next/core/realtime_client.js']) assert(read(file).includes(release),file);
assert(read('index.php').includes('r1885565-serialized-schema-index-recovery'));
console.log('R188.5.5.6.4 schema recovery tests OK');
