const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const flow=read('js/next/client/first_vehicle_flow.js');
const css=read('css/next/first_vehicle_flow.css');
const cab=read('js/next/pages/cabinet.js');
const api=read('api/client_cabinet.php');
const db=read('api/db.php');
const mig=read('api/migrations/132_client_first_entry_three_steps.php');
const bridge=read('api/identity/onboarding_identity_bridge.php');
const resolver=read('js/next/onboarding/post_auth_first_entry_resolver.js');
const config=read('config.php');
const version=read('inc/asset_version.php');
const gate=read('tools/release_gate.php');
const checks=[];const expect=(n,v)=>{checks.push([n,!!v]);console.log(`${v?'PASS':'FAIL'} ${n}`)};
expect('CLIENT visible stepper is exactly 3',flow.includes("[['1','Автомобиль'],['2','Детали'],['3','Проверка']]")&&!flow.includes("['4','Гараж']"));
expect('intro is outside numbered progress',flow.includes('function intro(){return `${flowHeader()}')&&flow.includes('Ваш первый автомобиль'));
expect('step 1 is basic vehicle form',flow.includes('`${flowHeader(1)}')&&flow.includes('Шаг 1 из 3 · Марка, модель и год выпуска'));
expect('step 2 is optional details form',flow.includes('`${flowHeader(2)}')&&flow.includes('Шаг 2 из 3')&&flow.includes('name="transmission"'));
expect('step 3 is review and save',flow.includes('`${flowHeader(3)}')&&flow.includes('Шаг 3 из 3')&&flow.includes('data-first-vehicle-save'));
expect('success is result state not fourth step',flow.includes('flowHeader(3,true)')&&flow.includes('Автомобиль добавлен'));
expect('review can edit both sections and return',flow.includes('data-first-vehicle-edit-step="1"')&&flow.includes('data-first-vehicle-edit-step="2"')&&flow.includes("returnTarget:'review'"));
expect('legacy v1 draft normalized to v2 3 steps',flow.includes('const UI_VERSION=2')&&flow.includes('legacy){step=step<=1?1:step===2?1:step===3?2:3'));
expect('in-progress resumes despite daily prompt cap',flow.includes("server.status==='in_progress'")&&flow.includes("if(server.shouldPrompt===false&&!resume)")&&flow.includes("setPendingIntro(resume?'resume':'intro')"));
expect('daily dismissal still available',flow.includes('data-first-vehicle-later')&&flow.includes('dismissServerFirstEntry')&&flow.includes("markPrompt('shown:'+localDate())"));
expect('first-entry hides normal shell like MASTER',css.includes('.k-client-first-vehicle-active #k-shell-header')&&css.includes('.k-client-first-vehicle-active #k-mobile-nav')&&css.includes('min-height:100dvh'));
expect('manual and edit garage flows start at step 1',cab.includes("startStep:1,data:data||{},mode:'manual'")&&cab.includes("startStep:1,data:data||{},mode:'edit'"));
expect('pending/direct resume restores server draft step',cab.includes('resumeEntry')&&cab.includes('directResume')&&cab.includes('firstVehicleFlow.readDraft'));
expect('post-auth routes new empty CLIENT directly',bridge.includes("$status==='not_started'||$resume")&&bridge.includes("#/cabinet/garage?firstEntry=1")&&resolver.includes("server?.redirectRoute"));
expect('CLIENT context mismatch fails closed',resolver.includes("client_context_not_selected"));
expect('server stores only 1..3 current step',api.includes("min(3,(int)($draft['step']??1))")&&api.includes("min(3,(int)($row['current_step']??1))")&&api.includes("current_step=3"));
expect('server lets in-progress resume same day',api.includes("(string)($row['status']??'')==='in_progress'||$localDate===''"));
expect('vehicle API accepts v2 flow and transmission',db.includes("['first-vehicle-v1','first-vehicle-v2']")&&db.includes("$transmission=kareta_clean_text"));
expect('details transmission reads form control',flow.includes("transmission=normalizeText(form.elements.transmission?.value||'')")&&flow.includes("fuelType:fuel,transmission,engine:"));
expect('migration 132 normalizes legacy 4-step state',/['\"]version['\"]\s*=>\s*132/.test(mig)&&mig.includes('current_step>=4 THEN 3')&&mig.includes("status='completed'")&&/['\"]run['\"]\s*=>/.test(mig));
expect('DB version is 132',/KARETA_DB_VERSION',\s*132/.test(config));
expect('runtime version 84.25+',/188\.5\.5\.6\.84\.(2[5-9]|[3-9]\d|\d{3,})/.test(version));
expect('release gate registers client 84.25 test',gate.includes('test_client_first_vehicle_three_steps_84_25.js'));
const bad=checks.filter(x=>!x[1]);console.log(`\n${checks.length-bad.length}/${checks.length} checks passed`);if(bad.length)process.exit(1);
