'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const read = p => fs.readFileSync(p, 'utf8');
let role = 'client';
const window = { addEventListener:()=>{}, dispatchEvent:()=>{}, KaretaNavigationCore:{interfaceRole:()=>role} };
const location = { hash:'#/scan', href:'https://kareta.kz/#/scan' };
const sandbox = { window, location, URL, document:{currentScript:null,documentElement:{dataset:{} }}, localStorage:{getItem:()=>null},sessionStorage:{getItem:()=>null} };
vm.createContext(sandbox);
vm.runInContext(read('js/next/route_registry.js'), sandbox);
vm.runInContext(read('js/next/role_access.js'), sandbox);
window.KaretaRoleAccess.refresh('client');
vm.runInContext(read('js/next/pages/scanner.js'), sandbox);
const registry = window.KaretaRouteRegistry, scanner = window.KaretaScannerPages;
assert.equal(registry.uxAudit().ok, true);
for (const [key,hash] of [['scanner','#/scan'],['scannerQr','#/scan/qr'],['scannerDocument','#/scan/document']]) {
  assert.equal(registry.keyFromHash(hash), key);
  for (const r of ['client','master']) assert.equal(window.KaretaRoleAccess.canAccess(key,r),true);
  for (const r of ['seller','sto']) assert.equal(window.KaretaRoleAccess.canAccess(key,r),false);
}
assert.match(scanner.render(), /href="#\/home"/);
role = 'master';
assert.match(scanner.render(), /href="#\/master"/);
location.hash = '#/scan/qr';
assert.match(scanner.render(), /href="#\/scan"/);
assert.equal(scanner.qrTarget('https://kareta.kz/#/services/item/oil_1'), '#/services/item/oil_1');
assert.equal(scanner.qrTarget('#/masters/profile/master/ms_001'), '#/masters/profile/master/ms_001');
for (const code of ['javascript:alert(1)','https://evil.example/#/services/item/oil','https://kareta.kz.evil.example/#/services/item/oil','https://u:p@kareta.kz/#/services/item/oil','http://kareta.kz/#/services/item/oil','https://kareta.kz:444/#/services/item/oil','#/admin/users','#/services/item/oil?x=1','#/services/item/%3Cimg%3E','<img onerror=alert(1)>']) assert.throws(()=>scanner.qrTarget(code));
location.hash = '#/scan/document';
assert.match(scanner.render(), /Автоматическое распознавание полей техпаспорта пока недоступно/);
const manifest = read('inc/asset_registry.php');
assert.match(manifest, /'scannerDomain' => \[\s*'lazy' => true/);
assert.match(manifest, /'routeKeys' => \['scanner','scannerQr','scannerDocument'\]/);
for (const key of ['scanner','scannerQr','scannerDocument']) assert.ok(read('js/next/route_asset_loader.js').includes(`'${key}'`));
assert.ok(read('js/next/pages/core.js').includes("route:'#/scan'"));
assert.ok(read('js/next/pages/master_workplace.js').includes("quickAction('#/scan','camera'"));
assert.ok(!read('tools/build_boot_js_bundles.js').includes('pages/scanner.js'));
console.log('PASS home scanner: route resolution, both roles/back links, QR positive/negative, lazy contract');
async function lifecycleTests() {
  const nodes = {};
  for (const name of ['video','start','stop','status','value','target','form','file']) nodes[name] = {hidden:true,isConnected:true,disabled:false,value:'',handlers:{},removeAttribute(k){delete this[k];}};
  nodes.video.play = async()=>{};
  const root = {isConnected:true,querySelector(selector){return nodes[selector.match(/data-scan-([a-z]+)/)[1]];}};
  sandbox.document.querySelector = ()=>root;
  location.hash = '#/scan/qr';
  let enabled = true, cleanup, stopped = 0, acceptCamera;
  const life = {isActive:()=>enabled,listen:(node,event,handler)=>{node.handlers[event]=handler;},addCleanup:fn=>{cleanup=fn;}};
  window.BarcodeDetector = class {static async getSupportedFormats(){return ['qr_code'];} async detect(){return [];} };
  window.setTimeout = ()=>1; window.clearTimeout = ()=>{};
  sandbox.navigator = {mediaDevices:{getUserMedia:()=>new Promise(resolve=>{acceptCamera=resolve;})}};
  scanner.mount({lifecycle:life});
  const task = nodes.start.handlers.click();
  await new Promise(resolve=>setImmediate(resolve));
  enabled=false; cleanup();
  acceptCamera({getTracks:()=>[{stop:()=>stopped++}]});
  await task;
  assert.equal(stopped,1,'late camera must stop after route disposal');
  assert.equal(nodes.video.srcObject,null);
  enabled=true;
  scanner.mount({lifecycle:life});
  sandbox.navigator.mediaDevices.getUserMedia = async()=>{const error=new Error('denied');error.name='NotAllowedError';throw error;};
  await nodes.start.handlers.click();
  assert.match(nodes.status.textContent,/Доступ к камере запрещён/);
  assert.equal(nodes.start.disabled,false);
  nodes.value.value='javascript:alert(1)';
  nodes.form.handlers.submit({preventDefault(){}});
  assert.equal(nodes.target.hidden,true);
  nodes.value.value='#/services/item/oil';
  nodes.form.handlers.submit({preventDefault(){}});
  assert.equal(nodes.target.hidden,false);
  nodes.value.handlers.input();
  assert.equal(nodes.target.hidden,true,'editing code must invalidate target');
  delete window.BarcodeDetector;
  await nodes.start.handlers.click();
  assert.match(nodes.status.textContent,/недоступно в этом браузере/);
  cleanup();
  console.log('PASS camera lifecycle: late permission/disposal, denial, unavailable detector, invalidation');
}
lifecycleTests().catch(error=>{console.error(error);process.exitCode=1;});
