'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const fail=[]; const expect=(v,m)=>{if(!v)fail.push(m)};
const config=read('config.php');
const configExample=read('config.private.example.php');
const asset=read('inc/asset_version.php');
const sw=read('sw.js');
const auth=read('api/auth_session.php');
const gateway=read('api/onboarding_code.php');
const challenge=read('api/identity/challenge_service.php');
const lifecycle=read('js/next/onboarding/onboarding_lifecycle.js');
const validation=read('js/next/onboarding/onboarding_form_validation.js');
const role=read('js/next/onboarding/pages/role_page.js');
const va=(asset.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1];
const vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
expect(/^188\.5\.5\.6\.84\.(?:79|8[0-9]|9[0-9]|[1-9][0-9]{2,})$/.test(va)&&vs===va,'84.79+ asset/SW release parity missing');
expect(!fs.existsSync(path.join(root,'config.private.php')),'private config must not be shipped');
expect(config.includes("kareta_config_value('KARETA_DB_AUTO_MIGRATE', 'db_auto_migrate', false)"),'DB auto-migrate default is not fail-closed');
expect(config.includes("KARETA_DB_RUNTIME_MIGRATION_WINDOW")&&config.includes('$kareta_db_auto_migrate = false'),'production runtime migration maintenance guard missing');
expect(config.includes("'otp_temp_static_until',\n        ''")||config.includes("'otp_temp_static_until',\r\n        ''"),'temporary 0000 is not manual-off by default');
expect(config.includes("$kareta_otp_test_code = '0000'")&&config.includes("$kareta_otp_transport = 'test_static'"),'temporary 0000 commissioning mode missing');
expect(configExample.includes("'otp_temp_static_until' => ''")&&configExample.includes("'otp_temp_static_enabled' => true"),'private config example does not describe manual-off commissioning mode');
expect(challenge.includes("$temporaryStatic=$transport==='test_static' && $this->temporaryStaticMode()"),'challenge commissioning mode detection missing');
expect(challenge.includes('if(!$temporaryStatic){'),'temporary 0000 does not bypass ordinary challenge counters');
expect(challenge.includes('SELECT GET_LOCK'),'concurrency lock was removed while bypassing rate limits');
expect(challenge.includes('challenge_rate_limited'),'real-provider rate limiting was removed');
expect(auth.includes('function kareta_identity_profile_snapshot_by_phone'),'Identity Core phone fallback missing');
expect(auth.includes('function kareta_restore_legacy_profile_from_identity'),'legacy users projection repair missing');
expect(auth.includes("$identityWarnings[] = 'identity_session_degraded'")&&auth.includes("$profileWarnings[] = 'identity_session_degraded'"),'Identity bridge fail-soft warnings missing');
expect(!auth.includes("'error'=>'identity_session_issue_failed'"),'successful OTP can still be converted into identity_session_issue_failed');
expect(lifecycle.includes("window.addEventListener('kareta:session-anonymous'")&&lifecycle.includes("lastAction='session-anonymous-stale-done-reset'")&&lifecycle.includes('state.reset()'),'stale DONE reset on authoritative anonymous session missing');
expect(validation.includes('options.requireName !== false'),'registration validation cannot make name optional for login');
expect(role.includes('requireName:verifiedNew'),'phone-first login/name-after-verification validation contract missing');
expect(role.includes('phoneVerified:true')&&role.includes("source:'registration-new-account-phone-verified'"),'new-account name-after-OTP branch missing');
expect(role.includes("source:'registration-phone-changed-after-verification'")&&role.includes('phoneVerified:false'),'verified phone invalidation on phone change missing');
const requestBlock=(gateway.match(/if\(\$action==='onboarding\.requestCode'\)\{([\s\S]*?)\n\}/)||[])[1]||'';
expect(!requestBlock.includes('accountExists'),'legacy gateway discloses account existence before OTP');
expect(gateway.includes("existingAccount'=>true")&&gateway.includes("KaretaOnboardingIdentityBridge"),'legacy gateway does not establish existing-account login after OTP');
const protectedHash=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'js/next/smart_action_hub.js'))).digest('hex');
expect(protectedHash==='6e3941b4cc27e1f45e0f44ab0085efdd1b8e043fc9f55e0a4a66d58c05a50532','protected smart_action_hub.js changed');
const indexHash=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'index.php'))).digest('hex');
expect(indexHash==='5e3dbc84e0ff808dd023d490399677f7ff1616d3c7bebaeb1bfab462d0854d26','frozen index.php changed');
if(fail.length){console.error(fail.join('\n'));process.exit(1)}
console.log('R188.5.5.6.84.79 recovery merge regression OK');
