'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const failures=[];const expect=(v,m)=>{if(!v)failures.push(m)};
const config=read('config.php'),migration=read('api/migrations/113_master_service_pricing_native.php'),page=read('js/next/pages/service_management.js'),server=read('api/catalog/service_catalog.php'),db=read('api/db.php'),client=read('js/next/services/service_offers_api.js'),details=read('js/next/pages/details.js'),catalog=read('api/catalog_details.php'),css=read('css/next/master_service_pricing_native.css'),registry=read('inc/asset_registry.php'),manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
const dbv=Number((/KARETA_DB_VERSION',\s*(\d+)/.exec(config)||[])[1]||0);expect(dbv>=113,'DB version must be >=113');expect(migration.includes("'version' => 113"),'migration 113 missing');for(const t of ['price_type','price_max','duration_max_min'])expect(migration.includes(t),`migration field missing ${t}`);
for(const t of ["NATIVE_SERVICE_CONTRACT = 'R188.5.5.6.56'",'data-service-open-add','data-service-open-filter','data-service-edit-dialog','data-service-remove-dialog','k-service-native-card','k-service-specialty-grid','Фиксированная','Диапазон','По договорённости','Сферы работы'])expect(page.includes(t),`Native service UI missing ${t}`);expect(!page.includes('<select'),'service management must not contain select/dropdown');expect(!page.includes('Swiper'),'service management must not contain Swiper');
for(const t of ['priceType','priceMax','durationMaxMin',"['fixed','from','range','agreement']",'kareta_resolve_api_actor'])expect(server.includes(t),`server service contract missing ${t}`);expect(db.includes("kareta_require_api_capability($pdo,'services.manageOwn'"),'service offers must use services.manageOwn capability');
for(const t of ['priceType','priceMax','durationMaxMin'])expect(client.includes(t),`offer client normalization missing ${t}`);for(const t of ['servicePriceLabel','serviceDurationLabel','service_category_name'])expect(details.includes(t),`public profile integration missing ${t}`);expect(catalog.includes('service_category_name'),'provider API must surface active service category as specialization');
expect(css.includes('height:100dvh')&&css.includes('@media(max-width:700px)'),'mobile service dialogs must become full-screen');expect(!css.includes('scroll-snap-type'),'service CSS must not introduce horizontal slider');expect(registry.includes('css/next/master_service_pricing_native.css'),'R56 CSS not registered');for(const f of ['inc/asset_version.php','sw.js'])expect(read(f).includes('r1885616-master-service-pricing-native'),`${f} release suffix missing`);
for(const [file,hash] of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`)}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('R188.5.5.6.56 services: card pricing + modal editing + specialization feed + capability isolation + shell freeze OK');
