const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
let failed=0,total=0;
const expect=(name,ok)=>{total++;if(ok)console.log('PASS',name);else{failed++;console.error('FAIL',name);}};
const fv=read('js/next/client/first_vehicle_flow.js');
const fvCss=read('css/next/first_vehicle_flow.css');
const mo=read('js/next/pages/master_onboarding.js');
const moCss=read('css/next/master_onboarding.css');
const core=read('js/next/pages/core.js');
const db=read('api/db.php');
const mob=read('api/master_onboarding.php');
expect('first vehicle has three stages',(fv.includes("['1','Старт'],['2','Автомобиль'],['3','Подтверждение']")||fv.includes('const rows=[1,2,3]'))&&fv.includes('Math.min(3'));
expect('first vehicle restores separate confirmation screen',fv.includes('function confirm(draft)')&&fv.includes('data-first-vehicle-confirm')&&fv.includes('data-first-vehicle-edit-basic'));
expect('first vehicle header matches master brand hierarchy',fv.includes('class="k-first-vehicle-logo"')&&!fv.includes('k-first-vehicle-brand-separator')&&fvCss.includes('flex-direction:column')&&(fvCss.includes('grid-template-columns:repeat(3,minmax(0,1fr))')||fv.includes('kmo-stepper k-first-vehicle-steps')));
expect('first vehicle draft saves are debounced and 429 backed off',fv.includes('function scheduleServerDraft(delay=1400)')&&fv.includes('state.serverBackoffUntil')&&fv.includes('===429')&&fv.includes('state.serverDraftSignature'));
expect('master dependent block shows incomplete state',mo.includes('kmo-dependent${dependentIncomplete?\' is-incomplete\':\'\'}')&&mo.includes('data-kmo-dependent-state=')&&moCss.includes('.kmo-dependent.is-incomplete'));
expect('master step 4 service rules open modal',mo.includes('data-kmo-terms>правилами сервиса</a>')&&mo.includes("model.modal==='terms'")&&mo.includes("openModal('terms'")&&!mo.includes('target="_blank" rel="noopener">правилами сервиса'));
expect('client cabinet home fetch is client-only',core.includes("if(homeInterfaceRole(context)!=='client')return;")&&core.includes("action=clientCabinet.get"));
expect('master exchange feed supports GET route',db.includes("if ($action === 'masterExchange.feed')")&&db.includes("kareta_master_exchange_feed_v2($pdo);"));
expect('master onboarding completion capabilities are fail-soft after commit',mob.includes('function kmob_effective_capabilities_safe')&&mob.includes("kareta_log_error('MASTER_ONBOARDING_CAPABILITIES'")&&mob.includes('$allowed=kmob_effective_capabilities_safe'));
console.log(`${total-failed}/${total} checks passed`);
process.exit(failed?1:0);
