#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const must=(ok,label)=>{if(!ok){console.error(`[84.87][FAIL] ${label}`);process.exitCode=1;}else console.log(`[84.87][OK] ${label}`);};
const asset=read('inc/asset_version.php'),sw=read('sw.js'),core=read('api/messaging_core.php'),live=read('api/messaging_live_actions.php'),tg=read('api/webhooks/telegram.php'),db=read('api/db.php'),installer=read('tools/messaging_schema_install.php'),gate=read('tools/release_gate.php');
const av=(asset.match(/KARETA_ASSET_VERSION\s*=\s*'188\.5\.5\.6\.84\.(\d+)'/)||[])[1];
const sv=(sw.match(/const RELEASE = '188\.5\.5\.6\.84\.(\d+)'/)||[])[1];
must(Number(av)>=87,'asset version .84.87+');
must(Number(sv)>=87&&sv===av,'service worker release .84.87+ parity');
must(core.includes('messaging_action_tokens')&&core.includes('token_hash CHAR(64)')&&core.includes('used_at DATETIME')&&core.includes('expires_at DATETIME'),'server-side short-lived action token schema');
must(core.includes("hash('sha256',$raw)")&&core.includes("hash('sha256',trim($rawToken))"),'raw Telegram action token is stored/verified only by SHA-256 hash');
must(core.includes("'callback_data'=>'ka:'.$claim")&&core.includes("'callback_data'=>'ka:'.$token"),'Telegram callback_data contains opaque token, not trusted order action payload');
must(core.includes('kareta_messaging_enqueue_notification')&&db.includes('kareta_messaging_enqueue_notification($pdo,$notificationId,$row)'),'internal notifications asynchronously fan out through Messaging');
must(db.includes('catch (Throwable $_) {}'),'notification external fan-out is fail-soft');
must(core.includes("if($eventType==='message.new')return 0"),'message notifications are not duplicated by generic fan-out');
must(core.includes("'notifyApprovals'")&&core.includes("'notifySchedule'")&&core.includes("'notifyOrders'"),'notification fan-out honors channel preference classes');
must(core.includes("'Предложить цену'")&&core.includes("#/master/exchange?focus=")&&core.includes("&quick=1"),'exchange card provides price-offer deep link');
must(core.includes("'master.exchange.claim'")&&core.includes("'master.exchange.hide'")&&core.includes("'master.order.start_diagnostics'")&&core.includes("'master.order.complete_work'"),'Telegram action cards cover claim/hide/diagnostics/work-complete');
must(tg.includes("$update['callback_query']")&&tg.includes("preg_match('~^ka:")&&tg.includes('kareta_messaging_action_token_get')&&tg.includes('kareta_messaging_execute_live_action'),'Telegram webhook handles only opaque ka: callbacks through live-action dispatcher');
must(tg.includes("kareta_messaging_find_user_by_external($pdo,'telegram',$tgUserId)")&&tg.includes("kareta_messaging_action_token_get($pdo,$userId,'telegram'"),'callback actor is re-bound to linked Telegram identity before token resolution');
must(tg.includes('kareta_messaging_action_token_finish')&&tg.includes('kareta_messaging_telegram_answer_callback'),'successful action is consumed and callback is acknowledged');
must(live.includes("'requests.respond'")&&live.includes("'work_orders.update_status'"),'live mutations are guarded by Identity capabilities');
must(live.includes('new KaretaCapabilityService')&&live.includes("profileType")&&live.includes("=== 'master'"),'MASTER profile context is resolved explicitly without trusting webhook session context');
must(live.includes('FOR UPDATE')&&live.includes("status IN ('new','waiting_responses')")&&live.includes('race_condition'),'exchange claim uses locked availability/race guard');
must(live.includes('kareta_tariff_master_guard')&&live.includes('kareta_tariff_record_master_acceptance'),'Telegram claim preserves master tariff/capacity accounting');
must(live.includes("schedule_required_in_kareta")&&live.includes("preg_match('/^\\d{4}-\\d{2}-\\d{2}$/',$date)"),'Telegram claim never invents missing client schedule');
must(live.includes("kareta_sto_workflow_transition_apply($pdo,$orderId,'diagnostics'")&&live.includes("kareta_sto_workflow_transition_apply($pdo,$orderId,'quality_control'"),'lifecycle actions reuse workflow engine requirements');
must(live.includes('order_not_assigned_to_master')&&live.includes('kareta_messaging_master_owned_order'),'assigned-order actions verify current master ownership');
must(installer.includes('kareta_messaging_install_schema')&&core.includes("'messaging_action_tokens',"),'explicit Messaging schema installer includes .84.87 token table');
must(gate.includes("'84.87' => 'tools/test_telegram_live_actions_84_87.js'"),'release gate runs .84.87 regression');
must(!read('js/next/smart_action_hub.js').includes('Telegram Live Actions'),'protected smart action hub remains untouched');
if(process.exitCode)process.exit(process.exitCode);console.log('[84.87] Telegram Live Actions stage 2 regression passed.');
