const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8');
const vehicle=read('js/next/pages/vehicle.js');
const chats=read('js/next/pages/chats.js');
const vehicleCss=read('css/next/vehicle.css');
const chatCss=read('css/next/chats.css');
const asset=read('inc/asset_version.php');
const sw=read('sw.js');
const ok=(cond,msg)=>{if(!cond){console.error('FAIL',msg);process.exit(1)}console.log('OK',msg)};
const va=(asset.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1];
const vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
ok(/^188\.5\.5\.6\.84\.(?:7[89]|[89]\d|\d{3,})$/.test(va)&&vs===va,'release version 84.78+ parity');
ok(vehicle.includes('k-vehicle-r78-hero'),'vehicle native hero');
ok(vehicle.includes('data-vehicle-scroll="state"'),'vehicle section navigation');
ok(vehicle.includes('data-vehicle-create-request'),'vehicle request action preserved');
ok(vehicle.includes("KaretaRequestWindow?.open?.('#/orders/new')"),'vehicle request window logic preserved');
ok(vehicle.includes("data-vehicle-open-section"),'vehicle dialogs preserved');
ok(vehicle.includes("data-vehicle-action"),'vehicle issue/mileage actions preserved');
ok(vehicleCss.includes('vehicle detail aligned with Garage native UI'),'vehicle route CSS override');
ok(vehicleCss.includes('.k-vehicle-r78-nav{position:sticky'),'vehicle sticky section rail');
ok(chats.includes('k-chat-layout-r78'),'chat native workspace');
ok(chats.includes("icon('send')"),'chat send icon');
ok(chats.includes("data-chat-mobile-back"),'chat mobile back preserved');
ok(chats.includes('api.getMessages'),'chat message API preserved');
ok(chats.includes('api.openDirectChat'),'direct chat API preserved');
ok(chatCss.includes('native chat workspace'),'chat route CSS override');
ok(chatCss.includes('.k-page[data-page="chats"]>.k-workspace-head{display:none}'),'duplicate chat workspace header removed');
ok(chatCss.includes('.k-chat-composer-r78'),'mobile composer redesign');
console.log('R188.5.5.6.84.78 vehicle detail + chats native UI regression OK');
