'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const assert=(ok,msg)=>{if(!ok){console.error('[FAIL]',msg);process.exit(1)}};
const role=read('js/next/onboarding/pages/role_page.js');
const form=read('js/next/onboarding/onboarding_form_ui.js');
const css=read('css/next/onboarding_kflow_reference.css');
const version=read('inc/asset_version.php');
const sw=read('sw.js');

assert(role.includes('function shellHtml(step)'),'persistent onboarding shell is missing');
assert(role.includes('data-onb2-dynamic'),'dynamic stage mount is missing');
assert(role.includes('dynamic.innerHTML=stageHtml(step)'),'step changes must replace only content below the fixed top');
assert(role.includes("const creating = !overlay"),'overlay reuse guard is missing');
assert(!role.includes('cleanup();\n    const parsed'),'render must not destroy the overlay on every step');
assert((role.match(/class="onb2-welcome-logo"/g)||[]).length===1,'role_page must mount exactly one official onboarding logo');
assert((role.match(/class="onb2-welcome-copy"/g)||[]).length===1,'role_page must mount exactly one .onb2-welcome-copy');
assert(!role.includes('class="k-flow-logo"'),'per-step logo header returned');
assert(!form.includes('kareta_logo_full.png'),'form helper must not mount another onboarding logo');
assert(role.includes('<h1>Добро пожаловать!</h1>'),'shared welcome heading missing');
assert(role.includes('Всё для автомобиля<br>в одном месте'),'shared welcome subtitle missing');
for(const text of ['Кто вы?','Давайте познакомимся','Подтвердите номер']) assert(role.includes(text),`dynamic step copy missing: ${text}`);
assert(css.includes('84.27 — one persistent top block'),'84.27 shared-top CSS marker missing');
assert(css.includes('#onb2-overlay .k-flow-unified-shell>.onb2-flow-brand'),'fixed brand CSS missing');
assert(css.includes('#onb2-overlay .k-flow-unified-shell>.onb2-welcome-copy'),'fixed welcome-copy CSS missing');
assert(css.includes('#onb2-overlay .onb2-flow-stage'),'dynamic-stage CSS missing');
assert(css.includes('#onb2-overlay #onb2-step-role .k-flow-unified-shell::before'),'welcome background must stay welcome-only');
const current=(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/.exec(version)||[])[1]||'';
assert(/^188\.5\.5\.6\.84\.(?:2[7-9]|[3-9]\d)$/.test(current),`unexpected version ${current}`);
assert(sw.includes(`const RELEASE = '${current}';`),'service worker version mismatch');
console.log('KARETA onboarding persistent shared top 84.27: OK');
