'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const failures=[];const expect=(v,m)=>{if(!v)failures.push(m)};
const route=read('js/next/route_registry.js'),app=read('js/next/app_next.js'),page=read('js/next/pages/master_profile_owner.js'),api=read('api/master_workplace.php'),db=read('api/db.php'),catalog=read('api/masters_catalog.php'),css=read('css/next/master_owner_profile.css'),work=read('js/next/pages/master_workplace.js'),manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
expect(route.includes("masterProfileOwner:Object.freeze({ path:'#/master/profile'"),'owner profile route missing');
expect(app.includes('masterProfileOwner:masterProfileOwnerPages.renderMasterProfileOwner'),'owner renderer missing');expect(app.includes('masterProfileOwner:masterProfileOwnerPages.mountMasterProfileOwner'),'owner mount missing');
for(const token of ["sectionCard('basic'","sectionCard('specialties'","sectionCard('experience'","sectionCard('expertise'","sectionCard('publicity'",'data-owner-form','profileVisible','primaryServices','brands','equipment','certificates','Посмотреть как клиент'])expect(page.includes(token),`owner UI missing ${token}`);
for(const token of ['window.Swiper','new window.Swiper','<select'])expect(!page.includes(token),`native owner profile forbids ${token}`);
expect(page.includes("snapshot.context?.profileType"),'owner page must check current Master Identity context');expect(page.includes("action:'masterProfile.save'"),'owner form must save through server API');
for(const token of ['kareta_master_owner_profile_get','kareta_master_owner_profile_save','kareta_assert_master_owns_profile','primary_services','profile_visible','resume'])expect(api.includes(token),`owner server model missing ${token}`);
expect(db.includes("$action === 'masterProfile.get'")&&db.includes("case 'masterProfile.save'"),'owner API routes missing');expect(db.includes("'profile.manage'") ,'owner API must be capability protected');
expect(catalog.includes('AS avatar_url'),'public catalog must expose account avatar');if(!work.includes("NATIVE_WORKPLACE_CONTRACT='R188.5.5.6.55'"))expect(work.includes("quickAction('#/master/profile'"),'workplace must link owner profile without shell change');
else expect(page.includes('#/master/wall')&&page.includes('#/master/works')&&page.includes('#/master/reviews'),'owner profile must remain the hub for public-profile content after workplace separation');
expect(css.includes('@media (max-width:600px)')&&css.includes('height:100dvh'),'mobile editors must become full-screen');expect(css.includes('.k-master-owner-sections{display:grid'),'owner sections must use cards/grid');
for(const [file,hash] of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`);}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('R188.5.5.6.51 master owner profile: native cards + identity ownership + shell freeze OK');
