'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[];const expect=(name,ok)=>{checks.push([name,!!ok]);console.log(`${ok?'PASS':'FAIL'} ${name}`)};
const migration=read('api/migrations/133_vehicle_catalog_stable_ids.php');
const catalog=read('api/catalog/vehicle_catalog.php');
const db=read('api/db.php');
const schema=read('api/identity/schema_contract.php');
const clientApi=read('js/next/client/client_cabinet_api.js');
const flow=read('js/next/client/first_vehicle_flow.js');
const cabinet=read('api/client_cabinet.php');
const config=read('config.php');
const manifest=JSON.parse(read('api/migration_manifest.json'));
let seed=[];try{seed=JSON.parse(cp.execFileSync('php',['-r',`require ${JSON.stringify(path.join(root,'api/catalog/vehicle_catalog.php'))}; echo json_encode(kareta_vehicle_catalog_seed(), JSON_UNESCAPED_UNICODE);`],{encoding:'utf8'}));}catch(e){console.error(e.stdout||e.message);}
expect('migration 133 exists',migration.includes("'version'=>133")&&migration.includes('vehicle_catalog_brands')&&migration.includes('vehicle_catalog_models')&&migration.includes('vehicle_catalog_generations'));
expect('client vehicles store stable ids',migration.includes("'brand_id'")&&migration.includes("'model_id'")&&migration.includes("'generation_id'"));
expect('catalog has broad fallback seed',Array.isArray(seed)&&seed.length>=25);
const brandIds=seed.map(x=>x.id);expect('brand ids unique',new Set(brandIds).size===brandIds.length);
expect('model ids stable per brand',seed.every(b=>Array.isArray(b.models)&&new Set(b.models.map(m=>m.id)).size===b.models.length));
const camry=seed.find(b=>b.id==='toyota')?.models?.find(m=>m.id==='camry');expect('generation ids stable',Array.isArray(camry?.generations)&&camry.generations.length>=5&&camry.generations.every(g=>g.id&&g.name&&g.from&&g.to));
expect('read API route',db.includes("$action === 'vehicleCatalog.list'")&&db.includes('kareta_vehicle_catalog_list($pdo)'));
expect('VIN adapter API route',db.includes("case 'vehicles.decodeVin'")&&catalog.includes('function kareta_vehicle_vin_decode'));
expect('server validates catalog on save',db.includes('kareta_vehicle_catalog_resolve')&&db.includes("error'=>'invalid_vehicle_brand")&&db.includes("error'=>'invalid_vehicle_model"));
expect('formatted vehicles expose ids',db.includes("'brandId' =>")&&db.includes("'modelId' =>")&&db.includes("'generationId' =>"));
expect('vehicle insert persists ids',db.includes('brand,brand_id,model,model_id')&&db.includes('generation,generation_id'));
expect('client API caches server catalog',clientApi.includes('getVehicleCatalog')&&clientApi.includes("cacheKey:'vehicle.catalog'")&&clientApi.includes('decodeVin'));
expect('first vehicle server catalog with fallback',flow.includes('FALLBACK_CATALOG')&&flow.includes('loadVehicleCatalog')&&flow.includes('catalogRows()'));
expect('first vehicle sends generation id',flow.includes('generationId:draft.generationId')&&flow.includes('generationByName'));
expect('server draft preserves generation id',cabinet.includes("'generationId'=>$clean($draft['generationId']"));
expect('cabinet returns catalog ids',cabinet.includes('brand_id,brand,model_id,model')&&cabinet.includes('generation_id,generation'));
expect('schema contract covers catalog',schema.includes("'vehicle_catalog_brands'")&&schema.includes("'vehicle_catalog_models'")&&schema.includes("'vehicle_catalog_generations'")&&schema.includes("'client_vehicles'"));
expect('db version 133',config.includes("KARETA_DB_VERSION', 133"));
expect('migration manifest 133',manifest.targetDbVersion===133&&manifest.migrations.length===133&&manifest.migrations.at(-1)?.file==='133_vehicle_catalog_stable_ids.php');
const failed=checks.filter(x=>!x[1]);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed`);process.exit(failed.length?1:0);
