'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const expect=(v,m)=>{if(!v)throw new Error(m)};
const js=read('js/next/pages/master_workplace.js');
const css=read('css/next/master_workplace_native.css');
const registry=read('inc/asset_registry.php');
const asset=read('inc/asset_version.php');
const sw=read('sw.js');
const order="Object.freeze(['header','status','quick-actions','my-requests','notes','paused','today'])";
expect(js.includes("MASTER_HOME_STRUCTURE_CONTRACT='R188.5.5.6.84.115'"),'84.115 Master home contract missing');
expect(js.includes(order),'approved seven-block DOM order changed');
expect(js.includes("quickAction('#/orders','orders','Мои заявки'"),'My requests quick action missing');
expect(js.includes("quickAction('#/master','edit','Заметки'"),'Notes quick action missing');
expect(js.includes('data-master-home-jump="notes"'),'Notes in-page jump missing');
expect(js.includes("quickAction('#/services/manage','services','Услуги'"),'Services quick action missing');
expect(js.includes("quickAction('#/parts','parts','Запчасти'"),'Parts quick action missing');
const quickBlock=(js.match(/'quick-actions':masterHomeBlock[\s\S]*?,'k-master-home-quick-actions'\),/)||[])[0]||'';
expect(!quickBlock.includes("'График'"),'Schedule still occupies approved four quick-action slots');
expect(js.includes("event.target.closest('[data-master-home-jump]')"),'Master home jump interaction missing');
expect(css.includes('R188.5.5.6.84.115 — Master desktop 70/30 home composition'),'desktop Master CSS marker missing');
expect(css.includes('@media (min-width:1024px)'),'desktop 1024 breakpoint missing');
expect(css.includes('grid-template-columns:repeat(12,minmax(0,1fr))'),'Master 12-column desktop grid missing');
expect(css.includes('grid-column:1/9;\n    grid-row:3/span 3'),'requests 8/12 work-area placement missing');
expect(css.includes('grid-column:9/-1;\n    grid-row:3'),'status 4/12 side-area placement missing');
expect(css.includes('grid-column:9/-1;\n    grid-row:4'),'today side-area placement missing');
expect(css.includes('grid-column:9/-1;\n    grid-row:5'),'notes side-area placement missing');
expect(css.includes('grid-column:1/-1;\n    grid-row:6'),'paused full-row placement missing');
expect(css.includes('@media (min-width:1280px)'),'1280 quick-action breakpoint missing');
expect(registry.includes("'css/next/master_workplace_native.css'"),'Master workplace CSS not registered');
const va=(asset.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1];
const vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
expect(va==='188.5.5.6.84.115','asset version is not 84.115');
expect(va===vs,'asset/service-worker release mismatch');
console.log('MASTER_HOME_DESKTOP_CONTRACT: PASS release='+va+' work=8/12 side=4/12 quick=approved4 mobileOrder=preserved');
