'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const hub=read('js/next/smart_action_hub.js');
assert(hub.includes("MORE_WINDOW_CONTRACT='KARETA_MORE_WINDOW_V1_2'"),'V1.2 contract missing');
assert(hub.includes("layout:'honeycomb'"),'fixed honeycomb layout missing');
assert(hub.includes('class="k-more-window-profile"'),'More profile card missing');
assert(hub.includes('data-smart-action-route="cabinet"'),'account/profile route missing');
assert(hub.includes('class="k-more-window-hub"'),'honeycomb hub missing');
assert(hub.includes('class="k-more-window-support"'),'support card missing');
assert(!hub.includes("new Set(['grid','arc','hex'])"),'legacy layout variants returned');
assert(!fs.existsSync(path.join(root,'css/next/smart_action_account.css')),'legacy smart_action_account.css returned');
const css=read('css/next/smart_action_hub.css');
for(const needle of ['.k-more-window-hub','.k-more-window-action--6','.k-more-window-core','.k-more-window-support'])assert(css.includes(needle),needle);
const registry=read('js/next/route_registry.js');
assert(registry.includes("cabinet:Object.freeze({ path:'#/cabinet'"),'cabinet route must exist');
assert(!read('inc/asset_registry.php').includes('smart_action_account.css'),'legacy account More CSS still registered');
console.log('R188.5.5.6.9 smart action account tests OK (V1.2 override)');
