'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const expect=(v,m)=>{if(!v){console.error('FAIL:',m);process.exit(1)}};
const routes=read('js/next/route_registry.js'),app=read('js/next/app_next.js'),core=read('js/next/navigation_core.js');
const shell=read('js/next/shell_nav.js'),loader=read('js/next/route_asset_loader.js'),registry=read('inc/asset_registry.php');
const version=read('inc/asset_version.php'),sw=read('sw.js'),bundle=read('js/boot/runtime_shell_bundle.js');
const routeKeys=[...routes.matchAll(/^\s{4}([A-Za-z_][A-Za-z0-9_]*)\:Object\.freeze\(\{/gm)].map(m=>m[1]);
const block=(app.match(/const PAGE_BINDINGS = Object\.freeze\(\{([\s\S]*?)\n  \}\);/)||[])[1]||'';
const bindings=[...block.matchAll(/^\s{4}([A-Za-z_][A-Za-z0-9_]*)\:/gm)].map(m=>m[1]);
expect(routeKeys.filter(k=>!bindings.includes(k)).length===0,'route without PAGE_BINDING');
expect(bindings.filter(k=>!routeKeys.includes(k)).length===0,'PAGE_BINDING without route');
expect(!registry.includes('masterWorkplaceSettings')&&!loader.includes('masterWorkplaceSettings'),'phantom masterWorkplaceSettings remains');
expect(registry.includes("'routeKeys' => ['masterDashboard','cabinetSettings']"),'master settings lazy bundle mismatch');
expect(loader.includes("'masterDashboard','masterSchedule','cabinetSettings','masterProfileOwner'"),'cabinetSettings not known lazy');
expect(core.includes("if (role === 'master') return 'master';"),'Master degraded context missing');
expect(core.includes("if (role === 'seller') return 'seller';"),'Seller degraded context missing');
expect(core.includes("if (['sto','service'].includes(role)) return 'organization_service';"),'STO degraded context missing');
expect(shell.includes('function itemsFor(surface)')&&shell.includes("access?.keys?.(surface)"),'shell mode authority missing');
for(const m of ["if (role === 'master') return 'master';",'function itemsFor(surface)',"'masterDashboard','masterSchedule','cabinetSettings','masterProfileOwner'"])expect(bundle.includes(m),'stale shell bundle: '+m);
const va=(version.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1]||'',vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1]||'';
expect(va==='188.5.5.6.84.150'&&vs===va,'release parity mismatch');
console.log('NAVIGATION_INTEGRITY_84_150: PASS routes='+routeKeys.length+' bindings='+bindings.length);
