'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const masters=read('js/next/pages/masters.js');
const details=read('js/next/pages/details.js');
const firstVehicle=read('js/next/client/first_vehicle_flow.js');
const routes=read('js/next/route_registry.js');
const app=read('js/next/app_next.js');
const access=read('js/next/role_access.js');
const db=read('api/db.php');
const version=read('inc/asset_version.php');
let failed=0,total=0;const expect=(n,ok)=>{total++;if(ok)console.log('PASS',n);else{failed++;console.error('FAIL',n)}};
expect('masters screen uses reference title/search/filter row',masters.includes('<h1>Мастера</h1>')&&masters.includes('Услуга или имя мастера')&&masters.includes('Свободны сегодня'));
expect('master cards use image reference composition',masters.includes('k-master-reference-card__main')&&masters.includes('Свободен сегодня')&&masters.includes('k-master-reference-profile'));
expect('legacy public masters workspace hero removed from client render',!masters.includes('КАТАЛОГ ИСПОЛНИТЕЛЕЙ'));
expect('master profile uses reference identity/actions/services/works',details.includes('k-master-ref-identity')&&details.includes('Услуги и цены')&&details.includes('Последние работы'));
expect('master booking has 3-step reference screen',details.includes('k-master-ref-booking-stepper')&&details.includes('Запись к мастеру')&&details.includes('Свободное время'));
expect('profile booking routes to dedicated master booking route',details.includes("#/masters/book/master/${encodeURIComponent(id)}"));
expect('booking route registered and mounted',routes.includes('providerBooking')&&routes.includes('masters\\/book\\/master')&&app.includes('renderProviderBooking')&&app.includes('mountProviderBooking'));
expect('provider booking is allowed deep route',access.includes("'providerBooking'"));
expect('catalog returns avatar and experience for visual cards',db.includes('avatar_url,{$experienceExpr} experienceLabel')||db.includes('{$avatarExpr} avatar_url,{$experienceExpr} experienceLabel'));
expect('first vehicle reuses kmo-stepper geometry',firstVehicle.includes('kmo-stepper k-first-vehicle-steps')&&firstVehicle.includes("[1,2,3]"));
expect('release 84.38',version.includes('188.5.5.6.84.38'));
console.log(`\n${total-failed}/${total} checks passed`);process.exit(failed?1:0);
