'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const assert=(v,m)=>{if(!v)throw new Error(m);};
const migration=read('api/migrations/105_master_aftercare_finance_inventory.php');
for(const table of ['master_finance_settings','work_order_cost_entries','work_order_financial_results','work_order_warranty_claims','work_order_warranty_claim_events'])assert(migration.includes(table),`missing ${table}`);
for(const column of ['cost_price','warehouse_id','product_id','qty_issued','qty_returned','stock_status','claim_id'])assert(migration.includes(column),`missing ${column}`);
const aftercare=read('api/master_order_aftercare.php');
for(const fn of ['kareta_master_aftercare_inventory_reserve','kareta_master_aftercare_inventory_return','kareta_master_aftercare_recalculate','kareta_client_warranty_claim_submit','kareta_master_warranty_claim_inspect','kareta_master_warranty_claim_start_repair','kareta_master_warranty_claim_quality','kareta_client_warranty_claim_confirm'])assert(aftercare.includes(`function ${fn}`),`missing ${fn}`);
assert(aftercare.includes("$professional=in_array")&&aftercare.includes("'financialResult'=>$finance"),'professional finance scope missing');
assert(aftercare.includes("status']!=='inspection'")&&aftercare.includes('inspection_notes'),'warranty repair can bypass inspection');
assert(aftercare.includes("'issue'")&&aftercare.includes("'return'")&&aftercare.includes('market_stock_movements'),'inventory movements missing');
const db=read('api/db.php');
for(const action of ['masterOrder.inventory.reserve','masterOrder.inventory.return','masterOrder.finance.settings.save','masterOrder.cost.save','clientOrder.warrantyClaim.submit','masterOrder.warrantyClaim.inspect','masterOrder.warrantyClaim.startRepair','masterOrder.warrantyClaim.quality','clientOrder.warrantyClaim.confirm'])assert(db.includes(`'${action}'`),`missing dispatch ${action}`);
const page=read('js/next/pages/work_order.js');
for(const marker of ['data-aftercare-form="claim-submit"','data-aftercare-form="claim-inspect"','data-aftercare-form="finance-settings"','data-lifecycle-modal="inventory"','data-aftercare-click="inventory-return"'])assert(page.includes(marker),`missing UI ${marker}`);
const api=read('js/next/work_orders/work_order_api.js');
for(const marker of ['reserveInventory','returnInventory','saveFinanceSettings','submitWarrantyClaim','startWarrantyRepair','confirmWarrantyReturn'])assert(api.includes(marker),`missing API ${marker}`);
console.log('R188.5.5.6.19 master aftercare finance inventory OK');
