'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const fail=[];const expect=(v,m)=>{if(!v)fail.push(m)};
const role=read('js/next/onboarding/pages/role_page.js'),app=read('js/next/onboarding/onboarding_app.js'),life=read('js/next/onboarding/onboarding_lifecycle.js'),boot=read('js/next/app_next.js'),version=read('inc/asset_version.php');
expect(!role.includes('k-flow-role-direction'),'legacy external role-direction blocks must not exist in role DOM');
expect(role.includes('roleIntent:role')&&role.includes('roleIntentLocked:true'),'role intent must lock when role is selected');
expect(role.includes('synchronizeSession(verifyResult,flow,{emit:false})'),'existing account must suppress early session-confirmed');
expect(role.includes('activateEntryRole(desiredRole,flow)'),'existing account must activate selected Identity context before app transition');
expect(app.includes("const intendedRole=flow?.roleIntentLocked===true"),'confirmed user must honor locked role intent');
expect(app.includes("'/api/context.php?action=request-type'"),'professional account type request missing');
expect(app.includes('identityApi.select(target.id||target.key)'),'selected Identity context must be explicitly selected');
expect(/synchronizeSession\(result,\s*flow,\s*\{\s*emit:false\s*\}\)/.test(app),'new account finalize must also suppress early session-confirmed');
expect(/emitSessionConfirmed\(user,\s*result,\s*activation\?\.identity\s*\|\|\s*null\)/.test(app),'new account must emit session-confirmed only after context activation');
expect(life.includes('onboarding.session_confirmed_role_mismatch_ignored'),'lifecycle must ignore mismatched early session-confirmed while role intent is locked');
expect(life.includes("roleIntent:'', roleIntentLocked:false"),'fresh welcome must clear stale role intent');
expect(boot.includes('function generalOnboardingOwnsRoute()'),'app boot must recognize general onboarding route authority');
expect(boot.includes("const targetRoute = onboardingOwnsRoute ? '' : routeKeyFromHash(location.hash)"),'business route must not be resolved under general onboarding');
expect(boot.includes("outlet.innerHTML=''"),'business outlet must remain empty under onboarding');
const vm=/188\.5\.5\.6\.84\.(\d+)/.exec(version);expect(vm&&Number(vm[1])>=23,'asset version 84.23+ required');
if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log('Onboarding role authority 84.23: Identity > roleIntent > legacy; no CLIENT Home under onboarding OK');
