const fs=require('fs');
const core=fs.readFileSync('js/next/navigation_core.js','utf8');
const shell=fs.readFileSync('js/next/shell_nav.js','utf8');
const menu=fs.readFileSync('js/next/shell_menu.js','utf8');
const access=fs.readFileSync('js/next/role_access.js','utf8');
const fail=m=>{throw new Error(m)};
const expect=(cond,m)=>{if(!cond)fail(m)};
expect(/organization_service:\s*Object\.freeze\(\['stoDashboard','orders','masters','workflow','serviceManagement','finance','parts','chats','cabinet'\]\)/.test(core),'STO desktop contract mismatch');
expect(/seller:\s*Object\.freeze\(\['seller','sellerProducts','sellerOrders','market','finance','parts','chats','cabinet'\]\)/.test(core),'seller desktop contract mismatch');
expect(/organization_store:\s*Object\.freeze\(\['seller','sellerProducts','sellerOrders','market','finance','parts','chats','cabinet'\]\)/.test(core),'store organization desktop contract mismatch');
expect(/organization:\s*Object\.freeze\(\['orders','workflow','calendarBooking','finance','crm','chats','cabinet'\]\)/.test(core),'generic organization desktop contract mismatch');
expect(shell.includes("workflow:'Производство'"),'production desktop label missing');
expect(shell.includes("finance:'Выручка / KPI'"),'STO KPI label missing');
expect(shell.includes("market:'Склад'"),'seller warehouse label missing');
expect(shell.includes("['organization_service','organization'].includes(kind)&&['workOrder','requestNew'].includes(key)"),'STO active routing must keep workflow as workflow');
expect(!shell.includes("['personal','master','organization_service','organization'].includes(kind)&&['workOrder','requestNew','workflow'].includes(key)"),'old workflow-to-orders active mapping still present');
expect(menu.includes("desktopPrimary=new Set(window.KaretaNavigationCore?.desktopItems?.()||[])"),'desktop drawer de-dup missing');
expect(menu.includes("window.matchMedia?.('(min-width: 861px)')"),'desktop-only drawer de-dup breakpoint missing');
expect(menu.includes("section.keys.filter(key=>!desktopPrimary.has(key))"),'desktop primary items are not filtered from drawer');
expect(/sto:\{ role:'sto'.*desktop:\['stoDashboard','orders','masters','workflow','serviceManagement','finance','parts','chats','cabinet'\]/.test(access),'legacy STO desktop policy mismatch');
expect(/seller:\{ role:'seller'.*desktop:\['seller','sellerProducts','sellerOrders','market','finance','parts','chats','cabinet'\]/.test(access),'legacy seller desktop policy mismatch');
console.log('R188.5.5.6.43 role desktop menu completion: OK');
