'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const auth=read('api/auth_session.php');
const bridge=read('api/identity/onboarding_identity_bridge.php');
const contexts=read('api/identity/context_service.php');
const capability=read('api/identity/capability_service.php');
const masterApi=read('api/master_onboarding.php');
const onbApi=read('js/next/onboarding/onboarding_api.js');
const onbApp=read('js/next/onboarding/onboarding_app.js');
const rolePage=read('js/next/onboarding/pages/role_page.js');
const resolverSource=read('js/next/onboarding/post_auth_first_entry_resolver.js');
const masterGate=read('js/next/master_onboarding_gate.js');
const firstVehicle=read('js/next/client/first_vehicle_flow.js');
const cabinet=read('js/next/pages/cabinet.js');
const cabinetApi=read('js/next/client/client_cabinet_api.js');
const db=read('api/db.php');
const assets=read('inc/asset_registry.php');
const navigation=read('js/next/navigation_core.js');
const roleAccess=read('js/next/role_access.js');
const shellNav=read('js/next/shell_nav.js');
const checks=[];
const expect=(name,ok)=>{checks.push([name,!!ok]);console.log(`${ok?'PASS':'FAIL'} ${name}`);};

expect('OTP carries selected entry role',onbApi.includes("entryRole:selectedRole")&&rolePage.includes("flow.entryRole || flow.role || state.selectedRole"));
expect('existing account uses post-auth resolver',rolePage.includes('app.targetAfterAuth?.(verifyResult,flow,user)'));
expect('new account uses post-auth resolver',onbApp.includes('targetAfterAuth(result,flow,user)')&&onbApp.includes('const target = options.target || targetAfterAuth'));
expect('legacy users.role is not route authority',onbApp.includes('legacy_role:legacyRole')&&onbApp.includes('result?.selectedRole || result?.entryRole'));
expect('backend verify activates selected role',auth.includes('establish($existingProfile,$selectedEntryRole)')&&auth.includes("'selectedRole' => $selectedEntryRole"));
expect('backend complete activates requested role',auth.includes('establish($profile,$requestedRole)')&&auth.includes("'selectedRole'=>$requestedRole"));
expect('identity bridge selects entry context before capabilities',bridge.includes('activateEntryRoleForOnboarding')&&bridge.indexOf('activateEntryRoleForOnboarding')<bridge.indexOf('->effective('));
expect('CLIENT and MASTER activation supported',contexts.includes("in_array($role,['client','master'],true)")&&contexts.includes("$role==='client'&&$type==='personal'")&&contexts.includes("$role==='master'&&$type==='profile'&&$profileType==='master'"));
expect('MASTER activation is separate from verification',contexts.includes("'verificationStatus'=>'unverified'")&&contexts.includes("'publicationStatus'=>'pending_onboarding'"));
expect('incomplete master hidden from public catalog',contexts.includes('UPDATE masters SET profile_visible=0')&&masterApi.includes("$put('profile_visible',1)"));
expect('MASTER work capabilities fail closed before completion',capability.includes("'master.onboarding.view'=>true")&&capability.includes('state_lookup_failed'));
expect('MASTER gate blocks work routes',masterGate.includes("ALLOWED_WHILE_BLOCKED")&&masterGate.includes("'masterOnboarding'"));

const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(resolverSource,sandbox);
const R=sandbox.window.KaretaPostAuthFirstEntryResolver;
const client=R.resolve({selectedRole:'client',identity:{currentContext:{type:'personal'}}},{entryRole:'client'},{role:'client'});
expect('scenario new CLIENT -> home before garage gate',client.role==='client'&&client.target==='#/home');
const masterNew=R.resolve({selectedRole:'master',identity:{currentContext:{type:'profile',profileType:'master'}},postAuth:{onboardingStatus:'not_started',step:1,view:'master-profile'}},{entryRole:'master'},{role:'client'});
expect('scenario new MASTER -> master onboarding',masterNew.target==='#/onboarding/master?step=1&view=master-profile'&&masterNew.firstEntryRequired===true);
const masterProgress=R.resolve({selectedRole:'master',identity:{currentContext:{type:'profile',profileType:'master'}},postAuth:{onboardingStatus:'in_progress',step:3,view:'master-work-place'}},{entryRole:'master'},{role:'client'});
expect('scenario MASTER draft restores exact step/view',masterProgress.target==='#/onboarding/master?step=3&view=master-work-place');
const masterDone=R.resolve({selectedRole:'master',identity:{currentContext:{type:'profile',profileType:'master'}},postAuth:{onboardingStatus:'completed',redirectRoute:'#/master'}},{entryRole:'master'},{role:'client'});
expect('scenario completed MASTER -> workspace',masterDone.target==='#/master'&&masterDone.firstEntryRequired===false);
const badMaster=R.resolve({selectedRole:'master',identity:{currentContext:{type:'personal'}},postAuth:{}},{entryRole:'master'},{role:'client'});
expect('MASTER never silently falls back PERSONAL',badMaster.ok===false&&badMaster.error==='master_context_not_selected');
const backClient=R.resolve({selectedRole:'client',identity:{currentContext:{type:'personal'}}},{entryRole:'client'},{role:'master'});
expect('scenario MASTER -> CLIENT selects personal route',backClient.role==='client'&&backClient.target==='#/home');
const returnMaster=R.resolve({selectedRole:'master',identity:{currentContext:{type:'profile',profileType:'master'}},postAuth:{onboardingStatus:'completed',redirectRoute:'#/master'}},{entryRole:'master'},{role:'client'});
expect('scenario CLIENT -> completed MASTER returns workspace',returnMaster.target==='#/master');

expect('client first vehicle flow restored',firstVehicle.includes('Ваш первый автомобиль')&&firstVehicle.includes('Автомобиль добавлен')&&firstVehicle.includes('В гараже пока нет автомобилей'));
expect('client garage inspected only after confirmed session',firstVehicle.includes("addEventListener('kareta:session-confirmed'")&&firstVehicle.includes('clientCabinet.get')===false&&firstVehicle.includes('api.get({cacheTtlMs:0'));
expect('client with any active/archive vehicle skips intro',firstVehicle.includes('vehicles.length||archived.length'));
expect('client may dismiss without creating vehicle',firstVehicle.includes("markPrompt('dismissed')")&&firstVehicle.includes('clearDraft()'));
expect('manual garage add starts at step 2',cabinet.includes("startStep:2")&&cabinet.includes("mode:'manual'"));
expect('automatic empty garage starts at step 1',cabinet.includes('consumePendingIntro')&&cabinet.includes('startStep:directFirstVehicle?2:1'));
expect('garage multi-vehicle lifecycle restored',cabinetApi.includes('setDefaultVehicle')&&cabinetApi.includes('archiveVehicle')&&cabinetApi.includes('restoreVehicle')&&cabinet.includes('data-garage-edit-vehicle'));
expect('request vehicle ownership is server enforced',db.includes("error'=>'client_vehicle_forbidden")&&db.includes("error'=>'client_scope_mismatch"));
expect('vehicle restore endpoint wired',db.includes("case 'vehicles.restore'")&&db.includes('function vehicles_restore'));
expect('assets load resolver before onboarding app',assets.indexOf('post_auth_first_entry_resolver.js')>0&&assets.indexOf('post_auth_first_entry_resolver.js')<assets.indexOf('onboarding_app.js'));
expect('assets load first vehicle after cabinet API',assets.indexOf('first_vehicle_flow.js')>assets.indexOf('client_cabinet_api.js')&&assets.includes('first_vehicle_flow.css'));
expect('removed role direction stays removed',!rolePage.includes('k-flow-role-direction')&&!rolePage.includes('k-flow-direction-button'));


expect('CLIENT mobile contract is six items',navigation.includes("personal: Object.freeze(['home','services','works','masters','parts','__more__'])")&&navigation.includes("['personal','master','seller','admin','organization_store'].includes(kind) ? 6 : 5"));
expect('legacy CLIENT fallback is also six items',roleAccess.includes("mobile:['home','services','works','masters','parts','__more__']"));
expect('garage active state maps mobile More / desktop Cabinet',shellNav.includes("const personalMoreKeys=new Set(['cabinetGarage'])")&&shellNav.includes("?'cabinet':key")&&shellNav.includes("?'__more__':key"));
const failed=checks.filter(x=>!x[1]);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed`);if(failed.length)process.exit(1);
