'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const expect=(v,m)=>{if(!v)throw new Error(m)};
const index=read('index.php');
const css=read('css/next/app_next.css');
const boot=read('css/runtime_boot_bundle.css');
const nav=read('js/next/shell_nav.js');
const version=read('inc/asset_version.php');
expect(index.includes('id="k-desktop-sidebar"'),'desktop sidebar markup missing');
expect(index.indexOf('id="k-desktop-sidebar"')>index.indexOf('</header>'),'desktop sidebar must live outside header');
expect(/--k-page-max:1440px/.test(css),'bounded desktop page max missing');
expect(/--k-desktop-sidebar-w:84px/.test(css),'compact rail width missing');
expect(/--k-desktop-sidebar-w:248px/.test(css),'full desktop sidebar width missing');
expect(/@media \(min-width:1024px\)/.test(css),'desktop breakpoint 1024 missing');
expect(/@media \(min-width:1280px\)/.test(css),'desktop full-sidebar breakpoint 1280 missing');
expect(/@media \(max-width:1023px\) and \(min-width:861px\)/.test(css),'tablet nav continuity breakpoint missing');
expect(css.includes('.k-desktop-sidebar{display:none}'),'desktop sidebar default hidden rule missing');
expect(nav.includes('title="${esc(route.label)}"'),'rail tooltip contract missing');
expect(boot.includes('R188.5.5.6.84.111 — shared desktop application shell'),'desktop shell not synced to boot CSS');
expect(boot.length<=850000,'boot CSS exceeds critical size budget: '+boot.length);
expect(version.includes('188.5.5.6.84.111'),'asset version not bumped');
console.log('DESKTOP_SHELL_84_111: PASS bounded=1440 rail=84 sidebar=248 tablet<=1023');
