'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const must=(cond,msg)=>{if(!cond){console.error('FAIL:',msg);process.exit(1)}};
const nav=read('js/next/navigation_core.js');
const role=read('js/next/role_access.js');
const mobile=read('js/next/mobile_back.js');
const index=read('index.php');
const css=read('css/next/master_orders_dedup.css');
const registry=read('inc/asset_registry.php');
const version=read('inc/asset_version.php');
const sw=read('sw.js');
must(nav.includes("master: Object.freeze(['masterDashboard','masterExchange','serviceManagement','parts','cabinet','__more__'])"),'master bottom nav still contains Orders');
must(!nav.includes("master: Object.freeze(['masterDashboard','masterExchange','orders','community','parts','__more__'])"),'old six-item master bottom nav remains');
must(nav.includes("master: Object.freeze({ key:'orders', label:'Открыть заявки', icon:'orders' })"),'master side orders action is not bound to orders');
must(nav.includes("['personal','master','seller','admin','organization_store'].includes(kind) ? 6 : 5"),'master mobile limit is not five');
must(role.includes("mobile:['masterDashboard','masterExchange','serviceManagement','parts','cabinet','__more__']"),'legacy master bottom nav still contains Orders');
must(index.includes('id="k-mobile-orders"')&&index.includes('aria-label="Открыть заявки"'),'side orders button is missing');
must(mobile.includes('function isOrdersSurface')&&mobile.includes("hash === '#/workflow'"),'side orders button does not cover workflow surfaces');
must(mobile.includes("button?.dataset.actionRoute || window.KaretaNavigationCore?.primaryAction?.().key || 'orders'"),'side orders routing fallback changed unexpectedly');
must(!css.includes('#k-mobile-nav'),'historical orders dedup must no longer own Master navigation geometry');
must(!registry.includes("'css/next/master_orders_dedup.css'"),'retired orders dedup CSS is still eager-registered');
must(version.includes('r1885587-master-mobile-orders-dedup'),'asset version missing');
must(sw.includes('r1885587-master-mobile-orders-dedup'),'service worker version missing');
console.log('OK R188.5.5.6.27 master mobile orders dedup');
