'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const expect=(v,m)=>{if(!v){console.error('FAIL:',m);process.exit(1)}};
const pageUi=read('js/next/page_ui.js');
const workplace=read('js/next/pages/master_workplace.js');
const schedule=read('js/next/pages/master_schedule.js');
const cabinet=read('js/next/pages/cabinet.js');
const services=read('js/next/pages/service_management.js');
const orders=read('js/next/pages/orders.js');
const routes=read('js/next/route_registry.js');
const css=read('css/next/master_surface_contract.css');
const version=read('inc/asset_version.php');
const sw=read('sw.js');
expect(pageUi.includes('function masterPageHeader('),'canonical masterPageHeader renderer missing');
expect(pageUi.includes('? masterPageHeader(title, subtitle, { eyebrow, actions })'),'pageShell does not route Master workspaces through canonical header');
expect(workplace.includes('k-master-page-header__copy'),'#/master header not migrated');
expect(!workplace.includes('k-page-hero'),'#/master still contains a page hero');
expect(schedule.includes('k-master-page-header__copy')&&schedule.includes('k-master-page-header__actions'),'#/master/schedule header not migrated');
expect(cabinet.includes("ui.masterPageHeader(title,text,{eyebrow:'НАСТРОЙКИ МАСТЕРА'"),'Master settings do not use canonical header');
expect(cabinet.includes('k-master-page-header__back'),'Master settings Back action is not in canonical action slot');
expect(services.includes("ui.pageShell(context,'Мои услуги'"),'#/services/manage is not on shared pageShell');
expect(orders.includes('return ui.pageShell(context,copy.title,copy.description'),'Master requests/orders are not on shared pageShell');
for(const pair of [["'#/master/requests':'#/orders'",'master requests alias'],["'#/master/workplace':'#/master'",'master workplace alias'],["'#/master/settings':'#/cabinet/settings'",'master settings alias']]) expect(routes.includes(pair[0]),`${pair[1]} missing`);
expect(workplace.includes("Object.freeze(['header','status','quick-actions','my-requests','notes','paused','today'])"),'task 101 order regressed');
expect(css.includes('R188.5.5.6.84.108 — MASTER HEADER CONTRACT'),'84.108 CSS contract missing');
expect(css.includes('--k-master-page-header-h:88px')&&css.includes('--k-master-page-header-mobile-h:72px'),'canonical header heights missing');
expect(css.includes('#k-shell-header>#k-mobile-back.k-mobile-back'),'Master mobile Back placement is not locked');
expect(css.includes('#k-shell-header>.k-brand')&&css.includes('transform:translate(-50%,-50%)!important'),'Master mobile brand position is not locked');
expect(version.includes("KARETA_ASSET_VERSION = '188.5.5.6.84.108'"),'asset version is not 84.108');
expect(sw.includes("RELEASE = '188.5.5.6.84.108'"),'service worker release is not 84.108');
console.log('OK MASTER HEADER CONTRACT 84.108');
