const fs=require('fs');
const read=f=>fs.readFileSync(f,'utf8');
const must=(v,m)=>{if(!v)throw new Error(m)};
const info=read('js/next/pages/info.js');
const works=read('js/next/pages/work_feed.js');
const cards=read('js/next/catalog_cards.js');
const css=read('css/next/client_surface_modernization_phase2.css');
const reg=read('inc/asset_registry.php');
const av=read('inc/asset_version.php');
const sw=read('sw.js');
must(info.includes('k-info-ref-v2')&&info.includes('k-info-ref-service-hero')&&info.includes('data-lawyer-chat')&&info.includes('data-tow-location'),'info/service surfaces missing');
must(!info.includes('onclick="history.back()"'),'legacy inline back handler remains');
must(works.includes('k-work-feed-ref-v2')&&works.includes('k-work-detail-ref-v2')&&works.includes('k-work-detail-ref-post'),'work surfaces missing');
must(cards.includes('data-work-save="${esc(item.id)}"'),'work save action missing');
must(css.includes('.k-work-feed-page.k-work-feed-ref-v2')&&css.includes('.k-work-detail-window.k-work-detail-ref-v2')&&css.includes('.k-info-ref-page.k-info-ref-v2'),'phase2 css contract missing');
must(css.includes('var(--k-client-mobile-nav-clearance,86px)'),'mobile nav clearance missing');
must(reg.includes("'css/next/client_surface_modernization_phase2.css'"),'phase2 CSS not registered');
const va=(av.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1],vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
must(/^188\.5\.5\.6\.84\.(?:6[2-9]|[7-9]\d|\d{3,})$/.test(va)&&vs===va,'84.62+ version mismatch');
console.log('R188.5.5.6.84.62 client surface modernization phase 2: OK');
