const fs=require('fs');
const read=f=>fs.readFileSync(f,'utf8');
const must=(v,m)=>{if(!v)throw new Error(m)};
const n=read('js/next/pages/notifications.js');
const d=read('js/next/pages/details.js');
const f=read('js/next/pages/following.js');
const p=read('js/next/pages/profile_relations.js');
const css=read('css/next/client_legacy_surface_modernization.css');
const reg=read('inc/asset_registry.php');
const av=read('inc/asset_version.php');
const sw=read('sw.js');
must(n.includes('k-notifications-ref-v2')&&n.includes('data-notifications-tab="unread"')&&n.includes('k-notification-ref-card'),'notifications v2 missing');
must(d.includes('k-service-detail-ref')&&d.includes('Что входит в работу')&&d.includes('Предложения мастеров и СТО'),'service detail v2 missing');
must(f.includes('k-following-ref-v2'),'following v2 missing');
must(p.includes('k-profile-ref-v2'),'profile v2 missing');
must(css.includes('.k-service-detail-ref-primary')&&css.includes('.k-profile-page.k-profile-ref-v2')&&css.includes('.k-following-page.k-following-ref-v2'),'surface CSS missing');
must(reg.includes("'css/next/client_legacy_surface_modernization.css'"),'late CSS not registered');
const va=(av.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1],vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
must(/^188\.5\.5\.6\.84\.(?:6[1-9]|[7-9]\d|\d{3,})$/.test(va)&&vs===va,'84.61+ version mismatch');
console.log('R188.5.5.6.84.61 client surface modernization phase 1: OK');
