'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),fail=[];
const expect=(value,message)=>{if(!value)fail.push(message)};
const page=read('js/next/pages/seller.js');
const details=read('js/next/pages/details.js');
const api=read('api/seller_shop.php');
const db=read('api/db.php');
const publicDetail=read('api/catalog_details.php');
const sellerApi=read('js/next/seller/seller_api.js');
const client=read('js/next/api_client.js');
const routes=read('js/next/route_registry.js');
const css=read('css/next/seller_profile_storefront_native.css');
const registry=read('inc/asset_registry.php');
const asset=read('inc/asset_version.php');
const sw=read('sw.js');
const config=read('config.php');
const migration=read('api/migrations/116_seller_storefront_profile.php');
const bootstrap=read('api/bootstrap.php');
const manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
const dbv=Number((/KARETA_DB_VERSION',\s*(\d+)/.exec(config)||[])[1]||0);
expect(dbv===116,'R63 expected DB version 116');
for(const token of ['data-seller-open-profile','data-seller-profile-form','returnPolicy','data-seller-archive-products','data-seller-restore','data-seller-stock-delta','data-seller-stock-open','data-seller-order-search','openOrderChat','client_user_id','maskPhone'])expect(page.includes(token),`R63 seller UI missing ${token}`);
expect(!/<select\b/i.test(page),'R63 seller UI must not contain select controls');
expect(!/swiper/i.test(page),'R63 seller UI must not use Swiper');
for(const token of ['shop_storefront','seller_product_restore','seller_product_stock','archivedProducts','category_labels','client_user_id',"status='draft'",'warehouse.stock.manage'])expect(api.includes(token),`R63 seller API missing ${token}`);
for(const token of ["shop.store","seller.products.restore","seller.products.stock"])expect(db.includes(token),`R63 db router missing ${token}`);
for(const token of ['restoreProduct','updateStock'])expect(sellerApi.includes(token),`R63 seller JS API missing ${token}`);
expect(client.includes('storeDetail')&&client.includes('getStoreDetail'),'R63 public storefront client endpoint missing');
expect(routes.includes("^#\\/parts\\/store\\/[^/]+$/.test(hash)) return 'productDetail'"),'R63 storefront route must reuse productDetail surface');
for(const token of ['mountStore','data-storefront-chat','kareta.chat.open','openSupportChat','category_labels'])expect(details.includes(token),`R63 storefront UI missing ${token}`);
expect(!publicDetail.includes('sp.contact_phone')&&!publicDetail.includes('sp.email'),'public product detail must not expose seller phone/email');
expect(!api.match(/shop_storefront[\s\S]*?SELECT[\s\S]*?(contact_phone|\bemail\b)[\s\S]*?FROM seller_profiles/),'public storefront query must not expose seller phone/email');
for(const token of ['return_policy','moderation_reason','version\' => 116','ALTER TABLE seller_profiles'])expect(migration.includes(token),`R63 migration missing ${token}`);
expect(bootstrap.includes('`return_policy` VARCHAR(1000)')&&bootstrap.includes('`moderation_reason` VARCHAR(500)')&&bootstrap.includes(':return_policy'),'R63 bootstrap schema/upsert missing storefront profile columns');
for(const token of ['.k-seller-profile-summary','.k-seller-profile-dialog','.k-seller-stock-quick','.k-seller-archive-card','.k-storefront-hero','.k-storefront-trust','.k-storefront-products','.k-storefront-info','height:100dvh'])expect(css.includes(token),`R63 CSS missing ${token}`);
expect(!css.includes('#k-mobile-nav')&&!css.includes('#k-desktop-nav')&&!css.includes('#k-menu-toggle'),'R63 CSS must not alter frozen Shell');
expect(registry.includes('css/next/seller_profile_storefront_native.css'),'R63 stylesheet missing from registry');
expect(asset.includes('r1885623-seller-profile-storefront-native')&&sw.includes('r1885623-seller-profile-storefront-native'),'R63 release suffix missing from asset/SW');
for(const [file,hash] of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`)}
if(fail.length){console.error(fail.join('\n'));process.exit(1)}
console.log('R188.5.5.6.63 seller profile + storefront + archive/stock + order chat + Shell Freeze 2 OK');
