'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const failures=[];const expect=(v,m)=>{if(!v)failures.push(m)};
const config=read('config.php'),migration=read('api/migrations/112_master_social_wall.php'),server=read('api/master_social_wall.php'),db=read('api/db.php'),route=read('js/next/route_registry.js'),dynamic=read('js/next/dynamic_navigation.js'),role=read('js/next/role_access.js'),icons=read('js/next/ui_icons.js'),app=read('js/next/app_next.js'),page=read('js/next/pages/master_wall.js'),css=read('css/next/master_social_wall.css'),details=read('js/next/pages/details.js'),community=read('js/next/pages/community.js'),catalog=read('api/catalog_details.php'),registry=read('inc/asset_registry.php'),manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
expect((/KARETA_DB_VERSION',\s*(\d+)/.exec(config)||[])[1]>=112,'DB version must be >=112');expect(migration.includes("'version' => 112"),'migration 112 missing');for(const t of ['visibility','linked_product_id','video_url','published_at','master_wall_reactions','master_wall_saved','master_wall_comments_social'])expect(migration.includes(t),`migration contract missing ${t}`);
expect(db.includes("require_once __DIR__ . '/master_social_wall.php'"),'master_social_wall server include missing');for(const t of ['masterSocialWall.feed','masterSocialWall.community','masterSocialWall.mine','masterSocialWall.comments','masterSocialWall.save','masterSocialWall.delete','masterSocialWall.like','masterSocialWall.saveState','masterSocialWall.comment','masterSocialWall.commentDelete'])expect(db.includes(t),`API missing ${t}`);
for(const t of ["['note','advice','news','video','part']",'kareta_master_social_wall_feed','kareta_master_social_wall_community','kareta_master_social_wall_save','kareta_master_social_wall_comments','work_posts','news_articles','profile.manage'])expect(server.includes(t),`server contract missing ${t}`);expect(!server.includes("['note','advice','news','video','part','work']"),'work may not be generic editable wall type');expect(server.includes("LEFT JOIN users u ON u.id=m.user_id"),'Community wall author avatar/name must come from users rather than unsupported masters.avatar_url');
expect(route.includes("masterWallOwner:Object.freeze({ path:'#/master/wall'"),'owner wall route missing');expect(dynamic.includes("{ key:'masterWallOwner'")&&dynamic.includes("profile.manage"),'owner wall capability gate missing');expect(role.includes("'masterWallOwner'"),'role access missing owner wall');expect(icons.includes("masterWallOwner:'community'"),'route icon missing');for(const t of ['KaretaMasterWallPages','masterWallOwner:masterWallPages.renderMasterWall','masterWallOwner:masterWallPages.mountMasterWall'])expect(app.includes(t),`app integration missing ${t}`);
for(const t of ['Моя Стена','Новая публикация','Публикация','Совет','Новость','Видео','Запчасть','Опубликовать','Черновик','masterSocialWall.save'])expect(page.includes(t),`owner page missing ${t}`);expect(!page.includes('<select'),'owner wall must not use select/dropdown');expect(!page.includes('Swiper'),'owner wall must not use Swiper');expect(!css.includes('scroll-snap-type'),'wall CSS must not introduce horizontal slider pattern');
for(const t of ['masterSocialWall.feed','masterSocialWall.comments','masterSocialWall.like','masterSocialWall.saveState','data-provider-open="wall-filter"'])expect(details.includes(t),`public wall missing ${t}`);expect(details.includes("source==='work'")&&details.includes('api.likeWorkPost')&&details.includes('api.getWorkPostComments'),'verified works must retain work social lifecycle');
for(const t of ['masterSocialWall.community','Публикации Мастеров','socialSource:\'masterWall\'','masterSocialWall.comment','masterSocialWall.like','masterSocialWall.saveState'])expect(community.includes(t),`Community integration missing ${t}`);expect(catalog.includes('wallPosts'),'public profile summary must include unified wall posts');expect(registry.includes('js/next/pages/master_wall.js')&&registry.includes('css/next/master_social_wall.css'),'R54 assets missing');
for(const f of ['inc/asset_version.php','sw.js'])expect(read(f).includes('r1885614-master-social-wall'),`${f} release suffix missing`);
for(const f of ['js/next/pages/master_profile_owner.js','js/next/pages/cabinet.js','js/next/pages/community.js'])expect(read(f).includes('#/master/wall'),`${f} must link to unified wall`);
const workplace=read('js/next/pages/master_workplace.js');if(!workplace.includes("NATIVE_WORKPLACE_CONTRACT='R188.5.5.6.55'"))expect(workplace.includes('#/master/wall'),'legacy workplace must link to unified wall');
for(const [file,hash] of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`)}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('R188.5.5.6.54 Master unified social wall: typed posts + verified works + Community + server social + shell freeze OK');
