'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const assert=(v,m)=>{if(!v)throw new Error(m);};
const migration=read('api/migrations/106_operational_finance_payroll_receivables.php');
for(const table of ['sto_cash_accounts','sto_cash_movements','work_order_receivables','sto_master_payroll_rules','sto_payroll_periods','sto_payroll_accruals'])assert(migration.includes(table),`missing ${table}`);
const api=read('api/operational_finance.php');
for(const fn of ['kareta_operational_finance_dashboard','kareta_operational_finance_order_payment','kareta_operational_finance_expense','kareta_operational_finance_payroll_rule_save','kareta_operational_finance_payroll_close','kareta_operational_finance_payroll_pay','kareta_operational_finance_receivable_due'])assert(api.includes(`function ${fn}`),`missing ${fn}`);
for(const table of ['finance_invoices','finance_transactions','payment_records','finance_ledger','work_order_financial_results'])assert(api.includes(table),`finance integration missing ${table}`);
assert(api.includes("$financeActor['masterId']=$masterId")&&api.includes('kareta_master_aftercare_recalculate($pdo,$orderId,$order,$financeActor)'), 'order payment must recalculate with assigned master settings');
const aftercare=read('api/master_order_aftercare.php');assert(aftercare.includes('?array $actorOverride=null')&&aftercare.includes('$actor=$actorOverride?:kareta_master_aftercare_actor($pdo)'), 'aftercare actor override missing');
const db=read('api/db.php');
for(const action of ['operationalFinance.dashboard','operationalFinance.orderPayment.record','operationalFinance.expense.record','operationalFinance.payrollRule.save','operationalFinance.payroll.close','operationalFinance.payroll.pay','operationalFinance.receivable.due'])assert(db.includes(action),`missing dispatch ${action}`);
const page=read('js/next/pages/finance.js');
for(const marker of ['data-order-pay','data-payroll-close','data-payroll-rule','data-payroll-pay','data-cash-expense','serviceProfitability','masterProfitability'])assert(page.includes(marker),`missing UI ${marker}`);
const client=read('js/next/api_client.js');
for(const marker of ['getOperationalFinanceDashboard','recordOrderPayment','recordStoExpense','savePayrollRule','closePayrollPeriod','payPayroll','updateReceivableDue'])assert(client.includes(marker),`missing client ${marker}`);
const master=fs.existsSync(path.join(root,'js/next/master_surface_runtime.js'))?read('js/next/master_surface_runtime.js'):'';const cabinet=read('js/next/pages/cabinet.js');const hub=read('js/next/smart_action_hub.js');const r84=read('inc/asset_version.php').includes('r1885644-global-ux-cleanup-legacy-removal');assert((r84||master.includes("'finance'"))&&cabinet.includes("'#/finance'")&&hub.includes("key:'finance'"),'master finance access missing');
console.log('R188.5.5.6.20 operational finance OK');
