'use strict';
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const assert=(v,m)=>{if(!v)throw new Error(m);};
const migration=read('api/migrations/104_master_order_full_lifecycle.php');
for(const table of ['master_order_diagnostics','work_order_part_reservations','work_order_quality_checks','work_order_handovers','work_order_warranties','work_order_publication_policies'])assert(migration.includes(table),`missing ${table}`);
const engine=read('api/sto_workflow_engine.php');
for(const stage of ['diagnostics','approval','parts_reservation','quality_control','delivery','warranty','completed'])assert(engine.includes(`'${stage}'`),`missing stage ${stage}`);
for(const condition of ['diagnostics_report','parts_not_reserved','quality_not_passed','handover_not_accepted','warranty_not_activated'])assert(engine.includes(condition),`missing requirement ${condition}`);
const lifecycle=read('api/master_order_lifecycle.php');
for(const fn of ['kareta_master_order_accept','kareta_master_order_diagnostics_save','kareta_master_order_extra_request','kareta_client_order_extra_decide','kareta_master_order_parts_reserve','kareta_master_order_quality_save','kareta_master_order_handover_prepare','kareta_client_order_handover_confirm'])assert(lifecycle.includes(`function ${fn}`),`missing ${fn}`);
assert(lifecycle.includes("'automatic'=>true")&&lifecycle.includes('consentVerified'),'automatic publication is not consent-verified');
assert(lifecycle.includes('quality_checks_incomplete')&&lifecycle.includes("'noLeaks'")&&lifecycle.includes("'clientRequestVerified'"),'quality pass is not guarded by mandatory checks');
for(const marker of ['lifecycle_stage_conflict','parts_required_by_diagnostics','diagnostics_incomplete','handover_payment_pending'])assert(lifecycle.includes(marker),`missing lifecycle guard ${marker}`);
const lifecycleCss=read('css/next/master_order_lifecycle.css');
assert(lifecycleCss.includes('repeat(12,minmax(92px,1fr))')&&lifecycleCss.includes('repeat(12,112px)'),'workflow track does not support 12 stages');
const page=read('js/next/pages/work_order.js');
for(const marker of ['data-lifecycle-form="diagnostics"','data-lifecycle-form="quality"','data-lifecycle-form="handover"','data-lifecycle-form="delivery"','data-lifecycle-click="open-reserve"'])assert(page.includes(marker),`missing UI ${marker}`);
const db=read('api/db.php');
for(const action of ['masterOrder.accept','masterOrder.diagnostics.save','masterOrder.extraWork.request','clientOrder.extraWork.decide','masterOrder.parts.reserve','masterOrder.quality.save','masterOrder.handover.prepare','clientOrder.handover.confirm'])assert(db.includes(`'${action}'`),`missing dispatch ${action}`);
console.log('R188.5.5.6.18 master order lifecycle OK');
