const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m);};
const details=read('js/next/pages/details.js');
const seller=read('js/next/pages/seller.js');
const parts=read('js/next/pages/parts.js');
const storeCss=read('css/next/seller_profile_storefront_native.css');
const usedCss=read('css/next/used_market_listing_wizard.css');
const asset=read('inc/asset_version.php');
const sw=read('sw.js');
ok(details.includes('k-storefront-ref-page'),'public storefront reference root missing');
ok(details.includes('data-storefront-search'),'storefront search missing');
ok(details.includes('data-storefront-tab="products"'),'storefront tabs missing');
ok(seller.includes('k-seller-profile-summary--ref'),'seller profile reference card missing');
ok(seller.includes('Профиль заполнен на ${percent}%'),'seller completion meter missing');
ok(parts.includes('k-listing-main-steps'),'listing four-stage stepper missing');
ok(parts.includes('ЭТАП ${macro} ИЗ 4'),'listing macro step label missing');
ok(storeCss.includes('R188.5.5.6.84.48'),'storefront css release contract missing');
ok(usedCss.includes('four-stage used-parts listing K-Flow'),'listing css contract missing');
const av=(asset.match(/KARETA_ASSET_VERSION = '188\.5\.5\.6\.84\.(\d+)'/)||[])[1];const sv=(sw.match(/RELEASE = '188\.5\.5\.6\.84\.(\d+)'/)||[])[1];ok(Number(av)>=48&&Number(sv)>=48&&av===sv,'version mismatch');
console.log('R188.5.5.6.84.48 seller/storefront/used-listing regression: OK');
