'use strict';
const fs=require('fs');
const core=fs.readFileSync('js/next/navigation_core.js','utf8');
const shell=fs.readFileSync('js/next/shell_nav.js','utf8');
const fail=m=>{throw new Error(m)};
const expect=(cond,m)=>{if(!cond)fail(m)};
expect(core.includes('const DESKTOP_TEMPLATES = Object.freeze({'),'desktop templates missing');
expect(/personal:\s*Object\.freeze\(\['home','services','community','masters','parts','orders','chats'\]\)/.test(core),'client desktop template mismatch');
expect(/master:\s*Object\.freeze\(\['masterDashboard','masterExchange','orders','masterSchedule','serviceManagement','parts','community','chats','cabinet'\]\)/.test(core),'master desktop template mismatch');
expect(core.includes("if (role === 'master') return 'master';"),'degraded Master context lost');
expect(core.includes("if (role === 'seller') return 'seller';"),'degraded Seller context lost');
expect(core.includes("if (['sto','service'].includes(role)) return 'organization_service';"),'degraded STO context lost');
expect(shell.includes('function itemsFor(surface)')&&shell.includes("access?.keys?.(surface)"),'mode-aware role-access fallback missing');
expect(shell.includes("identity.mode==='identity'"),'Identity navigation authority guard missing');
expect(shell.includes("master:{masterDashboard:'Рабочее место',masterExchange:'Биржа',orders:'Заявки'"),'master labels missing');
console.log('R188.5.5.6.84.150 contextual desktop navigation: OK');
