'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[];
const expect=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const flow=read('js/next/client/first_vehicle_flow.js');
const css=read('css/next/first_vehicle_flow.css');
const cabinet=read('js/next/pages/cabinet.js');
const nav=read('js/next/navigation_core.js');
const access=read('js/next/role_access.js');
const shell=read('js/next/shell_nav.js');
const db=read('api/db.php');
const assets=read('inc/asset_registry.php');
const version=read('inc/asset_version.php');
const sw=read('sw.js');
['Ваш первый автомобиль','Основные данные','Автомобиль добавлен','В гараже пока нет автомобилей'].forEach(t=>expect(`flow:${t}`,flow.includes(t)));
expect('details screen removed',!flow.includes('function details(draft)')&&!flow.includes('data-first-vehicle-form="details"'));
expect('two progress steps',flow.includes("['1','Старт']")&&flow.includes("['2','Автомобиль']")&&!flow.includes("['3','Гараж']"));
expect('draft localStorage scoped',flow.includes('DRAFT_PREFIX')&&flow.includes('localStorage.setItem(draftKey()'));
expect('skip prompt without empty vehicle',flow.includes("markPrompt('dismissed')")&&flow.includes('clearDraft()'));
expect('minimal first card excludes VIN validation screen',!flow.includes('validateDetails')&&!flow.includes('VIN должен содержать 17 символов')||flow.includes('vehicle_duplicate_vin'));
expect('custom model branch',flow.includes('Моей модели нет')&&flow.includes("modelId:'custom'"));
expect('success request prefill',flow.includes('kareta.request.prefill')&&flow.includes('first_vehicle_success'));
expect('manual flow starts step2',flow.includes("state.step=startStep===1&&!state.editVehicleId?1:2"));
expect('manual back returns garage',flow.includes("state.step===2&&state.mode!=='intro'"));
expect('save double-click blocked',flow.includes('if(state.saving)return')&&flow.includes("disabled aria-busy"));
expect('responsive phone/tablet/desktop css',css.includes('@media(max-width:390px)')&&css.includes('@media(max-width:760px)')&&css.includes('@media(min-width:761px) and (max-width:1099px)')&&css.includes('@media(min-width:1100px)'));
expect('first vehicle page owns fullscreen surface',css.includes('.k-page.k-client-cabinet-page.k-first-vehicle-page')&&css.includes('max-width:none!important'));
expect('advanced data moved to garage',cabinet.includes('data-vehicle-passport-form')&&cabinet.includes('Дополнить данные автомобиля'));
expect('approved palette',css.includes('#F47A21')&&css.includes('#F8F6F2')&&css.includes('#D83A3A')&&css.includes('#2F9B62'));
expect('cabinet empty routes into flow',cabinet.includes('firstVehicleFlow.emptyGarage()')&&cabinet.includes("startStep:2")&&cabinet.includes('startStep:directFirstVehicle?2:1'));
expect('client mobile six actions',nav.includes("personal: Object.freeze(['home','services','works','masters','parts','__more__'])")&&nav.includes("['personal','master','seller','admin','organization_store'].includes(kind) ? 6 : 5"));
expect('legacy client six actions',access.includes("mobile:['home','services','works','masters','parts','__more__']")&&access.includes("key==='__more__'||registry.has(key)"));
expect('garage activates More and desktop cabinet',shell.includes("const personalMoreKeys=new Set(['cabinetGarage'])")&&shell.includes("?'cabinet':key")&&shell.includes("?'__more__':key")&&shell.includes('[data-mobile-more]'));
expect('server strict VIN',db.includes("error'=>'invalid_vehicle_vin")&&db.includes('A-HJ-NPR-Z0-9]{17}'));
expect('server VIN duplicate',db.includes("error'=>'vehicle_duplicate_vin")&&db.includes('stDupVin'));
expect('server plate duplicate',db.includes("error'=>'vehicle_duplicate_plate")&&db.includes('stDupPlate'));
expect('first vehicle auto primary',db.includes('stVehicleCount')&&db.includes('$isDefault=1'));
expect('new assets registered',assets.includes('css/next/first_vehicle_flow.css')&&assets.includes('js/next/client/first_vehicle_flow.js'));
expect('release current first-entry generation',/188\.5\.5\.6\.84\.(?:2[1-9]|[3-9]\d)/.test(version)&&/188\.5\.5\.6\.84\.(?:2[1-9]|[3-9]\d)/.test(sw));
const failed=checks.filter(x=>!x.ok);for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'} ${c.name}`);console.log(`\n${checks.length-failed.length}/${checks.length} checks passed`);if(failed.length)process.exit(1);
