'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const assert=(ok,msg)=>{if(!ok){console.error('[FAIL]',msg);process.exitCode=1;}else console.log('[OK]',msg);};
const css=read('css/next/client_mobile_geometry.css');
const registry=read('inc/asset_registry.php');
const guard=read('css/next/client_width_guard.css');
const layout=read('css/next/client_surface_layout.css');
const version=read('inc/asset_version.php');
const sw=read('sw.js');
assert(registry.includes("'css/next/client_mobile_geometry.css'"),'mobile geometry stylesheet registered');
assert(registry.indexOf("'css/next/client_mobile_geometry.css'")>registry.indexOf("'css/next/client_width_guard.css'"),'mobile geometry loads after width guard');
assert(css.includes('--k-mobile-nav-count:6!important'),'client bottom navigation is fixed to six items');
assert(css.includes('grid-template-columns:repeat(6,minmax(0,1fr))!important'),'six nav tracks are shrink-safe');
assert(css.includes('@media(max-width:359px)')&&css.includes('@media(min-width:360px) and (max-width:430px)')&&css.includes('@media(min-width:431px) and (max-width:767px)')&&css.includes('@media(min-width:768px) and (max-width:900px)'),'320/360/430/768 geometry breakpoints exist');
assert(css.includes('grid-template-columns:minmax(0,61.8fr) minmax(220px,38.2fr)!important'),'tablet community uses shrinkable 61.8/38.2 split');
assert(css.includes('.k-master-reference-filters{')&&css.includes('overflow-x:auto!important'),'master filters use a local horizontal rail');
assert(css.includes('.k-master-reference-card__main{')&&css.includes('grid-template-columns:clamp(112px,35vw,146px) minmax(0,1fr)!important'),'master card photo/text ratio scales on phones');
assert(css.includes('.k-parts-ref-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important'),'parts remains a safe two-column mobile grid');
assert(css.includes('[data-page="services"] .k-services-ref-tabs{')&&css.includes('overflow-x:auto!important'),'services tabs scroll locally on mobile');
assert(layout.includes('margin-bottom: 43px !important;'),'requested 43px client page clearance remains intact');
assert(/\.k-flow-community-main\.k-community-feed-column[\s\S]*?max-width:100%!important/.test(guard),'community feed width guard remains intact');
assert(/188\.5\.5\.6\.84\.(?:5[6-9]|[6-9]\d|\d{3,})/.test(version),'asset version is 84.56+');
assert(/188\.5\.5\.6\.84\.(?:5[6-9]|[6-9]\d|\d{3,})/.test(sw),'service worker version is 84.56+');
if(process.exitCode)process.exit(process.exitCode);else console.log('client mobile geometry 84.56 OK');
