'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('js/next/pages/parts.js','utf8');
const snapshot={products:[{id:'n1',name:'Brake disc',category:'brakes',price:100,image_url:'/photos/disc.jpg'},{id:'n2',name:'Oil filter',category:'filter',price:50}],categories:Array.from({length:12},(_,i)=>({key:i===0?'brakes':`category-${i}`,name:`Category ${i}`})),cart:[]};
const sandbox={window:{KaretaShopState:{getSnapshot:()=>snapshot},KaretaApiClient:{},KaretaCatalogCards:{}},document:{documentElement:{lang:'ru'},querySelector:()=>null},location:{hash:'#/parts'},URLSearchParams,Intl};
// Instrument only the in-memory module to exercise its real filtering/rendering functions.
const instrumented=source.replace('window.KaretaPartsPages=Object.freeze({renderParts,mountParts});','window.KaretaPartsPages={renderParts,readHashContext,categoryGrid,catalogContent,marketItems,categoryMedia,explicitCompatibility,setState:v=>{state=v;},getState:()=>state,setRows:v=>{usedRows=v;}};');
vm.runInNewContext(instrumented,sandbox);
const page=sandbox.window.KaretaPartsPages;
const vehicle={brand:'Toyota',model:'Camry',year:2012};
assert.equal(page.explicitCompatibility({vehicle:'Honda Civic 2012'},'used',vehicle),false,'matching year alone must not imply fitment');
assert.equal(page.explicitCompatibility({vehicle:'Toyota Corolla'},'used',vehicle),false,'matching brand alone must not imply fitment');
assert.equal(page.explicitCompatibility({description:'Toyota Camry'},'used',vehicle),false,'marketing description is not a fitment declaration');
assert.equal(page.explicitCompatibility({vehicle:'Toyota Camry 2012'},'used',vehicle),true);
assert.equal(page.explicitCompatibility({fitment:[{brand:'Toyota',model:'Corolla'},{brand:'Honda',model:'Camry'}]},'store',vehicle),false,'brand/model must be declared together in one fitment record');
const baseline={search:'',type:'all',category:'',city:'',sort:'newest'};
page.setState({...baseline});
assert.equal((page.categoryGrid(snapshot).match(/data-market-category=/g)||[]).length,12,'all available category tiles remain reachable');
assert.match(page.categoryGrid(snapshot),/src="\/photos\/disc.jpg"/,'category uses a product photograph');
assert.match(page.categoryMedia({key:'brakes',name:'Brakes',icon:'parts'},{products:[{category:'brakes',image_url:'/photo.jpg?x=" onload="bad'}]}),/&quot;/,'image attributes are escaped');
assert.match(page.renderParts(),/#\/parts\/used\?type=exchange/,'shop links directly to exchanges');
page.setState({...baseline,search:'Oil'});
assert.doesNotMatch(page.catalogContent(snapshot),/Brake disc/,'main shop respects search');
assert.match(page.catalogContent(snapshot),/Oil filter/);
sandbox.location.hash='#/parts/used?type=exchange';
page.setState({...baseline});page.readHashContext();
assert.equal(page.getState().type,'exchange','exchange deep link selects the exchange type');
page.setRows([{id:'u1',title:'Swap disc',category:'brakes',listingType:'exchange',image:'/photos/swap.jpg'},{id:'u2',title:'Used disc',category:'brakes',listingType:'used'},{id:'u3',title:'Swap filter',category:'filter',listingType:'exchange'}]);
assert.match(page.renderParts(),/data-used-exchange/,'owner can start an exchange listing');
assert.match(page.catalogContent(snapshot),/Swap disc/);
assert.doesNotMatch(page.catalogContent(snapshot),/Used disc/,'exchange mode excludes sale-only listings');
page.setState({...baseline,type:'exchange',category:'brakes'});
assert.equal(page.marketItems(snapshot).length,1,'exchange and category filters compose');
assert.equal(page.marketItems(snapshot)[0].item.id,'u1');
assert.match(page.categoryGrid(snapshot),/src="\/photos\/swap.jpg"/,'used categories use private listing photos');
sandbox.document.documentElement.lang='kk';assert.match(page.renderParts(),/>Бөлшегімді айырбастау</);
sandbox.document.documentElement.lang='en';assert.match(page.renderParts(),/>Swap my part</);
page.setState({...baseline,type:'sale'});assert.equal(page.marketItems(snapshot).length,1,'sale mode excludes swaps');
assert.match(page.renderParts(),/data-parts-ref-type="sale"/,'used shop exposes sale and swap scenarios');
const detailSource=fs.readFileSync('js/next/pages/details.js','utf8');
const detailTest=detailSource.replace(/\}\)\(\);\s*$/,'window.__usedOfferTest=usedOfferMessage;})();');
vm.runInNewContext(detailTest,sandbox);
const offer=sandbox.window.__usedOfferTest;
const target={id:'starter',title:'Starter',status:'active',isMine:false};
const own={id:'alternator',title:'Alternator',status:'active',isMine:true,listingType:'used'};
assert.match(offer(target,'price','10000'),/10000 ₸/);
assert.match(offer(target,'exchange','0',own),/used%3Aalternator/,'swap message links the offered listing');
assert.throws(()=>offer(target,'price','NaN'),/корректную сумму/);
assert.throws(()=>offer({...target,status:'sold'},'price','10000'),/активного чужого/);
assert.throws(()=>offer({...target,isMine:true},'price','10000'),/активного чужого/);
assert.throws(()=>offer(target,'exchange','0',{...own,isMine:false}),/своё активное/);
assert.throws(()=>offer(target,'exchange','0',{...own,status:'draft'}),/своё активное/);
for(const file of ['css/next/parts_native_marketplace.css','css/routes/parts_runtime.css'])assert.match(fs.readFileSync(file,'utf8'),/\.k-parts-ref-categories\.k-parts-visual-categories>div\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'two-column mobile category layout is present in source and lazy CSS');
console.log('PASS: category photos, escaping, all categories, search, exchange deep link/type/category isolation, RU/KK/EN and lazy CSS');
