'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const failures=[];const expect=(v,m)=>{if(!v)failures.push(m)};
const core=read('js/next/pages/core.js'),cabinet=read('js/next/pages/cabinet.js'),css=read('css/next/client_account_native.css'),registry=read('inc/asset_registry.php'),manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
const homeStart=core.indexOf('function renderHome(context)'),homeEnd=core.indexOf('function mountHome(context',homeStart),home=core.slice(homeStart,homeEnd);
for(const token of ['k-home-reference','data-home-greeting','k-home-ref-search','k-home-ref-hero','k-home-ref-actions','data-home-nearby','k-home-ref-chips'])expect(home.includes(token),`reference home missing ${token}`);
expect(!home.includes('Константин'),'hard-coded home name returned');for(const token of ['problemSlider()','homeServiceCategories()',"homeSliderShell('news'","homeSliderShell('products'","homeSliderShell('works'"])expect(!core.includes(token),`legacy home renderer returned ${token}`);
expect(cabinet.includes('k-client-account-native'),'native client account root missing');for(const token of ['k-client-account-overview','k-account-vehicles-grid','РАЗДЕЛЫ АККАУНТА','МОИ АВТОМОБИЛИ'])expect(cabinet.includes(token),`client account missing ${token}`);expect(!cabinet.includes('data-account-vehicles-slider'),'client account vehicle swiper still active');expect(!cabinet.includes('demoCabinetVehicles'),'demo vehicle cards must not be used in account');expect(!cabinet.includes('new window.Swiper'),'client account must not create Swiper');expect(css.includes('.k-account-vehicles-grid{display:grid'),'account vehicle grid CSS missing');expect(registry.includes('css/next/client_account_native.css'),'account CSS not registered');
for(const [file,hash] of Object.entries(manifest.files)){const p=path.join(root,file);if(!fs.existsSync(p)){if(file.startsWith('assets/'))continue;expect(false,`shell file missing ${file}`);continue;}const actual=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`);}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('R188.5.5.6.48 reference client home + native client account: OK');
