'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const assert=(ok,msg)=>{if(!ok){console.error('[FAIL]',msg);process.exitCode=1;}else console.log('[OK]',msg);};
const registry=read('inc/asset_registry.php');
const guard=read('css/next/client_width_guard.css');
const ref=read('css/next/reference_client_pages.css');
const parts=read('css/next/parts_native_marketplace.css');
const layout=read('css/next/client_surface_layout.css');
const community=read('js/next/pages/community.js');
const communityCss=read('css/next/community.css');
const fullscreen=read('css/next/social_fullscreen_pages.css');
const version=read('inc/asset_version.php');
const sw=read('sw.js');
assert(registry.includes("'css/next/client_width_guard.css'"),'client width guard registered');
assert(registry.indexOf("'css/next/client_width_guard.css'")>registry.indexOf("'css/next/reference_client_pages.css'"),'width guard loads after reference css');
assert(/\.k-flow-community-main\.k-community-feed-column[\s\S]*?width:100%!important;[\s\S]*?max-width:100%!important;[\s\S]*?min-width:0!important;/.test(guard),'community feed column is bounded to its track');
assert(/\.k-master-reference-inner[\s\S]*?max-width:none!important;/.test(guard),'masters reference inner is no longer artificially capped');
assert(/\.k-parts-native-page\.k-parts-ref-page[\s\S]*?max-width:none!important;/.test(guard),'parts reference page uses full outlet width');
assert(!ref.includes('.k-home-reference{max-width:430px!important'),'legacy 430px home cap removed');
assert(!ref.includes('.k-community-page.k-flow-primary-page{max-width:430px!important'),'legacy 430px community cap removed');
assert(!ref.includes('[data-page="services"].k-page-shell--workspace{max-width:430px'),'legacy 430px services cap removed');
assert(!ref.includes('.k-community-page.k-flow-primary-page{max-width:720px!important'),'legacy 720px community cap removed');
assert(!parts.includes('max-width:1180px!important;'),'parts 1180px page cap removed');
assert(!fullscreen.includes('width:100vw;max-width:none;margin-inline:calc(50% - 50vw)'),'masters legacy 100vw breakout removed');
assert(!communityCss.includes('.k-community-v2 .k-community-post-media{max-width:100vw}'),'community media no longer uses viewport width');
assert(layout.includes('margin-bottom: 43px !important;'),'requested 43px client bottom clearance is enforced');
assert(community.includes("let visibleCount=window.matchMedia?.('(max-width: 767px)')?.matches?6:12"),'community mobile initial render budget is six posts');
assert(/188\.5\.5\.6\.84\.(?:5[5-9]|[6-9]\d|\d{3,})/.test(version),'asset version is 84.55+');
assert(/188\.5\.5\.6\.84\.(?:5[5-9]|[6-9]\d|\d{3,})/.test(sw),'service worker version is 84.55+');
if(process.exitCode)process.exit(process.exitCode);else console.log('client width guard 84.55 OK');
