'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const api=read('api/db.php');
const cabinetApi=read('js/next/client/client_cabinet_api.js');
const cabinet=read('js/next/pages/cabinet.js');
const flow=read('js/next/client/first_vehicle_flow.js');
const request=read('js/next/pages/request.js');
const clientCabinet=read('api/client_cabinet.php');
const gate=read('tools/release_gate.php');
const checks=[];
const expect=(name,ok)=>{checks.push([name,!!ok]);console.log(`${ok?'PASS':'FAIL'} ${name}`);};
expect('order vehicle ownership enforced',api.includes("client_vehicle_forbidden")&&api.includes("client_vehicle_id")&&api.includes("(?<>'' AND user_phone=?) OR (?<>'' AND client_id=?)"));
expect('client order ignores browser clientId',api.includes("if ($actorRole === 'client')")&&api.includes("$clientId = $knownClientId !== '' ? $knownClientId")&&api.includes("$o['clientId'] = $clientId"));
expect('non-client supplied clientId is identity checked',api.includes("error'=>'client_scope_mismatch")&&api.includes('$sameClient = ($clientUserId > 0'));
expect('vehicle restore endpoint',api.includes("case 'vehicles.restore'")&&api.includes('function vehicles_restore'));
expect('archive promotes new primary',api.includes("'newDefaultId'=>$newDefaultId")&&api.includes('ORDER BY updated_at DESC,created_at DESC'));
expect('archive heals missing primary invariant',api.includes('$defaultCheck=$pdo->prepare')&&api.includes('$hasDefault=(bool)$defaultCheck->fetchColumn()'));
expect('editing primary preserves primary status',api.includes("$isExistingVehicle && !empty($existingVehicle['is_default'])")&&api.includes('$isDefault=1'));
expect('editing archived vehicle requires restore',api.includes("error'=>'vehicle_archived")&&api.includes('Сначала восстановите его'));
expect('secondary vehicle does not overwrite profile car',api.includes("if ($isDefault && $phone !== '') { kareta_upsert_profile")&&!api.includes("if ($isDefault || $title !== '') { kareta_upsert_profile"));
expect('VIN duplicate includes archive',api.includes('WHERE {$ownerSql} AND BINARY id<>BINARY ? AND UPPER(vin)=? LIMIT 1'));
expect('set default validates active target',api.includes("error'=>'vehicle_not_active")&&api.includes('active=1 AND {$ownerSql}'));
expect('restore blocks VIN duplicate',api.includes("Нельзя восстановить: VIN уже используется другой машиной"));
expect('restore blocks plate duplicate',api.includes("Нельзя восстановить: госномер уже используется другой машиной"));
expect('cabinet exposes archived vehicles',clientCabinet.includes('$archivedVehicles')&&clientCabinet.includes("active=0"));
expect('cabinet exposes edit fields',clientCabinet.includes('generation,plate,vin')&&clientCabinet.includes('engine_type,engine_volume,fuel_type'));
expect('client API lifecycle methods',cabinetApi.includes('setDefaultVehicle')&&cabinetApi.includes('archiveVehicle')&&cabinetApi.includes('restoreVehicle'));
expect('garage primary action',cabinet.includes('data-garage-set-default'));
expect('garage edit action opens detailed passport',cabinet.includes('data-garage-edit-vehicle')&&cabinet.includes('data-vehicle-passport-form')&&cabinet.includes('Дополнить данные'));
expect('garage archive action',cabinet.includes('data-garage-archive-vehicle'));
expect('garage restore action',cabinet.includes('data-garage-restore-vehicle'));
expect('edit uses isolated draft',flow.includes('EDIT_DRAFT_PREFIX')&&flow.includes('state.editVehicleId'));
expect('edit hydrates vehicle',flow.includes('function vehicleToDraft')&&flow.includes('customModelName'));
expect('legacy brand remains editable only in edit mode',flow.includes("brandId:legacyBrand?'legacy-edit'")&&flow.includes('function isLegacyEditBrand')&&flow.includes('state.editLegacyBrandName'));
expect('advanced duplicates stay server authoritative',api.includes('vehicle_duplicate_vin')&&api.includes('vehicle_duplicate_plate'));
expect('minimal first-entry no advanced duplicate gate',!flow.includes('state.data?.archivedVehicles')&&!flow.includes("filter(v=>String(v.id||'')!==String(state.editVehicleId||''))"));
expect('first entry does not repeat for archived garage',flow.includes('vehicles.length||archived.length'));
expect('new secondary car primary choice',flow.includes('data-first-vehicle-default')&&flow.includes('Сделать основным автомобилем'));
expect('request picks primary fallback',request.includes("vehicles.find(v=>Number(v.is_default)===1)||vehicles[0]||null"));
expect('request labels primary',request.includes("primary?'Основной':null"));
expect('NO_ASSETS release gate mode',gate.includes('--package=')&&gate.includes('assets_external_contract')&&gate.includes('Asset byte verification is external to NO_ASSETS'));
const passed=checks.filter(x=>x[1]).length;console.log(`\n${passed}/${checks.length} checks passed`);process.exit(passed===checks.length?0:1);
