'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const fail=[];const expect=(v,m)=>{if(!v)fail.push(m)};
const mig=read('api/migrations/129_client_first_entry_state.php'),prompt=read('api/entry_prompts.php'),flow=read('js/next/client/first_vehicle_flow.js'),page=read('js/next/pages/client_first_vehicle.js'),home=read('js/next/pages/core.js'),route=read('js/next/route_registry.js'),nav=read('js/next/dynamic_navigation.js'),cab=read('api/client_cabinet.php'),db=read('api/db.php'),api=read('js/next/client/client_cabinet_api.js'),config=read('config.php'),ver=read('inc/asset_version.php');
expect(/KARETA_DB_VERSION',\s*129/.test(config),'DB version 129 required');
for(const t of ['account_entry_prompt_state','client_first_vehicle_draft',"'version' => 129"])expect(mig.includes(t),'migration 129 missing '+t);
expect(!mig.includes('client_first_entry_state'),'migration 129 must not create legacy client_first_entry_state');
for(const t of ['client_first_vehicle','last_shown_local_date','last_dismissed_local_date','shouldShow','hasActiveVehicle','markShown','dismiss','active=1','claimed','rowCount()'])expect(prompt.includes(t),'entry prompt API missing '+t);
expect(!cab.includes('client_first_entry_state')&&!db.includes('clientFirstEntry.'),'legacy first-entry business state must be removed from cabinet/db dispatcher');
for(const t of ['entryPromptCurrent','entryPromptMarkShown','entryPromptDismiss'])expect(api.includes(t),'client API missing '+t);
for(const t of ["#/onboarding/client-car","clientFirstVehicle:'work-dialog'","return 'clientFirstVehicle'"])expect(route.includes(t),'first-car route missing '+t);
expect(nav.includes("key:'clientFirstVehicle'")&&nav.includes("any:['vehicles.update']") ,'first-car capability route missing');
for(const t of ['Добавьте автомобиль','Сделать позже','data-first-vehicle-create-request','promptCurrent','promptMarkShown','promptDismiss','localDateIso','clientFirstVehicle'])expect(flow.includes(t),'first vehicle flow missing '+t);
expect(!flow.includes('PROMPT_PREFIX')&&!flow.includes("status==='dismissed'")&&!flow.includes("status==='completed'"),'local/permanent completion state must not remain');
expect(flow.includes("if(draft.year&&(!/^\\d{4}$/.test"),'year must be optional but validated when present');
expect(db.includes("if($brand===''||$model==='')")&&db.includes("if($year!==''"),'server first-car brand/model required and year optional contract missing');
expect(page.includes("p.get('mode')==='manual'")&&page.includes('Math.max(2,requested)'),'manual add must start at step 2');
for(const t of ['data-home-garage','Мой гараж','В гараже пока нет автомобилей','+/onboarding/client-car'.replace('+','')])expect(home.includes(t),'Home garage state missing '+t);
expect(home.includes('maybeScheduleFirstEntry'),'Home must re-evaluate daily first-car prompt');
expect(flow.includes('const claimed=await promptMarkShown();')&&flow.includes('if(!claimed)return false'),'automatic prompt must require an atomic server daily claim');
expect(!/promptMarkShown\(\);[\s\S]{0,120}setPendingIntro\(\)/.test(flow),'dedicated automatic route must not leave legacy pendingIntro token');
expect(page.includes('flow.consumePendingIntro?.();'),'dedicated route must clear stale pendingIntro from older builds');
expect(home.includes('aria-label="Шаги заявки"><span class="is-active">1</span><i></i><span>2</span><i></i><span>3</span></div>'),'CLIENT Home request hero must show the current 3-step final Request contract');
const vm=/188\.5\.5\.6\.84\.(\d+)/.exec(ver);expect(vm&&Number(vm[1])>=23,'asset version 84.23+ required');
if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log('CLIENT First Car P0 84.23: 4-state flow + server daily prompt + persistent Home garage OK');
