'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const must=(ok,msg)=>{if(!ok){console.error('FAIL',msg);process.exitCode=1;}};
const css=read('css/next/master_surface_contract.css'),foundation=read('css/next/master_ui_foundation.css'),mobile=read('css/next/master_mobile_nav.css'),boot=read('css/runtime_boot_bundle.css');
const nav=read('js/next/navigation_core.js'),legacy=read('js/next/role_access.js'),shell=read('js/next/shell_nav.js');
const reg=read('inc/asset_registry.php'),ver=read('inc/asset_version.php'),sw=read('sw.js');
must(nav.includes("master: Object.freeze(['masterDashboard','masterExchange','serviceManagement','parts','cabinet'])"),'Master desktop IA must have five primary destinations');
must(nav.includes("master: Object.freeze(['masterDashboard','masterExchange','serviceManagement','parts','cabinet','__more__'])"),'Master mobile IA must have five primary destinations + More');
must(legacy.includes("desktop:['masterDashboard','masterExchange','serviceManagement','parts','cabinet']"),'legacy Master navigation must mirror primary IA');
must(shell.includes("kind==='master'&&key==='masterDashboard'?'Главная':baseLabel"),'Master dashboard label must be Главная on every shell surface');
must(mobile.includes('--k-mobile-nav-count:6;')&&mobile.includes('grid-template-columns:repeat(6,minmax(0,1fr))'),'Master mobile nav must own six stable slots');
must(!mobile.includes('!important')&&!mobile.includes('font-size:8px'),'Master mobile nav still contains legacy override/density rules');
must(css.includes("content:'МАСТЕР'")&&css.includes('#k-shell-header.k-shell-header'),'Master header context marker/style missing');
must(foundation.includes('--k-master-content-max:1420px')&&css.includes('.k-master-page-header'),'Master Surface Contract missing');
must(reg.includes("'masterSurfaceContract' => [")&&reg.includes("'cascade' => 'last'")&&reg.includes("'css/next/master_ui_foundation.css','css/next/master_role_skin.css','css/next/master_surface_contract.css'"),'Master canonical component/role/page layers are not registered');
must(!boot.includes('SOURCE: css/next/master_surface_contract.css'),'Master surface must not remain eager in boot CSS');
must(/188\.5\.5\.6\.84\.(?:10[1-9]|1[1-9]\d|[2-9]\d{2,})/.test(ver)&&/188\.5\.5\.6\.84\.(?:10[1-9]|1[1-9]\d|[2-9]\d{2,})/.test(sw),'84.101+ version mismatch');
if(!process.exitCode)console.log('R188.5.5.6.84.101+ Master contour contract OK');
