'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const expect=(v,m)=>{if(!v){console.error('FAIL:',m);process.exit(1)}};
const version=read('inc/asset_version.php'),sw=read('sw.js');
const workplace=read('js/next/pages/master_workplace.js');
const workplaceCss=read('css/next/master_ui_exchange_schedule_flattening.css');
const masterRuntime=read('css/routes/master_runtime.css');
const cabinet=read('js/next/pages/cabinet.js'),cabCss=read('css/next/client_cabinet.css');
const exchange=read('js/next/pages/work_feed.js');
const services=read('js/next/pages/service_management.js'),servicesCss=read('css/next/master_requests_workplace_services.css');
const more=read('js/next/smart_action_hub.js'),bundle=read('js/boot/runtime_shell_bundle.js');
expect(/188\.5\.5\.6\.84\.(?:100|1\d{2,})/.test(version),'version is older than 84.100');
expect(/188\.5\.5\.6\.84\.(?:100|1\d{2,})/.test(sw),'service worker release is older than 84.100');
expect(workplaceCss.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'master toolbar is not 2-column on mobile');
expect(!workplaceCss.includes('.k-master-r71-toolbar__actions{grid-template-columns:1fr 1fr 1fr}'),'stale 3-column phone toolbar remains');
expect(masterRuntime.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'final master_runtime does not contain current 2-column toolbar');
expect(!masterRuntime.includes('.k-master-r71-toolbar__actions{grid-template-columns:1fr 1fr 1fr}'),'stale 3-column toolbar remains in final master_runtime');
expect(!workplace.includes('exchangeLimit:6'),'dead exchangeLimit preference remains');
expect(!workplace.includes('const leads='),'dead Exchange leads variable remains on master home');
const account=(cabinet.match(/function renderMasterCabinet\(\)\{([\s\S]*?)\n  function renderStoCabinet/)||[])[1]||'';
expect(account.length>0,'master account render missing');
expect((account.match(/Публичный профиль/g)||[]).length===1,'Public profile is duplicated in master account');
expect(!account.includes('k-staff-cabinet-head-actions'),'duplicate master account header CTA remains');
expect(cabCss.includes('.k-staff-cabinet--master .k-staff-cabinet-grid{grid-template-columns:repeat(2,minmax(0,1fr))'),'master account 2x2 grid polish missing');
expect(exchange.includes("serviceScope:'mine'"),'Exchange does not default to My services');
expect(exchange.includes('class="is-active" data-exchange-scope="mine"'),'Exchange initial scope UI does not match state');
expect(!exchange.includes('без лишних вложенных карточек'),'technical Exchange copy leaked into user UI');
const serviceRender=(services.match(/function renderMasterServiceManagement\(context=\{\}\)\{([\s\S]*?)\n  function updateMasterMatrix/)||[])[1]||'';
expect((serviceRender.match(/<article>/g)||[]).length===2,'My services overview should have two counters');
expect(!serviceRender.includes('<span>в каталоге</span>'),'catalog-total noise remains in My services overview');
expect(servicesCss.includes('.k-master-services-help{display:none}'),'mobile help-panel reduction missing');
expect(more.includes('support.hidden=masterMode'),'master More support CTA is not hidden');
expect(more.includes("masterMode?'Действия мастера':'Быстрый доступ'"),'master More section title not normalized');
expect(bundle.includes('support.hidden=masterMode')&&bundle.includes("masterMode?'Действия мастера':'Быстрый доступ'"),'runtime shell bundle is stale');
console.log('OK master UI polish 84.100');
