'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const fail=[];const expect=(v,m)=>{if(!v)fail.push(m)};
const asset=read('inc/asset_version.php');
const currentVersion=(asset.match(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/)||[])[1]||'';
const runManifest=(query={})=>{
  const assigns=Object.entries(query).map(([k,v])=>`$_GET[${JSON.stringify(k)}]=${JSON.stringify(String(v))};`).join('');
  const code=`${assigns} include ${JSON.stringify(path.join(root,'asset_manifest.php'))};`;
  const out=cp.execFileSync('php',['-r',code],{encoding:'utf8'});
  return {raw:out,payload:JSON.parse(out)};
};
const atomic=runManifest({atomic_boot:1});
const probe=runManifest({runtime_probe:1});
const route=runManifest({route_loader:1,v:currentVersion});
const full=runManifest({});
expect(atomic.payload.mode==='atomic-boot','atomic manifest mode missing');
expect(atomic.payload.ok===true,'atomic manifest must stay healthy in NO_ASSETS package');
expect(Array.isArray(atomic.payload.assets)&&atomic.payload.assets.length===11,`atomic manifest must contain 11 boot scripts, got ${atomic.payload.assets?.length}`);
expect(atomic.payload.assets.every(x=>x.group==='scripts'&&x.lazy===false),'atomic manifest leaked non-script/lazy assets');
expect(Object.keys(atomic.payload.routeBundles||{}).length===0,'atomic manifest must not serialize route plan');
expect((atomic.payload.missing||[]).length===0,'atomic manifest reports missing boot scripts');
expect(Buffer.byteLength(atomic.raw)<10000,`atomic manifest too large: ${Buffer.byteLength(atomic.raw)}`);
expect(probe.payload.mode==='runtime-probe'&&probe.payload.ok===true,'runtime probe mode broken');
expect((probe.payload.assets||[]).length===0&&Object.keys(probe.payload.routeBundles||{}).length===0,'runtime probe performs asset inventory');
expect(Buffer.byteLength(probe.raw)<1024,`runtime probe response too large: ${Buffer.byteLength(probe.raw)}`);
expect(route.payload.mode==='route-loader','route-loader manifest mode missing');
expect(Array.isArray(route.payload.assets)&&route.payload.assets.length>0,'route-loader assets missing');
expect(route.payload.assets.every(x=>x.group==='styles'||x.group==='scripts'),'route-loader manifest leaked images');
expect(Object.keys(route.payload.routeBundles||{}).every(k=>!k.startsWith('_')),'route-loader leaked private route metadata');
expect((route.payload.assetMetrics||{}).routeOnly===true,'route-only manifest metric missing');
expect(Buffer.byteLength(route.raw)<Buffer.byteLength(full.raw)*0.85,`route manifest was not compacted enough: route=${Buffer.byteLength(route.raw)} full=${Buffer.byteLength(full.raw)}`);
const loader=read('js/next/route_asset_loader.js');
expect(loader.includes("url.searchParams.set('route_loader','1')"),'route loader does not use stable versioned route manifest');
expect(loader.includes("cache:'default'"),'route loader still forces no-store');
expect(!loader.includes('route_loader=${Date.now()}'),'route loader still cache-busts every manifest request');
const shellBundle=read('js/boot/runtime_shell_bundle.js');
expect(shellBundle.includes("url.searchParams.set('route_loader','1')")&&shellBundle.includes("cache:'default'"),'generated shell bundle is stale');
const sw=read('sw.js');
expect(sw.includes("url.searchParams.has('route_loader')")&&sw.includes('cacheFirstVersioned(request, STATIC_CACHE)'),'service worker does not cache versioned route manifest');
const va=currentVersion;const vs=(sw.match(/const RELEASE = '([^']+)'/)||[])[1];
expect(/^188\.5\.5\.6\.84\.(?:8[3-9]|9\d|\d{3,})$/.test(va)&&vs===va,'84.83+ release parity mismatch');
const indexHash=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'index.php'))).digest('hex');
expect(indexHash==='5e3dbc84e0ff808dd023d490399677f7ff1616d3c7bebaeb1bfab462d0854d26','frozen index.php changed');
if(fail.length){console.error(fail.join('\n'));process.exit(1)}
console.log(`R188.5.5.6.84.83 fast manifest hot path OK: atomic=${Buffer.byteLength(atomic.raw)}B probe=${Buffer.byteLength(probe.raw)}B route=${Buffer.byteLength(route.raw)}B full=${Buffer.byteLength(full.raw)}B`);
