'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const window={addEventListener(){},dispatchEvent(){},KaretaNavigationCore:{interfaceRole:()=> 'master'}};
const context={window,location:{hash:'#/master/qr'},URL,document:{currentScript:null,documentElement:{dataset:{}}},localStorage:{getItem:()=>null},sessionStorage:{getItem:()=>null}};
vm.createContext(context);
for(const file of ['route_registry.js','role_access.js','qr_encoder.js','pages/scanner.js'])vm.runInContext(fs.readFileSync('js/next/'+file,'utf8'),context);
const scanner=window.KaretaScannerPages;
assert.equal(window.KaretaRouteRegistry.keyFromHash('#/master/qr'),'masterQr');
assert.equal(window.KaretaRoleAccess.canAccess('masterQr','master'),true);
for(const role of ['client','sto','seller'])assert.equal(window.KaretaRoleAccess.canAccess('masterQr',role),false);
assert.match(scanner.render(),/Мой QR/);
assert.match(scanner.render(),/href="#\/master"/);
const url=scanner.masterQrUrl({profile:{id:'ms_001',profileVisible:true}});
assert.equal(scanner.qrTarget(url),'#/masters/profile/master/ms_001');
assert.notEqual(url,scanner.masterQrUrl({profile:{id:'ms_002'}}));
for(const data of [{},{profile:{id:'<evil>'}},{profile:{id:'ms_001',profileVisible:false}}])assert.throws(()=>scanner.masterQrUrl(data));
const qr=new window.KaretaQRCode(-1,1);qr.addData(url);qr.make();
assert.ok(qr.getModuleCount()>20);
const scale=8,size=(qr.getModuleCount()+8)*scale, pixels=Buffer.alloc(size*size,255);
for(let y=0;y<qr.getModuleCount();y++)for(let x=0;x<qr.getModuleCount();x++)if(qr.isDark(y,x))for(let a=0;a<scale;a++)for(let b=0;b<scale;b++)pixels[(y*scale+4*scale+a)*size+x*scale+4*scale+b]=0;
if(process.argv[2])fs.writeFileSync(process.argv[2],Buffer.concat([Buffer.from(`P5\n${size} ${size}\n255\n`),pixels]));
console.log('PASS personal master QR: owner route, roles, canonical identity, hidden/missing profile, scanner round trip, encoder');
