const fs=require('fs');
const root='/home/karetakz/sites/kareta.kz';
const read=p=>fs.readFileSync(root+'/'+p,'utf8');
const assert=(c,m)=>{if(!c)throw new Error(m)};
const index=read('index.php');
const nav=read('js/next/navigation_core.js');
const shell=read('js/next/shell_nav.js');
const guard=read('css/routes/client_guard_postlude.css');
const restore=read('css/next/shell_84_109_restore.css');
const version=read('inc/asset_version.php');

const h=index.indexOf('<header id="k-shell-header"');
const e=index.indexOf('</header>',h);
assert(h>=0&&e>h,'header missing');
const block=index.slice(h,e);
const pBack=block.indexOf('id="k-mobile-back"');
const pBrand=block.indexOf('class="k-brand"');
const pNav=block.indexOf('id="k-desktop-nav"');
const pActions=block.indexOf('class="k-shell-actions"');
assert(pBack>=0&&pBack<pBrand&&pBrand<pNav&&pNav<pActions,'header child order differs from 84.109');
assert(!index.includes('id="k-desktop-sidebar"'),'desktop sidebar still present');
assert((index.match(/id="k-mobile-back"/g)||[]).length===1,'mobile back must exist exactly once');
assert(nav.includes("personal: Object.freeze(['home','services','community','masters','parts','orders','chats'])"),'personal desktop nav != 84.109');
assert(nav.includes("personal: Object.freeze(['home','services','works','masters','parts','__more__'])"),'personal mobile nav != old six-item template');
assert(shell.includes("personal:{parts:'Новые запчасти',orders:'Заявки',cabinet:'Профиль'}"),'84.109 client labels missing');
assert(!/brand-logo--full\s*\{display:none!important/.test(guard),'route guard still hides full logo');
assert(!/k-menu-toggle\s*\{display:none!important/.test(guard),'route guard still hides burger');
assert(!guard.includes('--k-mobile-nav-count:5'),'route guard still forces five-item mobile nav');
assert(guard.includes('SOURCE: css/next/shell_84_109_restore.css'),'route guard missing final shell restore');
assert(restore.includes('#k-shell-header>#k-desktop-nav.k-desktop-nav'),'desktop nav shell restore missing');
assert(restore.includes('#k-shell-header>#k-mobile-back.k-mobile-back'),'header back restore missing');
assert(restore.includes('#k-menu-toggle.k-menu-toggle'),'burger restore missing');
assert(restore.includes('.k-shell-location-icon'),'geo addition missing');
assert(/const KARETA_ASSET_VERSION = '188\.5\.5\.6\.84\.\d+';/.test(version),'release version marker missing');
console.log('SHELL_84_109_RESTORE: PASS');
