'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const failures=[];const expect=(v,m)=>{if(!v)failures.push(m)};
const config=read('config.php'),route=read('js/next/route_registry.js'),dynamic=read('js/next/dynamic_navigation.js'),role=read('js/next/role_access.js'),app=read('js/next/app_next.js'),page=read('js/next/pages/master_works.js'),work=read('api/work_posts.php'),life=read('api/master_order_lifecycle.php'),orderPage=read('js/next/pages/work_order.js'),detail=read('js/next/pages/work_feed.js'),migration=read('api/migrations/110_work_portfolio_story.php'),registry=read('inc/asset_registry.php'),manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
const dbVersion=Number((config.match(/KARETA_DB_VERSION',\s*(\d+)/)||[])[1]||0);expect(dbVersion>=110,'DB version 110+ missing');expect(migration.includes("'version' => 110"),'migration 110 missing');
expect(route.includes("masterWorks:Object.freeze({ path:'#/master/works'"),'masterWorks route missing');expect(dynamic.includes("{ key:'masterWorks'")&&!dynamic.match(/key:'masterWorks'[^\n]*(desktop|menu|mobilePriority)/),'masterWorks must be hidden route, not Shell navigation');expect(role.includes("'masterWorks'"),'legacy masterWorks access missing');
expect(app.includes('KaretaMasterWorksPages')&&app.includes('masterWorks:masterWorksPages.renderMasterWorks')&&app.includes('masterWorks:masterWorksPages.mountMasterWorks'),'app mount missing');
for(const t of ['Готовы к публикации','Ожидают согласия','Опубликованные работы','data-master-work-publish','data-master-work-publish-form','masterWorks.portfolio'])expect(page.includes(t),`portfolio UI missing ${t}`);expect(!page.includes('<select'),'Master works page must not use dropdown select');expect(!page.includes('Swiper'),'Master works page must not use slider');
for(const t of ['kareta_master_works_portfolio','profile.manage','work_order_handovers','clientConsent','readyToPublish','problem_text','diagnosis_text','solution_text','parts_json','duration_minutes','price_visible','warranty_days','repair_not_completed'])expect(work.includes(t),`work server contract missing ${t}`);
expect(work.includes("'unitPrice'=>$showPrice"),'part prices must follow client price consent');expect(life.includes('show_price')&&life.includes("'showPrice'=>!empty($policy['show_price'])"),'automatic publication must preserve price consent');expect(orderPage.includes('name="showPrice"')&&orderPage.includes('showPrice:form.elements.showPrice.checked'),'client price consent UI missing');
const detailFn=detail.slice(detail.indexOf('async function mountWorkDetail'),detail.indexOf('window.KaretaWorkFeedPages'));expect(detailFn.includes('k-work-detail-media-grid'),'public work detail native media grid missing');expect(!detailFn.includes('new window.Swiper')&&!detailFn.includes('k-work-media-swiper'),'public work detail must not use Swiper');for(const t of ['Проблема','Диагностика','Что сделали','Установленные детали'])expect(detailFn.includes(t),`public work detail missing ${t}`);
expect(registry.includes('js/next/pages/master_works.js')&&registry.includes('css/next/master_works_portfolio.css'),'asset registry missing R52 assets');
for(const [file,hash] of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`)}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('R188.5.5.6.52 Master portfolio: verified repairs + explicit consent + native media + shell freeze OK');
