'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const failures=[];const expect=(v,m)=>{if(!v)failures.push(m)};
const config=read('config.php'),migration=read('api/migrations/111_master_reviews_social_contract.php'),route=read('js/next/route_registry.js'),dynamic=read('js/next/dynamic_navigation.js'),role=read('js/next/role_access.js'),icons=read('js/next/ui_icons.js'),app=read('js/next/app_next.js'),page=read('js/next/pages/master_reviews.js'),db=read('api/db.php'),comments=read('api/work_posts.php'),order=read('js/next/pages/work_order.js'),detail=read('js/next/pages/work_feed.js'),catalog=read('api/catalog_details.php'),owner=read('js/next/pages/master_profile_owner.js'),registry=read('inc/asset_registry.php'),manifest=JSON.parse(read('tools/shell_freeze_manifest_r1885603.json'));
const dbVersion=Number((config.match(/KARETA_DB_VERSION',\s*(\d+)/)||[])[1]||0);expect(dbVersion>=111,'DB version must be >=111');expect(migration.includes("'version' => 111"),'migration 111 missing');for(const t of ['quality_rating','timing_rating','neatness_rating','communication_rating','master_reply_at','account_id','author_master_id','JOIN orders o'])expect(migration.includes(t),`migration contract missing ${t}`);
expect(route.includes("masterReviews:Object.freeze({ path:'#/master/reviews'")&&route.includes("providerReviews:Object.freeze({ path:'#/masters/reviews'"),'review routes missing');expect(dynamic.includes("{ key:'masterReviews'")&&!/key:'masterReviews'[^\n]*(desktop|menu|mobilePriority)/.test(dynamic),'masterReviews must remain hidden route');expect(role.includes("'providerReviews'")&&role.includes("'masterReviews'"),'role access missing review routes');expect(icons.includes("masterReviews:'comment'")&&icons.includes("providerReviews:'comment'"),'route icons missing');
for(const t of ['KaretaMasterReviewsPages','masterReviews:masterReviewsPages.renderMasterReviews','providerReviews:masterReviewsPages.renderProviderReviews','masterReviews:masterReviewsPages.mountMasterReviews','providerReviews:masterReviewsPages.mountProviderReviews'])expect(app.includes(t),`app integration missing ${t}`);
for(const t of ['РЕПУТАЦИЯ МАСТЕРА','Ждут ответа','Ответить на отзыв','ПОДТВЕРЖДЁННАЯ РЕПУТАЦИЯ','masterReviews.reply','data-review-dialog'])expect(page.includes(t),`reviews page missing ${t}`);expect(!page.includes('<select'),'reviews page must not use dropdown');expect(!page.includes('Swiper'),'reviews page must not use slider');
expect(db.includes("case 'publicReviews.submit': kareta_require_api_session"),'verified review submit must use Identity-aware client actor');for(const t of ['order_not_done','not_owner','review_exists','kareta_sync_verified_master_review','qualityRating','timingRating','neatnessRating','communicationRating'])expect(db.includes(t),`review server missing ${t}`);expect(db.includes("JOIN orders o ON o.id=mr.order_id AND o.status='done'"),'owner review list must join completed real orders');expect(db.includes('masterReviews.reply')&&db.includes('master_reply_at'),'master reply sync missing');
const reviewSection=order.slice(order.indexOf('ПОДТВЕРЖДЁННЫЙ ОТЗЫВ'),order.indexOf("function modal",order.indexOf('ПОДТВЕРЖДЁННЫЙ ОТЗЫВ')));for(const t of ["reviewRatingField('stars'","reviewRatingField('qualityRating'","reviewRatingField('timingRating'","reviewRatingField('neatnessRating'","reviewRatingField('communicationRating'",'input type=\"radio\"'])expect(order.includes(t),`native order review missing ${t}`);expect(!reviewSection.includes('<select'),'order review must not use dropdown');
for(const t of ['kareta_require_api_session','account_id','person_id','author_master_id','author_sto_id','isWorkAuthorReply','parent_id'])expect(comments.includes(t),`comment identity contract missing ${t}`);expect(comments.includes("$parentId=(string)$pr['parent_id']"),'reply-to-reply must normalize to root');expect(detail.includes('Автор работы'),'work discussion must label work author replies');
expect(catalog.includes("JOIN orders o ON o.id=mr.order_id AND o.status='done'"),'public Master reputation must only use completed orders');expect(!catalog.includes("elseif(isset($provider['rating']))"),'public verified rating must not fallback to old seeded rating');expect(owner.includes('href="#/master/reviews"'),'owner profile must link to reviews owner page');expect(registry.includes('js/next/pages/master_reviews.js')&&registry.includes('css/next/master_reviews_social.css'),'R53 assets missing');
for(const [file,hash] of Object.entries(manifest.files)){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');expect(actual===hash,`SHELL FREEZE VIOLATION: ${file}`)}
if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('R188.5.5.6.53 Master reviews: verified orders + dimensions + replies + identity comments + shell freeze OK');
