const fs=require('fs'),path=require('path');
const root='/home/karetakz/sites/kareta.kz',read=p=>fs.readFileSync(path.join(root,p),'utf8'),a=(v,m)=>{if(!v)throw new Error(m)};
const icons=read('js/next/ui_icons.js'),visual=read('js/next/visual_assets.js'),core=read('js/next/pages/core.js'),parts=read('js/next/pages/parts.js'),masters=read('js/next/pages/masters.js'),vehicle=read('js/next/pages/vehicle.js'),fv=read('js/next/client/first_vehicle_flow.js'),reg=read('inc/asset_registry.php'),home=read('css/next/reference_client_pages.css'),routeHome=read('css/routes/home_responsive_84_134.css'),ver=read('inc/asset_version.php');
for(const key of ['menu','bell','search','services','location','parts','calendar','chats','masters','home','orders','plus','oil','diagnostics','battery','brakes','tires','suspension','paint','grid'])a(icons.includes(key+':')||icons.includes(key+"'"),'icon missing '+key);
a(icons.includes("filter:'<path"),'UI filter icon removed');
a(!/(^|[, {])filter:'airFilter'/.test(icons),'UI filter incorrectly aliased to engine filter');
a(core.includes('window.KaretaUIIcons?.svg?.'),'Home does not use shared icon engine');
a(!core.includes("const icons = {"),'Home still has local icon dictionary');
a(reg.includes("'js/next/visual_assets.js'"),'visual_assets.js not registered');
a(visual.includes('brands=Object.freeze'),'brand registry missing');
a((visual.match(/:'[A-Z]/g)||[]).length>=30,'brand registry incomplete');
a(vehicle.includes('KaretaVisualAssets?.vehicleImage'),'vehicle reference fallback missing');
a(parts.includes('KaretaVisualAssets?.partImage'),'parts reference fallback missing');
a(masters.includes('KaretaVisualAssets?.stationImage'),'STO reference fallback missing');
a(fv.includes('KaretaVisualAssets?.brandLogo'),'first vehicle brand logo missing');
a(home.includes('@media(min-width:600px)'),'eager home visibility guard missing');
a(routeHome.includes('@media(min-width:600px) and (max-width:899px)'),'tablet home route layout missing');
a(routeHome.includes('@media(min-width:900px)'),'desktop home route layout missing');
const autoDir=path.join(root,'assets/reference/automotive'),brandDir=path.join(root,'assets/reference/brands');
a(fs.readdirSync(autoDir).filter(x=>x.endsWith('.png')).length===11,'automotive asset count != 11');
a(fs.readdirSync(brandDir).filter(x=>x.endsWith('.png')).length===36,'brand asset count != 36');
a(core.includes("icon:'oil'")&&core.includes("icon:'tires'")&&core.includes("icon:'suspension'"),'Home service icons are not wired');
a(parts.includes("return 'brakes'")&&parts.includes("return 'airFilter'")&&parts.includes("return 'sparkPlug'"),'Parts semantic service icons are not wired');
a(/const KARETA_ASSET_VERSION = '188\.5\.5\.6\.84\.\d+';/.test(ver),'release marker missing');
console.log('VISUAL_SYSTEM: PASS');