'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const js=read('js/next/pages/request.js');
const css=read('css/next/request_5_steps.css');
const registry=read('inc/asset_registry.php');
const version=read('inc/asset_version.php');
const sw=read('sw.js');
const fail=[]; const must=(v,m)=>{if(!v)fail.push(m)};
const panelOrder=[...js.matchAll(/data-request-panel="([^"]+)" data-step-index="(\d+)"/g)].map(m=>[m[1],Number(m[2])]);
must(JSON.stringify(panelOrder)===JSON.stringify([['vehicle',0],['offer',1],['schedule',2],['problem',3],['review',4]]),`panel order mismatch ${JSON.stringify(panelOrder)}`);
must((js.match(/data-request-panel=/g)||[]).length===5,'must render exactly 5 panels');
must(js.includes('${[1,2,3,4,5].map'),'five progress circles missing');
must(js.includes('data-request-offer-choice="exchange"')&&js.includes('data-request-offer-choice="own_price"'),'two client offer choices missing');
const clientOffer=(/\$\{isClient\?`([\s\S]*?)`:`<button class="k-request-final-choice is-selected"/.exec(js)||[])[1]||'';
must(clientOffer&&!clientOffer.includes('data-request-offer-choice="direct_master"'),'direct-master must not appear in client step 2');
must(js.includes('data-request-problem-choice="services"')&&js.includes('data-request-problem-choice="custom"'),'problem modes missing');
must(js.includes("if(mode==='services'&&selectedServices().length<1)return false"),'service mode validation missing');
must(js.includes("if(mode==='custom'&&description.length<5)return false"),'custom problem validation missing');
must(js.includes("if(isClient&&mode==='own_price'&&budget<=0)return false"),'own price budget validation missing');
must(js.includes("const REQUEST_FLOW_VERSION=8"),'draft version 8 missing');
must(js.includes('[0,3,3,1,2,4]'),'v7 draft migration missing');
must(js.includes("const options=['','Утро','День','Вечер']"),'preferred dayparts missing');
must(js.includes('data-request-exact-time'),'exact-time preference missing');
must(css.includes('final five-step client request flow'),'five-step CSS marker missing');
must(registry.includes("'css/next/request_5_steps.css'"),'five-step CSS not registered');
const va=(/KARETA_ASSET_VERSION\s*=\s*'([^']+)'/.exec(version)||[])[1]||'';
const vs=(/const RELEASE\s*=\s*'([^']+)'/.exec(sw)||[])[1]||'';
const rev=Number(va.split('.').pop()||0);must(rev>=58&&vs===va,'version mismatch');
if(fail.length){console.error(fail.join('\n'));process.exit(1)}
console.log('R188.5.5.6.84.58 request five-step regression: OK');
