<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];$read=static fn(string $f)=>(string)@file_get_contents($root.'/'.$f);
$need=['docs/releases/changelog/CHANGELOG_R188_5_5_6_59.md','css/next/parts_windows_product_detail.css','tools/test_r1885619_parts_windows_product_detail.js','tools/shell_freeze_manifest_r1885603.json'];foreach($need as $f)if(!is_file($root.'/'.$f))$fail[]='missing '.$f;
$page=$read('js/next/pages/parts.js');$details=$read('js/next/pages/details.js');$used=$read('api/used_market.php');$catalog=$read('api/catalog_details.php');$db=$read('api/db.php');$api=$read('js/next/api_client.js');$css=$read('css/next/parts_windows_product_detail.css');$registry=$read('inc/asset_registry.php');$config=$read('config.php');
foreach(['data-market-window','data-parts-market-list-dialog','data-market-category','data-compatible-window','Открыть список ·'] as $t)if(!str_contains($page,$t))$fail[]='parts windows missing '.$t;if(str_contains($page,'data-parts-types')||str_contains($page,'function typeGrid'))$fail[]='legacy type selector still active';if(preg_match('/<select\b/i',$page)||stripos($page,'swiper')!==false)$fail[]='parts page violates native contract';
foreach(["token.startsWith('used:')",'getUsedMarketDetail','donorVehicle','realInstallations','data-review-rating','k-part-detail-gallery'] as $t)if(!str_contains($details,$t))$fail[]='product detail missing '.$t;if(preg_match('/<select\b/i',$details)||stripos($details,'swiper')!==false)$fail[]='product detail violates native contract';
foreach(['function kareta_used_market_detail','donorVehicle','sellerStats','realInstallations'] as $t)if(!str_contains($used,$t))$fail[]='used backend missing '.$t;if(!str_contains($db,"\$action === 'usedMarket.detail'"))$fail[]='used detail dispatch missing';if(!str_contains($api,'function getUsedMarketDetail'))$fail[]='used detail API missing';
foreach(['realInstallations','installationCount','work_order_part_reservations','client_consent=1'] as $t)if(!str_contains($catalog,$t))$fail[]='catalog installations missing '.$t;
foreach(['.k-parts-market-list-dialog','.k-part-native-detail','.k-part-detail-layout','.k-part-rating-choice'] as $t)if(!str_contains($css,$t))$fail[]='R59 CSS missing '.$t;if(str_contains($css,'#k-mobile-nav')||str_contains($css,'#k-desktop-nav')||str_contains($css,'#k-menu-toggle'))$fail[]='R59 CSS alters Shell';if(!str_contains($registry,'css/next/parts_windows_product_detail.css'))$fail[]='R59 CSS not registered';
if(!str_contains($read('inc/asset_version.php'),'r1885619-parts-window-lists-product-detail')||!str_contains($read('sw.js'),'r1885619-parts-window-lists-product-detail'))$fail[]='R59 release suffix missing';$later=str_contains($read('inc/asset_version.php'),'r1885620-used-market-listing-wizard');if(!preg_match("/KARETA_DB_VERSION',\s*(\d+)/",$config,$m)||($later?(int)$m[1]<114:(int)$m[1]!==114))$fail[]='R59 DB version must be 114 at R59 and >=114 later';
$manifest=json_decode($read('tools/shell_freeze_manifest_r1885603.json'),true);foreach(($manifest['files']??[]) as $file=>$hash){$path=$root.'/'.$file;if(!is_file($path)){$fail[]='shell file missing '.$file;continue;}if(hash_file('sha256',$path)!==$hash)$fail[]='SHELL FREEZE VIOLATION '.$file;}
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "R188.5.5.6.59 parts list windows + unified product detail + Shell Freeze 2: OK\n";
