<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
foreach(['docs/releases/changelog/CHANGELOG_R188_5_2.md','docs/releases/plans/PLAN_R188_5_3.md','tools/test_r18852_migration_recovery.js'] as $file)if(!is_file($root.'/'.$file))$fail[]='missing:'.$file;
$version=(string)@file_get_contents($root.'/inc/asset_version.php');if(!str_contains($version,'r18852-migration-98-recovery')&&!str_contains($version,'r18853-more-menu-navigation-fix')&&!str_contains($version,'r18854-context-switcher-more-layouts')&&!str_contains($version,'r18855-client-community-navigation')&&!str_contains($version,'r188551-onboarding-identity-session')&&!str_contains($version,'r188552-legacy-role-picker-center-removal')&&!str_contains($version,'r188553-role-surface-chat-master-spacing')&&!str_contains($version,'r188554-role-e2e-recovery-chat-search')&&!str_contains($version,'r188555-runtime-dependency-bootstrap'))$fail[]='asset_version';
$sw=(string)@file_get_contents($root.'/sw.js');if(!str_contains($sw,'r18852-migration-98-recovery')&&!str_contains($sw,'r18853-more-menu-navigation-fix')&&!str_contains($sw,'r18854-context-switcher-more-layouts')&&!str_contains($sw,'r18855-client-community-navigation')&&!str_contains($sw,'r188551-onboarding-identity-session')&&!str_contains($sw,'r188552-legacy-role-picker-center-removal')&&!str_contains($sw,'r188553-role-surface-chat-master-spacing')&&!str_contains($sw,'r188554-role-e2e-recovery-chat-search')&&!str_contains($sw,'r188555-runtime-dependency-bootstrap'))$fail[]='service_worker_version';
$migrationFile=$root.'/api/migrations/098_role_workspaces_completion.php';$migrationHash=is_file($migrationFile)?hash_file('sha256',$migrationFile):'';if($migrationHash!=='02a2d591dbc6eb68733177da1b79283f0c0e2b44f66d11ae37f26dd7725c3a0d')$fail[]='migration_98_checksum';
$bootstrap=(string)@file_get_contents($root.'/api/bootstrap.php');foreach(['kareta_prepare_migration_98_dashboard_layout_compatibility','idx_dashboard_layout_account_fk','uq_dashboard_layout_scope','Migration 98 compatibility repair failed','if ($version === 98)'] as $needle)if(!str_contains($bootstrap,$needle))$fail[]='bootstrap:'.$needle;
$helperStart=strpos($bootstrap,'function kareta_prepare_migration_98_dashboard_layout_compatibility');$helperEnd=$helperStart===false?false:strpos($bootstrap,"\nfunction kareta_migrate",$helperStart);$helper=($helperStart!==false&&$helperEnd!==false)?substr($bootstrap,$helperStart,$helperEnd-$helperStart):'';$fkDrop=strpos($helper,'DROP FOREIGN KEY');$legacyDrop=strpos($helper,'DROP INDEX `uq_dashboard_layout`');$fkAdd=strpos($helper,'ADD CONSTRAINT');if($helper===''||$fkDrop===false||$legacyDrop===false||$fkAdd===false||!($fkDrop<$legacyDrop&&$legacyDrop<$fkAdd))$fail[]='unsafe_compatibility_helper';
$hook=strpos($bootstrap,'kareta_prepare_migration_98_dashboard_layout_compatibility($pdo);');$apply=strpos($bootstrap,'kareta_apply_migration($pdo, $migration);',$hook===false?0:$hook);if($hook===false||$apply===false||$hook>$apply)$fail[]='recovery_hook_order';
if($fail){fwrite(STDERR,implode("\n",$fail)."\n");exit(1);}echo "R188.5.2 verifier OK\n";
