<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
foreach(['docs/releases/changelog/CHANGELOG_R188_5_5.md','docs/releases/plans/PLAN_R188_5_6_MASTER_STO_PAGES.md','css/next/client_mobile_navigation.css','tools/test_r18855_client_navigation.js'] as $file)if(!is_file($root.'/'.$file))$fail[]='missing:'.$file;
$version=(string)@file_get_contents($root.'/inc/asset_version.php');if(!str_contains($version,'r18855-client-community-navigation')&&!str_contains($version,'r188551-onboarding-identity-session')&&!str_contains($version,'r188552-legacy-role-picker-center-removal')&&!str_contains($version,'r188553-role-surface-chat-master-spacing')&&!str_contains($version,'r188554-role-e2e-recovery-chat-search')&&!str_contains($version,'r188555-runtime-dependency-bootstrap'))$fail[]='asset_version';
$sw=(string)@file_get_contents($root.'/sw.js');if(!str_contains($sw,'r18855-client-community-navigation')&&!str_contains($sw,'r188551-onboarding-identity-session')&&!str_contains($sw,'r188552-legacy-role-picker-center-removal')&&!str_contains($sw,'r188553-role-surface-chat-master-spacing')&&!str_contains($sw,'r188554-role-e2e-recovery-chat-search')&&!str_contains($sw,'r188555-runtime-dependency-bootstrap'))$fail[]='service_worker_version';
$app=(string)@file_get_contents($root.'/js/next/app_next.js');if(!str_contains($app,'dataset.userRole')||!str_contains($app,'roleAccess.normalizeRole?.(activeRole)'))$fail[]='legacy_role_state';
$navigation=(string)@file_get_contents($root.'/js/next/navigation_core.js');if(!str_contains($navigation,"personal: Object.freeze(['home','services','works','masters','parts','__more__'])"))$fail[]='client_mobile_order';if(!str_contains($navigation,'hasLegacySession()')||!str_contains($navigation,"return 'personal'"))$fail[]='legacy_client_context';
$hub=(string)@file_get_contents($root.'/js/next/smart_action_hub.js');$personalStart=strpos($hub,'personal:Object.freeze([');$masterStart=strpos($hub,'master:Object.freeze([');$personal=$personalStart!==false&&$masterStart!==false?substr($hub,$personalStart,$masterStart-$personalStart):'';if(!str_contains($personal,"key:'cabinetSettings',label:'Настройки'"))$fail[]='client_more_settings';
$routes=(string)@file_get_contents($root.'/js/next/route_registry.js');if(!str_contains($routes,"works:Object.freeze({ path:'#/works', label:'Сообщество'"))$fail[]='community_route';
$css=(string)@file_get_contents($root.'/css/next/client_mobile_navigation.css');if(!str_contains($css,'--k-mobile-nav-count: 6 !important')||!str_contains($css,'repeat(6, minmax(0, 1fr))'))$fail[]='client_six_columns';
$assets=(string)@file_get_contents($root.'/inc/asset_registry.php');if(substr_count($assets,'css/next/client_mobile_navigation.css')!==1)$fail[]='r18855_css_asset';
$plan=(string)@file_get_contents($root.'/docs/releases/plans/PLAN_R188_5_6_MASTER_STO_PAGES.md');foreach(['#/master','#/works','#/services/manage','#/sto','Критерии готовности'] as $needle)if(!str_contains($plan,$needle))$fail[]='plan:'.$needle;
if($fail){fwrite(STDERR,implode("\n",$fail)."\n");exit(1);}echo "R188.5.5 verifier OK\n";
