<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
foreach(['api/migrations/098_role_workspaces_completion.php','docs/releases/changelog/CHANGELOG_R188_5.md','css/next/role_workspaces.css','tools/test_r1885_role_contexts.js','tools/verify_r1885.php'] as $file)if(!is_file($root.'/'.$file))$fail[]='missing:'.$file;
$config=(string)@file_get_contents($root.'/config.php');if(!preg_match("/KARETA_DB_VERSION',\s*(9[8-9]|[1-9][0-9]{2,})/",$config))$fail[]='db_version';
$version=(string)@file_get_contents($root.'/inc/asset_version.php');if(!str_contains($version,'r1885-role-workspaces-completion')&&!str_contains($version,'r18851-navigation-icon-hotfix')&&!str_contains($version,'r18852-migration-98-recovery')&&!str_contains($version,'r18853-more-menu-navigation-fix')&&!str_contains($version,'r18854-context-switcher-more-layouts')&&!str_contains($version,'r18855-client-community-navigation')&&!str_contains($version,'r188551-onboarding-identity-session')&&!str_contains($version,'r188552-legacy-role-picker-center-removal')&&!str_contains($version,'r188553-role-surface-chat-master-spacing')&&!str_contains($version,'r188554-role-e2e-recovery-chat-search')&&!str_contains($version,'r188555-runtime-dependency-bootstrap'))$fail[]='asset_version';
$assets=(string)@file_get_contents($root.'/inc/asset_registry.php');if(substr_count($assets,'css/next/role_workspaces.css')!==1)$fail[]='r1885_css_asset';
$migration=(string)@file_get_contents($root.'/api/migrations/098_role_workspaces_completion.php');foreach(['context_key','revision','uq_dashboard_layout_scope','profile.seller','organization.seller','market.orders.read','work_orders.assign'] as $needle)if(!str_contains($migration,$needle))$fail[]='migration:'.$needle;
$dashboardApi=(string)@file_get_contents($root.'/api/dashboard_preferences.php');foreach(['expectedRevision','dashboard_revision_conflict','contextKey',"\$action==='reset'"] as $needle)if(!str_contains($dashboardApi,$needle))$fail[]='dashboard_api:'.$needle;
$dashboard=(string)@file_get_contents($root.'/js/next/dashboard_engine.js');foreach(['data-dashboard-edit','data-dashboard-reset','data-dashboard-move','data-dashboard-span','resetLayout','expectedRevision'] as $needle)if(!str_contains($dashboard,$needle))$fail[]='dashboard_ui:'.$needle;
$sto=(string)@file_get_contents($root.'/api/sto_workplace.php');foreach(['workflowStage','waitingApproval','waitingParts','calendar_events','kareta_sto_master_assign'] as $needle)if(!str_contains($sto,$needle))$fail[]='sto:'.$needle;
$stoPage=(string)@file_get_contents($root.'/js/next/pages/sto_workplace.js');$r82=str_contains($stoPage,"STO_WORKSPACE_R82_CONTRACT='R188.5.5.6.82'");if($r82){foreach(['k-sto-r82-kpis','k-sto-r82-operations','data-sto-master-assign'] as $needle)if(!str_contains($stoPage,$needle))$fail[]='sto_page:'.$needle;}else{foreach(['sto.overdue','sto.approvals','sto.parts','sto.calendar','data-sto-master-assign'] as $needle)if(!str_contains($stoPage,$needle))$fail[]='sto_page:'.$needle;}
$admin=(string)@file_get_contents($root.'/js/next/pages/admin_workspaces.js');foreach(['accountDetail','setProfileStatus','setContextStatus','setMembershipStatus','revokeSession','data-admin-action-dialog'] as $needle)if(!str_contains($admin,$needle))$fail[]='admin:'.$needle;if(str_contains($admin,'prompt(')||str_contains($admin,'confirm('))$fail[]='admin_legacy_dialogs';
$adminApi=(string)@file_get_contents($root.'/api/admin_operations.php');foreach(['catch(DomainException $e)','identity_account_unavailable','admin_identity_resolution_failed'] as $needle)if(!str_contains($adminApi,$needle))$fail[]='admin_scope:'.$needle;
$seller=(string)@file_get_contents($root.'/js/next/navigation_core.js');foreach(["seller: Object.freeze(['seller','sellerProducts','sellerOrders','parts','chats','__more__'])","organization_store: Object.freeze(['seller','sellerProducts','sellerOrders','parts','chats','__more__'])"] as $needle)if(!str_contains($seller,$needle))$fail[]='seller_navigation';
$sellerApi=(string)@file_get_contents($root.'/api/seller_shop.php');foreach(['KaretaAuthResolver','seller_context_required','organizationType',"seller_actor(\$pdo,['market.products.manage'])","seller_actor(\$pdo,['market.orders.fulfill','market.orders.manage'])",'identity_account_unavailable'] as $needle)if(!str_contains($sellerApi,$needle))$fail[]='seller_scope:'.$needle;
$identityContext=(string)@file_get_contents($root.'/api/identity/context_service.php');foreach(['$organizationId=$organizationKey',"'organizationId'=>\$organizationId"] as $needle)if(!str_contains($identityContext,$needle))$fail[]='identity_context_bridge:'.$needle;
$domain=(string)@file_get_contents($root.'/api/domain.php');foreach(['$context = $identityDecision->context',"\$context['organizationId'] = \$organizationKey",'JOIN calendar_events c ON c.id=b.calendar_event_id'] as $needle)if(!str_contains($domain,$needle))$fail[]='domain_context_bridge:'.$needle;
$capabilityRegistry=(string)@file_get_contents($root.'/api/identity/capability_registry.php');if(!str_contains($capabilityRegistry,"'market.manage' => 'market.products.manage'"))$fail[]='market_capability_alias';
$db=(string)@file_get_contents($root.'/api/db.php');if(!str_contains($db,"case 'stoOrders.assignMaster'"))$fail[]='sto_action_route';
if($fail){fwrite(STDERR,implode("\n",$fail)."\n");exit(1);}echo "R188.5 verifier OK\n";
