<?php
declare(strict_types=1);
function kareta_booking_slots(?PDO $pdo,array $in):void{
 if(!$pdo)kareta_json(['ok'=>false,'error'=>'db_unavailable'],503);
 $date=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($in['date']??''))?(string)$in['date']:date('Y-m-d');
 $masterId=trim((string)($in['masterId']??''));
 $masters=[];try{$q=$pdo->query("SELECT id,name,city,active FROM masters WHERE active=1 ORDER BY name LIMIT 50");$masters=$q->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){}
 if($masterId===''&&$masters)$masterId=(string)$masters[0]['id'];
 $busy=[];if($masterId!==''){try{$st=$pdo->prepare("SELECT time,COALESCE(estimated_duration_min,120) AS duration FROM orders WHERE master_id=? AND date=? AND status NOT IN ('cancelled','deleted') AND time<>''");$st->execute([$masterId,$date]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){$start=strtotime($date.' '.$r['time']);if($start)$busy[]=[$start,$start+max(60,(int)$r['duration'])*60];}}catch(Throwable $e){}}
 $slots=[];for($h=9;$h<=17;$h++){foreach([0,30] as $m){$t=mktime($h,$m,0,(int)date('m',strtotime($date)),(int)date('d',strtotime($date)),(int)date('Y',strtotime($date)));$end=$t+60*60;$ok=true;foreach($busy as[$a,$b])if($t<$b&&$end>$a){$ok=false;break;}if($ok)$slots[]=['value'=>date('H:i',$t),'label'=>date('H:i',$t)];}}
 kareta_json(['ok'=>true,'data'=>['date'=>$date,'masterId'=>$masterId,'masters'=>$masters,'slots'=>$slots]]);
}
function kareta_product_review_submit(?PDO $pdo,array $b):void{if(!$pdo)_no_db();$u=function_exists('kareta_resolve_api_actor')?kareta_resolve_api_actor($pdo):(kareta_session_user()?:[]);$pid=trim((string)($b['productId']??''));$rating=max(1,min(5,(int)($b['rating']??5)));$text=kareta_clean_text($b['text']??'',2000);if($pid===''||$text==='')kareta_json(['ok'=>false,'error'=>'product_and_text_required'],422);$id='pr_'.substr(sha1($pid.'|'.($u['id']??0)),0,24);$st=$pdo->prepare("INSERT INTO product_reviews(id,product_id,user_id,author_name,rating,body,status,created_at,updated_at) VALUES(?,?,?,?,? ,?,'published',NOW(),NOW()) ON DUPLICATE KEY UPDATE rating=VALUES(rating),body=VALUES(body),author_name=VALUES(author_name),updated_at=NOW()");$st->execute([$id,$pid,(int)($u['id']??0)?:null,kareta_clean_text($u['name']??'Клиент',160),$rating,$text]);kareta_json(['ok'=>true,'id'=>$id]);}
function kareta_product_question_submit(?PDO $pdo,array $b):void{if(!$pdo)_no_db();$u=function_exists('kareta_resolve_api_actor')?kareta_resolve_api_actor($pdo):(kareta_session_user()?:[]);$pid=trim((string)($b['productId']??''));$text=kareta_clean_text($b['text']??'',2000);if($pid===''||$text==='')kareta_json(['ok'=>false,'error'=>'product_and_text_required'],422);$id='pq_'.substr(sha1($pid.'|'.($u['id']??0).'|'.microtime(true)),0,24);$st=$pdo->prepare("INSERT INTO product_questions(id,product_id,user_id,author_name,body,status,created_at) VALUES(?,?,?,?,?,'published',NOW())");$st->execute([$id,$pid,(int)($u['id']??0)?:null,kareta_clean_text($u['name']??'Пользователь',160),$text]);kareta_json(['ok'=>true,'id'=>$id]);}
