<?php
declare(strict_types=1);

/** R188.5.5.6.72 — observable and controllable schedule recovery. */

function kareta_master_recovery_reason_label(string $reason): string {
    return [
      'day_off'=>'смена стала выходной','outside_hours'=>'запись вне рабочей смены','blocked'=>'перерыв или блокировка времени',
      'order'=>'пересечение с другой записью','tariff'=>'лимит тарифа','bay_conflict'=>'занят бокс СТО','no_slot'=>'нет свободного окна',
      'running_repair_delay'=>'предыдущий ремонт задерживается','invalid_time'=>'некорректное время','conflict'=>'конфликт графика'
    ][$reason]??$reason;
}

function kareta_master_recovery_bay_candidate(PDO $pdo,string $orderId,string $stoId,string $start,string $end): array {
    if($stoId===''||!kareta_table_exists($pdo,'sto_service_bays')||!kareta_table_exists($pdo,'sto_bay_assignments'))return ['required'=>false,'available'=>true,'bayId'=>'','bayName'=>''];
    $current=[];try{$q=$pdo->prepare("SELECT a.bay_id,b.name FROM sto_bay_assignments a LEFT JOIN sto_service_bays b ON BINARY b.id=BINARY a.bay_id WHERE BINARY a.order_id=BINARY ? LIMIT 1");$q->execute([$orderId]);$current=$q->fetch(PDO::FETCH_ASSOC)?:[];}catch(Throwable $_){}
    $q=$pdo->prepare("SELECT id,name FROM sto_service_bays WHERE BINARY sto_id=BINARY ? AND active=1 ORDER BY CASE WHEN BINARY id=BINARY ? THEN 0 ELSE 1 END,sort_order,name");$q->execute([$stoId,(string)($current['bay_id']??'')]);
    foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $bay){$cq=$pdo->prepare("SELECT COUNT(*) FROM sto_bay_assignments WHERE BINARY bay_id=BINARY ? AND BINARY order_id<>BINARY ? AND status IN ('planned','active') AND planned_start<? AND planned_end>?");$cq->execute([(string)$bay['id'],$orderId,$end,$start]);$busy=(int)$cq->fetchColumn();if($busy===0&&function_exists('kareta_sto_bay_incident_conflicts'))$busy+=kareta_sto_bay_incident_conflicts($pdo,$stoId,(string)$bay['id'],$start,$end);if($busy===0)return ['required'=>true,'available'=>true,'bayId'=>(string)$bay['id'],'bayName'=>(string)$bay['name'],'changed'=>(string)$bay['id']!==(string)($current['bay_id']??'')];}
    return ['required'=>true,'available'=>false,'bayId'=>'','bayName'=>'','currentBayId'=>(string)($current['bay_id']??''),'currentBayName'=>(string)($current['name']??'')];
}

function kareta_master_recovery_plan_rows(PDO $pdo,string $masterId,int $horizonDays): array {
    if(!kareta_table_exists($pdo,'master_order_plans'))return [];
    $from=(new DateTimeImmutable('now'))->modify('-120 minutes');$to=(new DateTimeImmutable('today'))->modify('+'.max(1,min(30,$horizonDays)).' days')->setTime(23,59,59);
    $sql="SELECT p.*,o.status order_status,o.client_user_id,o.client_phone,o.client_vehicle_id,o.vehicle_title,o.client_car,o.service_names,o.estimated_duration_min,o.sto_id,(SELECT c.id FROM chats c WHERE BINARY c.order_id=BINARY o.id ORDER BY c.created_at DESC LIMIT 1) chat_id FROM master_order_plans p JOIN orders o ON BINARY o.id=BINARY p.order_id WHERE BINARY p.master_id=BINARY ? AND p.planned_start>=? AND p.planned_start<=? AND p.status NOT IN ('done','completed','cancelled','closed','no_show') AND LOWER(o.status) NOT IN ('completed','done','delivered','closed','cancelled') ORDER BY p.planned_start,p.created_at";
    $q=$pdo->prepare($sql);$q->execute([$masterId,$from->format('Y-m-d H:i:s'),$to->format('Y-m-d H:i:s')]);return $q->fetchAll(PDO::FETCH_ASSOC)?:[];
}

function kareta_master_recovery_preview_data(PDO $pdo,string $masterId,string $triggerType='manual_preview',string $affectedDate=''): array {
    $prefs=kareta_master_day_ops_preferences($pdo,$masterId);$horizon=max(1,(int)$prefs['autoRecoveryHorizonDays']);$items=[];$safe=0;$unresolved=0;$protected=0;$tariffBlocked=0;$bayBlocked=0;
    foreach(kareta_master_recovery_plan_rows($pdo,$masterId,$horizon) as $plan){$orderId=(string)$plan['order_id'];if($orderId===''||kareta_master_day_ops_running($pdo,$orderId))continue;
        $validation=kareta_master_day_ops_plan_valid($pdo,$masterId,$plan);if($validation['valid'])continue;
        $oldStart=(string)$plan['planned_start'];$oldEnd=(string)$plan['planned_end'];$reasons=$validation['reasons']??[];$base=['orderId'=>$orderId,'vehicleTitle'=>(string)($plan['vehicle_title']??$plan['client_car']??'Автомобиль'),'serviceNames'=>(string)($plan['service_names']??''),'oldStart'=>$oldStart,'oldEnd'=>$oldEnd,'reasons'=>$reasons,'reasonLabels'=>array_map('kareta_master_recovery_reason_label',$reasons),'protected'=>!empty($plan['auto_recovery_protected']),'stoId'=>(string)($plan['sto_id']??'')];
        if(!empty($plan['auto_recovery_protected'])){$protected++;$items[]=array_merge($base,['status'=>'protected','safe'=>false]);continue;}
        $order=$plan;$order['id']=$orderId;$slots=kareta_master_schedule_free_slots_for_order($pdo,$masterId,$order,$horizon)['slots']??[];$choice=null;$oldTs=strtotime($oldStart)?:0;
        foreach($slots as $slot){$ts=strtotime((string)($slot['start']??''))?:0;if($ts<=0)continue;if($oldTs>0&&$ts<$oldTs)continue;$choice=$slot;break;}if(!$choice&&$slots)$choice=$slots[0];
        if(!$choice){$unresolved++;$items[]=array_merge($base,['status'=>'unresolved','safe'=>false,'blockReason'=>'no_slot']);continue;}
        $newStart=(string)$choice['start'];$newEnd=(string)$choice['end'];$guard=function_exists('kareta_tariff_master_intake_guard')?kareta_tariff_master_intake_guard($pdo,$masterId,substr($newStart,0,10),$orderId,false):['canSchedule'=>true];
        if(empty($guard['canSchedule'])){$tariffBlocked++;$items[]=array_merge($base,['status'=>'tariff_blocked','safe'=>false,'candidateStart'=>$newStart,'candidateEnd'=>$newEnd,'tariff'=>$guard,'blockReason'=>'tariff']);continue;}
        $bay=kareta_master_recovery_bay_candidate($pdo,$orderId,(string)($plan['sto_id']??''),$newStart,$newEnd);if(empty($bay['available'])){$bayBlocked++;$items[]=array_merge($base,['status'=>'bay_blocked','safe'=>false,'candidateStart'=>$newStart,'candidateEnd'=>$newEnd,'bay'=>$bay,'blockReason'=>'bay_conflict']);continue;}
        $safe++;$items[]=array_merge($base,['status'=>'safe','safe'=>true,'candidateStart'=>$newStart,'candidateEnd'=>$newEnd,'durationMin'=>max(15,(int)($plan['estimated_repair_min']??$choice['workMinutes']??120)),'bufferMin'=>max(0,(int)($plan['buffer_min']??$choice['bufferMin']??0)),'bay'=>$bay]);
    }
    return ['ok'=>true,'triggerType'=>$triggerType,'affectedDate'=>$affectedDate,'items'=>$items,'summary'=>['conflicts'=>count($items),'safe'=>$safe,'unresolved'=>$unresolved,'protected'=>$protected,'tariffBlocked'=>$tariffBlocked,'bayBlocked'=>$bayBlocked],'generatedAt'=>date(DATE_ATOM)];
}

function kareta_master_recovery_apply_one(PDO $pdo,string $masterId,array $candidate,bool $notify): array {
    $orderId=(string)($candidate['orderId']??'');$newStart=(string)($candidate['candidateStart']??'');$newEnd=(string)($candidate['candidateEnd']??'');if($orderId===''||$newStart===''||$newEnd==='')return ['orderId'=>$orderId,'status'=>'invalid'];
    $order=kareta_master_day_ops_order($pdo,$masterId,$orderId);if(!$order)return ['orderId'=>$orderId,'status'=>'not_found'];
    $q=$pdo->prepare("SELECT * FROM master_order_plans WHERE BINARY order_id=BINARY ? AND BINARY master_id=BINARY ? LIMIT 1");$q->execute([$orderId,$masterId]);$plan=$q->fetch(PDO::FETCH_ASSOC)?:[];if(!$plan)return ['orderId'=>$orderId,'status'=>'plan_not_found'];if(!empty($plan['auto_recovery_protected']))return ['orderId'=>$orderId,'status'=>'protected'];if(kareta_master_day_ops_running($pdo,$orderId))return ['orderId'=>$orderId,'status'=>'running'];
    $guard=function_exists('kareta_tariff_master_intake_guard')?kareta_tariff_master_intake_guard($pdo,$masterId,substr($newStart,0,10),$orderId,false):['canSchedule'=>true];if(empty($guard['canSchedule']))return ['orderId'=>$orderId,'status'=>'tariff_blocked','tariff'=>$guard];
    $conf=kareta_master_schedule_conflicts($pdo,$masterId,new DateTimeImmutable($newStart),new DateTimeImmutable($newEnd),$orderId,false);if($conf)return ['orderId'=>$orderId,'status'=>'race_conflict','conflicts'=>$conf];
    $bay=kareta_master_recovery_bay_candidate($pdo,$orderId,(string)($order['sto_id']??''),$newStart,$newEnd);if(empty($bay['available']))return ['orderId'=>$orderId,'status'=>'bay_blocked'];
    $oldStart=(string)($plan['planned_start']??'');$duration=max(15,(int)($plan['estimated_repair_min']??$candidate['durationMin']??120));$buffer=max(0,(int)($plan['buffer_min']??$candidate['bufferMin']??0));
    try{$pdo->beginTransaction();$lock=$pdo->prepare("SELECT id FROM masters WHERE BINARY id=BINARY ? LIMIT 1 FOR UPDATE");$lock->execute([$masterId]);$q=$pdo->prepare("SELECT auto_recovery_protected FROM master_order_plans WHERE BINARY order_id=BINARY ? AND BINARY master_id=BINARY ? FOR UPDATE");$q->execute([$orderId]);if((int)$q->fetchColumn()===1){$pdo->rollBack();return ['orderId'=>$orderId,'status'=>'protected'];}
      $conf=kareta_master_schedule_conflicts($pdo,$masterId,new DateTimeImmutable($newStart),new DateTimeImmutable($newEnd),$orderId,false);if($conf){$pdo->rollBack();return ['orderId'=>$orderId,'status'=>'race_conflict','conflicts'=>$conf];}
      $pdo->prepare("UPDATE master_order_plans SET planned_start=?,planned_end=?,estimated_repair_min=?,buffer_min=?,status=IF(status IN ('done','completed'),status,'planned'),source='recovery_control',conflict_override=0,updated_at=NOW() WHERE BINARY order_id=BINARY ? AND BINARY master_id=BINARY ?")->execute([$newStart,$newEnd,$duration,$buffer,$orderId,$masterId]);$dt=new DateTimeImmutable($newStart);$pdo->prepare("UPDATE orders SET date=?,time=?,estimated_duration_min=? WHERE BINARY id=BINARY ?")->execute([$dt->format('Y-m-d'),$dt->format('H:i'),$duration,$orderId]);
      if(kareta_table_exists($pdo,'master_reschedule_proposals'))$pdo->prepare("UPDATE master_reschedule_proposals SET status='cancelled',decision_note='recovery_control_applied',responded_at=NOW(),updated_at=NOW() WHERE BINARY order_id=BINARY ? AND status='pending'")->execute([$orderId]);
      if(!empty($bay['required'])&&!empty($bay['bayId'])){$existing=$pdo->prepare("SELECT id FROM sto_bay_assignments WHERE BINARY order_id=BINARY ? LIMIT 1");$existing->execute([$orderId]);$aid=(string)($existing->fetchColumn()?:'');if($aid!=='')$pdo->prepare("UPDATE sto_bay_assignments SET bay_id=?,master_id=?,status=IF(status='active',status,'planned'),planned_start=?,planned_end=?,estimated_minutes=?,updated_at=NOW() WHERE BINARY order_id=BINARY ?")->execute([(string)$bay['bayId'],$masterId,$newStart,$newEnd,$duration+$buffer,$orderId]);else{$aid='sba_'.bin2hex(random_bytes(8));$pdo->prepare("INSERT INTO sto_bay_assignments(id,sto_id,bay_id,order_id,master_id,status,planned_start,planned_end,estimated_minutes,priority_score) VALUES(?,?,?,?,?,'planned',?,?,?,0)")->execute([$aid,(string)$order['sto_id'],(string)$bay['bayId'],$orderId,$masterId,$newStart,$newEnd,$duration+$buffer]);}}
      $pdo->commit();
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();return ['orderId'=>$orderId,'status'=>'error','message'=>$e->getMessage()];}
    $notified=0;if($notify)$notified=kareta_master_day_ops_notify_move($pdo,$order,$oldStart,$newStart,'ручное восстановление графика','recovery_control');try{kareta_write_event($pdo,$orderId,'schedule_recovery_control_applied',['masterId'=>$masterId,'oldStart'=>$oldStart,'plannedStart'=>$newStart,'plannedEnd'=>$newEnd,'bayId'=>$bay['bayId']??'']);}catch(Throwable $_){}
    return ['orderId'=>$orderId,'status'=>'moved','oldStart'=>$oldStart,'plannedStart'=>$newStart,'plannedEnd'=>$newEnd,'notified'=>$notified,'bay'=>$bay];
}

function kareta_master_schedule_recovery_preview(PDO $pdo,array $body): void {$master=kareta_master_workplace_profile($pdo);$mid=(string)$master['id'];$date=trim((string)($body['date']??''));if($date!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date='';kareta_json(['ok'=>true,'preview'=>kareta_master_recovery_preview_data($pdo,$mid,'manual_preview',$date)]);}
function kareta_master_schedule_recovery_apply(PDO $pdo,array $body): void {$master=kareta_master_workplace_profile($pdo);$mid=(string)$master['id'];$ids=is_array($body['orderIds']??null)?array_values(array_unique(array_filter(array_map('strval',$body['orderIds'])))):[];$notify=!array_key_exists('notify',$body)||!empty($body['notify']);$preview=kareta_master_recovery_preview_data($pdo,$mid,'manual_apply','');$map=[];foreach($preview['items'] as $item)if(!empty($item['safe']))$map[(string)$item['orderId']]=$item;if(!$ids)$ids=array_keys($map);$results=[];$moved=0;$notified=0;foreach($ids as $id){if(!isset($map[$id])){$results[]=['orderId'=>$id,'status'=>'not_safe'];continue;}$r=kareta_master_recovery_apply_one($pdo,$mid,$map[$id],$notify);$results[]=$r;if(($r['status']??'')==='moved'){$moved++;$notified+=(int)($r['notified']??0);}}$result=['ok'=>true,'triggerType'=>'recovery_control_apply','movedCount'=>$moved,'notifiedCount'=>$notified,'items'=>$results,'generatedAt'=>date(DATE_ATOM)];kareta_master_day_ops_log($pdo,$mid,'recovery_control_apply','',date('Y-m-d'),$result);kareta_json(['ok'=>true,'recovery'=>$result]);}
function kareta_master_schedule_recovery_protect(PDO $pdo,array $body): void {if(!kareta_column_exists($pdo,'master_order_plans','auto_recovery_protected'))kareta_json(['ok'=>false,'error'=>'migration_required','message'=>'Требуется миграция БД 125.'],503);$master=kareta_master_workplace_profile($pdo);$mid=(string)$master['id'];$orderId=trim((string)($body['orderId']??''));$protected=!empty($body['protected']);if($orderId==='')kareta_json(['ok'=>false,'error'=>'order_id_required'],422);$uid=(int)(kareta_session_user()['id']??0)?:null;$q=$pdo->prepare("UPDATE master_order_plans SET auto_recovery_protected=?,auto_recovery_protected_at=?,auto_recovery_protected_by_user_id=?,updated_at=NOW() WHERE BINARY order_id=BINARY ? AND BINARY master_id=BINARY ?");$q->execute([$protected?1:0,$protected?date('Y-m-d H:i:s'):null,$protected?$uid:null,$orderId,$mid]);if($q->rowCount()===0)kareta_json(['ok'=>false,'error'=>'order_plan_not_found'],404);kareta_json(['ok'=>true,'orderId'=>$orderId,'protected'=>$protected]);}

function kareta_master_recovery_notification_history(PDO $pdo,string $masterId,int $limit=20): array {if(!kareta_table_exists($pdo,'notifications'))return [];$q=$pdo->prepare("SELECT n.id,n.entity_id,n.title,n.body,n.is_read,n.read_at,n.created_at,n.action_url FROM notifications n JOIN orders o ON BINARY o.id=BINARY n.entity_id WHERE BINARY o.master_id=BINARY ? AND n.event_type IN ('order.schedule.auto_rescheduled','order.schedule.auto_rescheduled.resend') ORDER BY n.created_at DESC LIMIT ".max(1,min(50,$limit)));$q->execute([$masterId]);$out=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)$out[]=['id'=>(int)$r['id'],'orderId'=>(string)$r['entity_id'],'title'=>(string)$r['title'],'body'=>(string)$r['body'],'isRead'=>!empty($r['is_read']),'readAt'=>(string)($r['read_at']??''),'createdAt'=>(string)$r['created_at'],'actionUrl'=>(string)$r['action_url']];return $out;}
function kareta_master_schedule_recovery_notify_resend(PDO $pdo,array $body): void {$master=kareta_master_workplace_profile($pdo);$mid=(string)$master['id'];$orderId=trim((string)($body['orderId']??''));$order=kareta_master_day_ops_order($pdo,$mid,$orderId);if(!$order)kareta_json(['ok'=>false,'error'=>'order_not_found'],404);$q=$pdo->prepare("SELECT planned_start FROM master_order_plans WHERE BINARY order_id=BINARY ? AND BINARY master_id=BINARY ? LIMIT 1");$q->execute([$orderId,$mid]);$start=(string)($q->fetchColumn()?:'');$human=$start;try{$human=(new DateTimeImmutable($start))->format('d.m.Y H:i');}catch(Throwable $_){}$chatId=(string)($order['chat_id']??'');$text='Повторное уведомление: актуальное время записи — '.$human.'.';if(function_exists('kareta_master_schedule_write_system_message'))kareta_master_schedule_write_system_message($pdo,$orderId,$chatId,$text,'recovery-resend|'.microtime(true));kareta_notification_insert($pdo,['recipientUserId'=>(int)($order['client_user_id']??0)?:null,'recipientPhone'=>(string)($order['client_phone']??''),'recipientRole'=>'client','eventType'=>'order.schedule.auto_rescheduled.resend','entityType'=>'order','entityId'=>$orderId,'title'=>'Напоминание о времени записи','body'=>$human,'actionUrl'=>'#/orders/item/'.rawurlencode($orderId),'meta'=>['orderId'=>$orderId,'chatId'=>$chatId,'plannedStart'=>$start,'manualResend'=>true]]);kareta_json(['ok'=>true,'orderId'=>$orderId,'plannedStart'=>$start]);}
