<?php
declare(strict_types=1);

function kareta_operational_finance_ensure(PDO $pdo): void {
    foreach (['sto_cash_accounts','sto_cash_movements','work_order_receivables','sto_master_payroll_rules','sto_payroll_periods','sto_payroll_accruals'] as $table) {
        if (!kareta_table_exists($pdo,$table)) {
            $migration=require __DIR__.'/migrations/106_operational_finance_payroll_receivables.php';
            if(is_array($migration)&&is_callable($migration['run']??null))($migration['run'])($pdo);
            return;
        }
    }
}

function kareta_operational_finance_actor(PDO $pdo,array $input=[]): array {
    $base=function_exists('kareta_master_order_lifecycle_actor')?kareta_master_order_lifecycle_actor($pdo):[];
    $session=kareta_session_user()?:[];$role=strtolower((string)($base['role']??$session['role']??'client'));
    $actor=['role'=>$role,'userId'=>(int)($base['userId']??0),'masterId'=>'','stoId'=>'','organizationId'=>''];
    if(in_array($role,['master'],true)){
        $master=kareta_master_workplace_profile($pdo);$actor['masterId']=(string)$master['id'];$actor['stoId']=(string)($master['sto_id']??'');
    } elseif(in_array($role,['sto'],true)){
        $sto=kareta_sto_workplace_profile($pdo);$actor['stoId']=(string)$sto['id'];$actor['organizationId']=(string)($sto['_organization_key']??('org_sto_'.$sto['id']));
    } elseif(in_array($role,['admin','owner'],true)){
        $stoId=trim((string)($input['stoId']??$_GET['stoId']??''));$masterId=trim((string)($input['masterId']??$_GET['masterId']??''));
        if($stoId!=='')$actor['stoId']=$stoId;
        if($masterId!==''){$actor['masterId']=$masterId;if($actor['stoId']===''){$q=$pdo->prepare("SELECT sto_id FROM masters WHERE id=? LIMIT 1");$q->execute([$masterId]);$actor['stoId']=(string)($q->fetchColumn()?:'');}}
    }
    if($actor['organizationId']===''&&$actor['stoId']!=='')$actor['organizationId']='org_sto_'.$actor['stoId'];
    return $actor;
}

function kareta_operational_finance_period(string $value=''): array {
    $value=trim($value);if(!preg_match('/^\d{4}-\d{2}$/',$value))$value=date('Y-m');
    $start=new DateTimeImmutable($value.'-01 00:00:00');$end=$start->modify('+1 month');
    return ['key'=>$value,'start'=>$start->format('Y-m-d H:i:s'),'end'=>$end->format('Y-m-d H:i:s')];
}

function kareta_operational_finance_cash_account(PDO $pdo,string $stoId,string $method='cash'): int {
    $type=in_array($method,['cash','card','bank_transfer'],true)?$method:'cash';
    $q=$pdo->prepare("SELECT id FROM sto_cash_accounts WHERE sto_id=? AND account_type=? AND active=1 ORDER BY is_default DESC,id LIMIT 1");$q->execute([$stoId,$type]);$id=(int)$q->fetchColumn();if($id>0)return $id;
    $title=['cash'=>'Основная касса','card'=>'Эквайринг','bank_transfer'=>'Расчётный счёт'][$type]??'Основная касса';
    $pdo->prepare("INSERT INTO sto_cash_accounts(sto_id,title,account_type,is_default) VALUES(?,?,?,1)")->execute([$stoId,$title,$type]);return (int)$pdo->lastInsertId();
}

function kareta_operational_finance_sync_receivables(PDO $pdo,array $actor): void {
    $where=[];$args=[];
    if($actor['role']==='master'&&$actor['masterId']!==''){$where[]='BINARY f.master_id=BINARY ?';$args[]=$actor['masterId'];}
    elseif($actor['stoId']!==''){$where[]='BINARY f.sto_id=BINARY ?';$args[]=$actor['stoId'];}
    elseif($actor['masterId']!==''){$where[]='BINARY f.master_id=BINARY ?';$args[]=$actor['masterId'];}
    else return;
    $sql="SELECT f.order_id,f.sto_id,f.master_id,f.revenue_total,o.client_user_id,o.client_phone,COALESCE(o.completed_at,o.updated_at,o.created_at) completed_at FROM work_order_financial_results f JOIN orders o ON BINARY o.id=BINARY f.order_id LEFT JOIN sto_workflows wf ON BINARY wf.order_id=BINARY f.order_id WHERE ".implode(' AND ',$where)." AND f.revenue_total>0 AND (LOWER(o.status) IN ('completed','done','delivered','closed') OR wf.current_stage IN ('payment','delivery','warranty','completed'))";
    $q=$pdo->prepare($sql);$q->execute($args);$pay=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM payment_records WHERE entity_type='order' AND BINARY entity_key=BINARY ? AND status='completed'");
    $up=$pdo->prepare("INSERT INTO work_order_receivables(order_id,sto_id,master_id,client_user_id,client_phone,total_amount,paid_amount,balance_amount,status,due_at,last_payment_at) VALUES(?,?,?,?,?,?,?,?,?,DATE_ADD(?,INTERVAL 3 DAY),IF(? > 0,NOW(),NULL)) ON DUPLICATE KEY UPDATE sto_id=VALUES(sto_id),master_id=VALUES(master_id),client_user_id=VALUES(client_user_id),client_phone=VALUES(client_phone),total_amount=VALUES(total_amount),paid_amount=VALUES(paid_amount),balance_amount=VALUES(balance_amount),status=VALUES(status),due_at=COALESCE(work_order_receivables.due_at,VALUES(due_at)),last_payment_at=IF(VALUES(paid_amount)>work_order_receivables.paid_amount,NOW(),work_order_receivables.last_payment_at),updated_at=NOW()");
    foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $row){$pay->execute([(string)$row['order_id']]);$paid=(float)$pay->fetchColumn();$total=(float)$row['revenue_total'];$balance=max(0,round($total-$paid,2));$status=$balance<=.001?'paid':($paid>0?'partial':'open');$completed=(string)($row['completed_at']??date('Y-m-d H:i:s'));$up->execute([(string)$row['order_id'],(string)$row['sto_id'],(string)$row['master_id'],(int)($row['client_user_id']??0)?:null,(string)($row['client_phone']??''),$total,$paid,$balance,$status,$completed,$paid]);}
    $masterScope=$actor['role']==='master'&&$actor['masterId']!=='';$scope=$masterScope?'master_id=?':'sto_id=?';$scopeValue=$masterScope?$actor['masterId']:$actor['stoId'];
    $pdo->prepare("UPDATE work_order_receivables SET status='overdue' WHERE {$scope} AND balance_amount>0 AND due_at<NOW() AND status IN ('open','partial')")->execute([$scopeValue]);
}

function kareta_operational_finance_profitability(array $rows): array {
    $groups=[];
    foreach($rows as $row){$label=trim((string)($row['serviceNames']??''))?:'Без категории';$names=array_values(array_filter(array_map('trim',preg_split('/[,;|]+/u',$label))))?:['Без категории'];$share=max(1,count($names));foreach($names as $name){$key=mb_strtolower($name);if(!isset($groups[$key]))$groups[$key]=['serviceName'=>$name,'ordersCount'=>0,'revenue'=>0.0,'cost'=>0.0,'profit'=>0.0,'marginPercent'=>0.0];$g=&$groups[$key];$g['ordersCount']++;$g['revenue']+=(float)$row['revenueTotal']/$share;$g['cost']+=(float)$row['directCostTotal']/$share;$g['profit']+=(float)$row['grossProfit']/$share;unset($g);}}
    foreach($groups as &$g){$g['revenue']=round($g['revenue'],2);$g['cost']=round($g['cost'],2);$g['profit']=round($g['profit'],2);$g['marginPercent']=$g['revenue']>0?round($g['profit']/$g['revenue']*100,2):0;}unset($g);
    usort($groups,static fn($a,$b)=>$b['profit']<=>$a['profit']);return array_slice(array_values($groups),0,30);
}

function kareta_operational_finance_dashboard(PDO $pdo,array $query=[]): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$query);
    if(!in_array($actor['role'],['master','sto','admin','owner'],true))kareta_json(['ok'=>false,'error'=>'finance_context_forbidden'],403);
    if($actor['masterId']===''&&$actor['stoId']==='')kareta_json(['ok'=>false,'error'=>'professional_context_required'],409);
    $period=kareta_operational_finance_period((string)($query['period']??$_GET['period']??''));kareta_operational_finance_sync_receivables($pdo,$actor);
    $masterScope=$actor['role']==='master'&&$actor['masterId']!=='';$where=$masterScope?'BINARY f.master_id=BINARY ?':'BINARY f.sto_id=BINARY ?';$scope=$masterScope?$actor['masterId']:$actor['stoId'];
    $q=$pdo->prepare("SELECT f.order_id AS orderId,f.master_id AS masterId,f.sto_id AS stoId,f.revenue_total AS revenueTotal,f.direct_cost_total AS directCostTotal,f.gross_profit AS grossProfit,f.margin_percent AS marginPercent,f.labor_revenue AS laborRevenue,f.parts_revenue AS partsRevenue,COALESCE(NULLIF(o.service_names,''),NULLIF(o.notes,''),'Без категории') AS serviceNames,COALESCE(o.completed_at,o.updated_at,o.created_at) AS completedAt,o.client_name AS clientName,o.client_phone AS clientPhone FROM work_order_financial_results f JOIN orders o ON BINARY o.id=BINARY f.order_id LEFT JOIN sto_workflows wf ON BINARY wf.order_id=BINARY f.order_id WHERE {$where} AND (LOWER(o.status) IN ('completed','done','delivered','closed') OR wf.current_stage IN ('payment','delivery','warranty','completed')) AND COALESCE(o.completed_at,o.updated_at,o.created_at)>=? AND COALESCE(o.completed_at,o.updated_at,o.created_at)<? ORDER BY completedAt DESC");$q->execute([$scope,$period['start'],$period['end']]);$orders=$q->fetchAll(PDO::FETCH_ASSOC)?:[];
    $summary=['revenue'=>0.0,'cost'=>0.0,'grossProfit'=>0.0,'marginPercent'=>0.0,'orders'=>count($orders),'cashBalance'=>0.0,'receivables'=>0.0,'overdue'=>0.0,'payrollAccrued'=>0.0,'payrollPaid'=>0.0];foreach($orders as $r){$summary['revenue']+=(float)$r['revenueTotal'];$summary['cost']+=(float)$r['directCostTotal'];$summary['grossProfit']+=(float)$r['grossProfit'];}$summary['marginPercent']=$summary['revenue']>0?round($summary['grossProfit']/$summary['revenue']*100,2):0;
    $receivableWhere=$masterScope?'master_id=?':'sto_id=?';$q=$pdo->prepare("SELECT r.order_id AS orderId,r.total_amount AS totalAmount,r.paid_amount AS paidAmount,r.balance_amount AS balanceAmount,r.status,r.due_at AS dueAt,o.client_name AS clientName,o.client_phone AS clientPhone,COALESCE(NULLIF(o.service_names,''),NULLIF(o.vehicle_title,''),NULLIF(o.client_car,''),'Заказ') AS title FROM work_order_receivables r JOIN orders o ON BINARY o.id=BINARY r.order_id WHERE {$receivableWhere}=? AND r.balance_amount>0 ORDER BY (r.status='overdue') DESC,r.due_at,r.updated_at DESC LIMIT 100");$q->execute([$scope]);$receivables=$q->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($receivables as $r){$summary['receivables']+=(float)$r['balanceAmount'];if($r['status']==='overdue')$summary['overdue']+=(float)$r['balanceAmount'];}
    $cashAccounts=[];$cashMovements=[];$payrollRules=[];$payrollPeriods=[];$payrollAccruals=[];$masters=[];
    if(!$masterScope&&$actor['stoId']!==''){
        kareta_operational_finance_cash_account($pdo,$actor['stoId'],'cash');
        $q=$pdo->prepare("SELECT id,title,account_type AS accountType,currency,active,is_default AS isDefault FROM sto_cash_accounts WHERE sto_id=? AND active=1 ORDER BY is_default DESC,id");$q->execute([$actor['stoId']]);$cashAccounts=$q->fetchAll(PDO::FETCH_ASSOC)?:[];
        $q=$pdo->prepare("SELECT movement_key AS movementKey,account_id AS accountId,order_id AS orderId,master_id AS masterId,movement_type AS movementType,category,amount,payment_method AS paymentMethod,description,occurred_at AS occurredAt FROM sto_cash_movements WHERE sto_id=? ORDER BY occurred_at DESC,id DESC LIMIT 100");$q->execute([$actor['stoId']]);$cashMovements=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$b=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN movement_type='income' THEN amount ELSE -amount END),0) FROM sto_cash_movements WHERE sto_id=?");$b->execute([$actor['stoId']]);$summary['cashBalance']=(float)$b->fetchColumn();
        $q=$pdo->prepare("SELECT m.id,m.name,m.spec,r.calculation_mode AS calculationMode,COALESCE(r.base_percent,0) AS basePercent,COALESCE(r.hourly_rate,0) AS hourlyRate,COALESCE(r.fixed_monthly,0) AS fixedMonthly,COALESCE(r.parts_bonus_percent,0) AS partsBonusPercent,COALESCE(r.active,0) AS ruleActive FROM sto_master_links l JOIN masters m ON BINARY m.id=BINARY l.master_id LEFT JOIN sto_master_payroll_rules r ON BINARY r.master_id=BINARY m.id AND BINARY r.sto_id=BINARY l.sto_id WHERE BINARY l.sto_id=BINARY ? AND l.status='active' ORDER BY m.name");$q->execute([$actor['stoId']]);$masters=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$payrollRules=$masters;
        $q=$pdo->prepare("SELECT id,period_key AS periodKey,status,orders_count AS ordersCount,masters_count AS mastersCount,gross_amount AS grossAmount,paid_amount AS paidAmount,closed_at AS closedAt,paid_at AS paidAt FROM sto_payroll_periods WHERE sto_id=? ORDER BY period_key DESC LIMIT 18");$q->execute([$actor['stoId']]);$payrollPeriods=$q->fetchAll(PDO::FETCH_ASSOC)?:[];
        $q=$pdo->prepare("SELECT a.id,a.period_id AS periodId,a.period_key AS periodKey,a.master_id AS masterId,m.name AS masterName,a.order_id AS orderId,a.accrual_type AS accrualType,a.base_amount AS baseAmount,a.hours_worked AS hoursWorked,a.rate_value AS rateValue,a.amount,a.status,a.paid_at AS paidAt FROM sto_payroll_accruals a LEFT JOIN masters m ON BINARY m.id=BINARY a.master_id WHERE BINARY a.sto_id=BINARY ? AND a.period_key=? ORDER BY m.name,a.created_at");$q->execute([$actor['stoId'],$period['key']]);$payrollAccruals=$q->fetchAll(PDO::FETCH_ASSOC)?:[];
    } else {
        $q=$pdo->prepare("SELECT a.id,a.period_key AS periodKey,a.order_id AS orderId,a.accrual_type AS accrualType,a.base_amount AS baseAmount,a.hours_worked AS hoursWorked,a.rate_value AS rateValue,a.amount,a.status,a.paid_at AS paidAt FROM sto_payroll_accruals a WHERE BINARY a.master_id=BINARY ? AND a.period_key=? ORDER BY a.created_at DESC LIMIT 200");$q->execute([$actor['masterId'],$period['key']]);$payrollAccruals=$q->fetchAll(PDO::FETCH_ASSOC)?:[];
    }
    foreach($payrollAccruals as $a){$summary['payrollAccrued']+=(float)$a['amount'];if($a['status']==='paid')$summary['payrollPaid']+=(float)$a['amount'];}
    $trend=[];for($i=5;$i>=0;$i--){$p=(new DateTimeImmutable('first day of this month'))->modify("-{$i} months");$key=$p->format('Y-m');$q=$pdo->prepare("SELECT COALESCE(SUM(f.revenue_total),0) revenue,COALESCE(SUM(f.gross_profit),0) profit FROM work_order_financial_results f JOIN orders o ON BINARY o.id=BINARY f.order_id LEFT JOIN sto_workflows wf ON BINARY wf.order_id=BINARY f.order_id WHERE {$where} AND (LOWER(o.status) IN ('completed','done','delivered','closed') OR wf.current_stage IN ('payment','delivery','warranty','completed')) AND COALESCE(o.completed_at,o.updated_at,o.created_at)>=? AND COALESCE(o.completed_at,o.updated_at,o.created_at)<?");$q->execute([$scope,$p->format('Y-m-01 00:00:00'),$p->modify('+1 month')->format('Y-m-01 00:00:00')]);$r=$q->fetch(PDO::FETCH_ASSOC)?:[];$trend[]=['periodKey'=>$key,'label'=>$p->format('m.Y'),'revenue'=>(float)($r['revenue']??0),'profit'=>(float)($r['profit']??0)];}
    $masterProfitability=[];if(!$masterScope&&$actor['stoId']!==''){$q=$pdo->prepare("SELECT f.master_id AS masterId,COALESCE(m.name,'Мастер') masterName,COUNT(*) ordersCount,COALESCE(SUM(f.revenue_total),0) revenue,COALESCE(SUM(f.direct_cost_total),0) cost,COALESCE(SUM(f.gross_profit),0) profit FROM work_order_financial_results f LEFT JOIN masters m ON BINARY m.id=BINARY f.master_id JOIN orders o ON BINARY o.id=BINARY f.order_id LEFT JOIN sto_workflows wf ON BINARY wf.order_id=BINARY f.order_id WHERE (LOWER(o.status) IN ('completed','done','delivered','closed') OR wf.current_stage IN ('payment','delivery','warranty','completed')) AND BINARY f.sto_id=BINARY ? AND COALESCE(o.completed_at,o.updated_at,o.created_at)>=? AND COALESCE(o.completed_at,o.updated_at,o.created_at)<? GROUP BY f.master_id,m.name ORDER BY profit DESC");$q->execute([$actor['stoId'],$period['start'],$period['end']]);$masterProfitability=$q->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($masterProfitability as &$m)$m['marginPercent']=(float)$m['revenue']>0?round((float)$m['profit']/(float)$m['revenue']*100,2):0;unset($m);}
    kareta_json(['ok'=>true,'data'=>['scope'=>['role'=>$actor['role'],'type'=>$masterScope?'master':'sto','stoId'=>$actor['stoId'],'masterId'=>$actor['masterId'],'periodKey'=>$period['key']],'summary'=>$summary,'trend'=>$trend,'orders'=>$orders,'serviceProfitability'=>kareta_operational_finance_profitability($orders),'masterProfitability'=>$masterProfitability,'receivables'=>$receivables,'cashAccounts'=>$cashAccounts,'cashMovements'=>$cashMovements,'payrollRules'=>$payrollRules,'payrollPeriods'=>$payrollPeriods,'payrollAccruals'=>$payrollAccruals,'masters'=>$masters]]);
}

function kareta_operational_finance_order_payment(PDO $pdo,array $body): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$body);if(!in_array($actor['role'],['master','sto','admin','owner'],true))kareta_json(['ok'=>false,'error'=>'finance_write_forbidden'],403);
    $orderId=trim((string)($body['orderId']??''));$order=kareta_master_order_lifecycle_order($pdo,$orderId,true);$amount=round((float)($body['amount']??0),2);if($amount<=0)kareta_json(['ok'=>false,'error'=>'payment_amount_invalid'],422);$method=(string)($body['method']??'cash');if(!in_array($method,['cash','card','bank_transfer'],true))$method='cash';
    $stoId=(string)($order['sto_id']??$actor['stoId']);$masterId=(string)($order['master_id']??$actor['masterId']);$financeActor=$actor;$financeActor['masterId']=$masterId;$financeActor['stoId']=$stoId;$finance=kareta_master_aftercare_recalculate($pdo,$orderId,$order,$financeActor);$total=(float)$finance['revenueTotal'];$org=$actor['organizationId']?:($stoId!==''?'org_sto_'.$stoId:null);$uid=max(1,(int)$actor['userId']);
    $pdo->beginTransaction();try{
        $q=$pdo->prepare("SELECT * FROM finance_invoices WHERE entity_type='order' AND BINARY entity_key=BINARY ? ORDER BY id DESC LIMIT 1 FOR UPDATE");$q->execute([$orderId]);$invoice=$q->fetch(PDO::FETCH_ASSOC);
        if(!$invoice){$invoiceKey='inv_order_'.substr(hash('sha256',$orderId),0,32);$pdo->prepare("INSERT IGNORE INTO finance_invoices(invoice_key,owner_user_id,organization_id,payer_user_id,entity_type,entity_key,title,status,currency,total_amount,paid_amount,due_at,sent_at,payload_json) VALUES(?,?,?,?,?,?,?,'sent','KZT',?,0,DATE_ADD(NOW(),INTERVAL 3 DAY),NOW(),?)")->execute([$invoiceKey,$uid,$org,(int)($order['client_user_id']??0)?:null,'order',$orderId,'Заказ-наряд '.$orderId,$total,json_encode(['schemaVersion'=>2,'source'=>'work_order'],JSON_UNESCAPED_UNICODE)]);$q=$pdo->prepare("SELECT * FROM finance_invoices WHERE invoice_key=? FOR UPDATE");$q->execute([$invoiceKey]);$invoice=$q->fetch(PDO::FETCH_ASSOC);if(!$invoice)throw new RuntimeException('order_invoice_create_failed');}
        $q=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM payment_records WHERE entity_type='order' AND BINARY entity_key=BINARY ? AND status='completed'");$q->execute([$orderId]);$paid=(float)$q->fetchColumn();$remaining=max(0,round($total-$paid,2));if($amount>$remaining+.001){$pdo->rollBack();kareta_json(['ok'=>false,'error'=>'payment_exceeds_order_balance','remaining'=>$remaining],422);}
        $payKey='pay_order_'.bin2hex(random_bytes(10));$txKey='txn_order_'.bin2hex(random_bytes(10));$pdo->prepare("INSERT INTO payment_records(payment_key,payer_user_id,payee_user_id,organization_id,entity_type,entity_key,amount,currency,status,method,payload_json) VALUES(?,?,?,?,?,?,?,'KZT','completed',?,?)")->execute([$payKey,(int)($order['client_user_id']??0)?:null,$uid,$org,'order',$orderId,$amount,$method,json_encode(['invoiceKey'=>$invoice['invoice_key'],'source'=>'order_payment'],JSON_UNESCAPED_UNICODE)]);$pdo->prepare("INSERT INTO finance_transactions(transaction_key,invoice_id,payment_key,payer_user_id,payee_user_id,organization_id,amount,currency,method,status,payload_json) VALUES(?,?,?,?,?,?,?,'KZT',?,'completed',?)")->execute([$txKey,(int)$invoice['id'],$payKey,(int)($order['client_user_id']??0),$uid,$org,$amount,$method,json_encode(['orderId'=>$orderId],JSON_UNESCAPED_UNICODE)]);
        $newPaid=round($paid+$amount,2);$status=$newPaid+.001>=$total?'paid':'partially_paid';$pdo->prepare("UPDATE finance_invoices SET total_amount=?,paid_amount=?,status=?,paid_at=IF(?='paid',NOW(),paid_at),updated_at=NOW() WHERE id=?")->execute([$total,$newPaid,$status,$status,(int)$invoice['id']]);
        $balance=max(0,round($total-$newPaid,2));$rstatus=$balance<=.001?'paid':'partial';$pdo->prepare("INSERT INTO work_order_receivables(order_id,sto_id,master_id,client_user_id,client_phone,total_amount,paid_amount,balance_amount,status,due_at,last_payment_at) VALUES(?,?,?,?,?,?,?,?,?,DATE_ADD(NOW(),INTERVAL 3 DAY),NOW()) ON DUPLICATE KEY UPDATE total_amount=VALUES(total_amount),paid_amount=VALUES(paid_amount),balance_amount=VALUES(balance_amount),status=VALUES(status),last_payment_at=NOW(),updated_at=NOW()")->execute([$orderId,$stoId,$masterId,(int)($order['client_user_id']??0)?:null,(string)($order['client_phone']??''),$total,$newPaid,$balance,$rstatus]);
        if($stoId!==''){$accountId=kareta_operational_finance_cash_account($pdo,$stoId,$method);$movement='cash_'.bin2hex(random_bytes(10));$pdo->prepare("INSERT INTO sto_cash_movements(movement_key,sto_id,account_id,order_id,master_id,movement_type,category,amount,payment_method,reference_type,reference_key,description,actor_user_id) VALUES(?,?,?,?,?,'income','order_payment',?,?,?,?,?,?)")->execute([$movement,$stoId,$accountId,$orderId,$masterId,$amount,$method,'payment',$payKey,'Оплата заказа '.$orderId,$uid]);}
        $ledger=$pdo->prepare("INSERT INTO finance_ledger(ledger_key,owner_user_id,organization_id,account_code,entry_type,amount,currency,reference_type,reference_key,description) VALUES(?,?,?,?,?,?,'KZT','order_payment',?,?)");$ledger->execute(['ledger:'.$txKey.':cash',$uid,$org,'cash','debit',$amount,$txKey,'Оплата заказа '.$orderId]);$ledger->execute(['ledger:'.$txKey.':revenue',$uid,$org,'service_revenue','credit',$amount,$txKey,'Выручка заказа '.$orderId]);
        if(kareta_table_exists($pdo,'work_order_handovers'))$pdo->prepare("UPDATE work_order_handovers SET payment_status=?,updated_at=NOW() WHERE order_id=?")->execute([$status==='paid'?'paid':'partial',$orderId]);$pdo->commit();
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    kareta_json(['ok'=>true,'paymentKey'=>$payKey,'transactionKey'=>$txKey,'paidAmount'=>$newPaid,'balanceAmount'=>$balance,'status'=>$status]);
}

function kareta_operational_finance_expense(PDO $pdo,array $body): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$body);if(!in_array($actor['role'],['sto','admin','owner'],true)||$actor['stoId']==='')kareta_json(['ok'=>false,'error'=>'sto_finance_required'],403);$amount=round((float)($body['amount']??0),2);$title=mb_substr(trim((string)($body['description']??'')),0,500);if($amount<=0||$title==='')kareta_json(['ok'=>false,'error'=>'expense_invalid'],422);$method=(string)($body['method']??'cash');if(!in_array($method,['cash','card','bank_transfer'],true))$method='cash';$category=trim((string)($body['category']??'operating_expense'))?:'operating_expense';$account=kareta_operational_finance_cash_account($pdo,$actor['stoId'],$method);$key='cash_'.bin2hex(random_bytes(10));$pdo->prepare("INSERT INTO sto_cash_movements(movement_key,sto_id,account_id,movement_type,category,amount,payment_method,description,actor_user_id) VALUES(?,?,?,'expense',?,?,?,?,?)")->execute([$key,$actor['stoId'],$account,$category,$amount,$method,$title,(int)$actor['userId']?:null]);$uid=max(1,(int)$actor['userId']);$ledger=$pdo->prepare("INSERT INTO finance_ledger(ledger_key,owner_user_id,organization_id,account_code,entry_type,amount,currency,reference_type,reference_key,description) VALUES(?,?,?,?,?,?,'KZT','cash_expense',?,?)");$ledger->execute(['ledger:'.$key.':expense',$uid,$actor['organizationId'],'operating_expense','debit',$amount,$key,$title]);$ledger->execute(['ledger:'.$key.':cash',$uid,$actor['organizationId'],'cash','credit',$amount,$key,$title]);kareta_json(['ok'=>true,'movementKey'=>$key]);
}

function kareta_operational_finance_payroll_rule_save(PDO $pdo,array $body): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$body);if(!in_array($actor['role'],['sto','admin','owner'],true)||$actor['stoId']==='')kareta_json(['ok'=>false,'error'=>'sto_finance_required'],403);$masterId=trim((string)($body['masterId']??''));$q=$pdo->prepare("SELECT 1 FROM sto_master_links WHERE BINARY sto_id=BINARY ? AND BINARY master_id=BINARY ? AND status='active' LIMIT 1");$q->execute([$actor['stoId'],$masterId]);if(!$q->fetchColumn())kareta_json(['ok'=>false,'error'=>'master_not_in_sto'],404);$mode=(string)($body['calculationMode']??'gross_profit_percent');if(!in_array($mode,['revenue_percent','gross_profit_percent','labor_percent','hourly','fixed_plus_percent'],true))kareta_json(['ok'=>false,'error'=>'payroll_mode_invalid'],422);$base=max(0,min(100,(float)($body['basePercent']??0)));$hour=max(0,(float)($body['hourlyRate']??0));$fixed=max(0,(float)($body['fixedMonthly']??0));$parts=max(0,min(100,(float)($body['partsBonusPercent']??0)));$pdo->prepare("INSERT INTO sto_master_payroll_rules(sto_id,master_id,calculation_mode,base_percent,hourly_rate,fixed_monthly,parts_bonus_percent,active,effective_from) VALUES(?,?,?,?,?,?,?,1,CURDATE()) ON DUPLICATE KEY UPDATE calculation_mode=VALUES(calculation_mode),base_percent=VALUES(base_percent),hourly_rate=VALUES(hourly_rate),fixed_monthly=VALUES(fixed_monthly),parts_bonus_percent=VALUES(parts_bonus_percent),active=1,updated_at=NOW()")->execute([$actor['stoId'],$masterId,$mode,$base,$hour,$fixed,$parts]);kareta_json(['ok'=>true]);
}

function kareta_operational_finance_payroll_close(PDO $pdo,array $body): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$body);if(!in_array($actor['role'],['sto','admin','owner'],true)||$actor['stoId']==='')kareta_json(['ok'=>false,'error'=>'sto_finance_required'],403);$period=kareta_operational_finance_period((string)($body['periodKey']??''));$periodId='payroll_'.$actor['stoId'].'_'.str_replace('-','',$period['key']);
    $pdo->beginTransaction();try{$q=$pdo->prepare("SELECT status FROM sto_payroll_periods WHERE id=? FOR UPDATE");$q->execute([$periodId]);$existing=(string)($q->fetchColumn()?:'');if(in_array($existing,['paid','partially_paid'],true)){$pdo->rollBack();kareta_json(['ok'=>false,'error'=>'payroll_period_paid'],409);} $pdo->prepare("DELETE FROM sto_payroll_accruals WHERE period_id=? AND status<>'paid'")->execute([$periodId]);
        $q=$pdo->prepare("SELECT * FROM sto_master_payroll_rules WHERE BINARY sto_id=BINARY ? AND active=1");$q->execute([$actor['stoId']]);$rules=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)$rules[(string)$r['master_id']]=$r;
        $q=$pdo->prepare("SELECT f.*,o.completed_at,o.updated_at FROM work_order_financial_results f JOIN orders o ON BINARY o.id=BINARY f.order_id LEFT JOIN sto_workflows wf ON BINARY wf.order_id=BINARY f.order_id WHERE (LOWER(o.status) IN ('completed','done','delivered','closed') OR wf.current_stage IN ('payment','delivery','warranty','completed')) AND BINARY f.sto_id=BINARY ? AND COALESCE(o.completed_at,o.updated_at,o.created_at)>=? AND COALESCE(o.completed_at,o.updated_at,o.created_at)<? AND f.master_id<>''");$q->execute([$actor['stoId'],$period['start'],$period['end']]);$rows=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$insert=$pdo->prepare("INSERT INTO sto_payroll_accruals(id,period_id,sto_id,period_key,master_id,order_id,accrual_type,base_amount,hours_worked,rate_value,amount,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,'accrued')");$masters=[];$total=0.0;$orders=0;
        foreach($rows as $r){$mid=(string)$r['master_id'];if(!isset($rules[$mid]))continue;$rule=$rules[$mid];$hours=0.0;$t=$pdo->prepare("SELECT COALESCE(SUM(duration_sec),0)/3600 FROM work_order_timers WHERE BINARY order_id=BINARY ? AND status='stopped'");$t->execute([(string)$r['order_id']]);$hours=(float)$t->fetchColumn();$mode=(string)$rule['calculation_mode'];$base=0.0;$rate=(float)$rule['base_percent'];$amount=0.0;if($mode==='revenue_percent'){$base=(float)$r['revenue_total'];$amount=$base*$rate/100;}elseif($mode==='labor_percent'){$base=(float)$r['labor_revenue'];$amount=$base*$rate/100;}elseif($mode==='hourly'){$base=$hours;$rate=(float)$rule['hourly_rate'];$amount=$hours*$rate;}else{$base=max(0,(float)$r['gross_profit']);$amount=$base*$rate/100;}if((float)$rule['parts_bonus_percent']>0)$amount+=(float)$r['parts_revenue']*(float)$rule['parts_bonus_percent']/100;$amount=round(max(0,$amount),2);$id='pa_'.substr(hash('sha256',$periodId.'|'.$mid.'|'.$r['order_id'].'|order'),0,48);$insert->execute([$id,$periodId,$actor['stoId'],$period['key'],$mid,(string)$r['order_id'],'order',$base,$hours,$rate,$amount]);$masters[$mid]=true;$total+=$amount;$orders++;}
        foreach($rules as $mid=>$rule){$fixed=round((float)$rule['fixed_monthly'],2);if($fixed<=0)continue;$id='pa_'.substr(hash('sha256',$periodId.'|'.$mid.'|fixed'),0,48);$insert->execute([$id,$periodId,$actor['stoId'],$period['key'],$mid,'','fixed',0,0,0,$fixed]);$masters[$mid]=true;$total+=$fixed;}
        $pdo->prepare("INSERT INTO sto_payroll_periods(id,sto_id,period_key,status,orders_count,masters_count,gross_amount,paid_amount,closed_by_user_id,closed_at) VALUES(?,?,?,'closed',?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE status='closed',orders_count=VALUES(orders_count),masters_count=VALUES(masters_count),gross_amount=VALUES(gross_amount),closed_by_user_id=VALUES(closed_by_user_id),closed_at=NOW(),updated_at=NOW()")->execute([$periodId,$actor['stoId'],$period['key'],$orders,count($masters),round($total,2),0,(int)$actor['userId']?:null]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}kareta_json(['ok'=>true,'periodId'=>$periodId,'periodKey'=>$period['key'],'grossAmount'=>round($total,2),'ordersCount'=>$orders,'mastersCount'=>count($masters)]);
}

function kareta_operational_finance_payroll_pay(PDO $pdo,array $body): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$body);if(!in_array($actor['role'],['sto','admin','owner'],true)||$actor['stoId']==='')kareta_json(['ok'=>false,'error'=>'sto_finance_required'],403);$periodId=trim((string)($body['periodId']??''));$masterId=trim((string)($body['masterId']??''));$method=(string)($body['method']??'cash');if(!in_array($method,['cash','card','bank_transfer'],true))$method='cash';
    $pdo->beginTransaction();try{$q=$pdo->prepare("SELECT id,amount FROM sto_payroll_accruals WHERE period_id=? AND BINARY sto_id=BINARY ? AND BINARY master_id=BINARY ? AND status='accrued' FOR UPDATE");$q->execute([$periodId,$actor['stoId'],$masterId]);$locked=$q->fetchAll(PDO::FETCH_ASSOC)?:[];$amount=round(array_sum(array_map(static fn($row)=>(float)$row['amount'],$locked)),2);if($amount<=0){$pdo->rollBack();kareta_json(['ok'=>false,'error'=>'payroll_nothing_to_pay'],409);} $account=kareta_operational_finance_cash_account($pdo,$actor['stoId'],$method);$key='payroll_'.bin2hex(random_bytes(10));$pdo->prepare("INSERT INTO sto_cash_movements(movement_key,sto_id,account_id,master_id,movement_type,category,amount,payment_method,reference_type,reference_key,description,actor_user_id) VALUES(?,?,?,?,'expense','payroll',?,?, 'payroll_period',?,?,?)")->execute([$key,$actor['stoId'],$account,$masterId,$amount,$method,$periodId,'Выплата Мастеру за период',(int)$actor['userId']?:null]);$pdo->prepare("UPDATE sto_payroll_accruals SET status='paid',paid_at=NOW(),updated_at=NOW() WHERE period_id=? AND BINARY master_id=BINARY ? AND status='accrued'")->execute([$periodId,$masterId]);$pdo->prepare("UPDATE sto_payroll_periods p SET paid_amount=(SELECT COALESCE(SUM(amount),0) FROM sto_payroll_accruals a WHERE a.period_id=p.id AND a.status='paid'),status=IF((SELECT COUNT(*) FROM sto_payroll_accruals a2 WHERE a2.period_id=p.id AND a2.status='accrued')=0,'paid','partially_paid'),paid_at=IF((SELECT COUNT(*) FROM sto_payroll_accruals a3 WHERE a3.period_id=p.id AND a3.status='accrued')=0,NOW(),paid_at),updated_at=NOW() WHERE p.id=?")->execute([$periodId]);$uid=max(1,(int)$actor['userId']);$ledger=$pdo->prepare("INSERT INTO finance_ledger(ledger_key,owner_user_id,organization_id,account_code,entry_type,amount,currency,reference_type,reference_key,description) VALUES(?,?,?,?,?,?,'KZT','payroll',?,?)");$ledger->execute(['ledger:'.$key.':wages',$uid,$actor['organizationId'],'payroll_expense','debit',$amount,$key,'Начисление зарплаты']);$ledger->execute(['ledger:'.$key.':cash',$uid,$actor['organizationId'],'cash','credit',$amount,$key,'Выплата зарплаты']);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}kareta_json(['ok'=>true,'movementKey'=>$key,'amount'=>$amount]);
}

function kareta_operational_finance_receivable_due(PDO $pdo,array $body): void {
    kareta_operational_finance_ensure($pdo);$actor=kareta_operational_finance_actor($pdo,$body);if(!in_array($actor['role'],['master','sto','admin','owner'],true))kareta_json(['ok'=>false,'error'=>'finance_write_forbidden'],403);$orderId=trim((string)($body['orderId']??''));kareta_master_order_lifecycle_order($pdo,$orderId,true);$raw=trim((string)($body['dueAt']??''));try{$due=(new DateTimeImmutable($raw))->format('Y-m-d H:i:s');}catch(Throwable $e){kareta_json(['ok'=>false,'error'=>'due_at_invalid'],422);} $pdo->prepare("UPDATE work_order_receivables SET due_at=?,status=IF(balance_amount<=0,'paid',IF(?<NOW(),'overdue',IF(paid_amount>0,'partial','open'))),updated_at=NOW() WHERE order_id=?")->execute([$due,$due,$orderId]);kareta_json(['ok'=>true]);
}
